import React from 'react';
import type * as FirebaseAuth from 'firebase/auth';
import type * as FirebaseFirestore from 'firebase/firestore';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import LoginPage from '../components/LoginPage';

const { resetEmail, createAccount, googleSignIn, getUserDoc, writeUserDoc } = vi.hoisted(() => ({ resetEmail: vi.fn(), createAccount: vi.fn(), googleSignIn: vi.fn(), getUserDoc: vi.fn(), writeUserDoc: vi.fn() }));
vi.mock('firebase/auth', async importOriginal => ({ ...(await importOriginal<typeof FirebaseAuth>()), sendPasswordResetEmail: resetEmail, createUserWithEmailAndPassword: createAccount, signInWithPopup: googleSignIn }));
vi.mock('firebase/firestore', async importOriginal => ({ ...(await importOriginal<typeof FirebaseFirestore>()), doc: () => ({}), getDoc: getUserDoc, setDoc: writeUserDoc }));
vi.mock('firebase/functions', () => ({ getFunctions: () => ({}), httpsCallable: () => vi.fn().mockRejectedValue(new Error('not signed in')) }));
vi.mock('../utils/funnel', () => ({ trackFunnel: vi.fn() }));
vi.mock('../hooks/useMobileAppDesign', () => ({ useMobileAppDesign: () => true }));

beforeEach(() => { localStorage.clear(); sessionStorage.clear(); googleSignIn.mockReset(); getUserDoc.mockReset(); writeUserDoc.mockReset(); writeUserDoc.mockResolvedValue(undefined); createAccount.mockReset(); resetEmail.mockReset(); resetEmail.mockResolvedValue(undefined); });
describe('account entry refinements', () => {
  it('uses password-manager semantics on the real sign-in form', () => {
    render(<LoginPage handleLoginSuccess={vi.fn()} />);
    expect(screen.getByLabelText('Email')).toHaveAttribute('autocomplete', 'username');
    expect(screen.getByLabelText('Password')).toHaveAttribute('autocomplete', 'current-password');
  });
  it('join-code help preserves the registration details', async () => {
    render(<LoginPage handleLoginSuccess={vi.fn()} />);
    fireEvent.click(screen.getByRole('button', { name: 'Create account' }));
    await screen.findByLabelText('Your Name');
    fireEvent.change(screen.getByLabelText('Your Name'), { target: { value: 'Alex' } });
    fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'alex@example.com' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByLabelText('School');
    fireEvent.click(screen.getByRole('button', { name: 'Where do I find my join code?' }));
    expect(screen.getByRole('dialog')).toHaveTextContent('Ask the teacher or guidance counsellor');
    fireEvent.click(screen.getByRole('button', { name: 'Back to your details' }));
    fireEvent.click(screen.getByRole('button', { name: 'Back' }));
    expect(await screen.findByLabelText('Your Name')).toHaveValue('Alex');
    expect(screen.getByLabelText('Email')).toHaveValue('alex@example.com');
  });
  it('keeps details and the chosen character when going back, and still requires consent', async () => {
    render(<LoginPage handleLoginSuccess={vi.fn()} />);
    fireEvent.click(screen.getByRole('button', { name: 'Create account' }));
    await screen.findByLabelText('Your Name');
    fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'aoife@example.com' } });
    fireEvent.change(screen.getByLabelText('Your Name'), { target: { value: 'Aoife' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByLabelText('School');
    await userEvent.click(screen.getByLabelText('School'));
    await userEvent.click(await screen.findByRole('option', { name: /Marino/ }));
    fireEvent.change(screen.getByLabelText('School join code'), { target: { value: 'preview-only' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByLabelText('Password', { selector: 'input' });
    fireEvent.change(screen.getByLabelText('Password', { selector: 'input' }), { target: { value: 'A memorable password phrase' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    const picker = await screen.findByRole('radiogroup', { name: 'Choose your Star Crew character' });
    expect(within(picker).getAllByRole('radio')).toHaveLength(8);
    fireEvent.click(within(picker).getByRole('radio', { name: 'Maker' }));
    expect(within(picker).getAllByRole('radio', { checked: true })).toHaveLength(1);
    expect(screen.getByRole('button', { name: 'Create my account' })).toBeDisabled();

    fireEvent.click(screen.getByRole('button', { name: 'Back' }));
    expect(await screen.findByLabelText('Password', { selector: 'input' })).toHaveValue('A memorable password phrase');
    fireEvent.click(screen.getByRole('button', { name: 'Back' }));
    expect(await screen.findByLabelText('School')).toHaveTextContent('Marino');
    expect(screen.getByLabelText('School join code')).toHaveValue('preview-only');
    fireEvent.click(screen.getByRole('button', { name: 'Back' }));
    expect(await screen.findByLabelText('Your Name')).toHaveValue('Aoife');
    expect(screen.getByLabelText('Email')).toHaveValue('aoife@example.com');
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByLabelText('School');
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByLabelText('Password', { selector: 'input' });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    expect(await screen.findByRole('radio', { name: 'Maker' })).toHaveAttribute('aria-checked', 'true');
    expect(screen.getByRole('status', { name: 'Account creation, step 4 of 4' })).toBeInTheDocument();
    const consent = screen.getByRole('checkbox', { name: 'I have read the Privacy Notice and agree to the Terms of Use' });
    fireEvent.click(consent);
    expect(screen.getByRole('button', { name: 'Create my account' })).toBeEnabled();
    fireEvent.click(consent);
    expect(screen.getByRole('button', { name: 'Create my account' })).toBeDisabled();
  });
  it('starts with the waiting crew and retains an early character choice when entering registration', async () => {
    const { container } = render(<LoginPage handleLoginSuccess={vi.fn()} />);
    fireEvent.click(screen.getByRole('button', { name: 'NextStepUni welcome' }));
    await screen.findByRole('button', { name: 'Create an account' });
    expect(screen.queryByText('Welcome to NextStepUni')).toBeNull();
    expect(container.querySelector('.auth-live-crew-waiting')).not.toBeNull();
    expect(container.querySelectorAll('img[src="/icons/onboarding/star-person.png"]')).toHaveLength(1);
    fireEvent.click(screen.getByRole('button', { name: 'Choose your Star Crew character' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('radio', { name: 'Reader' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Choose Reader' }));
    expect(screen.queryByRole('dialog')).toBeNull();
    expect(container.querySelector('.auth-live-crew-waiting')).toBeNull();
    fireEvent.click(screen.getByRole('button', { name: 'Create an account' }));
    await screen.findByLabelText('Your Name');
    expect(screen.getByRole('button', { name: 'Change your Star Crew character' })).toBeInTheDocument();
  });
  it('lets the popup preview a character without committing it on Escape', async () => {
    const user = userEvent.setup();
    render(<LoginPage handleLoginSuccess={vi.fn()} />);
    await user.click(screen.getByRole('button', { name: 'Choose your Star Crew character' }));
    await user.click(within(screen.getByRole('dialog')).getByRole('radio', { name: 'Maker' }));
    expect(within(screen.getByRole('dialog')).getByRole('radio', { name: 'Maker' })).toBeChecked();
    await user.keyboard('{Escape}');
    expect(screen.queryByRole('dialog')).toBeNull();
    expect(screen.getByRole('button', { name: 'Choose your Star Crew character' })).toHaveFocus();
    await user.click(screen.getByRole('button', { name: 'Choose your Star Crew character' }));
    expect(within(screen.getByRole('dialog')).queryAllByRole('radio', { checked: true })).toHaveLength(0);
    await user.click(within(screen.getByRole('dialog')).getByRole('radio', { name: 'Maker' }));
    await user.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Choose Maker' }));
    expect(screen.getByRole('button', { name: 'Change your Star Crew character' })).toBeInTheDocument();
  });
  it.each([false, true])('carries the chosen crew into a new Google account and preserves an existing profile (existing: %s)', async existing => {
    googleSignIn.mockResolvedValue({ user: { uid: 'local-social-user', displayName: 'Aoife', email: 'aoife@example.com', getIdTokenResult: async () => ({ claims: {} }) } });
    getUserDoc.mockResolvedValue({ exists: () => existing, data: () => ({ name: 'Aoife', avatar: 'star-crew:maker', role: 'student', school: 'marino' }) });
    const success = vi.fn();
    render(<LoginPage handleLoginSuccess={success} />);
    fireEvent.click(screen.getByRole('button', { name: 'NextStepUni welcome' }));
    await screen.findByRole('button', { name: 'Create an account' });
    fireEvent.click(screen.getByRole('button', { name: 'Choose your Star Crew character' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('radio', { name: 'Reader' }));
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Choose Reader' }));
    fireEvent.click(screen.getByRole('button', { name: 'Continue with Google' }));
    await waitFor(() => expect(success).toHaveBeenCalledOnce());
    expect(success.mock.calls[0][0].avatar).toBe(existing ? 'star-crew:maker' : 'star-crew:reader');
    if (existing) expect(writeUserDoc).not.toHaveBeenCalled();
    else expect(writeUserDoc).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ avatar: 'star-crew:reader' }));
  });
  it('enforces each step, locks pending submission, and returns email errors to the details step', async () => {
    let rejectRegistration: (error: unknown) => void = () => {};
    createAccount.mockImplementation(() => new Promise((_resolve, reject) => { rejectRegistration = reject; }));
    const success = vi.fn();
    render(<LoginPage handleLoginSuccess={success} />);
    fireEvent.click(screen.getByRole('button', { name: 'Create account' }));
    await screen.findByLabelText('Your Name');
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    expect(screen.getByRole('alert')).toHaveTextContent('Enter your name.');
    await waitFor(() => expect(screen.getByLabelText('Your Name')).toHaveFocus());
    expect(screen.getByLabelText('Your Name')).toHaveAccessibleDescription('Enter your name.');
    fireEvent.change(screen.getByLabelText('Your Name'), { target: { value: 'Aoife' } });
    fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'aoife@example.com' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByLabelText('School');
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    expect(screen.getByRole('alert')).toHaveTextContent('Choose your school.');
    await waitFor(() => expect(screen.getByLabelText('School')).toHaveFocus());
    expect(screen.getByLabelText('School')).toHaveAttribute('aria-invalid', 'true');
    expect(screen.getByLabelText('School')).toHaveAccessibleDescription('Choose your school.');
    await userEvent.click(screen.getByLabelText('School'));
    await userEvent.click(await screen.findByRole('option', { name: /Marino/ }));
    fireEvent.change(screen.getByLabelText('School join code'), { target: { value: 'test-only' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByLabelText('Password', { selector: 'input' });
    fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'short' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    expect(screen.getByRole('alert')).toHaveTextContent('12 characters');
    expect(createAccount).not.toHaveBeenCalled();
    fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'A memorable password phrase' } });
    fireEvent.click(screen.getByRole('button', { name: 'Continue' }));
    await screen.findByRole('radiogroup', { name: 'Choose your Star Crew character' });
    fireEvent.click(screen.getByRole('checkbox', { name: 'I have read the Privacy Notice and agree to the Terms of Use' }));
    expect(screen.getByRole('button', { name: 'Create my account' })).toBeDisabled();
    fireEvent.click(screen.getByRole('radio', { name: 'Maker' }));
    fireEvent.click(screen.getByRole('button', { name: 'Create my account' }));
    expect(createAccount).toHaveBeenCalledExactlyOnceWith(expect.anything(), 'aoife@example.com', 'A memorable password phrase');
    expect(screen.getByRole('button', { name: 'Creating your account…' })).toBeDisabled();
    expect(screen.getByRole('button', { name: 'Back' })).toBeDisabled();
    expect(screen.getByRole('radio', { name: 'Maker' })).toHaveAttribute('aria-disabled', 'true');
    rejectRegistration({ code: 'auth/email-already-in-use' });
    expect(await screen.findByLabelText('Email')).toHaveValue('aoife@example.com');
    expect(screen.getByRole('alert')).toHaveTextContent('An account with this email already exists');
    expect(success).not.toHaveBeenCalled();
  });
  it('allows correcting the reset email without losing it or sending twice', async () => {
    render(<LoginPage handleLoginSuccess={vi.fn()} />);
    fireEvent.click(screen.getByRole('button', { name: 'Forgot password?' }));
    await screen.findByRole('button', { name: 'Send Reset Link' });
    fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'wrong@example.com' } });
    fireEvent.click(screen.getByRole('button', { name: 'Send Reset Link' }));
    await screen.findByRole('button', { name: 'Change email address' });
    expect(resetEmail).toHaveBeenCalledOnce();
    expect(screen.getByRole('button', { name: /Resend in/ })).toBeDisabled();
    fireEvent.click(screen.getByRole('button', { name: 'Change email address' }));
    expect(screen.getByLabelText('Email')).toHaveValue('wrong@example.com');
    fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'right@example.com' } });
    fireEvent.click(screen.getByRole('button', { name: 'Send Reset Link' }));
    await waitFor(() => expect(resetEmail).toHaveBeenCalledTimes(2));
    expect(resetEmail.mock.calls[1][1]).toBe('right@example.com');
  });
});
