/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Command-Word Reflex content.
 *
 * FIRST SLICE: Leaving Cert Business (HL) — the subject where cue-word literacy
 * is the core exam skill. Demands and traps are source-grounded from the LC
 * Business Chief Examiner's Report 2015 and the 2025 marking scheme (see
 * examiner-reports/business/). Stems are faithful, representative LC Business
 * question stems that contain the real cue word; the marks-losing traps are the
 * exact patterns the examiners flag, with page citations.
 *
 * Scales subject-by-subject (the way Exam Reps did). Each cue word teaches a
 * transferable read-the-question skill.
 */

import { type CommandWordQuestion } from './types/commandWord';

export const COMMAND_WORD_QUESTIONS: CommandWordQuestion[] = [
  {
    id: 'biz-illustrate-specific-performance',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Business Law',
    stem: 'Illustrate, using an example, what is meant by ‘specific performance’ as a remedy for breach of contract.',
    commandWord: 'Illustrate',
    demand: 'Explain the term AND give a concrete example. With “Illustrate”, the example is not optional decoration — it earns marks in its own right (the marking grid gives separate marks for the example).',
    trap: 'Many candidates defined the term correctly but gave no example, “thereby losing marks.” The same requirement caught people out in Q3(B) and Q7(C).',
    source: 'LC Business Chief Examiner 2015, p.17',
    marks: 5,
  },
  {
    id: 'biz-list-discrimination-grounds',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Business Law',
    stem: 'List three grounds under which discrimination is prohibited by employment equality legislation.',
    commandWord: 'List',
    demand: 'Just name them — short, separate points. “List” rewards naming only; no explanation is needed or marked.',
    trap: 'Some candidates “wrote paragraphs to explain the protected grounds rather than just naming the grounds, as was required.” That extra writing earns nothing and burns time.',
    source: 'LC Business Chief Examiner 2015, p.17',
    marks: 6,
  },
  {
    id: 'biz-discuss-communication',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Managing',
    stem: 'Discuss the factors a business should consider when communicating with its stakeholders.',
    commandWord: 'Discuss',
    demand: 'Make several DISTINCT developed points (each typically Name + Explain). Range is the thing — different factors, not one idea reworded.',
    trap: '“Disproportionate focus on” one point — repeating variations of a single idea — limits the marks. Discussion questions reward distinct points.',
    source: 'LC Business Chief Examiner 2015, p.17',
    marks: 20,
  },
  {
    id: 'biz-evaluate-management-control',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Managing',
    stem: 'Evaluate the effectiveness of one method of management control used by a business.',
    commandWord: 'Evaluate',
    demand: 'Make a JUDGEMENT and justify it — say how effective it is and why. Evaluation is the most heavily weighted single component (3 of 7 marks in the 2025 grid).',
    trap: 'Candidates often name and explain the control, then stop. “Some evaluations continue to be very superficial and some candidates do not evaluate at all” — the highest-order, highest-mark step is the one most often skipped.',
    source: 'LC Business Chief Examiner 2015, p.17; 2025 marking scheme (B(i) weights evaluation 3/7)',
    marks: 7,
  },
  {
    id: 'biz-outline-entrepreneur-skills',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Enterprise',
    stem: 'Outline the main skills displayed by a successful entrepreneur.',
    commandWord: 'Outline',
    demand: 'Give DEVELOPED points (Name + Explain) — more than a bare list, but examples aren’t required.',
    trap: 'Cues like “outline” and “explain” are “often not addressed adequately.” Treating “Outline” like “List” (just naming) under-develops the answer and loses marks.',
    source: 'LC Business Chief Examiner 2015, p.20',
    marks: 20,
  },
  {
    id: 'biz-explain-utmost-good-faith',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Business in the Economy',
    stem: 'Explain the term ‘utmost good faith’ as a principle of insurance.',
    commandWord: 'Explain',
    demand: 'Give the precise business meaning — the exact technical sense, not a loose everyday paraphrase.',
    trap: 'Weaker answers explained it as “telling the truth” rather than “disclosing all material facts.” “Precision of language is required when explaining business concepts.”',
    source: 'LC Business Chief Examiner 2015, p.19',
    marks: 10,
  },
  {
    id: 'biz-distinguish-ltd-plc',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Business Ownership',
    stem: 'Distinguish between a private limited company and a public limited company as forms of business ownership.',
    commandWord: 'Distinguish',
    demand: 'Bring out the DIFFERENCE(S) — contrast the two directly (e.g. “whereas a private limited company…, a public limited company…”). The contrast is what’s marked.',
    trap: 'Describing each type separately, in isolation, without making the difference explicit, misses the comparison the cue demands.',
    source: 'LC Business Chief Examiner 2015, p.20 (compare/distinguish cues)',
    marks: 10,
  },
  {
    id: 'biz-define-delegation',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Managing',
    stem: 'Define the term ‘delegation’ as used in management.',
    commandWord: 'Define',
    demand: 'Give ONE precise sentence stating exactly what it means. “Define” wants brevity plus accuracy.',
    trap: 'A vague, roundabout or example-led sentence loses the mark — a definition must be tight and technically correct, not a story about it.',
    source: 'LC Business 2025 marking scheme (“Define” = a precise sentence)',
    marks: 5,
  },
  {
    id: 'biz-describe-recruitment',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Managing (HRM)',
    stem: 'Describe the stages a business goes through when recruiting a new employee.',
    commandWord: 'Describe',
    demand: 'Give an account of EACH stage — what happens and in what order. More than naming the stages.',
    trap: 'Just listing the stage names (treating “Describe” like “List”) under-answers it — the marks are in the account of what happens at each.',
    source: 'LC Business Chief Examiner 2015, p.20 (higher-order cues)',
    marks: 15,
  },
  {
    id: 'biz-analyse-exchange-rate',
    subjectId: 'business', subjectLabel: 'Business', level: 'higher',
    questionRef: 'HL · Business in the Economy',
    stem: 'Analyse the impact of a weakening exchange rate on an Irish business that exports to the UK.',
    commandWord: 'Analyse',
    demand: 'Break it down and show the cause-and-effect — explain HOW and WHY the change affects the business, with linked reasoning, not just a list of effects.',
    trap: 'Stating effects without showing the link back to the exporter (the “because… therefore…”) reads as description, and earns fewer marks than developed analysis.',
    source: 'LC Business Chief Examiner 2015, p.20 (higher-order skills)',
    marks: 15,
  },
  // ── English ──
  {
    id: 'eng-explain-comprehension-relationship',
    subjectId: 'english', subjectLabel: 'English', level: 'ordinary',
    questionRef: 'OL · Paper 1, Comprehending Q A(i)',
    stem: 'Based on a text you have studied, how would you describe the relationship between the writer and a person or animal in that text? Explain your answer, with reference to the text.',
    commandWord: 'Explain',
    demand: 'Don\'t just state an impression — give the REASONS behind it and anchor every reason in the text. The scheme accepts \'any reasonable, clear explanation\' but rewards \'sustained focus, clarity of expression, developed and supported ideas\' — a label on its own is not an explanation.',
    trap: 'Candidates name a quality (\'loving\', \'loyal\') and stop. The scheme directs examiners to give \'consideration to the quality of the explanation provided\' and to reward \'developed and supported ideas\'; an unsupported, unexplained assertion is marked low on Clarity of Purpose (P), the 30% primacy criterion that caps Coherence and Language. No reference, no reason = no marks beyond the bare point.',
    source: 'Marking scheme 2025 OL, Paper 1 Q A(i) (Paul Howard/Humphrey) + Criteria for Assessment',
    marks: 15,
  },
  {
    id: 'eng-compare-comparative-theme',
    subjectId: 'english', subjectLabel: 'English', level: 'ordinary',
    questionRef: 'OL · Paper 2, Comparative Study Q1(b) – Theme',
    stem: 'In relation to a theme you have studied, compare how exploring this theme in at least two texts on your comparative course helped you to understand the positive or negative behaviour of a central character in each text. Support your answer with reference to your chosen texts.',
    commandWord: 'compare',
    demand: 'Run the two texts SIDE BY SIDE — point out similarities and/or differences as you go. The scheme says \'the emphasis is on identifying similarities and/or differences\' and \'this requires the candidate to make comparison(s) throughout their response.\' Apply the theme to both texts, though not necessarily equally.',
    trap: 'Writing about Text 1 fully, then Text 2 fully, with no links — a \'two essays stapled together\' answer. The scheme awards comparison through the whole answer; serial writing forfeits the comparative credit, which is the bulk of P+C (the 40-mark part splits P=12, C=12, L=12, M=4).',
    source: 'Marking scheme 2025 OL, Paper 2 Comparative Study Q1(b) – Theme',
    marks: 40,
  },
  {
    id: 'eng-describe-singletext-mood-talk',
    subjectId: 'english', subjectLabel: 'English', level: 'ordinary',
    questionRef: 'OL · Paper 2, Single Text Q3 – talk task',
    stem: 'Write a talk for your class about the powerful mood created in a text you have studied. In your talk you should: describe two moments when the mood was particularly powerful; explain why the mood was so powerful in those moments; and explain your overall feelings on finishing the text.',
    commandWord: 'describe',
    demand: '\'Describe\' is only the first of three listed sub-tasks — do EVERY bullet: describe the two moments, AND explain why the mood works, AND give your overall feeling. Describing is not enough on its own; the explain-why and overall-feeling parts carry equal weight.',
    trap: 'Candidates describe two moments vividly, then skip the \'explain why\' and \'overall feelings\' sub-tasks, or just retell the plot. The scheme tells examiners to give \'consideration to the quality of the explanation provided\' across every listed element; a dropped sub-task drags down Clarity of Purpose (P=9 of the 30 discrete marks), which under the primacy rule then caps Coherence and Language.',
    source: 'Marking scheme 2024 OL, Paper 2 Single Text Q3 (talk on powerful mood, e.g. Doerr) + Criteria for Assessment',
    marks: 30,
  },
  {
    id: 'eng-toextent-comprehension-claim',
    subjectId: 'english', subjectLabel: 'English', level: 'higher',
    questionRef: 'HL · Paper 1, Comprehending Q A(ii)',
    stem: 'To what extent do you agree with the writer\'s central claim in a text you have studied? Develop at least two points in your response.',
    commandWord: 'To what extent',
    demand: 'Take a MEASURED position on degree — how far you agree, not a flat yes/no. You may agree, disagree or part-agree, but you must weigh the claim and develop at least two points to justify where you land.',
    trap: 'Candidates ignore the \'extent\' and just summarise the writer\'s argument, or assert total agreement with no weighing or development. The scheme says to \'focus on the extent to which they agree or disagree\' and to reward \'a sustained focus, development of ideas and clarity of expression\' — an undeveloped, one-line stance scores low on the 30%-primacy Clarity-of-Purpose criterion.',
    source: 'Marking scheme 2025 HL, Paper 1 Q A(ii) (\'fixation on status and prestige\')',
    marks: 15,
  },
  {
    id: 'eng-identify-comprehension-style',
    subjectId: 'english', subjectLabel: 'English', level: 'higher',
    questionRef: 'HL · Paper 1, Comprehending Q A(iii)',
    stem: 'Identify four elements of the writer\'s style in a text you have studied, and discuss how they contribute to making it engaging. Support your response with reference to the text.',
    commandWord: 'Identify',
    demand: 'Identifying the four techniques is only the trigger — the marks are in the \'discuss how they contribute\' half: show an awareness of the EFFECT each stylistic element has on the reader, backed by quotation. Naming without developing the effect is half an answer.',
    trap: 'Candidates list techniques (\'imagery, humour, tone\') and stop, treating \'Identify\' as the whole task. The scheme tells examiners to pay particular attention to \'the extent to which an awareness of the impact of stylistic elements/techniques is evident\' and to \'reward good analysis of the use of stylistic elements\' — feature-spotting without effect-analysis caps the answer well below the top band.',
    source: 'Marking scheme 2024 HL, Paper 1 Q A(iii) (identify four elements of style + discuss)',
    marks: 20,
  },
  {
    id: 'eng-compare-comparative-freedom',
    subjectId: 'english', subjectLabel: 'English', level: 'higher',
    questionRef: 'HL · Paper 2, Comparative Study (b) – Cultural Context',
    stem: 'In two texts you have studied on your comparative course, compare the extent to which the level of freedom enjoyed by a central character in each text is determined by that character\'s social position and status. Develop your response with reference to your chosen texts.',
    commandWord: 'compare',
    demand: 'Compare and/or contrast across BOTH texts within the mode, sustaining the comparison throughout — and because of the \'extent to which\', weigh the degree, not just whether freedom is restricted.',
    trap: 'Writing two separate single-text accounts with no comparative thread. The scheme makes \'evidence of effective comparison within the mode\' a Purpose (P) requirement, and \'sustained comparative focus\' a Coherence (C) requirement and \'use of comparative language\' a Language (L) requirement — so a serial answer loses credit on three of the four criteria, not one.',
    source: 'Marking scheme 2024 HL, Paper 2 Comparative Study (b), Cultural Context (compare extent of freedom by social position)',
    marks: 40,
  },
  // ── Mathematics ──
  {
    id: 'mat-find-surface-area',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'ordinary',
    questionRef: 'OL · Paper 2 · Q9(b) · Area & Volume',
    stem: 'Find the surface area of a sphere of radius 3.27 cm. Give your answer in cm², correct to 2 decimal places.',
    commandWord: 'Find',
    demand: 'Carry the calculation through to a numerical answer AND obey the answer-format instruction — here the right units (cm²) and the stated rounding (2 decimal places). \'Find\' is not finished until the value is presented as the question demands: surface area = 4πr² = 134.37 cm².',
    trap: 'Getting the right number (134.3709…) but rounding wrong, to the wrong number of places, or dropping units. The scheme\'s Full Credit −1 line for this part is literally \'Incorrect rounding\', and the front matter warns \'A rounding penalty is applied each time it occurs in the scheme\' — so it can bite more than once across a multi-part question.',
    source: 'LC Mathematics 2024 OL Paper 2 Q9(b) (tennis ball, smallest radius 3.27 cm); 2024 OL marking scheme Q9(b) Scale 5C, \'Full Credit (-1): Incorrect rounding\' and front-matter \'A rounding penalty is applied each time it occurs in the scheme\'',
    marks: 5,
  },
  {
    id: 'mat-solve-simultaneous',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'ordinary',
    questionRef: 'OL · Paper 1 · Q3(c) · Algebra',
    stem: 'Use algebra to solve the simultaneous equations 2x + y = 5 and x² + y² = 25.',
    commandWord: 'solve',
    demand: 'Find EVERY value of the unknowns that works — with a linear-and-quadratic pair that means BOTH co-ordinate sets (x = 0, y = 5) and (x = 4, y = −3), reached by substituting y = 5 − 2x into the quadratic, not by guessing.',
    trap: 'Finding the x-values but stopping before pairing them with their y-values, or finding only one solution. The scheme\'s four-step solution has step 4 as \'Finds the two co-ordinate sets\' — stop after step 3 (just the x\'s, or one set) and you cap at High Partial Credit. \'Trial and improvement\' is explicitly only Low Partial Credit.',
    source: 'LC Mathematics 2024 OL Paper 1 Q3(c); 2024 OL marking scheme Q3(c) Scale 15D, four-step solution with step 4 \'Finds the two co-ordinate sets\'; \'Trial and improvement\' listed under Low Partial Credit',
    marks: 15,
  },
  {
    id: 'mat-hence-indices',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'ordinary',
    questionRef: 'OL · Paper 1 · Q4(c)(ii) · Indices',
    stem: 'Given that 128 = 2⁷, hence solve the equation 2^(4x+1) = 128, where x ∈ ℝ.',
    commandWord: 'hence',
    demand: 'Use the result you just established (128 = 2⁷) as the route into this part — rewrite the right side as a power of 2, equate the indices 4x + 1 = 7, and solve to get x = 1.5. \'Hence\' signposts that the previous answer is the intended tool for this one.',
    trap: 'Not linking to the earlier result at all. The scheme credits \'equates 2^(4x+1) to their answer from (i)\' as a work-of-merit step that opens the partial-credit pathway — produce x with no connecting work and an answer without sufficient supporting work is awarded only the lowest non-zero level of credit.',
    source: 'LC Mathematics 2024 OL Paper 1 Q4(c)(ii) (\'Hence, or otherwise, solve\'); 2024 OL marking scheme Q4(c) Scale 10C, Low Partial Credit \'equates 2^(4x+1) to their answer from (i)\'',
    marks: 10,
  },
  {
    id: 'mat-investigate-point-circle',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'ordinary',
    questionRef: 'OL · Paper 2 · Q4(a)(ii) · Co-ordinate Geometry',
    stem: 'Use algebra to investigate whether the point (9, 2) is on, inside, or outside the circle of centre (5, −3) and radius 5.',
    commandWord: 'investigate',
    demand: 'Show the test, then conclude: substitute (9, 2) into the circle equation (or compare its distance from the centre with the radius), then state on/inside/outside as the result of that comparison. The verdict must be earned by visible working — here (9−5)² + (2+3)² = 41 > 25, so the point is outside.',
    trap: 'Just ticking \'outside\' with no comparison shown. The scheme gives \'Only correct box ticked\' just Low Partial Credit — the marks live in the substitution and the explicit comparison to the radius, not in the verdict alone.',
    source: 'LC Mathematics 2024 OL Paper 2 Q4(a)(ii); 2024 OL marking scheme Q4(a)(ii) Scale 5C, Low Partial Credit \'Only correct box ticked\'',
    marks: 5,
  },
  {
    id: 'mat-show-that-circles-touch',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'higher',
    questionRef: 'HL · Paper 2 · Q5(a)(ii) · Circle',
    stem: 'The circle s has equation x² + y² + 4x − 6y + 5 = 0 and the circle c has equation (x − 2)² + (y + 1)² = 72. Show that the circles s and c touch internally.',
    commandWord: 'Show that',
    demand: 'Work toward the stated result with full reasoning AND finish with the explicit conclusion. Find each centre and radius, compute the distance between the centres (4√2), compare it to the difference of the radii (6√2 − 2√2 = 4√2), then state \'therefore the circles touch internally\'.',
    trap: 'Doing all four calculation steps but never writing the conclusion. The scheme is blunt: \'Apply a * if there is no conclusion or an incorrect conclusion\' — so a fully-worked answer with no closing statement is docked to Full Credit −1. With a \'Show that\', the sentence at the end is a marked step.',
    source: 'LC Mathematics 2024 HL Paper 2 Q5(a)(ii); 2024 HL marking scheme Q5(a)(ii) Scale 10D (four steps before the conclusion), Full Credit −1 \'Apply a * if there is no conclusion or an incorrect conclusion\'',
    marks: 10,
  },
  {
    id: 'mat-prove-parallel-segments',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'higher',
    questionRef: 'HL · Paper 2 · Q4(b) · Geometry (theorem)',
    stem: 'Three parallel lines cut off equal segments on one transversal. Prove that they cut off equal segments on any other transversal, giving a reason for each statement that you make.',
    commandWord: 'Prove',
    demand: 'Build a complete logical chain where every claim is justified by name — \'given\', \'alternate angles\', \'vertically opposite\', \'ASA\', \'opposite sides of a parallelogram\', etc. A proof is the reasons, not just the true statements; each justified step is a separately credited line, and the question explicitly orders \'Give a reason for each statement\'.',
    trap: 'Writing correct geometric statements but omitting the reasons. The scheme caps \'Fully correct logical statements, but no justifications\' at High Partial Credit, not full marks. The unstated reasons are exactly where the top marks are lost on a \'Prove\' question.',
    source: 'LC Mathematics 2024 HL Paper 2 Q4(b) (parallel lines / equal-segments theorem, \'Give a reason for each statement that you make in your proof\'); 2024 HL marking scheme Q4(b) Scale 15D, High Partial Credit \'Fully correct logical statements, but no justifications\'',
    marks: 15,
  },
  // ── Geography ──
  {
    id: 'geo-examine-surface-processes',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'ordinary',
    questionRef: 'OL · Physical Geography',
    stem: 'Examine how humans interact with one surface process you have studied (river, coastal or mass-movement).',
    commandWord: 'Examine',
    demand: 'Don\'t just name an interaction — work it through. Identify ONE interaction, then keep EXPLAINING it point by point: how and why humans affect (or are affected by) the process. Almost all the marks live in the running explanation, not the naming.',
    trap: 'You only get the 3m for the interaction identified (plus, at most, one SRP for naming a second interaction) — after that \'All further interactions must be explained for SRP\'s\', so a list of human activities with no explanation stalls at 3-of-30. The scheme also requires \'At least one SRP must explain a relevant process\'.',
    source: 'LC Geography OL marking scheme 2024 (Q1C) & 2023 (Q1C): Interaction identified 3m, Explanation 9 SRP\'s @ 3m = 27m; \'Allow a second interaction identified for one SRP\', \'All further interactions must be explained for SRP\'s\', \'At least one SRP must explain a relevant process\'',
    marks: 30,
  },
  {
    id: 'geo-describe-region-problems',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'ordinary',
    questionRef: 'OL · Regional Geography',
    stem: 'Describe and explain two problems faced by a region you have studied.',
    commandWord: 'Describe',
    demand: '\'Describe AND explain\' is two jobs per problem: say WHAT the problem is, then WHY it happens / why it matters. Do this for TWO separate problems and name the region. Describing alone is only half the task.',
    trap: 'The scheme demands \'At least one SRP for explanation for each problem\' — pure description with no \'why\' loses the explanation marks. Each problem is capped at 15m (5 SRP\'s @ 3m), so covering only one problem caps you at 15-of-30.',
    source: 'LC Geography OL marking scheme 2023 (Q6C, Regional Development): Problem 1 Description/Explanation 5 SRP\'s @ 3m = 15m, Problem 2 = 15m; \'At least one SRP for explanation for each problem\', \'Allow a named region for one SRP\'',
    marks: 30,
  },
  {
    id: 'geo-explain-landform-formation',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'ordinary',
    questionRef: 'OL · Surface Processes',
    stem: 'Explain, with the aid of diagrams, the formation of any two landforms you have studied.',
    commandWord: 'Explain',
    demand: '\'Explain the formation\' means give the step-by-step PROCESS that builds the landform (e.g. erosion/deposition stages), not a picture of the finished feature. Name each landform, draw labelled diagrams, and let the process drive the answer.',
    trap: 'The scheme states \'At least one SRP must explain a relevant process\', and the diagram marks (\'Diagram(s) two aspects @ 2m each\' = 4m) only count if labelled — an unlabelled sketch, or a description of what the landform looks like with no formation process, forfeits the formation SRP\'s (15m of the 20m per landform).',
    source: 'LC Geography OL marking scheme 2024 (Q2B i) & 2025 (Q1B i): Landform named 1m, Diagram(s) two aspects @ 2m = 4m, Formation explained 5 SRP\'s @ 3m = 15m, 20m per landform x2 = 40m; \'At least one SRP must explain a relevant process\'',
    marks: 40,
  },
  {
    id: 'geo-account-for-secondary-activity',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'higher',
    questionRef: 'HL · Economic Geography',
    stem: 'Account for the development of secondary economic activity in an Irish region you have studied, with reference to two of the following factors: government policy, labour, markets, infrastructure.',
    commandWord: 'Account for',
    demand: '\'Account for\' = give the CAUSES. Examine TWO of the named factors that EXPLAIN why the activity developed there, and anchor every point to a named/clearly inferred Irish region. Two factors are required — one factor alone is half-marked.',
    trap: '\'Max 8 x SRP\'s if only one factor is examined\' — answer with just one factor and you cap at 8 SRP\'s (of the ~15). \'Max 2 x SRP\'s per factor if there is merely a description of the factor without a reference to development\' — describing instead of explaining the causal role caps that factor at 2. And \'Examination without link to a named or clearly inferred region 0 marks\'.',
    source: 'LC Geography HL marking scheme 2024 (Q4C): Examination of Factor 1 8/7 SRP\'s + Factor 2 7/8 SRP\'s; \'Max 8 x SRP\'s if only one factor is examined\', \'Max 2 x SRP\'s per factor if there is merely a description of the factor without a reference to development\', \'Examination without link to a named or clearly inferred region 0 marks\'',
    marks: 30,
  },
  {
    id: 'geo-discuss-gnp-hdi',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'higher',
    questionRef: 'HL · Economic Activity',
    stem: 'Discuss how GNP and the Human Development Index can each be used as a measure of economic development.',
    commandWord: 'Discuss',
    demand: '\'Discuss\' the named pair means develop BOTH elements (GNP and HDI) with reasoned points and examples — strengths and limits of each as a measure. The mark scheme splits the discussion SRP\'s between the two; you must cover both to score fully.',
    trap: 'The scheme caps you at \'Max 6 x SRP\'s if there only a discussion on GNP... and a max 6 x SRP\'s if only a discussion on HDI\' — discuss just one of the two named measures and you forfeit half the 12 discussion SRP\'s. Naming a measure without discussing it earns only the 2-mark reference.',
    source: 'LC Geography HL marking scheme 2024 (Q7B, Economic Development): Reference to GNP 2m + HDI 2m + Example 2m, Discussion 12 SRP\'s; \'Max 6 x SRP\'s if there only a discussion on GNP as a measure... and a max 6 x SRP\'s if only a discussion on HDI\'',
    marks: 30,
  },
  {
    id: 'geo-examine-fluvial-landform',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'higher',
    questionRef: 'HL · Landscape Development',
    stem: 'Examine the role of erosion processes in forming one fluvial, coastal or glacial landform you have studied.',
    commandWord: 'Examine',
    demand: 'Keep the FOCUS on the role of EROSION in building the landform: name the process(es) of erosion and work through how each shapes the feature, supported by a labelled diagram and example. The processes — not the scenery — carry the answer.',
    trap: '\'Credit a max of 2 x SRP\'s if merely a description of landform with no reference to formation\' — drifting into what the landform looks like caps you at 2; and \'Explanation of processes of deposition 0 marks\' because the question asks specifically about EROSION. A diagram without labelling scores 0.',
    source: 'LC Geography HL marking scheme 2024 (Q2B i, Landscape Development): Process of erosion identified 2m + Landform named 2m + Examination 13 SRP\'s; \'Credit a max of 2 x SRP\'s if merely a description of landform with no reference to formation\', \'Explanation of processes of deposition 0 marks\'',
    marks: 30,
  },
  // ── Biology ──
  {
    id: 'bio-describe-osmosis',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'ordinary',
    questionRef: 'OL · Cell experiments (osmosis)',
    stem: 'Describe how you carried out an experiment to demonstrate osmosis using a named plant or animal tissue.',
    commandWord: 'Describe',
    demand: 'Walk through the procedure as a sequence of separate, ordered steps you actually did: name the material/tissue, prepare the different sugar solutions, set it up and leave it for a time, describe a control, and measure mass or volume BEFORE and AFTER. Each distinct correct step is a separate mark — the scheme credits \'any four\' steps.',
    trap: 'The scheme lists the steps as separate award points (\'material described or tissue mentioned / different solutions of sugar prepared / left for a time / control described / measure volume or mass before / measure volume or mass after / other correct step — any four\'), and (per the scheme\'s intro \'correct context\' rule, e.g. its hare/pooter example) credits a key word ONLY if it is in the correct context. A vague \'I put the tissue in sugar water and it changed\' names nothing as a separate step and is treated as one point, so you forfeit most of the available step-marks for the procedure.',
    source: 'LC Biology OL marking scheme 2023, Q9(b)(ii) \'Describe how you carried out the experiment to demonstrate osmosis\' (any four steps); OL 2023 intro rule 1 — key words credited only \'in the correct context\'',
    marks: 6,
  },
  {
    id: 'bio-explain-metabolism',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'ordinary',
    questionRef: 'OL · Metabolism',
    stem: 'Explain the term metabolism.',
    commandWord: 'Explain',
    demand: 'Give the meaning precisely — for \'Explain the term\' the scheme expects the exact defining idea: \'(all) chemical reactions in an organism\'. State what it IS, not an example of it.',
    trap: 'The scheme credits only the defining phrase \'(all) chemical reactions in an organism\' — 3 marks. Answering with examples (\'respiration and photosynthesis\') or \'how the body works\' does not match the term being defined and scores 0. Naming a related process instead of explaining the word is the classic way to throw away the marks on \'Explain the term\'.',
    source: 'LC Biology OL marking scheme 2024, Q12(a)(i) — \'(All) chemical reactions in an organism\' 3 marks',
    marks: 3,
  },
  {
    id: 'bio-state-energy-uses',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'ordinary',
    questionRef: 'OL · Respiration',
    stem: 'State two ways in which the released energy may be used in living organisms.',
    commandWord: 'State',
    demand: 'Give TWO short, separate, correct points — no description needed. \'State two\' means exactly two distinct valid uses (e.g. growth, repair, movement), each a creditable point.',
    trap: 'This is a Section A item, so the surplus-answer rule bites: a surplus WRONG answer cancels a correct one. Listing three uses where one is wrong (e.g. \'growth, movement, digestion of food\') means the incorrect item cancels one of your two earned points. \'State two\' is not an invitation to list everything — an extra incorrect item actively costs you a mark you had already earned. The scheme accepts \'growth / repair / movement / other correct, any two\'.',
    source: 'LC Biology OL marking scheme 2023, Q4(c) \'State two ways in which the released energy may be used in living organisms\' (any two); OL 2023 intro rule 3 — surplus-answer rule [Section A only]',
    marks: 6,
  },
  {
    id: 'bio-outline-water-transport',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'higher',
    questionRef: 'HL · Transport in the flowering plant',
    stem: 'Outline how water absorbed from the soil reaches the leaves of a plant.',
    commandWord: 'Outline',
    demand: 'Trace the whole pathway as a series of distinct, correctly linked stages — osmosis/concentration gradient at the root hair, root pressure, cell-to-cell movement, up the xylem, then transpiration pulling it via cohesion/adhesion/tension. The scheme wants SIX separate correct points (any six at 3 marks each = 18).',
    trap: 'The official scheme sample answer is \'Water is drawn up the xylem by osmosis.\' Although it names two key terms (xylem, osmosis), the statement is incorrect, so it is awarded just 3 marks — credited only for the ONE idea in correct context (movement of water through the xylem) — i.e. only 3 of the 18 marks. Naming the right words without putting them in the correct sequential context loses almost all the marks: \'Outline\' rewards the chain of separate, correctly-linked steps, not a vocabulary list.',
    source: 'LC Biology HL marking scheme 2024, intro example 1 — \'Outline how water from the soil reaches the leaf\', any six 6(3); sample answer \'Water is drawn up the xylem by osmosis\' awarded only 3 marks',
    marks: 18,
  },
  {
    id: 'bio-suggest-human-population',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'higher',
    questionRef: 'HL · Ecology (population dynamics)',
    stem: 'Human population numbers do not follow the predator-prey pattern. Suggest two reasons for this.',
    commandWord: 'Suggest',
    demand: 'Apply biology to a situation where there is no single fixed answer — propose two plausible, scientifically reasonable causes (e.g. healthcare, food supply, lack of predators). \'Suggest\' is open: any valid biological reason is credited, so commit to a clear cause rather than hedging.',
    trap: 'The scheme accepts \'healthcare / food supply / lack of predators / other correct\' — any two, at 4 marks each. Candidates lose marks by restating the graph (\'our numbers keep rising\') instead of giving a CAUSE, or by offering one reason and padding. \'Suggest\' still demands a biological mechanism, not a description of the trend — a non-biological or circular answer scores nothing.',
    source: 'LC Biology HL marking scheme 2024, Q12(b)(v) \'Suggest two reasons human population numbers do not follow a similar pattern\' — any two 2(4)',
    marks: 8,
  },
  {
    id: 'bio-distinguish-anabolic-catabolic',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'higher',
    questionRef: 'HL · Metabolism',
    stem: 'Distinguish between the terms anabolic and catabolic.',
    commandWord: 'Distinguish between',
    demand: 'Write a clear point for EACH term that brings out the contrast — anabolic builds large molecules from small ones (uses energy); catabolic breaks large molecules down into small ones (releases energy). Both members must be addressed so the difference is explicit.',
    trap: 'The scheme allocates marks separately to each member (Anabolic: 3, Catabolic: 3). Defining only one term, or giving the same idea twice without the opposing build-up/break-down (and uses-energy/releases-energy) contrast, forfeits the second member\'s 3 marks. \'Distinguish between\' is not \'define one\' — leaving a term out is the most common way to lose half the marks here.',
    source: 'LC Biology HL marking scheme 2024, Q13(a)(ii) \'Distinguish between the terms anabolic and catabolic\' — Anabolic 3 / Catabolic 3',
    marks: 6,
  },
  // ── English (expansion) ──
  {
    id: 'eng-discuss-singletext-power',
    subjectId: 'english', subjectLabel: 'English', level: 'higher',
    questionRef: '2025 HL · Paper 2, Single Text A(i) (The Tenant of Wildfell Hall)',
    stem: '"The world Brontë creates in The Tenant of Wildfell Hall offers readers an opportunity to gain many fascinating insights into how power, in different forms, operates in this society." Discuss this statement, developing your response with reference to the text.',
    commandWord: 'Discuss',
    demand: 'Develop a sustained, many-sided treatment of the statement: because it is plural, you must deal with MORE than one insight into MORE than one form of power, each substantiated by apt reference to the text. Discussion here is range PLUS development, not one idea restated.',
    trap: 'Candidates latch onto a single insight or one form of power and pad it out, or simply retell the plot rather than discuss the statement. The 2025 HL scheme directs examiners that candidates \'must deal with more than one fascinating insight into the operation of more than one form of power\' and to \'Pay particular attention to the quality of the discussion and the development of the response\' — a single-strand, narrating answer caps low on Clarity of Purpose (P), the 30%-primacy criterion that then ceilings Coherence and Language across all 60 marks.',
    source: 'Marking scheme 2025 HL, Paper 2 Single Text A(i), \'Candidates must deal with more than one fascinating insight into the operation of more than one form of power... Pay particular attention to the quality of the discussion and the development of the response\'',
    marks: 60,
  },
  {
    id: 'eng-argue-singletext-ending',
    subjectId: 'english', subjectLabel: 'English', level: 'ordinary',
    questionRef: '2025 OL · Paper 2, Single Text Q4 (debate on the ending)',
    stem: 'Your class is having a debate about the ending of Brontë\'s novel, The Tenant of Wildfell Hall. Write the text of your contribution to the debate, beginning either \'I was satisfied with the ending… because…\' or \'I was not satisfied with the ending… because…\'. Argue three points in your response.',
    commandWord: 'Argue',
    demand: 'Take ONE clear side — satisfied or not — and back it with THREE developed points grounded in the text, presented as a debate contribution rather than a plot summary. The scheme expects candidates to be \'either satisfied or dissatisfied\' and the material \'presented in the guise of a debate\'.',
    trap: 'Candidates sit on the fence, give fewer than three points, or retell what happens at the end instead of arguing a case. The 2025 OL scheme tells examiners to \'Expect candidates to be either satisfied or dissatisfied with the ending\', that \'material should be presented in the guise of a debate\', and to \'Reward focus, development, support, clarity and accuracy\' across the discrete criteria (P=9, C=9, L=9, M=3) — an unargued, plot-retelling answer that ignores the \'Argue three points\' instruction loses on Purpose first, which under the primacy rule then caps Coherence and Language.',
    source: 'Marking scheme 2025 OL, Paper 2 Single Text Q4, \'Expect candidates to be either satisfied or dissatisfied with the ending... material should be presented in the guise of a debate\'; stem ends \'Argue three points in your response\'',
    marks: 30,
  },
  {
    id: 'eng-writeshortstory-composition-pet',
    subjectId: 'english', subjectLabel: 'English', level: 'ordinary',
    questionRef: '2025 OL · Paper 1, Composing Q1',
    stem: 'Imagine that you are a family pet. Write a short story as this pet, entitled, What I get up to when you\'re not around! Your story may be serious, humorous or a combination of both.',
    commandWord: 'Write a short story',
    demand: '\'Write a short story\' is a GENRE instruction, not just \'write about a pet\': the writing must be SHAPED as a story — a beginning, middle and end, central characters, a time-line, a defining moment followed by a change, and a resolution — and, given the framing, told in the first person as the pet. Command of narrative form is itself marked under Purpose.',
    trap: 'Candidates produce a descriptive piece, a personal essay, or a list of a pet\'s daily activities with no narrative arc — forfeiting the \'Understanding of genre\' marks. The 2025 OL scheme makes \'Understanding of genre – the writing should be shaped as a short story having some sense of a beginning – middle – end; central characters; a time-line; a defining moment of experience followed by a change; a resolution\' an explicit Purpose requirement, and expects the story to be \'written in the first person\'; a non-narrative answer fails Purpose first, which under the primacy rule caps Coherence and Language across the full 100 marks.',
    source: 'Marking scheme 2025 OL, Paper 1 Composing Q1 (short story as a family pet), \'Understanding of genre – the writing should be shaped as a short story having some sense of a beginning – middle – end... a resolution\', \'...written in the first person\'',
    marks: 100,
  },
  {
    id: 'eng-writespeech-composition-motion',
    subjectId: 'english', subjectLabel: 'English', level: 'higher',
    questionRef: '2024 HL · Paper 1, Composing Q3',
    stem: 'Write a speech for or against the motion that: "The accelerated pace of modern life detracts from our enjoyment of it."',
    commandWord: 'Write a speech',
    demand: '\'Write a speech\' is a genre-and-stance instruction: argue ONE side of the motion only, and deploy the controlled features of speech-writing — direct address and awareness of audience, rhetorical and inclusive language, anecdote, illustration. The persuasive genre conventions are a marked component, not optional flourish.',
    trap: 'Candidates write a balanced, two-sided discursive essay, or an undifferentiated \'about modern life\' piece with no rhetorical address. The 2024 HL scheme states candidates \'are expected to argue on one side of the motion only\', to \'Pay particular attention to the use of argument and persuasion\', tells examiners to \'Reward demonstration of competence in the controlled use of features of the genre\', and weights \'Understanding of genre – the effective use of some elements of speech-writing\' inside Purpose (P=30 of 100) — a balanced or genre-blind answer loses Purpose first, which under the primacy rule then ceilings Coherence and Language.',
    source: 'Marking scheme 2024 HL, Paper 1 Composing Q3 (speech for/against motion on pace of modern life), \'Candidates are expected to argue on one side of the motion only... Reward demonstration of competence in the controlled use of features of the genre\'',
    marks: 100,
  },
  {
    id: 'eng-writeletter-composition-graffiti',
    subjectId: 'english', subjectLabel: 'English', level: 'ordinary',
    questionRef: '2023 OL · Paper 1, Question B',
    stem: 'Graffiti has started to appear on walls and other surfaces in your local area. It has become a source of controversy, with some people considering it to be art and others considering it vandalism. Write a letter to your local newspaper in which you respond to the issue. In your letter you should: describe what some of the graffiti looks like, explain what your own views are on the controversy and make a suggestion as to what actions local authorities should take in relation to it.',
    commandWord: 'Write a letter',
    demand: '\'Write a letter\' fixes both the GENRE (letter register addressed to a newspaper) and a THREE-part task: describe the graffiti AND explain your views AND suggest actions for the authorities. Every one of the three listed elements must be covered, and the register must read as a letter to a newspaper, not an essay.',
    trap: 'Candidates write a general opinion essay with no letter register, or address only one or two of the three sub-tasks (describe / explain views / suggest actions). The 2023 OL scheme directs that candidates \'should explore the three areas outlined in the question, though not necessarily treating them equally\', to \'Expect an appropriate register\', and assesses across discrete criteria (P=15, C=15, L=15, M=5) — a dropped sub-task or wrong register drags down Purpose, the 30%-primacy criterion that then caps Coherence and Language.',
    source: 'Marking scheme 2023 OL, Paper 1 Question B (letter to local newspaper on graffiti), \'Candidates should explore the three areas outlined in the question, though not necessarily treating them equally. Expect an appropriate register\'',
    marks: 50,
  },
  {
    id: 'eng-suggest-singletext-advice',
    subjectId: 'english', subjectLabel: 'English', level: 'ordinary',
    questionRef: '2025 OL · Paper 2, Single Text Q3 (third element of the relationship task)',
    stem: 'Choose one relationship between two characters in Brontë\'s novel, The Tenant of Wildfell Hall, that you consider fascinating: … Suggest one piece of beneficial advice you would give to either, or both of the characters in this relationship. Your response should demonstrate your knowledge of the text.',
    commandWord: 'Suggest',
    demand: '\'Suggest\' invites your own recommendation — but here it must be ANCHORED in the text: propose one concrete, beneficial piece of advice that fits the actual relationship and plot, showing you know the characters\' situation. The freedom to suggest is fenced by the requirement to demonstrate knowledge of the text.',
    trap: 'Candidates offer generic, free-floating life advice (\'they should communicate more\') that could apply to any couple, with no reference to what actually happens between the characters. The 2025 OL scheme is explicit in its indicative material that \'Advice must be grounded in the plot of the text\' and that the \'response should demonstrate their knowledge of the text\', rewarding \'focus, development, support, clarity and accuracy\' — ungrounded advice fails Purpose and forfeits the development marks. Note this \'Suggest\' is the third element of the 30-mark Q3, not a standalone question.',
    source: 'Marking scheme 2025 OL, Paper 2 Single Text Q3 (\'Suggest one piece of beneficial advice you would give to either, or both of the characters\'), indicative material \'Advice must be grounded in the plot of the text\'',
    marks: 30,
  },
  // ── Mathematics (expansion) ──
  {
    id: 'mat-differentiate-first-principles',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'higher',
    questionRef: 'HL · Paper 1 · Q4(a) · Differentiation',
    stem: 'Differentiate the function f(x) = x² − 7x − 10 from first principles, with respect to x.',
    commandWord: 'Differentiate',
    demand: '\'From first principles\' dictates the METHOD, not just the answer: build f(x + h), form [f(x + h) − f(x)] / h, simplify to 2x + h − 7, then take the limit as h → 0 to reach f′(x) = 2x − 7. The chain of merit-steps (f(x+h) expanded, the difference 2hx + h² − 7h, the limit line) is what is marked.',
    trap: 'Differentiating by the quick power rule instead of the limit definition. The scheme carries the verbatim note \'No credit if first principles is not used\' — a correct 2x − 7 reached via the shortcut scores 0, because Scale 10D (0, 3, 5, 7, 10) marks the process, not the result.',
    source: 'LC Mathematics 2024 HL Paper 1 Q4(a) (\'Differentiate the following function from first principles, with respect to x: f(x) = x² − 7x − 10\'); 2024 HL marking scheme Q4(a) Scale 10D (0, 3, 5, 7, 10), \'Note: No credit if first principles is not used\'',
    marks: 10,
  },
  {
    id: 'mat-express-rearrange-subject',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'higher',
    questionRef: 'HL · Paper 1 · Q1(b) · Algebra',
    stem: 'For real numbers h, j and k, 1/h = k/(j + k). Express k in terms of h and j.',
    commandWord: 'Express',
    demand: '\'Express k in terms of h and j\' means k must end up ALONE on one side with only h and j on the other — k cannot remain on both sides of your final line. Clear the fraction (j + k = hk), gather every k-term, factor (k(1 − h) = −j), then divide: k = −j/(1 − h).',
    trap: 'Stopping once the fraction is cleared, leaving k on both sides (j + k = hk). That earns only Mid Partial Credit (\'Terms with k transposed to one side\'); the High mark needs the factored line \'k(1 − h) = −j\', so finishing without gathering and factoring the k-terms caps you well below the 10.',
    source: 'LC Mathematics 2023 HL Paper 1 Q1(b) (\'Express k in terms of h and j\'); 2023 HL marking scheme Q1(b) Scale 10D (0, 3, 5, 8, 10), Mid Partial Credit \'Terms with k transposed to one side of the equation\', High Partial Credit \'k(1 − h) = −j or equivalent\'',
    marks: 10,
  },
  {
    id: 'mat-sketch-trig-period-range',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'higher',
    questionRef: 'HL · Paper 2 · Q9(b)(ii) · Trigonometric Functions',
    stem: 'Sketch the function V(t) = 110√2 sin(120πt) for one full period, and indicate the period and range of the function on your graph.',
    commandWord: 'Sketch',
    demand: 'The scheme marks this \'Sketch\' as THREE aspects: (1) a sine curve of at least one period including (0, 0), (2) the range indicated on the graph, and (3) the period indicated on the graph. The annotation instruction (\'indicate the period and range\') is itself marked — the labels carry credit, not just the curve shape.',
    trap: 'Drawing a tidy sine curve but never marking the period and range on it. The scheme gives only High Partial Credit for \'Two of the aspects above present on the graph\' — an unlabelled curve forfeits the annotation marks, and a part-curve with no labels drops to Low Partial Credit out of the 10.',
    source: 'LC Mathematics 2021 HL Paper 2 Q9(b)(ii) (\'Sketch the function for 0 ≤ t ≤ p, where p is the period of V(t). Indicate the period and range of the function on your graph\'); 2021 HL marking scheme Q9(b)(ii) Scale 10C (0, 3, 7, 10), \'requiring 3 aspects: sine curve of at least one period including (0,0) / range indicated / period indicated\', High Partial Credit \'Two of the aspects above present on the graph\'',
    marks: 10,
  },
  {
    id: 'mat-verify-point-line',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'ordinary',
    questionRef: 'OL · Paper 2 · Q10(c)(i) · Co-ordinate Geometry',
    stem: 'Verify, using substitution, that the point T(−2, −5) is on the line k: x − y − 3 = 0.',
    commandWord: 'Verify',
    demand: '\'Verify\' signals the result is already given (T is on k) — your job is to PROVE it by substituting BOTH co-ordinates into the line equation and showing the two sides are equal: (−2) − (−5) − 3 = 0, i.e. 0 = 0, True. Closing with \'0 = 0 True\' is the point of the question.',
    trap: 'Substituting x and y but never finishing the arithmetic to the explicit 0 = 0. \'Full correct substitution into equation of line k\' is only High Partial Credit — full marks need the worked-through equality (the model solution ends \'[0 = 0 True]\'). Substituting one value only, or re-deriving the line, misses what \'Verify\' asks.',
    source: 'LC Mathematics 2021 OL Paper 2 Q10(c)(i) (\'The line k has equation x − y − 3 = 0. Verify, using substitution, that the point T(−2, −5) is on k\'); 2021 OL marking scheme Q10(c)(i) Scale 5C (0, 2, 3, 5), High Partial Credit \'Full correct substitution into equation of line k\', model solution \'[0 = 0 True]\'',
    marks: 5,
  },
  {
    id: 'mat-construct-angle-bisector',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'ordinary',
    questionRef: 'OL · Paper 2 · Q6(a) · Geometry (constructions)',
    stem: 'Construct the bisector of the angle X of triangle XYZ, using only a compass and straight edge, showing all construction lines and arcs; hence construct the incentre.',
    commandWord: 'Construct',
    demand: '\'Construct ... using only a compass and straight edge\' bans the protractor — the marks live in the construction ARCS, not the finished line. Swing equal arcs from vertex X, then equal arcs from those two points, draw the bisector through the intersection, then repeat for a second angle so the bisectors meet at the incentre. \'Show all your construction lines and arcs clearly\' is a marked instruction.',
    trap: 'Drawing the bisector freehand, or measuring with a protractor and halving, with no arcs shown. The combined (i)+(ii) Scale 15C (0, 6, 9, 15) gives only Low Partial Credit for \'one correct arc\' and only High Partial Credit for \'One correct bisector\' — strip out the arcs and the second bisector and an accurate-looking but un-constructed figure scores almost nothing of the 15.',
    source: 'LC Mathematics 2024 OL Paper 2 Q6(a) (\'Construct the bisector of the angle X, using only a compass and straight edge. Show all your construction lines and arcs clearly. ... Hence, construct the incentre of the triangle X\'); 2024 OL marking scheme Q6(a)(i)&(ii) Scale 15C (0, 6, 9, 15), Low Partial Credit \'one correct arc in (i)\', High Partial Credit \'One correct bisector\'',
    marks: 15,
  },
  {
    id: 'mat-calculate-percentage-vat',
    subjectId: 'mathematics', subjectLabel: 'Mathematics', level: 'ordinary',
    questionRef: 'OL · Paper 1 · Q1(b) · Arithmetic (percentages)',
    stem: 'A farmer bought livestock for €4716, including VAT. The cost excluding VAT was €4500. Calculate the percentage VAT rate used.',
    commandWord: 'Calculate',
    demand: '\'Calculate\' wants the working carried through to the number the question actually asks for — the VAT RATE. Either take the increase directly, 216/4500 × 100 = 4.8%, or via 4716/4500 × 100 = 104.8 and then SUBTRACT 100 to get 4.8%.',
    trap: 'Computing 4716/4500 × 100 = 104.8 and stopping, mistaking the \'whole including VAT\' percentage for the rate. The scheme gives \'104.8 with work\' only High Partial Credit — you must subtract the 100% to land on 4.8%, or the answer isn\'t the rate the question asked you to calculate.',
    source: 'LC Mathematics 2024 OL Paper 1 Q1(b) (\'A farmer bought some livestock for €4716, including VAT. The cost of the livestock was €4500, excluding VAT. Calculate the percentage VAT rate used\'); 2024 OL marking scheme Q1(b) Scale 10C (0, 4, 6, 10), High Partial Credit \'(4716−4500)/4500 × 100\' and \'104.8 with work\'',
    marks: 10,
  },
  // ── Geography (expansion) ──
  {
    id: 'geo-briefly-explain-farming-economy',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'ordinary',
    questionRef: 'OL · Data-skills (Part Three)',
    stem: 'Briefly explain the importance of farming to the Irish economy.',
    commandWord: 'Briefly explain',
    demand: '\'Briefly explain\' still means EXPLAIN — give a developed reason, not just name a fact. The scheme marks it as \'Brief explanation 2 SRP\'s @ 3m each\', so you need TWO short developed points (e.g. names jobs/exports AND says why that matters), each a creditable point.',
    trap: 'A one-word or single bare statement (\'it gives jobs\') is only one SRP — 3 of the 6 marks. \'Briefly\' tempts students to under-develop, but the scheme awards 2 SRP\'s @ 3m: a second developed point is needed for full marks, so the bare answer leaves half the marks on the table.',
    source: 'LC Geography OL marking scheme 2025 (farming/agriculture data, part v): \'Briefly explain the importance of farming to the Irish economy — Brief explanation 2 SRP\'s @ 3m each, 6m\'',
    marks: 6,
  },
  {
    id: 'geo-identify-account-climate',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'higher',
    questionRef: 'HL · Atmosphere–Ocean (Q23)',
    stem: 'Identify and account for the characteristics of one distinctive global climate that you have studied.',
    commandWord: 'Identify',
    demand: '\'Identify and account for\' is a two-stage instruction repeated per characteristic: NAME the characteristic (identify), then explain WHY it occurs (account for). The scheme runs three aspects, each scoring \'Identifying aspect 4 marks\' + \'Accounting for 8 x SRPs\', plus a separate \'Overall Coherence 20 marks graded\' for how well the whole answer hangs together.',
    trap: 'Identifying characteristics without accounting for them strands you on the 4-mark identify line per aspect and forfeits the 8 SRP\'s of explanation — the bulk of each 20-mark aspect. Candidates also overlook that Overall Coherence is a distinct 20-mark graded component: a list of disconnected facts with no developed, organised account scores low there even before the SRP shortfall.',
    source: 'LC Geography HL marking scheme 2024 (Q23): per aspect Identifying 4m + Accounting for 8 x SRPs (3 aspects @ 20m), plus Overall Coherence 20 marks graded; explanation (accounting) carries the bulk of each aspect',
    marks: 80,
  },
  {
    id: 'geo-state-migration-reasons',
    subjectId: 'geography', subjectLabel: 'Geography', level: 'ordinary',
    questionRef: 'OL · Human Environment (Q10B)',
    stem: 'State two reasons why people migrate from rural areas to urban areas.',
    commandWord: 'State',
    demand: '\'State\' wants the named item only — name two valid reasons (e.g. more jobs, better services) and stop. No explanation, no \'because\', no paragraph: each reason scores in full the moment it is named, and the scheme credits it as \'Valid reasons stated\' at 2m + 2m.',
    trap: 'On this same migration topic the NEXT part switches to \'Describe and explain\' (6 SRP\'s @ 3m, where you MUST explain) — so students carry that habit back into the \'State\' part and write developed paragraphs that earn nothing extra: the cap here is 2m + 2m for two named reasons. Over-explaining a \'State\' part burns time you need for the SRP parts; under-naming (giving one reason) forfeits half.',
    source: 'LC Geography OL marking scheme 2024 (Q10B Migration, part i): \'State two reasons why people migrate from rural areas to urban areas — Valid reasons stated, 2m + 2m\'; contrast part (ii) \'Describe and explain... 6 SRP\'s @ 3m each, 18m\'',
    marks: 4,
  },
  // ── Biology (expansion) ──
  {
    id: 'bio-define-enzyme',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'ordinary',
    questionRef: 'OL · Enzymes',
    stem: 'Define the term enzyme.',
    commandWord: 'Define',
    demand: 'Give the precise, technical meaning in the tightest correct phrase — for \'Define the term enzyme\' the scheme accepts only the defining idea \'(protein) catalyst\'. State exactly what it IS; brevity plus accuracy, not a description of what it does.',
    trap: 'The scheme credits only the defining phrase \'(Protein) catalyst\' (3 marks). Describing what enzymes do (\'they speed up reactions in digestion\', \'they break down food\') instead of naming what they ARE misses the exact term and scores 0. On \'Define the term\', a roundabout, example-led or function-only answer throws away the full mark — the definition must match the scheme\'s exact concept.',
    source: 'LC Biology OL marking scheme 2024, Q9(a)(i) \'Define the term enzyme\' — \'(Protein) catalyst\' 3 marks',
    marks: 3,
  },
  {
    id: 'bio-compare-seed-vegetative',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'ordinary',
    questionRef: 'OL · Reproduction in the flowering plant',
    stem: 'Compare reproduction by seed with reproduction by vegetative propagation: variation, dispersal.',
    commandWord: 'Compare',
    demand: 'Bring out the DIFFERENCE under each heading by setting the two methods against each other — e.g. seed reproduction gives MORE variation, and WIDER dispersal. The comparative word (\'more\', \'wider\') relative to the other method is the creditable point, not a fact about one method in isolation.',
    trap: 'The scheme answers are comparatives — \'More (variation) (in reproduction by seed)\' and \'Wider (dispersal) (in reproduction by seed)\'. Writing a true statement about only one method (e.g. \'seeds are dispersed by wind\') without the explicit comparison to vegetative propagation does not match the comparative answer and forfeits the mark. \'Compare\' means a relative statement under each heading, not two separate descriptions.',
    source: 'LC Biology OL marking scheme 2022, Q16(d)(vi) \'Compare reproduction by seed with reproduction by vegetative propagation under the following headings:\' — Variation: \'More (variation)…\'; Dispersal: \'Wider (dispersal)…\' (cumulative response-count table; ~3 marks per correct response)',
    marks: 6,
  },
  {
    id: 'bio-calculate-percentage-frequency',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'ordinary',
    questionRef: 'OL · Ecology (quantitative study)',
    stem: 'In an ecosystem study, dandelion was found in 30 of 50 quadrats and grass in all 50 quadrats. Calculate the percentage frequency of dandelion and grass in this habitat.',
    commandWord: 'Calculate',
    demand: 'Carry the arithmetic through to the actual numerical answer for EACH organism, as a percentage — not a method or a fraction left unworked. Percentage frequency = (quadrats containing the species ÷ total quadrats) × 100; with dandelion present in 30 of 50 quadrats and grass in all 50, dandelion = 30/50 × 100 = 60% and grass = 50/50 × 100 = 100%.',
    trap: 'The scheme awards the marks to the finished values (\'Dandelion: 60%\' and \'Grass: 100%\') — two separate award points. Calculating only one of the two asked-for values, leaving the answer as a fraction (30/50), or omitting the % so it isn\'t a frequency, loses the mark for that part. \'Calculate\' is not satisfied by stating the formula; the worked numerical answer for each named organism is the marked thing.',
    source: 'LC Biology OL marking scheme 2023, Q8(b)(ii) \'Calculate the percentage frequency of dandelion and grass in this habitat.\' — \'Dandelion: 60%\', \'Grass: 100%\' (cumulative response-count table for Q8(b)(i)–(iii))',
    marks: 6,
  },
  {
    id: 'bio-identify-triglyceride-phospholipid',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'higher',
    questionRef: 'HL · Biomolecules (Section A)',
    stem: 'Identify one difference between a triglyceride and a phospholipid.',
    commandWord: 'Identify',
    demand: 'Pin down a specific point of difference and state BOTH sides of it in one breath — e.g. \'a triglyceride has three fatty acids whereas a phospholipid has two\', or \'a triglyceride has no phosphate but a phospholipid has a phosphate\'. \'Identify one difference\' means a paired contrast, not a fact about just one molecule.',
    trap: 'The scheme answer names both halves (\'Triglyceride has three fatty acids and phospholipid has two fatty acids\'); a one-sided statement (\'a phospholipid contains phosphate\') isn\'t a difference and scores 0. This is a Section A item, so the surplus-answer rule bites: a surplus WRONG point cancels a correct one — pad the answer with an extra incorrect \'difference\' and you can lose the mark you had already earned.',
    source: 'LC Biology HL marking scheme 2021, Q1(b) (Section A, 5(4)) \'Identify one difference between a triglyceride and a phospholipid\'; HL 2024 marking-scheme intro rule 3 — \'Surplus answers: [only in Section A] - A surplus wrong answer cancels the marks awarded\'',
    marks: 4,
  },
  {
    id: 'bio-name-complementary-base-pair',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'ordinary',
    questionRef: 'OL · DNA',
    stem: 'Name a complementary base pair found in DNA.',
    commandWord: 'Name',
    demand: 'Just give the answer the term asks for, exactly — here a base PAIR, i.e. two bases that pair together: adenine and thymine (A and T), or guanine and cytosine (G and C). \'Name\' rewards the correct named item only; no explanation is needed, but the item must match what was asked.',
    trap: 'The scheme requires a PAIR — \'Adenine and thymine (or A and T) or Guanine and cytosine (or G and C)\'. Naming a single base (\'adenine\'), or a non-complementary pairing (e.g. \'adenine and guanine\'), does not answer \'a complementary base pair\' and scores 0. \'Name\' is unforgiving about precision: the correct named item, complete and correct, is the whole mark.',
    source: 'LC Biology OL marking scheme 2021, Q12(iii) \'Name a complementary base pair found in DNA\' — \'Adenine and thymine (or A and T) or Guanine and cytosine (or G and C)\' 3 marks',
    marks: 3,
  },
  {
    id: 'bio-givetwo-scientific-method',
    subjectId: 'biology', subjectLabel: 'Biology', level: 'higher',
    questionRef: 'HL · The scientific method',
    stem: 'Give two limitations of the scientific method.',
    commandWord: 'Give two',
    demand: 'Provide exactly TWO short, DISTINCT, correct points — no description needed, but they must be two genuinely separate limitations (e.g. human error, human bias, constrained by existing knowledge or technology, application to nature, experimental design). \'Give two\' is a counting cue: each separate valid limitation is one creditable point.',
    trap: 'The scheme lists discrete limitations separated by a solidus and credits \'Any two 2(3)\' — so it caps at two. Writing one idea twice in different words (\'people make mistakes / humans aren\'t perfect\') counts as a single point and forfeits the second mark, and listing five limitations earns nothing beyond the first two correct ones. \'Give two\' rewards two distinct hits, not volume.',
    source: 'LC Biology HL marking scheme 2025, Q7(d) (and HL 2023 Q2(f)) \'Give two limitations of the scientific method\' — accidental discovery / application to nature / (human) bias / human error / constrained by existing knowledge / constrained by existing technology / ability to interpret results / experimental design — \'Any two 2(3)\'',
    marks: 6,
  },
];

/** Subject ids that currently have command-word content (drives the picker). */
export function commandSubjects(): { subjectId: string; subjectLabel: string; count: number }[] {
  const map = new Map<string, { subjectId: string; subjectLabel: string; count: number }>();
  for (const q of COMMAND_WORD_QUESTIONS) {
    const e = map.get(q.subjectId) ?? { subjectId: q.subjectId, subjectLabel: q.subjectLabel, count: 0 };
    e.count++;
    map.set(q.subjectId, e);
  }
  return [...map.values()];
}

export function questionsForSubject(subjectId: string): CommandWordQuestion[] {
  return COMMAND_WORD_QUESTIONS.filter(q => q.subjectId === subjectId);
}
