/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CategoryType } from './components/KnowledgeTree';
import { CourseData } from './components/Library';

export const categoryColorMap: Record<CategoryType, { gradient: string; accentColor: string; auraColor: string; pillBgColor: string }> = {
  'architecture-mindset': {
    gradient: 'bg-gradient-to-tr from-blue-50 via-white to-zinc-50',
    accentColor: 'text-blue-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(59,130,246,0.15)]',
    pillBgColor: 'bg-blue-700',
  },
  'science-growth': {
    gradient: 'bg-gradient-to-tr from-amber-50 via-white to-zinc-50',
    accentColor: 'text-amber-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(245,158,11,0.15)]',
    pillBgColor: 'bg-amber-700',
  },
  'learning-cheat-codes': {
    gradient: 'bg-gradient-to-tr from-teal-50 via-white to-zinc-50',
    accentColor: 'text-teal-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(13,148,136,0.15)]',
    pillBgColor: 'bg-teal-700',
  },
  'subject-specific-science': {
    gradient: 'bg-gradient-to-tr from-slate-50 via-white to-zinc-50',
    accentColor: 'text-slate-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(71,85,105,0.15)]',
    pillBgColor: 'bg-slate-700',
  },
  'exam-zone': {
    gradient: 'bg-gradient-to-tr from-red-50 via-white to-zinc-50',
    accentColor: 'text-red-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(220,38,38,0.15)]',
    pillBgColor: 'bg-red-700',
  },
};

const COURSE_DEFINITIONS = [
  {
    id: 'agency-protocol',
    category: 'architecture-mindset',
    title: 'Establishing Your Academic Identity',
    subtitle: 'The Driver\'s Manual',
    description: 'Synthesising research on motivation and identity, this module provides the blueprint for becoming the "Origin" of your academic success.',
    sectionsCount: 6,
    tags: ['Mindset', 'Motivation'],
  },
  {
    id: 'hope-protocol',
    category: 'architecture-mindset',
    title: 'The Science of Hope',
    subtitle: 'Your Brain\'s Engineering Manual',
    description: 'Explore the neurobiology of hope, learning how to engineer the mental circuits for motivation and resilience under pressure.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Resilience'],
  },
  {
    id: 'affirming-values-protocol',
    category: 'architecture-mindset',
    title: 'Affirming Values',
    subtitle: 'The Psychological Shield',
    description: 'Learn the science of "stereotype threat" and how a 15-minute writing exercise can act as a psychological shield in high-stakes exams.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'best-possible-self-protocol',
    category: 'architecture-mindset',
    title: 'Finding Your Best Possible Self',
    subtitle: 'The Future-Proofing Playbook',
    description: 'Learn how to turn vague daydreams into actionable plans using the scientifically-proven WOOP method for goal achievement.',
    sectionsCount: 5,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'grammar-of-grit-protocol',
    category: 'architecture-mindset',
    title: 'The Grammar of Grit',
    subtitle: 'The Language of Resilience',
    description: 'Discover how the words you use to define yourself can either build resilience or create fragility in the face of failure.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'agency-architecture-protocol',
    category: 'architecture-mindset',
    title: 'Controlling the Controllables',
    subtitle: 'The Attribution Retraining Guide',
    description: 'Learn to distinguish between what you can and cannot control, and rewire your brain to see failure as feedback, not a final verdict.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'strategic-advantage-protocol',
    category: 'architecture-mindset',
    title: 'Your Strategic Advantage',
    subtitle: 'The Narrative Identity Playbook',
    description: 'Discover how to turn your personal story of adversity into your greatest competitive advantage in academia and beyond.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'self-efficacy-protocol',
    category: 'architecture-mindset',
    title: 'Self Efficacy',
    subtitle: 'The Architecture of Agency',
    description: 'Move beyond "trying harder" and learn the science of building bulletproof belief in your own ability. This module deconstructs the myth of "natural talent" and gives you the tools to reverse-engineer success.',
    sectionsCount: 5,
    tags: ['Mindset', 'Motivation'],
  },
  {
    id: 'illusion-of-competence-protocol',
    category: 'learning-cheat-codes',
    title: 'Overcoming Illusions of Competence',
    subtitle: 'The Fluency Illusion',
    description: 'Deconstruct the cognitive biases that trick you into feeling confident when you\'re unprepared, and learn the science-backed strategies to build real, durable knowledge.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'procrastination-protocol',
    category: 'architecture-mindset',
    title: 'Understanding Procrastination and Motivation',
    subtitle: 'The Architecture of Delay',
    description: 'Go beyond "laziness" and understand the real science of why you delay. Learn to master your motivation with evidence-based strategies.',
    sectionsCount: 8,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'reframing-catastrophic-thoughts-protocol',
    category: 'architecture-mindset',
    title: 'Reframing Catastrophic Thoughts',
    subtitle: 'The CBT Toolkit',
    description: 'Deconstruct the neurobiology of exam panic and learn the gold-standard psychological tools (CBT & ACT) to dismantle catastrophic thinking and regain control.',
    sectionsCount: 8,
    tags: ['Resilience', 'Performance Psych'],
  },
  {
    id: 'emotional-intelligence-protocol',
    category: 'architecture-mindset',
    title: 'Building Emotional Intelligence',
    subtitle: 'The Stress Management Toolkit',
    description: 'Learn the neurobiology of exam stress and master the "top-down" and "bottom-up" strategies to transform anxiety into a high-performance state.',
    sectionsCount: 8,
    tags: ['Performance Psych', 'Resilience'],
  },
  {
    id: 'neuroplasticity-protocol',
    category: 'science-growth',
    title: 'Neuroplasticity',
    subtitle: 'Your Brain\'s User Manual',
    description: 'Discover that your brain isn\'t fixed. Learn the science of how your brain physically changes when you study, and how to use this to your advantage.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'myelin-manual-protocol',
    category: 'science-growth',
    title: 'The Myelin Manual',
    subtitle: 'The Neurobiology of Mastery',
    description: 'Reframe "struggle" from a sign of failure into the biological trigger for building faster, more efficient brain circuits. This is the science of Deep Practice.',
    sectionsCount: 5,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'praise-protocol',
    category: 'science-growth',
    title: 'The Power of Praise',
    subtitle: 'The Architecture of Potential',
    description: 'Learn how the language you use to interpret success and failure programs your brain for a fixed or growth mindset. It\u2019s not what you say, but how you say it.',
    sectionsCount: 6,
    tags: ['Mindset', 'Motivation'],
  },
  {
    id: 'effective-struggle-protocol',
    category: 'science-growth',
    title: 'Effective Struggle and Growth',
    subtitle: 'The Cognitive Architecture of Friction',
    description: 'Synthesizing key learning theories to define the "sweet spot" of difficulty where real learning happens. Re-calibrate your internal dashboard for what growth feels like.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'science-of-making-mistakes-protocol',
    category: 'science-growth',
    title: 'The Science of Making Mistakes',
    subtitle: 'The Neural Architecture of Failure',
    description: 'Learn why your brain\'s reaction to mistakes predicts success, and how to rewire it for resilience under pressure in high-stakes exams.',
    sectionsCount: 5,
    tags: ['Brain Science', 'Resilience'],
  },
  {
    id: 'autodidact-engine-protocol',
    category: 'learning-cheat-codes',
    title: 'Using Feedback Loops',
    subtitle: 'The Autodidact\'s Engine',
    description: 'Become your own teacher by learning to build autonomous feedback loops. This is the science of Deliberate Practice without a coach.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Productivity'],
  },
  {
    id: 'power-of-yet-protocol',
    category: 'science-growth',
    title: 'The Power of "Yet"',
    subtitle: 'The Persistence Playbook',
    description: 'A simple, three-letter word that can rewire your brain for resilience. This module unpacks the neuroscience of error-processing and gives you a practical protocol to turn failure from a verdict into a fuel source.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'controllable-variables-protocol',
    category: 'science-growth',
    title: 'Using Controllable Variables to Grow',
    subtitle: 'The Biological Blueprint',
    description: 'Learn to manage your brain as a biological system. This module covers the non-negotiable inputs of Sleep, Nutrition, and Exercise required for high performance.',
    sectionsCount: 6,
    tags: ['Performance Psych', 'Brain Science'],
  },
  {
    id: 'reframing-progress-protocol',
    category: 'architecture-mindset',
    title: 'Reframing Progress',
    subtitle: 'The Outcome-Based Approach',
    description: 'Shift from measuring "hours logged" to "wins secured." This module gives you the project management tools to study smarter, not just harder.',
    sectionsCount: 7,
    tags: ['Productivity', 'Mindset'],
  },
  {
    id: 'linking-study-future-goals-protocol',
    category: 'science-growth',
    title: 'Linking Study to Future Goals',
    subtitle: 'The Architecture of Purpose',
    description: 'Deconstruct the "why bother?" problem and learn the science of linking today\'s effort to tomorrow\'s success. This is the antidote to burnout.',
    sectionsCount: 8,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'growth-mindset-protocol',
    category: 'science-growth',
    title: 'The Growth Playbook',
    subtitle: 'The Mind\'s Operating System',
    description: 'Upgrade your brain\'s core operating system from "fixed" to "growth." This module deconstructs the science of neuroplasticity and gives you the tools to see challenges as opportunities.',
    sectionsCount: 6,
    tags: ['Mindset', 'Brain Science'],
  },
  {
    id: 'mastering-active-recall-protocol',
    category: 'learning-cheat-codes',
    title: 'Mastering Active Recall',
    subtitle: 'The Test Effect',
    description: 'Go beyond "practice testing" and learn the science of why active retrieval is the single most effective way to build durable, long-term memory.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'mastering-spaced-repetition-protocol',
    category: 'learning-cheat-codes',
    title: 'Mastering Spaced Repetition',
    subtitle: 'The Forgetting Curve Method',
    description: 'Learn to defeat the "forgetting curve" by understanding the science of when and how often to review material for maximum long-term retention.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Productivity'],
  },
  {
    id: 'mastering-interleaving-protocol',
    category: 'learning-cheat-codes',
    title: 'Mastering Interleaving',
    subtitle: 'The Topic Salad Method',
    description: 'Ditch "blocked" study and learn the science of mixing topics to build deep, flexible knowledge that stands up under exam pressure.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'cognitive-architecture-protocol',
    category: 'learning-cheat-codes',
    title: 'Cognitive Architecture',
    subtitle: 'Your Brain\'s User Manual',
    description: 'Understand the fundamental architecture of your memory to move information from the fragile workbench of Short-Term Memory to the permanent library of Long-Term Memory.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'elaborative-interrogation-protocol',
    category: 'learning-cheat-codes',
    title: 'Elaborative Interrogation',
    subtitle: 'The "Why" Method',
    description: 'Move beyond rote learning by mastering the art of asking "Why?". This module teaches you how to transform shallow facts into deep, interconnected knowledge for the new Leaving Cert.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Mindset'],
  },
  {
    id: 'cognitive-endurance-protocol',
    category: 'learning-cheat-codes',
    title: 'Cognitive Endurance',
    subtitle: 'The Marathon Method',
    description: 'The Leaving Cert isn\'t a sprint. Learn the science of mental stamina and train your brain to perform under the sustained pressure of the exam timetable.',
    sectionsCount: 6,
    tags: ['Performance Psych', 'Brain Science'],
  },
  {
    id: 'mental-modelling-protocol',
    category: 'learning-cheat-codes',
    title: 'Mental Modelling',
    subtitle: 'The Mind\'s Eye Method',
    description: 'Learn to see the answer in your mind\'s eye. This module deconstructs the \'hidden curriculum\' of subjects like DCG and Engineering, teaching you how to build robust mental simulations.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Subject Strategy'],
  },
  {
    id: 'bimodal-brain-protocol',
    category: 'learning-cheat-codes',
    title: 'Focused vs Diffuse Mode',
    subtitle: 'The Bimodal Brain',
    description: 'Your brain has two gears. Learn to switch between intense focus and creative relaxation to unlock deep learning and solve complex problems.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Productivity'],
  },
  {
    id: 'learning-math-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Maths',
    subtitle: 'Deconstructing the Exam',
    description: 'A strategic deep-dive into the structure, marking schemes, and high-yield topics of the Leaving Cert Higher Level Maths exam.',
    sectionsCount: 9,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-foreign-languages-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Foreign Languages',
    subtitle: 'The Language Mastery Guide',
    description: 'A strategic deconstruction of the MFL exams, providing a bifurcated strategy for both foundational proficiency and top-tier performance.',
    sectionsCount: 8,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-the-sciences-protocol',
    category: 'subject-specific-science',
    title: 'Mastering the Sciences',
    subtitle: 'The STEM Grade Optimization Guide',
    description: 'A strategic deconstruction of the STEM exams, revealing the "hidden curriculum" of Biology, Chemistry, Physics, and Ag Science.',
    sectionsCount: 7,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-english-protocol',
    category: 'subject-specific-science',
    title: 'Mastering English',
    subtitle: 'The PCLM Framework',
    description: 'A strategic deconstruction of the Leaving Cert English exam, focusing on mastering the PCLM marking scheme and optimizing for H1 performance.',
    sectionsCount: 7,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-business-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Business',
    subtitle: 'The Grade Optimization Guide',
    description: 'Deconstruct the Business exam for 2026, focusing on the ABQ, "outcome verbs", and the "SEE/SEEE" structure to engineer a H1.',
    sectionsCount: 6,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'applied-sciences-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Applied Sciences',
    subtitle: 'The 2026 Technical Briefs',
    description: 'A deep dive into the 2026 briefs for Engineering, DCG, CS, Construction & Technology, blending theory with project strategy.',
    sectionsCount: 6,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-the-creatives-protocol',
    category: 'subject-specific-science',
    title: 'Mastering the Creatives',
    subtitle: 'The Art, Music & Film Guide',
    description: 'A strategic deconstruction of the \'creative\' subjects, revealing them as learnable skills governed by process, not just talent.',
    sectionsCount: 6,
    tags: ['Subject Strategy', 'Exam Tactics', 'Creativity'],
  },
  {
    id: 'leaving-cert-strategy-protocol',
    category: 'exam-zone',
    title: 'The Points Playbook',
    subtitle: 'The Economics of Academic Assessment',
    description: 'Deconstruct the Leaving Cert as a points-based marketplace and learn the tactical framework for maximizing your score.',
    sectionsCount: 6,
    tags: ['Exam Tactics', 'Productivity'],
  },
  {
    id: 'reverse-engineering-protocol',
    category: 'exam-zone',
    title: 'Reverse Engineering Your Schedule',
    subtitle: 'The Temporal Architecture',
    description: 'Ditch the failed \'start-to-finish\' study plan. Learn to plan backwards from your exam date to create a realistic, resilient, and effective study schedule.',
    sectionsCount: 6,
    tags: ['Productivity', 'Exam Tactics'],
  },
  {
    id: 'exam-hall-strategies-protocol',
    category: 'exam-zone',
    title: 'Exam Hall Strategies',
    subtitle: 'The Operational Playbook',
    description: 'Deconstruct the exam hall as a resource-management challenge and learn the operational tactics used by elite performers to close the "Execution Gap".',
    sectionsCount: 7,
    tags: ['Exam Tactics', 'Performance Psych'],
  },
  {
    id: 'exam-crisis-management-protocol',
    category: 'exam-zone',
    title: 'Exam Crisis Management',
    subtitle: 'The Cognitive Athlete\'s Playbook',
    description: 'Learn the neurobiology of exam stress and master the physiological protocols to maintain mental stamina and overcome the "Blank Mind" phenomenon.',
    sectionsCount: 7,
    tags: ['Resilience', 'Performance Psych'],
  },
  {
    id: 'game-day-protocol',
    category: 'exam-zone',
    title: 'Game Day: Peak Performance',
    subtitle: 'Peak Performance on Demand',
    description: 'Transform your exam preparation by adopting the mindset and physiological protocols of an elite athlete. This is your playbook for peak performance.',
    sectionsCount: 8,
    tags: ['Performance Psych', 'Exam Tactics'],
  },
  {
    id: 'mastering-the-humanities-protocol',
    category: 'subject-specific-science',
    title: 'Mastering the Humanities',
    subtitle: 'The Grade Optimisation Guide',
    description: 'Deconstruct the "hidden curriculum" of History, Geography, and Politics & Society to transform your strategic application and maximize your grade.',
    sectionsCount: 5,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'digital-distraction-protocol',
    category: 'learning-cheat-codes',
    title: 'Creating Barriers for Digital Distractions',
    subtitle: 'The Cognitive Sovereignty Guide',
    description: 'A blueprint for reclaiming your focus from the attention economy, using neuroscience-backed hardware, software, and behavioral barriers.',
    sectionsCount: 7,
    tags: ['Productivity', 'Performance Psych'],
  },
  {
    id: 'learning-radar-protocol',
    category: 'learning-cheat-codes',
    title: 'The Learning Radar',
    subtitle: 'The Metacognitive Calibration Guide',
    description: 'Discover why most students can\'t accurately judge what they know — and learn the trainable skill of metacognitive calibration backed by Kornell, Bjork, Dunning, and Kruger.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'note-taking-paradox-protocol',
    category: 'learning-cheat-codes',
    title: 'The Note-Taking Paradox',
    subtitle: 'The Generative Processing Method',
    description: 'Discover why students who write more notes learn less — and master the science of note-taking that actually builds durable knowledge.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Productivity'],
  },
  {
    id: 'teaching-effect-protocol',
    category: 'science-growth',
    title: 'The Teaching Effect',
    subtitle: 'The Protégé Effect',
    description: 'Learn why preparing to teach someone produces deeper learning than preparing for a test — even if you never actually teach.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'cognitive-load-protocol',
    category: 'learning-cheat-codes',
    title: 'Cognitive Load',
    subtitle: 'The Working Memory Blueprint',
    description: 'Your working memory can hold only 4 items at once. Learn why most study sessions accidentally overload this bottleneck — and how to design sessions that respect your brain\'s limits.',
    sectionsCount: 5,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'implementation-protocol',
    category: 'architecture-mindset',
    title: 'The Implementation Playbook',
    subtitle: 'The Intention-Action Blueprint',
    description: 'Motivation doesn\'t predict action. Learn the single most powerful psychological technique for closing the gap between planning to study and actually doing it.',
    sectionsCount: 5,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'context-effect-protocol',
    category: 'learning-cheat-codes',
    title: 'The Context Effect',
    subtitle: 'The Environmental Encoding Guide',
    description: 'Where you study changes what you remember. Learn why studying in multiple places beats one perfect spot — and how to design environments that enhance your brain\'s encoding.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Performance Psych'],
  },
  {
    id: 'points-optimization-protocol',
    category: 'exam-zone',
    title: 'The 625 Blueprint',
    subtitle: 'The Statistical Optimization Guide',
    description: 'Treat the Leaving Cert as a mathematical optimization problem. Use real H1 rate data, grade economics, and marking scheme mechanics to engineer your maximum possible score.',
    sectionsCount: 7,
    tags: ['Exam Tactics', 'Productivity'],
  },
] as const;

export const categoryTitles: Record<CategoryType, string> = {
  'architecture-mindset': 'The Architecture of your Mindset',
  'science-growth': 'The Science of Growth',
  'learning-cheat-codes': 'The Science of Learning Effectively',
  'exam-zone': 'Exam Strategy and Points Maximisation',
  'subject-specific-science': 'Subject Specific Science',
};

export const ALL_COURSES: CourseData[] = COURSE_DEFINITIONS.map(course => {
  const colors = categoryColorMap[course.category] || {
    gradient: 'bg-gradient-to-tr from-zinc-50 via-white to-zinc-50',
    accentColor: 'text-zinc-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(71,85,105,0.15)]',
  };
  return {
    ...course,
    ...colors,
  };
});
