/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CategoryType } from './components/KnowledgeTree';
import { CourseData } from './components/Library';

export const categoryColorMap: Record<CategoryType, { gradient: string; accentColor: string; auraColor: string; pillBgColor: string }> = {
  'architecture-mindset': {
    gradient: 'bg-gradient-to-tr from-blue-50 via-white to-zinc-50',
    accentColor: 'text-blue-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(59,130,246,0.15)]',
    pillBgColor: 'bg-blue-700',
  },
  'science-growth': {
    gradient: 'bg-gradient-to-tr from-amber-50 via-white to-zinc-50',
    accentColor: 'text-amber-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(245,158,11,0.15)]',
    pillBgColor: 'bg-amber-700',
  },
  'learning-cheat-codes': {
    gradient: 'bg-gradient-to-tr from-teal-50 via-white to-zinc-50',
    accentColor: 'text-teal-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(13,148,136,0.15)]',
    pillBgColor: 'bg-teal-700',
  },
  'subject-specific-science': {
    gradient: 'bg-gradient-to-tr from-slate-50 via-white to-zinc-50',
    accentColor: 'text-slate-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(71,85,105,0.15)]',
    pillBgColor: 'bg-slate-700',
  },
  'exam-zone': {
    gradient: 'bg-gradient-to-tr from-red-50 via-white to-zinc-50',
    accentColor: 'text-red-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(220,38,38,0.15)]',
    pillBgColor: 'bg-red-700',
  },
};

const COURSE_DEFINITIONS = [
  {
    id: 'agency-protocol',
    category: 'architecture-mindset',
    title: 'The Driver\'s Manual',
    subtitle: 'Taking the Wheel of Your Education',
    description: 'Learn how to stop being a passenger in your own school life and start driving toward the future you actually want.',
    sectionsCount: 6,
    tags: ['Mindset', 'Motivation'],
  },
  {
    id: 'hope-protocol',
    category: 'architecture-mindset',
    title: 'The Science of Hope',
    subtitle: 'Your Brain\'s Engineering Manual',
    description: 'Hope isn\'t wishful thinking — it\'s a skill you can train. Learn how your brain creates motivation and how to get it working for you.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Resilience'],
  },
  {
    id: 'affirming-values-protocol',
    category: 'architecture-mindset',
    title: 'Affirming Values',
    subtitle: 'The Psychological Shield',
    description: 'Discover the invisible pressure that steals your brainpower in exams — and a simple 15-minute exercise that shields you from it.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'best-possible-self-protocol',
    category: 'architecture-mindset',
    title: 'Best Possible Self',
    subtitle: 'The Future-Proofing Playbook',
    description: 'Daydreaming about the future feels good — but it can kill your motivation. Learn how to turn vague wishes into real plans that stick.',
    sectionsCount: 5,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'grammar-of-grit-protocol',
    category: 'architecture-mindset',
    title: 'The Grammar of Grit',
    subtitle: 'The Language of Resilience',
    description: 'The way you talk to yourself after a setback matters more than you think. This module shows you how to spot the patterns and change them.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'agency-architecture-protocol',
    category: 'architecture-mindset',
    title: 'Controlling the Controllables',
    subtitle: 'The Attribution Retraining Guide',
    description: 'Learn to distinguish between what you can and cannot control, and rewire your brain to see failure as feedback, not a final verdict.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'strategic-advantage-protocol',
    category: 'architecture-mindset',
    title: 'Your Strategic Advantage',
    subtitle: 'The Narrative Identity Playbook',
    description: 'Learn how to take the tough parts of your story and turn them into your biggest strength -- in school, in college, and in life.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'self-efficacy-protocol',
    category: 'architecture-mindset',
    title: 'Self Efficacy',
    subtitle: 'The Architecture of Agency',
    description: '"Try harder" is useless advice. This module shows you how to actually build real belief in yourself — where it comes from, why some people seem to have more of it, and how you can grow yours from scratch.',
    sectionsCount: 5,
    tags: ['Mindset', 'Motivation'],
  },
  {
    id: 'illusion-of-competence-protocol',
    category: 'learning-cheat-codes',
    title: 'Overcoming Illusions of Competence',
    subtitle: 'Why You Think You Know It (But Don\'t)',
    description: 'Ever walked out of a study session feeling confident, only to blank in the exam? Here\'s why that happens and how to make sure what you study actually sticks.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'procrastination-protocol',
    category: 'architecture-mindset',
    title: 'Understanding Procrastination and Motivation',
    subtitle: 'The Architecture of Delay',
    description: 'Procrastination isn\'t laziness -- your brain is just wired to dodge things that feel bad. Learn what\'s really going on and how to get yourself moving.',
    sectionsCount: 8,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'reframing-catastrophic-thoughts-protocol',
    category: 'architecture-mindset',
    title: 'Reframing Catastrophic Thoughts',
    subtitle: 'The CBT Toolkit',
    description: 'Ever had your brain spiral into worst-case scenarios before an exam? Learn practical tools to catch those panic thoughts, challenge them, and take back control.',
    sectionsCount: 8,
    tags: ['Resilience', 'Performance Psych'],
  },
  {
    id: 'emotional-intelligence-protocol',
    category: 'architecture-mindset',
    title: 'Building Emotional Intelligence',
    subtitle: 'The Stress Management Toolkit',
    description: 'Understand why your brain freaks out during exams and learn practical techniques -- both mental and physical -- to turn stress into something that works for you, not against you.',
    sectionsCount: 8,
    tags: ['Performance Psych', 'Resilience'],
  },
  {
    id: 'neuroplasticity-protocol',
    category: 'science-growth',
    title: 'Neuroplasticity',
    subtitle: 'Your Brain\'s User Manual',
    description: 'Your brain isn\'t stuck the way it is -- it physically changes shape when you learn new things. This module shows you how that works and how to make it work for you.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'myelin-manual-protocol',
    category: 'science-growth',
    title: 'The Myelin Manual',
    subtitle: 'How Your Brain Gets Faster',
    description: 'That stuck, frustrated feeling when you\'re working on something hard? It\'s not a sign you\'re failing — it\'s how your brain builds faster connections. Learn why the hard stuff is the stuff that actually works.',
    sectionsCount: 5,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'praise-protocol',
    category: 'science-growth',
    title: 'The Power of Praise',
    subtitle: 'How Words Shape Your Mindset',
    description: 'The way people praise you — and the way you talk to yourself — can either set you up to grow or keep you stuck. Here\'s how to tell the difference.',
    sectionsCount: 6,
    tags: ['Mindset', 'Motivation'],
  },
  {
    id: 'effective-struggle-protocol',
    category: 'science-growth',
    title: 'Effective Struggle and Growth',
    subtitle: 'Why the Hard Stuff Is the Stuff That Works',
    description: 'That frustrated feeling when you\'re stuck on a hard question? It\'s not a sign you\'re failing — it\'s how real learning actually happens. Learn to find the sweet spot of difficulty and reset your idea of what good study feels like.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'science-of-making-mistakes-protocol',
    category: 'science-growth',
    title: 'The Science of Making Mistakes',
    subtitle: 'Why Mistakes Are Your Best Study Tool',
    description: 'Your brain does something incredible when you mess up — if you let it. Here\'s how to stop fearing mistakes and start using them to get better, especially when the pressure is on.',
    sectionsCount: 5,
    tags: ['Brain Science', 'Resilience'],
  },
  {
    id: 'autodidact-engine-protocol',
    category: 'learning-cheat-codes',
    title: 'Using Feedback Loops',
    subtitle: 'How to Be Your Own Teacher',
    description: 'When you\'re studying alone, you don\'t have a teacher to tell you what you\'re getting wrong. This module shows you how to build that feedback into your study sessions yourself.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Productivity'],
  },
  {
    id: 'power-of-yet-protocol',
    category: 'science-growth',
    title: 'The Power of "Yet"',
    subtitle: 'The Persistence Playbook',
    description: 'One tiny word that changes everything about how you handle setbacks. Learn a dead-simple three-step method to stop beating yourself up when things go wrong and start actually moving forward.',
    sectionsCount: 5,
    tags: ['Mindset', 'Resilience'],
  },
  {
    id: 'controllable-variables-protocol',
    category: 'science-growth',
    title: 'Using Controllable Variables to Grow',
    subtitle: 'Sleep, Food, and Exercise',
    description: 'Your brain runs on three things: sleep, food, and exercise. Get these right and everything else gets easier. This module shows you how they actually work and what to do about it.',
    sectionsCount: 6,
    tags: ['Performance Psych', 'Brain Science'],
  },
  {
    id: 'reframing-progress-protocol',
    category: 'architecture-mindset',
    title: 'Reframing Progress',
    subtitle: 'The Outcome-Based Approach',
    description: 'Stop counting hours and start counting wins. This module shows you simple tools to track what actually matters so you can see real progress every day.',
    sectionsCount: 7,
    tags: ['Productivity', 'Mindset'],
  },
  {
    id: 'linking-study-future-goals-protocol',
    category: 'science-growth',
    title: 'Linking Study to Future Goals',
    subtitle: 'Finding Your Why',
    description: 'Ever sat down to study and thought "what\'s the point?" This module helps you figure out why your subjects actually matter to you -- and how to stay motivated when the work feels pointless.',
    sectionsCount: 8,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'growth-mindset-protocol',
    category: 'science-growth',
    title: 'The Growth Playbook',
    subtitle: 'The Mind\'s Operating System',
    description: 'Your brain can actually change and get better at things -- and once you believe that, everything shifts. This module shows you how to stop thinking "I\'m just not smart enough" and start seeing every challenge as a chance to grow.',
    sectionsCount: 6,
    tags: ['Mindset', 'Brain Science'],
  },
  {
    id: 'mastering-active-recall-protocol',
    category: 'learning-cheat-codes',
    title: 'Mastering Active Recall',
    subtitle: 'Why Testing Yourself Is a Superpower',
    description: 'Testing yourself isn\'t just for checking what you know — it\'s actually the single best way to make things stick in your memory for good.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'mastering-spaced-repetition-protocol',
    category: 'learning-cheat-codes',
    title: 'Mastering Spaced Repetition',
    subtitle: 'The Forgetting Curve Method',
    description: 'Stop forgetting what you study. Learn when and how often to review so the stuff you learn actually sticks for the Leaving Cert and beyond.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Productivity'],
  },
  {
    id: 'mastering-interleaving-protocol',
    category: 'learning-cheat-codes',
    title: 'Mix It Up',
    subtitle: 'The Topic Salad Method',
    description: 'Stop studying one subject for hours on end. Mixing your topics feels harder, but it\'s the fastest way to build the kind of knowledge that actually holds up in the Leaving Cert.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'cognitive-architecture-protocol',
    category: 'learning-cheat-codes',
    title: 'How Your Memory Works',
    subtitle: 'Your Brain\'s User Manual',
    description: 'Learn how your memory actually works — how information gets in, why most of it falls out, and what you can do to make the important stuff stick for the Leaving Cert.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'elaborative-interrogation-protocol',
    category: 'learning-cheat-codes',
    title: 'Elaborative Interrogation',
    subtitle: 'The "Why" Method',
    description: 'Stop just memorising facts and start actually understanding them by asking one simple question: "Why?". This module shows you how to make what you study stick — and mean something — for the Leaving Cert.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Mindset'],
  },
  {
    id: 'cognitive-endurance-protocol',
    category: 'learning-cheat-codes',
    title: 'Cognitive Endurance',
    subtitle: 'The Marathon Method',
    description: 'The Leaving Cert isn\'t a sprint. Learn how to keep your brain sharp across weeks of exams, even when you\'re tired and stressed.',
    sectionsCount: 6,
    tags: ['Performance Psych', 'Brain Science'],
  },
  {
    id: 'mental-modelling-protocol',
    category: 'learning-cheat-codes',
    title: 'Mental Modelling',
    subtitle: 'The Mind\'s Eye Method',
    description: 'Learn to see the answer in your head before you put pen to paper. In subjects like DCG and Engineering, the real skill isn\'t drawing — it\'s picturing 3D objects in your mind. This module shows you how.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Subject Strategy'],
  },
  {
    id: 'bimodal-brain-protocol',
    category: 'learning-cheat-codes',
    title: 'Focused vs Diffuse Mode',
    subtitle: 'The Bimodal Brain',
    description: 'Your brain has two modes — one for grinding through problems, one for creative breakthroughs. Learning when to switch between them is a game-changer for your study.',
    sectionsCount: 6,
    tags: ['Brain Science', 'Productivity'],
  },
  {
    id: 'learning-math-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Maths',
    subtitle: 'How to Beat the Exam',
    description: 'Everything you need to know about how Higher Level Maths actually works -- the papers, the marking, and the tricks that earn you extra marks.',
    sectionsCount: 9,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-foreign-languages-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Foreign Languages',
    subtitle: 'Your Complete Guide to the Language Exams',
    description: 'Whether you\'re aiming to pass or chasing a H1, this module breaks down exactly how the Leaving Cert language exams work and how to get the most out of every section.',
    sectionsCount: 8,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-the-sciences-protocol',
    category: 'subject-specific-science',
    title: 'Mastering the Sciences',
    subtitle: 'Your Science Subjects, Decoded',
    description: 'Each science exam has its own unwritten rules. This module breaks them down so you know exactly what the examiner is looking for.',
    sectionsCount: 7,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-english-protocol',
    category: 'subject-specific-science',
    title: 'Mastering English',
    subtitle: 'How the Marking Scheme Actually Works',
    description: 'English isn\'t about luck or natural talent. Once you understand how PCLM marking works, you\'ll know exactly what the examiner wants -- and how to give it to them.',
    sectionsCount: 7,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-business-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Business',
    subtitle: 'Your Complete Guide to Getting Top Marks',
    description: 'Everything you need to crack the 2026 Business exam -- from the ABQ to the action words and the SEE/SEEE answer structure that examiners actually reward.',
    sectionsCount: 6,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'applied-sciences-protocol',
    category: 'subject-specific-science',
    title: 'Mastering Applied Sciences',
    subtitle: 'Your 2026 Project & Exam Guide',
    description: 'Everything you need to know about this year\'s Engineering, DCG, Computer Science, and Construction projects -- plus how to nail the exams.',
    sectionsCount: 6,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'mastering-the-creatives-protocol',
    category: 'subject-specific-science',
    title: 'Mastering the Creatives',
    subtitle: 'Your Art, Music & Film Playbook',
    description: 'Think you need \'natural talent\' for the creatives? Think again. This module breaks it all down into skills you can learn step by step.',
    sectionsCount: 6,
    tags: ['Subject Strategy', 'Exam Tactics', 'Creativity'],
  },
  {
    id: 'leaving-cert-strategy-protocol',
    category: 'exam-zone',
    title: 'The Points Playbook',
    subtitle: 'Your Game Plan for the Leaving Cert',
    description: 'The Leaving Cert is a points game -- and once you know the rules, you can play it way smarter. Here\'s your game plan for getting the most points you can.',
    sectionsCount: 6,
    tags: ['Exam Tactics', 'Productivity'],
  },
  {
    id: 'reverse-engineering-protocol',
    category: 'exam-zone',
    title: 'Reverse Engineering Your Schedule',
    subtitle: 'Plan Backwards, Get Ahead',
    description: 'Most study plans fall apart within weeks. This module shows you how to start from your exam date and work backwards to build a schedule that actually holds up.',
    sectionsCount: 6,
    tags: ['Productivity', 'Exam Tactics'],
  },
  {
    id: 'exam-hall-strategies-protocol',
    category: 'exam-zone',
    title: 'Exam Hall Strategies',
    subtitle: 'Your Game Plan for Exam Day',
    description: 'You\'ve done the study — now learn the practical tips that help top students turn what they know into the marks they deserve.',
    sectionsCount: 7,
    tags: ['Exam Tactics', 'Performance Psych'],
  },
  {
    id: 'exam-crisis-management-protocol',
    category: 'exam-zone',
    title: 'Exam Crisis Management',
    subtitle: 'Your Exam Survival Guide',
    description: 'Understand why your brain freezes under pressure and learn practical techniques to stay calm, think clearly, and bounce back when things go wrong in an exam.',
    sectionsCount: 7,
    tags: ['Resilience', 'Performance Psych'],
  },
  {
    id: 'game-day-protocol',
    category: 'exam-zone',
    title: 'Game Day: Peak Performance',
    subtitle: 'Peak Performance on Demand',
    description: 'Train for the Leaving Cert the way athletes train for competition. Sleep, food, mindset, and a solid game plan -- this is your playbook for performing at your best when it counts.',
    sectionsCount: 8,
    tags: ['Performance Psych', 'Exam Tactics'],
  },
  {
    id: 'mastering-the-humanities-protocol',
    category: 'subject-specific-science',
    title: 'Mastering the Humanities',
    subtitle: 'Your Guide to Getting Better Marks',
    description: 'History, Geography, and Politics & Society each have their own unwritten rules for how marks are given. Once you know them, everything changes.',
    sectionsCount: 5,
    tags: ['Subject Strategy', 'Exam Tactics'],
  },
  {
    id: 'digital-distraction-protocol',
    category: 'learning-cheat-codes',
    title: 'Creating Barriers for Digital Distractions',
    subtitle: 'Take Back Your Focus',
    description: 'Your phone is designed to steal your attention. This module gives you a step-by-step plan to block distractions and actually get your study hours to count.',
    sectionsCount: 7,
    tags: ['Productivity', 'Performance Psych'],
  },
  {
    id: 'learning-radar-protocol',
    category: 'learning-cheat-codes',
    title: 'The Learning Radar',
    subtitle: 'Know What You Actually Know',
    description: 'Most students think they know more than they do — and it costs them marks. This module shows you how to spot your blind spots and study smarter.',
    sectionsCount: 6,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'note-taking-paradox-protocol',
    category: 'learning-cheat-codes',
    title: 'The Note-Taking Paradox',
    subtitle: 'Why Less Is More',
    description: 'More notes doesn\'t mean more learning. Find out why writing less — but thinking more — is the secret to notes that actually help you in the exam.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Productivity'],
  },
  {
    id: 'teaching-effect-protocol',
    category: 'science-growth',
    title: 'The Teaching Effect',
    subtitle: 'Learn It by Teaching It',
    description: 'Want to actually remember what you study? Pretend you have to explain it to someone else. It completely changes how your brain stores everything -- even if you never teach a single person.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Brain Science'],
  },
  {
    id: 'cognitive-load-protocol',
    category: 'learning-cheat-codes',
    title: 'Cognitive Load',
    subtitle: 'Why Your Brain Gets Overloaded',
    description: 'Your brain can only juggle about 4 things at once. Most study sessions accidentally blow past that limit — and you don\'t even notice. This module shows you how to stop wasting brainpower and start actually learning.',
    sectionsCount: 5,
    tags: ['Brain Science', 'Learning Strategy'],
  },
  {
    id: 'implementation-protocol',
    category: 'architecture-mindset',
    title: 'The Implementation Playbook',
    subtitle: 'The Intention-Action Blueprint',
    description: 'Feeling motivated doesn\'t mean you\'ll actually study. This module teaches you a dead-simple planning trick that closes the gap between saying you\'ll study and actually doing it.',
    sectionsCount: 5,
    tags: ['Motivation', 'Productivity'],
  },
  {
    id: 'context-effect-protocol',
    category: 'learning-cheat-codes',
    title: 'The Context Effect',
    subtitle: 'Where You Study Matters',
    description: 'Where you study changes what you remember. Learn why switching study spots beats sticking to one \'perfect\' place.',
    sectionsCount: 5,
    tags: ['Learning Strategy', 'Performance Psych'],
  },
  {
    id: 'points-optimization-protocol',
    category: 'exam-zone',
    title: 'The 625 Blueprint',
    subtitle: 'How to Maximise Your Points',
    description: 'The Leaving Cert is a points game — and there are smart ways to play it. Use real data on H1 rates, how points really work, and marking scheme tricks to get the most points you can.',
    sectionsCount: 7,
    tags: ['Exam Tactics', 'Productivity'],
  },
] as const;

export const categoryTitles: Record<CategoryType, string> = {
  'architecture-mindset': 'The Architecture of your Mindset',
  'science-growth': 'The Science of Growth',
  'learning-cheat-codes': 'The Science of Learning Effectively',
  'exam-zone': 'Exam Strategy and Points Maximisation',
  'subject-specific-science': 'Decoding the Subjects',
};

export const ALL_COURSES: CourseData[] = COURSE_DEFINITIONS.map(course => {
  const colors = categoryColorMap[course.category] || {
    gradient: 'bg-gradient-to-tr from-zinc-50 via-white to-zinc-50',
    accentColor: 'text-zinc-700',
    auraColor: 'hover:shadow-[0_20px_50px_rgba(71,85,105,0.15)]',
  };
  return {
    ...course,
    ...colors,
  };
});
