/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * "How They Did It" content — 11 people, tightened for the immersive deck
 * (2026-06-03). Same researched, source-cited biographies as before, rewritten
 * to one-idea-per-line so the cards read fast: a short hook, their own words, a
 * 2-3 beat struggle, 2-3 copyable moves, the outside help, where they are now,
 * and one move to steal. Written to the evidence model (struggle-led, copyable
 * PROCESS, named help, attainable framing, no genius/bootstraps language;
 * specific-barrier matched; Irish-leaning where possible). Sources carried verbatim.
 */

import { type PersonCard } from './types/howTheyDidIt';

export const PEOPLE: PersonCard[] = [
  {
    id: 'kellie-harrington',
    name: 'Kellie Harrington',
    barrier: 'financial',
    field: 'Boxing',
    emoji: '🥊',
    portraitKey: 'kellie-harrington',
    hook: "Expelled at 14. Told 'girls don't box.' Every club said no.",
    quote: "I've been in dark places.",
    struggle: [
      'Inner-city Dublin — people said she’d end up in prison or dead by 25.',
      'Club after club turned her away for being a girl.',
      'No women’s showers, so she trained, then walked home to wash.',
    ],
    moves: [
      { title: 'Showed up anyway', detail: 'No facilities for girls? She trained regardless and washed at home rather than quit.' },
      { title: 'Did the hard thing first', detail: 'Deliberately trained the roadwork she hated, so nothing in a fight could scare her.' },
      { title: 'Guarded her head', detail: 'Talked things out and started a walking group — mental health as part of training, not separate.' },
    ],
    helpedBy: 'Volunteer coaches at Corinthians, then St Mary’s, took in a kid nobody else wanted; national coach Zaur Antia built the Olympian. She says boxing saved her life.',
    now: 'Double Olympic gold (Tokyo 2020, Paris 2024) and former World champion.',
    stealThisMove: 'Pick the one thing you keep avoiding — the past paper, the question you skip — and do it first. Build the “I can handle hard” muscle on purpose.',
    strengthsLine: '',
    sources: [
      'https://en.wikipedia.org/wiki/Kellie_Harrington',
      'https://www.irishtimes.com/sport/other-sports/i-m-kellie-harrington-i-train-i-box-and-i-m-proud-of-that-1.3795261',
      'https://www.offtheball.com/other-sports/corinthians-harrington-toilets-1236658',
      'https://iaba.ie/the-last-mile-is-never-crowded-kellie-harrington-on-mental-health/',
      'https://www.bluewin.ch/en/sport/kellie-harrington-boxes-her-way-to-olympic-gold-and-goes-back-to-work-as-a-cleaner-2317521.html',
    ],
  },
  {
    id: 'roddy-doyle',
    name: 'Roddy Doyle',
    barrier: 'financial',
    field: 'Writing',
    emoji: '✍️',
    portraitKey: 'roddy-doyle',
    hook: 'A working-class Dublin teacher. No time, no money, no publisher.',
    quote: '',
    struggle: [
      'Taught geography and English full-time in Kilbarrack — and stayed.',
      'Wrote The Commitments in the Easter and summer holidays.',
      'No publisher would bite.',
    ],
    moves: [
      { title: 'Wrote in the gaps', detail: 'Used Easter and summer holidays as fixed writing shifts instead of waiting for free time.' },
      { title: 'Wrote what he knew', detail: 'The voices and streets of working-class Dublin — not posh literary imitation.' },
      { title: 'Self-published', detail: 'Rejected, he and a partner funded and printed it under their own “King Farouk” press.' },
    ],
    helpedBy: 'He teamed up with John Sutton of the Passion Machine theatre company to fund the self-published edition and stage his early work — a route the mainstream wasn’t offering.',
    now: 'A Booker Prize-winning novelist whose Barrytown books became hit films.',
    stealThisMove: 'Name two fixed work shifts this week — say Saturday morning and Tuesday study hall — instead of waiting to “find time”.',
    strengthsLine: 'He treated his working-class Dublin background as his material, not something to hide.',
    sources: [
      'https://en.wikipedia.org/wiki/The_Commitments_(novel)',
      'https://en.wikipedia.org/wiki/Roddy_Doyle',
      'https://www.britannica.com/biography/Roddy-Doyle',
      'https://www.dublincityofliterature.ie/literary-city/featured-authors/roddy-doyle',
    ],
  },
  {
    id: 'keira-knightley',
    name: 'Keira Knightley',
    barrier: 'dyslexia',
    field: 'Acting / Film',
    emoji: '🎬',
    portraitKey: 'keira-knightley',
    hook: 'Diagnosed dyslexic at 6 — top of the class to the bottom.',
    quote: 'I record it and listen to it, and that’s how I learn it.',
    struggle: [
      'She’d been reciting books from memory, not reading.',
      'Hand her an unseen page and the words wouldn’t come.',
      'Decades on, sight-reading still doesn’t work some days.',
    ],
    moves: [
      { title: 'Tied reading to a reward', detail: 'A deal: keep acting only if grades hold. Every page of practice bought stage time.' },
      { title: 'Practised on what she loved', detail: 'Learned to read aloud over the summer using the Sense and Sensibility film script.' },
      { title: 'Turned reading into listening', detail: 'Records her lines and replays them on a loop to get around sight-reading.' },
    ],
    helpedBy: 'Her mum sourced a real film script to practise on; her head teacher David Cooper built the “acting only if grades hold” rule around her, not generic homework.',
    now: 'Oscar-nominated, OBE-honoured actor who still works around dyslexia — the workaround is the win.',
    stealThisMove: 'Pick something you’re dreading reading, record yourself reading it slowly, and listen back twice. Let your ears do the work your eyes find hard.',
    strengthsLine: 'Her dyslexia came with a huge memory — the same memory that lets her hold whole scripts in her head.',
    sources: [
      'https://dyslexiahelp.umich.edu/success-story/keira-knightley/',
      'https://www.ldrfa.org/another-celebrity-with-dyslexia-keira-knightley/',
      'https://www.dyslexia-reading-well.com/keira-knightley.html',
    ],
  },
  {
    id: 'keith-dunphy',
    name: 'Keith Dunphy',
    barrier: 'dyslexia',
    field: 'Acting / Theatre',
    emoji: '🎭',
    portraitKey: 'keith-dunphy',
    hook: 'Left an Irish school unable to read or write. Never told he was dyslexic.',
    quote: 'In pressured situations, my dyslexia is exacerbated.',
    struggle: [
      'Put in the “remedial” class; nobody spotted dyslexia.',
      '“I avoided reading; it was a disaster.”',
      'Auditions — reading cold under pressure — are the worst.',
    ],
    moves: [
      { title: 'Got the script early', detail: 'His agent phones directors ahead, explains the dyslexia, and asks for the script and a little extra time.' },
      { title: 'Named it out loud', detail: 'Telling directors turned a hidden weakness into an adjustment people could make.' },
      { title: 'Out-grafted it', detail: 'He works very hard to learn lines — treating effort, not talent, as the engine.' },
    ],
    helpedBy: 'A teacher, Brother Benedict, pulled him into theatre; actor Andy Hines pushed him toward RADA; and his community fundraised to pay the fees.',
    now: 'A working classical and screen actor, and a voice for Dyslexia Ireland.',
    stealThisMove: 'Before your next read-aloud, ask the teacher for the material a day early and say you need a little extra time. Getting it in advance is a strategy, not a cop-out.',
    strengthsLine: 'He reframes the difference as exploration, not deficit: “You’re an explorer.”',
    sources: ['https://dyslexia.ie/keith-dunphy-actor/'],
  },
  {
    id: 'steven-spielberg',
    name: 'Steven Spielberg',
    barrier: 'dyslexia',
    field: 'Film directing',
    emoji: '🎥',
    portraitKey: 'steven-spielberg',
    hook: 'Read two years behind his class. Teachers called him lazy.',
    quote: 'Movies saved me from shame.',
    struggle: [
      'Bullied for being slow, a band kid, the outsider.',
      'No actual diagnosis until he was about 60.',
      'He’d carried the shame for fifty years.',
    ],
    moves: [
      { title: 'Built his own outlet', detail: 'Started making movies at 12 — a place where his brain was the asset, not the problem.' },
      { title: 'Used the slow read', detail: 'A script takes him ~3 hours, not 70 minutes — so he uses the extra time to notice more.' },
      { title: 'Dropped the secret', detail: 'Named the diagnosis publicly: “you can dart between the raindrops to get where you want to go.”' },
    ],
    helpedBy: 'His parents backed his filmmaking from age 12 instead of forcing him to look “normal”; a late professional diagnosis finally reframed decades of struggle as dyslexia, not laziness.',
    now: 'The most commercially successful director in Hollywood — and at peace with reading slowly.',
    stealThisMove: 'Next time a page takes you longer than the person beside you, don’t rush to hide it. Take the time and notice one thing you’d otherwise have missed.',
    strengthsLine: 'He reads slowly because his brain thinks in pictures — the same wiring that lets him see whole films in his head.',
    sources: [
      'https://childmind.org/blog/steven-spielberg-talks-bullying-and-dyslexia/',
      'https://www.additudemag.com/steven-spielberg-dyslexia-hollywood-success/',
    ],
  },
  {
    id: 'suaad-alshleh',
    name: 'Suaad Alshleh',
    barrier: 'eal',
    field: 'Medicine',
    emoji: '🩺',
    portraitKey: 'suaad-alshleh',
    hook: 'Came from Syria at 14. A year in Direct Provision. Still got into medicine.',
    quote: 'All the burden of the paperwork fell on my shoulders.',
    struggle: [
      'Months in Direct Provision she’s “blocked out”.',
      'At 14 she handled the family’s official letters and GP forms.',
      'Her school didn’t even offer the chemistry she needed.',
    ],
    moves: [
      { title: 'Chased the subject', detail: 'Switched schools purely to get the Leaving Cert chemistry medicine required.' },
      { title: 'Doubled up', detail: 'Sat her Junior Cert in one year, not three, to close the gap — without waiting to feel ready.' },
      { title: 'Applied for everything', detail: '“It’s just a paper you fill out — the points do the rest.”' },
    ],
    helpedBy: 'She won the first State scholarship for disadvantaged high-achievers, plus the Campbell Bursary and RCSI Aim High — “life-changing”; the fees were otherwise out of reach.',
    now: 'Graduated medicine from RCSI in 2024 with first-class honours and started her hospital internship.',
    stealThisMove: 'Find one grant, bursary or scholarship you qualify for — ask your guidance counsellor or check SUSI — and start the form this week.',
    strengthsLine: 'Her Arabic is an asset, not a gap — doctors who speak more than one language are needed, not penalised.',
    sources: [
      'https://www.irishtimes.com/news/education/syrian-refugee-student-wins-state-scholarship-1.4074645',
      'https://www.irishexaminer.com/news/arid-30962262.html',
      'https://www.rte.ie/news/ireland/2024/0620/1455557-syrian-refugee-doctor/',
    ],
  },
  {
    id: 'ola-majekodunmi',
    name: 'Ola Majekodunmi',
    barrier: 'eal',
    field: 'Irish-language media',
    emoji: '🎙️',
    portraitKey: 'ola-majekodunmi',
    hook: 'The only Black kid in an all-Irish school — still told Irish “isn’t for her”.',
    quote: 'I’m a black woman who happens to speak Irish.',
    struggle: [
      'Her parents risked an all-Irish education in a language not spoken at home.',
      'Years of double-takes and not being expected to belong.',
      '“I don’t want to be the black girl who speaks Irish.”',
    ],
    moves: [
      { title: 'Used the surprise as fuel', detail: 'Kept showing up in Irish-language spaces until fluency spoke for itself.' },
      { title: 'Immersed, didn’t dabble', detail: 'Did primary and secondary fully as Gaeilge, so the language became automatic.' },
      { title: 'Made her story the work', detail: 'Presents in Irish and produces media about diversity instead of hiding her difference.' },
    ],
    helpedBy: 'Her parents took the risk of Irish-medium schooling; the community station Raidió na Life gave her a first platform to broadcast in 2014.',
    now: 'A Nigerian-Irish broadcaster and producer working as Gaeilge, and a former board member of Foras na Gaeilge.',
    stealThisMove: 'Pick the fuller path into a skill, not the easy taster — commit to using your second (or third) language every day this week, not just in class.',
    strengthsLine: 'Bilingualism is capital: English, fluent Irish and her Nigerian heritage all widen the door, they don’t narrow it.',
    sources: [
      'https://www.irishtimes.com/culture/heritage/haigh-i-m-a-black-woman-and-i-happen-to-speak-irish-1.4286427',
      'https://en.wikipedia.org/wiki/Ola_Majekodunmi',
      'https://weareirish.ie/ola-majekodunmi-diversity-gaeilge/',
    ],
  },
  {
    id: 'mila-kunis',
    name: 'Mila Kunis',
    barrier: 'eal',
    field: 'Acting',
    emoji: '🌟',
    portraitKey: 'mila-kunis',
    hook: 'Started US school at 7 speaking only Russian. Cried every day.',
    quote: 'I cried every day.',
    struggle: [
      'Dropped into second grade with not one word of English.',
      '“I didn’t understand the culture or the language.”',
      'She’s blocked the whole year out.',
    ],
    moves: [
      { title: 'Learned it sideways', detail: 'After-school acting classes were really low-stakes English practice, not a grammar drill.' },
      { title: 'Got daily social reps', detail: 'Absorbed English by being around English-speaking kids and scripts every week.' },
      { title: 'Kept her first language', detail: 'Never dropped Russian — still speaks it with her parents to this day.' },
    ],
    helpedBy: 'Her parents, who arrived with almost nothing, found and paid for after-school acting classes — a structured, low-pressure place to practise English.',
    now: 'Within a few years, fluent and confident enough to be cast in a major US sitcom.',
    stealThisMove: 'Practise English through something you already enjoy this week — a club, a game chat, a sport — so the reps don’t feel like extra homework.',
    strengthsLine: 'She stayed fully bilingual — your home language isn’t baggage to drop; keeping it is an asset worth protecting.',
    sources: [
      'https://www.scmp.com/magazines/style/celebrity/article/3170684/inside-mila-kunis-ukrainian-heritage-she-moved-los',
      'https://actingmagazine.com/2024/12/how-mila-kunis-got-into-acting/',
      'https://www.today.com/parents/moms/mila-kunis-kids-ukrainian-heritage-rcna22616',
    ],
  },
  {
    id: 'brian-gunnery',
    name: 'Brian Gunnery',
    barrier: 'first-gen',
    field: 'Psychology / Education',
    emoji: '🧠',
    portraitKey: 'brian-gunnery',
    hook: "Left school at 15. Didn't know a single person who'd gone to college.",
    quote: 'I barely knew anybody who had a Leaving Cert.',
    struggle: [
      'Walked out at 15 with no plan and no map.',
      'Felt teachers had written him off as a troublemaker.',
      'It took years, a carpentry course and a gym before a degree felt possible.',
    ],
    moves: [
      { title: 'Found a setting that fit', detail: 'Youthreach — small classes, teachers who adapted — instead of the room that had failed him.' },
      { title: 'Acted on belief', detail: 'When an expert said he was capable, he enrolled part-time so he could keep earning.' },
      { title: 'Studied part-time', detail: 'Fitted a psychology degree around gym work rather than waiting for the “perfect” moment.' },
    ],
    helpedBy: 'Youthreach gave him a small-class second-chance course; Prof Katriona O’Sullivan spotted his curiosity, encouraged him to study, then brought him in to mentor others.',
    now: 'Honours Psychology BA, now running the STEM Passport for Inclusion at Maynooth — opening doors like his were opened.',
    stealThisMove: 'Find the second-chance route that fits how you actually learn — smaller class, hands-on, part-time. Ask a guidance counsellor about Youthreach and PLC courses this week.',
    strengthsLine: '',
    sources: [
      'https://www.irishtimes.com/ireland/2026/04/28/school-dropout-turned-educator-helps-open-doors-for-disadvantaged-students/',
      'https://www.maynoothuniversity.ie/all-institute/all-projects/stem-passport-inclusion',
    ],
  },
  {
    id: 'dr-katriona-o-sullivan',
    name: "Dr Katriona O'Sullivan",
    barrier: 'first-gen',
    field: 'Psychology',
    emoji: '📚',
    portraitKey: 'dr-katriona-o-sullivan',
    hook: 'Pregnant and out of school at 15, homeless — first in her family to reach college.',
    quote: 'There are no doctors, lawyers or graduates in my family.',
    struggle: [
      'Grew up in deep poverty; parents struggled with addiction.',
      'Homeless while expecting her son, raising him alone on welfare.',
      'Cleaned Connolly Station — college was something other people did.',
    ],
    moves: [
      { title: 'Took the door', detail: 'Applied to an access programme “on a whim” even when she didn’t feel she belonged.' },
      { title: 'Built a network', detail: 'Became class rep on purpose, to grow confidence and a support circle.' },
      { title: 'Protected her record', detail: 'Across four years she never missed a deadline — even pregnant and caring for a second child.' },
    ],
    helpedBy: 'The Trinity Access Programme was her route in; her director Irena “dragged me into my exams”; St Vincent de Paul paid childcare; a lecturer sparked her love of psychology.',
    now: 'First-class degree, a Trinity PhD, now a Maynooth senior lecturer and bestselling author of “Poor”.',
    stealThisMove: 'Take the access door even if you feel like an impostor — look up TAP, DARE/HEAR or your college’s access route and put your name down this week.',
    strengthsLine: 'The grit she built surviving hardship became the exact strength that carried her through a degree and a PhD.',
    sources: [
      'https://www.irishtimes.com/life-and-style/people/i-sat-drinking-in-the-knowledge-and-for-the-first-time-in-my-life-i-felt-alive-1.4674595',
      'https://www.penguin.co.uk/books/452168/poor-by-osullivan-katriona/9780241996768',
      'https://www.maynoothuniversity.ie/faculty-science-engineering/research/focus-research/dr-katriona-osullivan',
    ],
  },
  {
    id: 'tim-sheridan',
    name: 'Tim Sheridan',
    barrier: 'first-gen',
    field: 'Paramedicine',
    emoji: '🚑',
    portraitKey: 'tim-sheridan',
    hook: 'Dropped out around October of sixth year. Still reached a frontline medical career.',
    quote: 'Leaving Cert points aren’t everything.',
    struggle: [
      'Depression and anxiety wrecked his attendance.',
      '“I missed almost all of fourth, fifth and sixth year.”',
      'Nowhere near the points for any Level 8 course.',
    ],
    moves: [
      { title: 'Worked backwards from the job', detail: 'Found the real entry rule for student paramedic: six ordinary passes, including maths and a science.' },
      { title: 'Got the exact passes', detail: 'Secured the few results that unlocked the door, not a high points total.' },
      { title: 'Took the side route', detail: 'Joined the National Ambulance Service direct-entry scheme the moment it opened.' },
    ],
    helpedBy: 'Teachers and year heads were “extremely persistent” in getting him back; the National Ambulance Service recruitment drive gave him a paid, points-free route into training.',
    now: 'Four years on, a paramedic in Dublin planning postgraduate study.',
    stealThisMove: 'Pick a job you actually want and look up its real entry requirements — often a few specific passes or an apprenticeship, not a points total. Build toward those exact requirements.',
    strengthsLine: '',
    sources: ['https://www.irishtimes.com/life-and-style/people/i-m-living-proof-that-leaving-cert-points-aren-t-everything-1.3597015'],
  },
];

export function peopleForBarrier(barrier: string): PersonCard[] {
  return PEOPLE.filter((p) => p.barrier === barrier);
}
