/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ModuleTheme } from './types';

// Each theme uses literal Tailwind class strings so the CDN scanner can find them.

export const amberTheme: ModuleTheme = {
  highlightBg: 'bg-amber-100/40',
  highlightText: 'text-amber-900',
  highlightDecor: 'decoration-amber-400/40',
  highlightHover: 'hover:bg-amber-200/60',
  tooltipAccent: 'text-amber-400',
  readingIconColor: 'text-amber-400',
  readingEyebrowBg: 'bg-amber-50',
  readingEyebrowText: 'text-amber-600',
  microBg: 'bg-amber-50/50',
  microBorder: 'border-amber-200',
  microIconBg: 'bg-amber-500',
  microIconShadow: 'shadow-amber-500/20',
  microTitle: 'text-amber-800',
  sidebarModuleText: 'text-amber-500',
  sidebarProgressBg: 'bg-amber-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(245,158,11,0.5)]',
  sidebarActiveBg: 'bg-amber-50',
  sidebarCompletedBg: 'bg-amber-600',
  sidebarCompletedBorder: 'border-amber-600',
  sidebarActiveBorder: 'border-amber-500',
  sidebarActiveText: 'text-amber-600',
  sidebarActiveEyebrow: 'text-amber-500',
  footerHoverBg: 'hover:bg-amber-600',
  activityRingColor: '#f59e0b',
};

export const blueTheme: ModuleTheme = {
  highlightBg: 'bg-blue-100/40',
  highlightText: 'text-blue-900',
  highlightDecor: 'decoration-blue-400/40',
  highlightHover: 'hover:bg-blue-200/60',
  tooltipAccent: 'text-blue-400',
  readingIconColor: 'text-blue-400',
  readingEyebrowBg: 'bg-blue-50',
  readingEyebrowText: 'text-blue-600',
  microBg: 'bg-blue-50/50',
  microBorder: 'border-blue-200',
  microIconBg: 'bg-blue-500',
  microIconShadow: 'shadow-blue-500/20',
  microTitle: 'text-blue-800',
  sidebarModuleText: 'text-blue-500',
  sidebarProgressBg: 'bg-blue-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(59,130,246,0.5)]',
  sidebarActiveBg: 'bg-blue-50',
  sidebarCompletedBg: 'bg-blue-600',
  sidebarCompletedBorder: 'border-blue-600',
  sidebarActiveBorder: 'border-blue-500',
  sidebarActiveText: 'text-blue-600',
  sidebarActiveEyebrow: 'text-blue-500',
  footerHoverBg: 'hover:bg-blue-600',
  activityRingColor: '#3b82f6',
};

export const roseTheme: ModuleTheme = {
  highlightBg: 'bg-rose-100/40',
  highlightText: 'text-rose-900',
  highlightDecor: 'decoration-rose-400/40',
  highlightHover: 'hover:bg-rose-200/60',
  tooltipAccent: 'text-rose-400',
  readingIconColor: 'text-rose-400',
  readingEyebrowBg: 'bg-rose-50',
  readingEyebrowText: 'text-rose-600',
  microBg: 'bg-rose-50/50',
  microBorder: 'border-rose-200',
  microIconBg: 'bg-rose-500',
  microIconShadow: 'shadow-rose-500/20',
  microTitle: 'text-rose-800',
  sidebarModuleText: 'text-rose-500',
  sidebarProgressBg: 'bg-rose-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(225,29,72,0.5)]',
  sidebarActiveBg: 'bg-rose-50',
  sidebarCompletedBg: 'bg-rose-600',
  sidebarCompletedBorder: 'border-rose-600',
  sidebarActiveBorder: 'border-rose-500',
  sidebarActiveText: 'text-rose-600',
  sidebarActiveEyebrow: 'text-rose-500',
  footerHoverBg: 'hover:bg-rose-600',
  activityRingColor: '#e11d48',
};

export const emeraldTheme: ModuleTheme = {
  highlightBg: 'bg-emerald-100/40',
  highlightText: 'text-emerald-900',
  highlightDecor: 'decoration-emerald-400/40',
  highlightHover: 'hover:bg-emerald-200/60',
  tooltipAccent: 'text-emerald-400',
  readingIconColor: 'text-emerald-400',
  readingEyebrowBg: 'bg-emerald-50',
  readingEyebrowText: 'text-emerald-600',
  microBg: 'bg-emerald-50/50',
  microBorder: 'border-emerald-200',
  microIconBg: 'bg-emerald-500',
  microIconShadow: 'shadow-emerald-500/20',
  microTitle: 'text-emerald-800',
  sidebarModuleText: 'text-emerald-500',
  sidebarProgressBg: 'bg-emerald-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(16,185,129,0.5)]',
  sidebarActiveBg: 'bg-emerald-50',
  sidebarCompletedBg: 'bg-emerald-600',
  sidebarCompletedBorder: 'border-emerald-600',
  sidebarActiveBorder: 'border-emerald-500',
  sidebarActiveText: 'text-emerald-600',
  sidebarActiveEyebrow: 'text-emerald-500',
  footerHoverBg: 'hover:bg-emerald-600',
  activityRingColor: '#10b981',
};

export const orangeTheme: ModuleTheme = {
  highlightBg: 'bg-orange-100/40',
  highlightText: 'text-orange-900',
  highlightDecor: 'decoration-orange-400/40',
  highlightHover: 'hover:bg-orange-200/60',
  tooltipAccent: 'text-orange-400',
  readingIconColor: 'text-orange-400',
  readingEyebrowBg: 'bg-orange-50',
  readingEyebrowText: 'text-orange-600',
  microBg: 'bg-orange-50/50',
  microBorder: 'border-orange-200',
  microIconBg: 'bg-orange-500',
  microIconShadow: 'shadow-orange-500/20',
  microTitle: 'text-orange-800',
  sidebarModuleText: 'text-orange-500',
  sidebarProgressBg: 'bg-orange-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(249,115,22,0.5)]',
  sidebarActiveBg: 'bg-orange-50',
  sidebarCompletedBg: 'bg-orange-600',
  sidebarCompletedBorder: 'border-orange-600',
  sidebarActiveBorder: 'border-orange-500',
  sidebarActiveText: 'text-orange-600',
  sidebarActiveEyebrow: 'text-orange-500',
  footerHoverBg: 'hover:bg-orange-600',
  activityRingColor: '#f97316',
};

export const tealTheme: ModuleTheme = {
  highlightBg: 'bg-teal-100/40',
  highlightText: 'text-teal-900',
  highlightDecor: 'decoration-teal-400/40',
  highlightHover: 'hover:bg-teal-200/60',
  tooltipAccent: 'text-teal-400',
  readingIconColor: 'text-teal-400',
  readingEyebrowBg: 'bg-teal-50',
  readingEyebrowText: 'text-teal-600',
  microBg: 'bg-teal-50/50',
  microBorder: 'border-teal-200',
  microIconBg: 'bg-teal-500',
  microIconShadow: 'shadow-teal-500/20',
  microTitle: 'text-teal-800',
  sidebarModuleText: 'text-teal-500',
  sidebarProgressBg: 'bg-teal-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(20,184,166,0.5)]',
  sidebarActiveBg: 'bg-teal-50',
  sidebarCompletedBg: 'bg-teal-600',
  sidebarCompletedBorder: 'border-teal-600',
  sidebarActiveBorder: 'border-teal-500',
  sidebarActiveText: 'text-teal-600',
  sidebarActiveEyebrow: 'text-teal-500',
  footerHoverBg: 'hover:bg-teal-600',
  activityRingColor: '#14b8a6',
};

export const cyanTheme: ModuleTheme = {
  highlightBg: 'bg-cyan-100/40',
  highlightText: 'text-cyan-900',
  highlightDecor: 'decoration-cyan-400/40',
  highlightHover: 'hover:bg-cyan-200/60',
  tooltipAccent: 'text-cyan-400',
  readingIconColor: 'text-cyan-400',
  readingEyebrowBg: 'bg-cyan-50',
  readingEyebrowText: 'text-cyan-600',
  microBg: 'bg-cyan-50/50',
  microBorder: 'border-cyan-200',
  microIconBg: 'bg-cyan-500',
  microIconShadow: 'shadow-cyan-500/20',
  microTitle: 'text-cyan-800',
  sidebarModuleText: 'text-cyan-500',
  sidebarProgressBg: 'bg-cyan-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(6,182,212,0.5)]',
  sidebarActiveBg: 'bg-cyan-50',
  sidebarCompletedBg: 'bg-cyan-600',
  sidebarCompletedBorder: 'border-cyan-600',
  sidebarActiveBorder: 'border-cyan-500',
  sidebarActiveText: 'text-cyan-600',
  sidebarActiveEyebrow: 'text-cyan-500',
  footerHoverBg: 'hover:bg-cyan-600',
  activityRingColor: '#06b6d4',
};

export const slateTheme: ModuleTheme = {
  highlightBg: 'bg-slate-100/40',
  highlightText: 'text-slate-900',
  highlightDecor: 'decoration-slate-400/40',
  highlightHover: 'hover:bg-slate-200/60',
  tooltipAccent: 'text-slate-400',
  readingIconColor: 'text-slate-400',
  readingEyebrowBg: 'bg-slate-50',
  readingEyebrowText: 'text-slate-600',
  microBg: 'bg-slate-50/50',
  microBorder: 'border-slate-200',
  microIconBg: 'bg-slate-500',
  microIconShadow: 'shadow-slate-500/20',
  microTitle: 'text-slate-800',
  sidebarModuleText: 'text-slate-500',
  sidebarProgressBg: 'bg-slate-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(100,116,139,0.5)]',
  sidebarActiveBg: 'bg-slate-50',
  sidebarCompletedBg: 'bg-slate-600',
  sidebarCompletedBorder: 'border-slate-600',
  sidebarActiveBorder: 'border-slate-500',
  sidebarActiveText: 'text-slate-600',
  sidebarActiveEyebrow: 'text-slate-500',
  footerHoverBg: 'hover:bg-slate-600',
  activityRingColor: '#64748b',
};

export const skyTheme: ModuleTheme = {
  highlightBg: 'bg-sky-100/40',
  highlightText: 'text-sky-900',
  highlightDecor: 'decoration-sky-400/40',
  highlightHover: 'hover:bg-sky-200/60',
  tooltipAccent: 'text-sky-400',
  readingIconColor: 'text-sky-400',
  readingEyebrowBg: 'bg-sky-50',
  readingEyebrowText: 'text-sky-600',
  microBg: 'bg-sky-50/50',
  microBorder: 'border-sky-200',
  microIconBg: 'bg-sky-500',
  microIconShadow: 'shadow-sky-500/20',
  microTitle: 'text-sky-800',
  sidebarModuleText: 'text-sky-500',
  sidebarProgressBg: 'bg-sky-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(14,165,233,0.5)]',
  sidebarActiveBg: 'bg-sky-50',
  sidebarCompletedBg: 'bg-sky-600',
  sidebarCompletedBorder: 'border-sky-600',
  sidebarActiveBorder: 'border-sky-500',
  sidebarActiveText: 'text-sky-600',
  sidebarActiveEyebrow: 'text-sky-500',
  footerHoverBg: 'hover:bg-sky-600',
  activityRingColor: '#0ea5e9',
};

export const redTheme: ModuleTheme = {
  highlightBg: 'bg-red-100/40',
  highlightText: 'text-red-900',
  highlightDecor: 'decoration-red-400/40',
  highlightHover: 'hover:bg-red-200/60',
  tooltipAccent: 'text-red-400',
  readingIconColor: 'text-red-400',
  readingEyebrowBg: 'bg-red-50',
  readingEyebrowText: 'text-red-600',
  microBg: 'bg-red-50/50',
  microBorder: 'border-red-200',
  microIconBg: 'bg-red-500',
  microIconShadow: 'shadow-red-500/20',
  microTitle: 'text-red-800',
  sidebarModuleText: 'text-red-500',
  sidebarProgressBg: 'bg-red-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(239,68,68,0.5)]',
  sidebarActiveBg: 'bg-red-50',
  sidebarCompletedBg: 'bg-red-600',
  sidebarCompletedBorder: 'border-red-600',
  sidebarActiveBorder: 'border-red-500',
  sidebarActiveText: 'text-red-600',
  sidebarActiveEyebrow: 'text-red-500',
  footerHoverBg: 'hover:bg-red-600',
  activityRingColor: '#ef4444',
};

export const purpleTheme: ModuleTheme = {
  highlightBg: 'bg-purple-100/40',
  highlightText: 'text-purple-900',
  highlightDecor: 'decoration-purple-400/40',
  highlightHover: 'hover:bg-purple-200/60',
  tooltipAccent: 'text-purple-400',
  readingIconColor: 'text-purple-400',
  readingEyebrowBg: 'bg-purple-50',
  readingEyebrowText: 'text-purple-600',
  microBg: 'bg-purple-50/50',
  microBorder: 'border-purple-200',
  microIconBg: 'bg-purple-500',
  microIconShadow: 'shadow-purple-500/20',
  microTitle: 'text-purple-800',
  sidebarModuleText: 'text-purple-500',
  sidebarProgressBg: 'bg-purple-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(168,85,247,0.5)]',
  sidebarActiveBg: 'bg-purple-50',
  sidebarCompletedBg: 'bg-purple-600',
  sidebarCompletedBorder: 'border-purple-600',
  sidebarActiveBorder: 'border-purple-500',
  sidebarActiveText: 'text-purple-600',
  sidebarActiveEyebrow: 'text-purple-500',
  footerHoverBg: 'hover:bg-purple-600',
  activityRingColor: '#a855f7',
};

export const fuchsiaTheme: ModuleTheme = {
  highlightBg: 'bg-fuchsia-100/40',
  highlightText: 'text-fuchsia-900',
  highlightDecor: 'decoration-fuchsia-400/40',
  highlightHover: 'hover:bg-fuchsia-200/60',
  tooltipAccent: 'text-fuchsia-400',
  readingIconColor: 'text-fuchsia-400',
  readingEyebrowBg: 'bg-fuchsia-50',
  readingEyebrowText: 'text-fuchsia-600',
  microBg: 'bg-fuchsia-50/50',
  microBorder: 'border-fuchsia-200',
  microIconBg: 'bg-fuchsia-500',
  microIconShadow: 'shadow-fuchsia-500/20',
  microTitle: 'text-fuchsia-800',
  sidebarModuleText: 'text-fuchsia-500',
  sidebarProgressBg: 'bg-fuchsia-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(217,70,239,0.5)]',
  sidebarActiveBg: 'bg-fuchsia-50',
  sidebarCompletedBg: 'bg-fuchsia-600',
  sidebarCompletedBorder: 'border-fuchsia-600',
  sidebarActiveBorder: 'border-fuchsia-500',
  sidebarActiveText: 'text-fuchsia-600',
  sidebarActiveEyebrow: 'text-fuchsia-500',
  footerHoverBg: 'hover:bg-fuchsia-600',
  activityRingColor: '#d946ef',
};

export const indigoTheme: ModuleTheme = {
  highlightBg: 'bg-indigo-100/40',
  highlightText: 'text-indigo-900',
  highlightDecor: 'decoration-indigo-400/40',
  highlightHover: 'hover:bg-indigo-200/60',
  tooltipAccent: 'text-indigo-400',
  readingIconColor: 'text-indigo-400',
  readingEyebrowBg: 'bg-indigo-50',
  readingEyebrowText: 'text-indigo-600',
  microBg: 'bg-indigo-50/50',
  microBorder: 'border-indigo-200',
  microIconBg: 'bg-indigo-500',
  microIconShadow: 'shadow-indigo-500/20',
  microTitle: 'text-indigo-800',
  sidebarModuleText: 'text-indigo-500',
  sidebarProgressBg: 'bg-indigo-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(79,70,229,0.5)]',
  sidebarActiveBg: 'bg-indigo-50',
  sidebarCompletedBg: 'bg-indigo-600',
  sidebarCompletedBorder: 'border-indigo-600',
  sidebarActiveBorder: 'border-indigo-500',
  sidebarActiveText: 'text-indigo-600',
  sidebarActiveEyebrow: 'text-indigo-500',
  footerHoverBg: 'hover:bg-indigo-600',
  activityRingColor: '#4f46e5',
};

export const violetTheme: ModuleTheme = {
  highlightBg: 'bg-violet-100/40',
  highlightText: 'text-violet-900',
  highlightDecor: 'decoration-violet-400/40',
  highlightHover: 'hover:bg-violet-200/60',
  tooltipAccent: 'text-violet-400',
  readingIconColor: 'text-violet-400',
  readingEyebrowBg: 'bg-violet-50',
  readingEyebrowText: 'text-violet-600',
  microBg: 'bg-violet-50/50',
  microBorder: 'border-violet-200',
  microIconBg: 'bg-violet-500',
  microIconShadow: 'shadow-violet-500/20',
  microTitle: 'text-violet-800',
  sidebarModuleText: 'text-violet-500',
  sidebarProgressBg: 'bg-violet-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(139,92,246,0.5)]',
  sidebarActiveBg: 'bg-violet-50',
  sidebarCompletedBg: 'bg-violet-600',
  sidebarCompletedBorder: 'border-violet-600',
  sidebarActiveBorder: 'border-violet-500',
  sidebarActiveText: 'text-violet-600',
  sidebarActiveEyebrow: 'text-violet-500',
  footerHoverBg: 'hover:bg-violet-600',
  activityRingColor: '#8b5cf6',
};

export const pinkTheme: ModuleTheme = {
  highlightBg: 'bg-pink-100/40',
  highlightText: 'text-pink-900',
  highlightDecor: 'decoration-pink-400/40',
  highlightHover: 'hover:bg-pink-200/60',
  tooltipAccent: 'text-pink-400',
  readingIconColor: 'text-pink-400',
  readingEyebrowBg: 'bg-pink-50',
  readingEyebrowText: 'text-pink-600',
  microBg: 'bg-pink-50/50',
  microBorder: 'border-pink-200',
  microIconBg: 'bg-pink-500',
  microIconShadow: 'shadow-pink-500/20',
  microTitle: 'text-pink-800',
  sidebarModuleText: 'text-pink-500',
  sidebarProgressBg: 'bg-pink-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(236,72,153,0.5)]',
  sidebarActiveBg: 'bg-pink-50',
  sidebarCompletedBg: 'bg-pink-600',
  sidebarCompletedBorder: 'border-pink-600',
  sidebarActiveBorder: 'border-pink-500',
  sidebarActiveText: 'text-pink-600',
  sidebarActiveEyebrow: 'text-pink-500',
  footerHoverBg: 'hover:bg-pink-600',
  activityRingColor: '#ec4899',
};

export const limeTheme: ModuleTheme = {
  highlightBg: 'bg-lime-100/40',
  highlightText: 'text-lime-900',
  highlightDecor: 'decoration-lime-400/40',
  highlightHover: 'hover:bg-lime-200/60',
  tooltipAccent: 'text-lime-400',
  readingIconColor: 'text-lime-400',
  readingEyebrowBg: 'bg-lime-50',
  readingEyebrowText: 'text-lime-600',
  microBg: 'bg-lime-50/50',
  microBorder: 'border-lime-200',
  microIconBg: 'bg-lime-500',
  microIconShadow: 'shadow-lime-500/20',
  microTitle: 'text-lime-800',
  sidebarModuleText: 'text-lime-500',
  sidebarProgressBg: 'bg-lime-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(101,163,13,0.5)]',
  sidebarActiveBg: 'bg-lime-50',
  sidebarCompletedBg: 'bg-lime-600',
  sidebarCompletedBorder: 'border-lime-600',
  sidebarActiveBorder: 'border-lime-500',
  sidebarActiveText: 'text-lime-600',
  sidebarActiveEyebrow: 'text-lime-500',
  footerHoverBg: 'hover:bg-lime-600',
  activityRingColor: '#65a30d',
};

export const yellowTheme: ModuleTheme = {
  highlightBg: 'bg-yellow-100/40',
  highlightText: 'text-yellow-900',
  highlightDecor: 'decoration-yellow-400/40',
  highlightHover: 'hover:bg-yellow-200/60',
  tooltipAccent: 'text-yellow-400',
  readingIconColor: 'text-yellow-400',
  readingEyebrowBg: 'bg-yellow-50',
  readingEyebrowText: 'text-yellow-600',
  microBg: 'bg-yellow-50/50',
  microBorder: 'border-yellow-200',
  microIconBg: 'bg-yellow-500',
  microIconShadow: 'shadow-yellow-500/20',
  microTitle: 'text-yellow-800',
  sidebarModuleText: 'text-yellow-500',
  sidebarProgressBg: 'bg-yellow-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(202,138,4,0.5)]',
  sidebarActiveBg: 'bg-yellow-50',
  sidebarCompletedBg: 'bg-yellow-600',
  sidebarCompletedBorder: 'border-yellow-600',
  sidebarActiveBorder: 'border-yellow-500',
  sidebarActiveText: 'text-yellow-600',
  sidebarActiveEyebrow: 'text-yellow-500',
  footerHoverBg: 'hover:bg-yellow-600',
  activityRingColor: '#ca8a04',
};

export const grayTheme: ModuleTheme = {
  highlightBg: 'bg-gray-100/40',
  highlightText: 'text-gray-900',
  highlightDecor: 'decoration-gray-400/40',
  highlightHover: 'hover:bg-gray-200/60',
  tooltipAccent: 'text-gray-400',
  readingIconColor: 'text-gray-400',
  readingEyebrowBg: 'bg-gray-50',
  readingEyebrowText: 'text-gray-600',
  microBg: 'bg-gray-50/50',
  microBorder: 'border-gray-200',
  microIconBg: 'bg-gray-500',
  microIconShadow: 'shadow-gray-500/20',
  microTitle: 'text-gray-800',
  sidebarModuleText: 'text-gray-500',
  sidebarProgressBg: 'bg-gray-500',
  sidebarProgressShadow: 'shadow-[0_0_10px_rgba(75,85,99,0.5)]',
  sidebarActiveBg: 'bg-gray-50',
  sidebarCompletedBg: 'bg-gray-600',
  sidebarCompletedBorder: 'border-gray-600',
  sidebarActiveBorder: 'border-gray-500',
  sidebarActiveText: 'text-gray-600',
  sidebarActiveEyebrow: 'text-gray-500',
  footerHoverBg: 'hover:bg-gray-600',
  activityRingColor: '#4b5563',
};
