/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Module section titles extracted from individual module components.
// Used by ModuleShowcase to display real section names instead of generic labels.

export interface SectionInfo {
  title: string;
  eyebrow: string;
}

export const MODULE_SECTIONS: Record<string, SectionInfo[]> = {
  'agency-protocol': [
    { title: 'Setting the Sat-Nav', eyebrow: '01 // Your Destination' },
    { title: 'Driver or Passenger?', eyebrow: '02 // Seizing the Wheel' },
    { title: "The Driver's Controls", eyebrow: '03 // Hacking Your Classroom' },
    { title: 'Roadblocks & Potholes', eyebrow: '04 // When the Journey is Unfair' },
    { title: 'Your Unique Engine', eyebrow: '05 // The Power of Your Story' },
    { title: 'Your Route Plan', eyebrow: '06 // Building Your Driver Identity' },
  ],
  'hope-protocol': [
    { title: 'The Schematic: De-Coding Hope', eyebrow: '01 // The Blueprint' },
    { title: "Your Brain's Circuit Board", eyebrow: '02 // The Hardware' },
    { title: "Powering Up: The Science of 'Willpower'", eyebrow: '03 // The Voltage' },
    { title: "Designing the Wires: The Art of 'Waypower'", eyebrow: '04 // The Wiring' },
    { title: 'Stress Shield: Your Surge Protector', eyebrow: '05 // System Protection' },
    { title: 'Upgrading the Hardware', eyebrow: '06 // System Upgrade' },
  ],
  'affirming-values-protocol': [
    { title: 'The Invisible Threat', eyebrow: '01 // The Problem' },
    { title: 'The Psychological Shield', eyebrow: '02 // The Solution' },
    { title: 'How It Works: The Zoom-Out Effect', eyebrow: '03 // The Mechanism' },
    { title: 'The Real World Data', eyebrow: '04 // The Evidence' },
    { title: 'Your Pre-Exam Protocol', eyebrow: '05 // The Action Plan' },
  ],
  'best-possible-self-protocol': [
    { title: 'The Daydream Problem', eyebrow: '01 // The Trap' },
    { title: 'The "Best Possible Self" Protocol', eyebrow: '02 // The Vision' },
    { title: 'The Reality Check', eyebrow: '03 // Mental Contrasting' },
    { title: 'The WOOP Method', eyebrow: '04 // The System' },
    { title: 'Build Your First WOOP', eyebrow: '05 // The Action Plan' },
  ],
  'grammar-of-grit-protocol': [
    { title: 'Your Internal Narrator', eyebrow: '01 // The Source Code' },
    { title: 'The 3 Ps of Failure', eyebrow: '02 // Personal, Pervasive, Permanent' },
    { title: 'The Re-Write Protocol', eyebrow: '03 // From Fragile to Agile' },
    { title: 'The Role of Self-Compassion', eyebrow: '04 // The Antidote to Shame' },
    { title: 'Your Resilience Blueprint', eyebrow: '05 // The Action Plan' },
  ],
  'agency-architecture-protocol': [
    { title: 'The Story of Failure', eyebrow: '01 // The Source Code' },
    { title: 'The Three Dimensions', eyebrow: '02 // The Control Panel' },
    { title: "The Pessimist's Script", eyebrow: '03 // Learned Helplessness' },
    { title: 'The Agency Re-Write', eyebrow: '04 // Retraining' },
    { title: 'Your New OS', eyebrow: '05 // The Blueprint' },
  ],
  'strategic-advantage-protocol': [
    { title: 'The Story of You', eyebrow: '01 // Your Internal Script' },
    { title: 'The Two Pillars', eyebrow: '02 // Agency & Communion' },
    { title: 'The Power of Failure', eyebrow: '03 // Pivotal Moments' },
    { title: 'The Advantage of Disadvantage', eyebrow: '04 // Desirable Difficulties' },
    { title: 'Your Redemption Script', eyebrow: '05 // The Blueprint' },
  ],
  'self-efficacy-protocol': [
    { title: 'The Belief Barrier', eyebrow: '01 // Your Secret Engine' },
    { title: 'How Belief is Built', eyebrow: '02 // The 4 Sources' },
    { title: 'The Role Model Myth', eyebrow: '03 // The Struggle Story' },
    { title: 'The Success Iceberg', eyebrow: '04 // Detective of Process' },
    { title: 'The Habit Blueprint', eyebrow: '05 // Reverse-Engineer Success' },
  ],
  'illusion-of-competence-protocol': [
    { title: 'The Great Deception', eyebrow: '01 // The Illusion' },
    { title: 'The Passive Traps', eyebrow: '02 // The False Comfort' },
    { title: 'The Antidote', eyebrow: '03 // The Hard Way That Works' },
    { title: 'The Strategic Toolkit', eyebrow: '04 // The System' },
    { title: 'The Explain-It Test', eyebrow: '05 // The Reality Check' },
    { title: 'Building Bulletproof Knowledge', eyebrow: '06 // The Action Plan' },
  ],
  'procrastination-protocol': [
    { title: 'The Real Reason You Delay', eyebrow: '01 // Not Laziness' },
    { title: 'The Amygdala Hijack', eyebrow: '02 // Brain Battle' },
    { title: 'The Procrastination Equation', eyebrow: '03 // The Formula' },
    { title: "The Ego's Defence System", eyebrow: '04 // The Traps' },
    { title: 'The Guilt Cycle', eyebrow: '05 // The Downward Spiral' },
    { title: 'The Forgiveness Protocol', eyebrow: '06 // The Circuit Breaker' },
    { title: 'The "If-Then" Protocol', eyebrow: '07 // The Antidote' },
    { title: 'Scaffolding Your Focus', eyebrow: '08 // The Toolkit' },
  ],
  'neuroplasticity-protocol': [
    { title: 'The Plastic Brain', eyebrow: '01 // The Paradigm Shift' },
    { title: "The Brain's Renovation", eyebrow: '02 // Sculpt & Upgrade' },
    { title: 'The Rulebook of Learning', eyebrow: '03 // Fire Together, Wire Together' },
    { title: 'The Physical Evidence', eyebrow: '04 // The Juggling Study' },
    { title: 'The Learning Blueprint', eyebrow: '05 // Why Some Methods Work' },
    { title: 'System Maintenance', eyebrow: '06 // Sleep & Stress' },
  ],
  'myelin-manual-protocol': [
    { title: 'The Silent Revolution', eyebrow: '01 // The Other Brain' },
    { title: 'The Signal of Struggle', eyebrow: '02 // The Chemical Trigger' },
    { title: 'Deep Practice', eyebrow: '03 // The Behavioural Trigger' },
    { title: 'The Mastery Metaphors', eyebrow: '04 // The Mental Models' },
    { title: 'The Rules of Myelination', eyebrow: '05 // The Action Plan' },
  ],
  'praise-protocol': [
    { title: 'The Praise Paradox', eyebrow: '01 // The Big Idea' },
    { title: 'The Praise Experiment', eyebrow: '02 // What Actually Happens' },
    { title: 'The Brain on Praise', eyebrow: '03 // What Your Brain Does' },
    { title: 'The Real World Data', eyebrow: '04 // The Gender Gap' },
    { title: 'The "Effort" Trap', eyebrow: '05 // The Common Mistake' },
    { title: 'The Feedback Audit', eyebrow: '06 // Your Action Plan' },
  ],
  'effective-struggle-protocol': [
    { title: 'The Fallacy of Ease', eyebrow: '01 // The Illusion' },
    { title: "Your Brain's Bottleneck", eyebrow: '02 // The Governor' },
    { title: 'The Sweet Spot', eyebrow: '03 // The Boundary' },
    { title: 'The Engine of Memory', eyebrow: '04 // The Engine' },
    { title: 'The Unified Model', eyebrow: '05 // The Formula' },
    { title: 'Recalibrate Your Dashboard', eyebrow: '06 // The Feeling' },
  ],
  'science-of-making-mistakes-protocol': [
    { title: "The Brain's Alarm", eyebrow: '01 // The "Uh-Oh" Signal' },
    { title: 'The Second Signal', eyebrow: '02 // The Analysis' },
    { title: 'The Mindset Switch', eyebrow: '03 // Leaning In' },
    { title: 'The High-Stakes Hijack', eyebrow: '04 // The Leaving Cert Brain' },
    { title: 'Your Error Toolkit', eyebrow: '05 // Building Better Habits' },
  ],
  'autodidact-engine-protocol': [
    { title: 'Not All Study Is Equal', eyebrow: '01 // The Big Idea' },
    { title: 'How Feedback Loops Work', eyebrow: '02 // Two Key Rules' },
    { title: 'The Maths Loop', eyebrow: '03 // Step-by-Step Practice' },
    { title: 'The Language Loop', eyebrow: '04 // Translate and Compare' },
    { title: 'The Writing Loop', eyebrow: '05 // Audit Your Writing' },
    { title: 'Build Your Engine', eyebrow: '06 // The Action Plan' },
  ],
  'power-of-yet-protocol': [
    { title: 'The Full Stop', eyebrow: '01 // The Verdict' },
    { title: 'The Software Patch', eyebrow: '02 // The "Yet" Upgrade' },
    { title: 'The Brain on "Yet"', eyebrow: '03 // The Science' },
    { title: 'The Action Bridge', eyebrow: '04 // The Protocol' },
    { title: 'Your "Yet" Audit', eyebrow: '05 // The Blueprint' },
  ],
  'growth-mindset-protocol': [
    { title: 'The Two Brains: Fixed vs. Growth', eyebrow: '01 // The Operating System' },
    { title: 'Your Brain is Plastic', eyebrow: '02 // The Hardware Upgrade' },
    { title: 'The Most Powerful Word', eyebrow: '03 // The Software Patch' },
    { title: 'Effort is the Real Talent', eyebrow: '04 // The Engine' },
    { title: 'Feedback is Fuel, Not a Verdict', eyebrow: '05 // The Navigation Data' },
    { title: 'Installing Your Growth OS', eyebrow: '06 // System Integration' },
  ],
  'mastering-active-recall-protocol': [
    { title: 'The Great Forgetting', eyebrow: '01 // The Problem' },
    { title: 'Why Testing Yourself Works', eyebrow: '02 // How It Works' },
    { title: 'The "I Know This" Trap', eyebrow: '03 // The Common Mistake' },
    { title: 'Beyond Just Memorising Facts', eyebrow: '04 // Real Understanding' },
    { title: 'The Anxiety Myth', eyebrow: '05 // The Surprising Truth' },
    { title: 'Your Recall Toolkit', eyebrow: '06 // The Action Plan' },
  ],
  'mastering-spaced-repetition-protocol': [
    { title: 'The Forgetting Curve', eyebrow: '01 // The Default Setting' },
    { title: 'The Cramming Paradox', eyebrow: '02 // The Illusion of Speed' },
    { title: 'The Struggle Sweet Spot', eyebrow: '03 // The Brain\'s Trigger' },
    { title: 'The Best Review Schedule', eyebrow: '04 // When to Review' },
    { title: 'Apps That Do It For You', eyebrow: '05 // The Autopilot' },
    { title: 'Your Spacing Blueprint', eyebrow: '06 // The Action Plan' },
  ],
  'mastering-interleaving-protocol': [
    { title: 'Why "Finishing a Topic" Fools You', eyebrow: '01 // The Trap' },
    { title: 'The "Topic Salad" Method', eyebrow: '02 // The Fix' },
    { title: 'Why Harder Feels Better (For Your Brain)', eyebrow: '03 // Why It Works' },
    { title: 'The "Worst First" Timetable', eyebrow: '04 // The System' },
    { title: 'Your Mix-It-Up Game Plan', eyebrow: '05 // Your Action Plan' },
  ],
  'cognitive-architecture-protocol': [
    { title: 'Your Three Types of Memory', eyebrow: '01 // The Basics' },
    { title: 'Why Your Brain Gets Overloaded', eyebrow: '02 // The Bottleneck' },
    { title: 'How Long-Term Memory Is Organised', eyebrow: '03 // The Library' },
    { title: 'How to Actually Save What You Learn', eyebrow: '04 // Making It Stick' },
    { title: 'Why Sleep Is Non-Negotiable', eyebrow: '05 // The Night Shift' },
    { title: 'Your Action Plan', eyebrow: '06 // Next Steps' },
  ],
  'elaborative-interrogation-protocol': [
    { title: 'The "Why" Engine', eyebrow: '01 // How It Works' },
    { title: 'The Rules of the Road', eyebrow: '02 // When It Works Best' },
    { title: 'The STEM Toolkit', eyebrow: '03 // Science & Maths' },
    { title: 'The Humanities Engine', eyebrow: '04 // Essays & Arguments' },
    { title: 'The Language Edge', eyebrow: '05 // Gaeilge & Beyond' },
    { title: 'Your Study Plan', eyebrow: '06 // The Action Plan' },
  ],
  'cognitive-endurance-protocol': [
    { title: 'The Marathon Mindset', eyebrow: '01 // The Big Picture' },
    { title: 'The Sleep Banking Strategy', eyebrow: '02 // The Non-Negotiable' },
    { title: 'Fueling the Engine', eyebrow: '03 // Food & Drink' },
    { title: 'The In-Exam Toolkit', eyebrow: '04 // Staying Calm Under Pressure' },
    { title: 'The Training Plan', eyebrow: '05 // Building Up Gradually' },
    { title: 'The Recovery Protocol', eyebrow: '06 // Real Rest' },
  ],
  'mental-modelling-protocol': [
    { title: "The Mind's Eye", eyebrow: '01 // The Skill Nobody Teaches' },
    { title: 'The Modelling Cycle', eyebrow: '02 // The Process' },
    { title: 'The "Glass Box" (DCG)', eyebrow: '03 // Picturing Shapes' },
    { title: 'The "Mental Movie" (Eng)', eyebrow: '04 // Picturing Movement' },
    { title: 'The Procedural Trap', eyebrow: '05 // Where Students Get Stuck' },
    { title: 'The Training Plan', eyebrow: '06 // The Action Plan' },
  ],
  'bimodal-brain-protocol': [
    { title: 'Your Brain Has Two Gears', eyebrow: '01 // The Big Idea' },
    { title: 'Gear One: Laser Focus', eyebrow: '02 // Locking In' },
    { title: 'Gear Two: The Wandering Mind', eyebrow: '03 // Letting Go' },
    { title: 'Switching Between Gears', eyebrow: '04 // The Art of the Break' },
    { title: 'Why We Put Things Off', eyebrow: '05 // Why We Delay' },
    { title: 'Your Two-Gear Game Plan', eyebrow: '06 // Your Action Plan' },
  ],
  'leaving-cert-strategy-protocol': [
    { title: 'How the Points Game Works', eyebrow: '01 // The Rules' },
    { title: 'Picking Your Subjects Smartly', eyebrow: '02 // Subject Choice' },
    { title: 'English, Maths & Irish', eyebrow: '03 // The Big Three' },
    { title: 'Your Other Subjects', eyebrow: '04 // Working the System' },
    { title: 'What Examiners Actually Want', eyebrow: '05 // Reading the Exam' },
    { title: 'Exam Day: Your Game Plan', eyebrow: '06 // On the Day' },
  ],
  'reverse-engineering-protocol': [
    { title: 'Why Most Study Plans Fail', eyebrow: '01 // The Problem' },
    { title: 'Why Planning Backwards Works', eyebrow: '02 // The Idea' },
    { title: 'Breaking Down the Syllabus', eyebrow: '03 // The Inventory' },
    { title: 'Your Four Study Phases', eyebrow: '04 // The Timeline' },
    { title: 'Studying Smarter', eyebrow: '05 // The Science' },
    { title: 'Making a Plan That Actually Lasts', eyebrow: '06 // Your Plan' },
  ],
  'exam-hall-strategies-protocol': [
    { title: 'Knowing vs. Showing It', eyebrow: '01 // The Real Problem' },
    { title: 'The Brain Dump', eyebrow: '02 // Your First 3 Minutes' },
    { title: 'Reading Time Triage', eyebrow: '03 // Sorting the Paper' },
    { title: 'Order of Attack', eyebrow: '04 // Building Momentum' },
    { title: 'Time Budgeting', eyebrow: '05 // Spending Minutes Wisely' },
    { title: 'Staying Calm Under Pressure', eyebrow: '06 // Managing Panic' },
    { title: 'Practice Drills', eyebrow: '07 // Building the Habits' },
  ],
  'exam-crisis-management-protocol': [
    { title: 'Why You "Go Blank"', eyebrow: '01 // Stress vs. Your Brain' },
    { title: 'The "Blank Mind" Fix', eyebrow: '02 // Body-Based Fixes' },
    { title: 'Protect Your Head After Exams', eyebrow: '03 // The Post-Exam Trap' },
    { title: 'Sleep: Your Secret Weapon', eyebrow: '04 // Sleep for Exams' },
    { title: 'Food and Focus', eyebrow: '05 // Eating for Exam Day' },
    { title: 'Your Personal Crisis Plan', eyebrow: '06 // Plan Before Panic Hits' },
    { title: 'The 7-Day Countdown', eyebrow: '07 // Your Final Week Plan' },
  ],
  'game-day-protocol': [
    { title: 'The Athlete Mindset', eyebrow: '01 // The Game Plan' },
    { title: '1 Month Out', eyebrow: '02 // Building Your Base' },
    { title: 'The Final Week', eyebrow: '03 // The Wind-Down' },
    { title: 'Mental Rehearsal', eyebrow: '04 // Visualization' },
    { title: 'The Day Before', eyebrow: '05 // Setting Up' },
    { title: 'Game Day Morning', eyebrow: '06 // The Warm-Up' },
    { title: 'In The Arena', eyebrow: '07 // Go Time' },
    { title: 'Halftime & Post-Game', eyebrow: '08 // Recovery' },
  ],
  'reframing-catastrophic-thoughts-protocol': [
    { title: 'The Catastrophe Machine', eyebrow: '01 // The Problem' },
    { title: 'Why You Go "Blank"', eyebrow: '02 // What Happens in Your Brain' },
    { title: 'Challenging Your Thoughts (CBT)', eyebrow: '03 // The Main Approach' },
    { title: 'The Thought Record', eyebrow: '04 // The Core Tool' },
    { title: 'Decatastrophizing', eyebrow: '05 // The "So What?" Drill' },
    { title: 'Facing the Fear', eyebrow: '06 // Exposure' },
    { title: 'Stepping Back from Your Thoughts', eyebrow: '07 // A Different Approach' },
    { title: 'The Action Plan', eyebrow: '08 // The Blueprint' },
  ],
  'emotional-intelligence-protocol': [
    { title: 'Why Stress Messes With Your Brain', eyebrow: '01 // The Hardware' },
    { title: 'What is Emotional Intelligence?', eyebrow: '02 // The Software' },
    { title: 'Reading Your Own Body', eyebrow: '03 // Early Warning Signs' },
    { title: 'Using Your Mind to Manage Stress', eyebrow: '04 // The Mind' },
    { title: 'Using Your Body to Calm Down', eyebrow: '05 // The Body' },
    { title: 'Sleep, Food, and Water', eyebrow: '06 // Fuel & Maintenance' },
    { title: 'Putting It All Together', eyebrow: '07 // The Plan' },
  ],
  'controllable-variables-protocol': [
    { title: 'The Performance Engine', eyebrow: '01 // The Core Idea' },
    { title: 'The Save Button: Sleep', eyebrow: '02 // The Foundation' },
    { title: 'The Fuel Supply: Nutrition', eyebrow: '03 // The Energy' },
    { title: 'The Upgrade: Exercise', eyebrow: '04 // The Catalyst' },
    { title: 'The Vicious Cycle', eyebrow: '05 // The Feedback Loop' },
    { title: 'The High-Performance Blueprint', eyebrow: '06 // Your Protocol' },
  ],
  'reframing-progress-protocol': [
    { title: 'The Time Trap', eyebrow: '01 // Naive vs. Deliberate' },
    { title: 'The 80/20 Protocol', eyebrow: '02 // The Vital Few' },
    { title: 'The "Banked Grade" Heist', eyebrow: '03 // Securing Early Wins' },
    { title: 'The Quest System', eyebrow: '04 // Mastery vs. Performance' },
    { title: 'The Kanban Flow', eyebrow: '05 // Visualizing Work' },
    { title: 'The Retrospective Log', eyebrow: '06 // Data-Driven Study' },
    { title: 'The XP Engine', eyebrow: '07 // Gamifying the Grind' },
  ],
  'linking-study-future-goals-protocol': [
    { title: 'The "Why Bother?" Problem', eyebrow: '01 // When Motivation Drops' },
    { title: 'The Horizon of Purpose', eyebrow: '02 // Seeing Your Future' },
    { title: 'The "Writing Cure"', eyebrow: '03 // Making It Personal' },
    { title: 'From Dream to Plan', eyebrow: '04 // Getting Real About Goals' },
    { title: 'Becoming the Author', eyebrow: '05 // Taking Ownership' },
    { title: 'Curriculum as Career Training', eyebrow: '06 // Reframing the Work' },
    { title: 'Hacking the System', eyebrow: '07 // Using Every Advantage' },
    { title: 'The Purpose Protocol', eyebrow: '08 // Putting It Together' },
  ],
  'learning-math-protocol': [
    { title: 'The New Game', eyebrow: '01 // What Changed' },
    { title: 'The Two Papers', eyebrow: '02 // Paper 1 vs. Paper 2' },
    { title: 'The Five Strands', eyebrow: '03 // What You Need to Know' },
    { title: 'How Marking Actually Works', eyebrow: '04 // Getting Marks You Deserve' },
    { title: 'Never Leave a Question Blank', eyebrow: '05 // Free Marks' },
    { title: 'Spotting the Patterns', eyebrow: '06 // Tricky Questions & Crossovers' },
    { title: 'What Examiners Actually Look For', eyebrow: '07 // Common Mistakes' },
    { title: 'Study Smarter for Maths', eyebrow: '08 // How to Actually Learn This Stuff' },
    { title: 'The H1 Pathway', eyebrow: '09 // Locking In Top Marks' },
  ],
  'mastering-foreign-languages-protocol': [
    { title: 'Two Plans, One Goal', eyebrow: '01 // Your Game Plan' },
    { title: 'The Oral Exam', eyebrow: '02 // Bank 25% Early' },
    { title: 'What Examiners Actually Want', eyebrow: '03 // Common Mistakes vs Top Marks' },
    { title: 'Building Your Vocabulary', eyebrow: '04 // Making Words Stick' },
    { title: 'The Listening Exam', eyebrow: '05 // Training Your Ear' },
    { title: 'Reading Comprehension', eyebrow: '06 // Find the Answer Fast' },
    { title: 'Writing Strong Essays', eyebrow: '07 // Building Great Paragraphs' },
    { title: 'Your Action Plan', eyebrow: '08 // Make It Happen' },
  ],
  'mastering-the-sciences-protocol': [
    { title: "What They Don't Teach You", eyebrow: '01 // The Big Picture' },
    { title: 'Biology: Every Word Counts', eyebrow: '02 // Know Your Keywords' },
    { title: 'Chemistry: Seeing the Molecules', eyebrow: '03 // Build the Logic' },
    { title: 'Physics: Problem-Solving Mindset', eyebrow: '04 // Think It Through' },
    { title: 'Ag Science: Think Like a Scientist', eyebrow: '05 // Get Investigative' },
    { title: 'Study Smarter for Science', eyebrow: '06 // Your Toolkit' },
    { title: 'Your Action Plan', eyebrow: '07 // Get Started' },
  ],
  'mastering-the-humanities-protocol': [
    { title: 'The Unwritten Rules', eyebrow: '01 // What They Don\'t Tell You' },
    { title: 'How History Is Really Marked', eyebrow: '02 // CM + OE' },
    { title: 'How Geography Is Really Marked', eyebrow: '03 // SRPs' },
    { title: 'The Essay Toolkit', eyebrow: '04 // The PEE Chain' },
    { title: 'Your Action Plan', eyebrow: '05 // What to Do Next' },
  ],
  'mastering-english-protocol': [
    { title: 'How You Actually Get Marked', eyebrow: '01 // The Marking Scheme' },
    { title: 'Paper 1: Where the Marks Are', eyebrow: '02 // Language & Comprehension' },
    { title: 'Paper 1: The 100-Mark Essay', eyebrow: '03 // Composing' },
    { title: 'Paper 2: The Single Text', eyebrow: '04 // Macbeth 2026' },
    { title: 'Paper 2: The Comparative Study', eyebrow: '05 // The Modes' },
    { title: 'Paper 2: Prescribed Poetry', eyebrow: '06 // The "Big 4" Rule' },
    { title: 'Your English Toolkit', eyebrow: '07 // Smart Techniques' },
  ],
  'mastering-business-protocol': [
    { title: 'What You Need to Know for 2026', eyebrow: '01 // The Big Picture' },
    { title: 'How the Paper Works', eyebrow: '02 // The Layout' },
    { title: 'ABQ Deep Dive', eyebrow: '03 // The Game-Changer' },
    { title: 'How to Pick Up Every Mark', eyebrow: '04 // Getting Better Marks' },
    { title: 'Quick Wins and Smart Moves', eyebrow: '05 // The Toolkit' },
    { title: 'Your Study Plan', eyebrow: '06 // The Action Plan' },
  ],
  'applied-sciences-protocol': [
    { title: 'The Big Picture', eyebrow: '01 // What Ties It All Together' },
    { title: 'Engineering', eyebrow: '02 // Semiconductors & Your Project' },
    { title: 'DCG', eyebrow: '03 // Soap Dispensers & CAD' },
    { title: 'Computer Science', eyebrow: '04 // Forests & Climate' },
    { title: 'Construction & Tech', eyebrow: '05 // Your Project Counts' },
    { title: 'How These Subjects Connect', eyebrow: '06 // Your Action Plan' },
  ],
  'mastering-the-creatives-protocol': [
    { title: 'The Talent Myth', eyebrow: '01 // Mindset Reset' },
    { title: 'Art: The Visual Journal', eyebrow: '02 // Art' },
    { title: 'Music: Writing a Melody', eyebrow: '03 // Music' },
    { title: 'Film: Reading the Screen', eyebrow: '04 // Film' },
    { title: 'Handling Exam Nerves', eyebrow: '05 // Exam Day' },
    { title: 'Your Creative Game Plan', eyebrow: '06 // Next Steps' },
  ],
  'digital-distraction-protocol': [
    { title: 'Why Your Phone Wins', eyebrow: '01 // Your Brain vs Your Phone' },
    { title: 'The Phone Swap', eyebrow: '02 // The Physical Barrier' },
    { title: 'Locking Down Your Laptop', eyebrow: '03 // Blocking Distractions' },
    { title: 'Setting Up Your Space', eyebrow: '04 // Your Study Zone' },
    { title: 'Building Better Habits', eyebrow: '05 // Making It Automatic' },
    { title: 'Dealing with FOMO', eyebrow: '06 // Your Friends Will Survive' },
    { title: 'Your Step-by-Step Plan', eyebrow: '07 // Putting It All Together' },
  ],
  'points-optimization-protocol': [
    { title: 'The 12-Point Cliff', eyebrow: '01 // How Points Really Work' },
    { title: 'The Maths Multiplier', eyebrow: '02 // The 25-Point Bonus' },
    { title: 'H1 Probability Map', eyebrow: '03 // The Data' },
    { title: 'The Objectivity Advantage', eyebrow: '04 // Reducing Exam-Day Risk' },
    { title: 'Subject Overlap', eyebrow: '05 // Study Smarter' },
    { title: 'The Surplus Rule', eyebrow: '06 // Banking Extra Marks' },
    { title: 'Your 625 Blueprint', eyebrow: '07 // Your Personal Plan' },
  ],
  'marking-scheme-decoder-protocol': [
    { title: "The Examiner's Secret", eyebrow: '01 // The Mindset' },
    { title: 'The Three Types of Marks', eyebrow: '02 // The System' },
    { title: 'Reading a Real Marking Scheme', eyebrow: '03 // The Decode' },
    { title: 'The Keyword Effect', eyebrow: '04 // The Language' },
    { title: 'Attempt Marks: The Free Points', eyebrow: '05 // The Safety Net' },
    { title: 'The Presentation Protocol', eyebrow: '06 // The Polish' },
    { title: 'Your Decoding Action Plan', eyebrow: '07 // The Plan' },
  ],
  'answer-engineering-protocol': [
    { title: 'The Structure Gap', eyebrow: '01 // The Problem' },
    { title: 'The PEEL Framework', eyebrow: '02 // The Essay Engine' },
    { title: 'The Science Answer Stack', eyebrow: '03 // The Formula' },
    { title: 'The Marks-Shape Connection', eyebrow: '04 // The Decoder' },
    { title: 'The 60% Answer', eyebrow: '05 // The Rescue' },
    { title: 'Subject-Specific Structures', eyebrow: '06 // The Toolkit' },
    { title: 'Your Engineering Toolkit', eyebrow: '07 // The Plan' },
  ],
  'learning-radar-protocol': [
    { title: "You Don't Know What You Don't Know", eyebrow: '01 // The Blind Spot' },
    { title: 'Why the Least Prepared Feel Most Confident', eyebrow: '02 // The Confidence Trap' },
    { title: "When to Check If You've Learned Something", eyebrow: '03 // The Timing Trick' },
    { title: 'The Traffic Light Audit', eyebrow: '04 // The Reality Check' },
    { title: 'Checking Yourself During Study', eyebrow: '05 // The Signals' },
    { title: 'The Prediction Game', eyebrow: '06 // The Training Ground' },
  ],
  'note-taking-paradox-protocol': [
    { title: 'The Copy-Paste Trap', eyebrow: '01 // The Paradox' },
    { title: 'Notes That Actually Work', eyebrow: '02 // Think, Don\'t Copy' },
    { title: 'The Cornell Method', eyebrow: '03 // The System' },
    { title: 'Maps vs Lists', eyebrow: '04 // Choosing Your Layout' },
    { title: 'Building Your Own System', eyebrow: '05 // Putting It Together' },
  ],
  'teaching-effect-protocol': [
    { title: 'Why Teaching Beats Testing', eyebrow: '01 // The Discovery' },
    { title: 'Explaining Changes How You Think', eyebrow: '02 // How It Works' },
    { title: "You Don't Need an Audience", eyebrow: '03 // Going Solo' },
    { title: 'The Simplicity Technique', eyebrow: '04 // The Technique' },
    { title: 'Putting It All Together', eyebrow: '05 // Your System' },
  ],
  'cognitive-load-protocol': [
    { title: 'The Bottleneck', eyebrow: '01 // The Hard Limit' },
    { title: 'Three Kinds of Brain Drain', eyebrow: '02 // The Breakdown' },
    { title: 'Why Separate Diagrams Kill Learning', eyebrow: '03 // The Design Trap' },
    { title: 'When Easy Becomes Harmful', eyebrow: '04 // The Plot Twist' },
    { title: "Managing Your Brain's Limits", eyebrow: '05 // Your Game Plan' },
  ],
  'implementation-protocol': [
    { title: 'The Intention-Action Gap', eyebrow: '01 // The Problem' },
    { title: 'If-Then Plans', eyebrow: '02 // The Solution' },
    { title: 'Temptation Bundling', eyebrow: '03 // The Reward Hack' },
    { title: 'Commitment Devices', eyebrow: '04 // The Lock-In' },
    { title: 'Building Your Protocol', eyebrow: '05 // The System' },
  ],
  'context-effect-protocol': [
    { title: 'Why You Blank in the Exam Hall', eyebrow: '01 // The Problem' },
    { title: "The 'Switch It Up' Fix", eyebrow: '02 // The Solution' },
    { title: 'Does Noise Help or Hurt?', eyebrow: '03 // The Noise Question' },
    { title: 'Why Switching Spots Works', eyebrow: '04 // How It Works' },
    { title: 'Setting Up Your Study Rotation', eyebrow: '05 // Your Game Plan' },
  ],
};
