import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './index.html',
    './**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        zinc: {
          50:  '#FAFAF7',
          100: '#F0F0EB',
          200: '#E5E4DF',
          300: '#BFBFBA',
          400: '#91918D',
          500: '#666663',
          600: '#52524F',
          700: '#40403E',
          800: '#262625',
          900: '#191919',
          950: '#131311',
        },
        accent: {
          DEFAULT: '#CC785C',
          light: '#D98E74',
          dark: '#B56A50',
        },
        brand: {
          teal: '#2A7D6F',
          cream: '#FAFBF6',
          sage: '#6B8F71',
          amber: '#C4873B',
        },
      },
      fontFamily: {
        serif: ['"Source Serif 4"', 'serif'],
        sans: ['"DM Sans"', 'sans-serif'],
        mono: ['"Roboto Mono"', 'monospace'],
        apercu: ['"Apercu Mono Pro"', '"DM Sans"', 'monospace'],
      },
      keyframes: {
        shine: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'blob-drift-1': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
        },
        'blob-drift-2': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(-40px, 30px) scale(1.05)' },
          '66%': { transform: 'translate(25px, -35px) scale(0.95)' },
        },
        'blob-drift-3': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(25px, 45px) scale(1.08)' },
          '66%': { transform: 'translate(-35px, -25px) scale(0.92)' },
        },
      },
      animation: {
        'blob-1': 'blob-drift-1 20s ease-in-out infinite',
        'blob-2': 'blob-drift-2 25s ease-in-out infinite',
        'blob-3': 'blob-drift-3 18s ease-in-out infinite',
      },
    },
  },
  // Safelist dynamic theme classes generated by moduleThemes.ts createTheme() factory.
  // Only the exact shades actually used: 50, 100, 200, 400, 500, 600, 800, 900
  safelist: (() => {
    const colors = ['amber','blue','rose','emerald','orange','teal','cyan','slate','sky','red','purple','fuchsia','indigo','violet','pink','lime','yellow','gray'];
    const classes: string[] = [];
    for (const c of colors) {
      // Exact classes produced by createTheme()
      classes.push(
        `bg-${c}-100/40`, `text-${c}-900`, `decoration-${c}-400/40`, `hover:bg-${c}-200/60`,
        `text-${c}-400`, `bg-${c}-50`, `text-${c}-600`, `bg-${c}-50/50`,
        `border-${c}-200`, `bg-${c}-500`, `shadow-${c}-500/20`, `text-${c}-800`,
        `text-${c}-500`, `bg-${c}-600`, `border-${c}-600`, `border-${c}-500`,
        `hover:bg-${c}-600`,
      );
    }
    return classes;
  })(),
  plugins: [],
};

export default config;
