/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Construction Studies cards, Ordinary Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/construction-studies/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the sections of the Construction Studies syllabus these
 * papers were sat under. Construction Technology replaces it from 2028.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "construction-studies",
  specVersion: "lc-construction-studies-syllabus",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2021 Ordinary Level — © State Examinations Commission.",
    id: "cons-2021-ol-q3-a", topicId: "cons-5-2", conceptId: "cold-water-pipework-from-the-tank",
    section: "B", questionRef: "2021 OL Q3(a)",
    questionText: "Using a single-line labelled sketch, show the pipework required to supply cold water from the water main to the kitchen sink and to the water storage tank.",
    tariffModel: {"kind":"bestNofParts","notation":"8 x 4","answer":8,"ofParts":12,"perPart":4}, totalMarks: 32,
    rows: [
    { id: "cons-2021-ol-q3-a-r1", kind: "anyN", verbatim: "Typical details", marks: 32, contextNote: "Typical details", openList: true, group: {"claimMax":8,"perOption":4,"options":["Mains water supply","Water meter","Stop valve","15 mm rising main","Kitchen sink","Connection to kitchen sink","Ball-valve","Cold water storage tank","Insulation around storage tank","28 mm overflow","Pipework insulation","Valves"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2021 Ordinary Level — © State Examinations Commission.",
    id: "cons-2021-ol-q5-a", topicId: "cons-3-6", conceptId: "vertical-section-external-wall-and-window",
    section: "B", questionRef: "2021 OL Q5(a)",
    questionText: "To a scale of 1:5, draw a vertical section through the external wall and bottom portion of the window. Show the typical construction details from a level 400 mm below to a level 300 mm above the concrete window cill.",
    tariffModel: {"kind":"bestNofParts","notation":"7 x 5","answer":7,"ofParts":14,"perPart":5}, totalMarks: 35,
    rows: [
    { id: "cons-2021-ol-q5-a-r1", kind: "anyN", verbatim: "Specifications", marks: 35, contextNote: "Specifications", openList: true, group: {"claimMax":7,"perOption":5,"options":["19 mm external render","100 mm concrete block outer leaf","Full filled insulated cavity","Wall ties","100 mm concrete block inner leaf","13 mm internal plaster","Cavity closer","DPC","Precast concrete window cill","Throating / drip","Window board","Airtight tape","Window frame 120 × 80 mm","Triple glazing"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2021 Ordinary Level — © State Examinations Commission.",
    id: "cons-2021-ol-q6-c", topicId: "cons-1-8", conceptId: "safety-precautions-in-a-deep-trench",
    section: "B", questionRef: "2021 OL Q6(c)",
    questionText: "Using notes and a freehand sketch, describe one safety precaution that workers should observe when working in a deep trench on a construction site.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 13","answer":2,"ofParts":4,"perPart":13}, totalMarks: 26,
    rows: [
    { id: "cons-2021-ol-q6-c-r1", kind: "anyN", verbatim: "Using notes and a freehand sketch, describe one safety precaution that workers should observe when working in a deep tre", marks: 26, openList: true, group: {"claimMax":2,"perOption":13,"options":["Slope or battering back the trench sides to a safe angle to stabilise the sides and stop collapse","Support trench walls with sheeting/trench box when the depth exceeds 1.25 metres to prevent the collapse of the sides","Ensure guard rails and exclusion zone notices are in place to limit the proximity of machines and workers to the edge of the trench","Ensure excavated material is stored at a safe distance from the open trench to prevent material falling into the trench"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2021 Ordinary Level — © State Examinations Commission.",
    id: "cons-2021-ol-q7-c", topicId: "cons-5-7", conceptId: "a-wood-burning-stove-in-a-living-room",
    section: "B", questionRef: "2021 OL Q7(c)",
    questionText: "Discuss one advantage of incorporating a wood-burning stove in a modern living room.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 6","answer":2,"ofParts":4,"perPart":6}, totalMarks: 12,
    rows: [
    { id: "cons-2021-ol-q7-c-r1", kind: "anyN", verbatim: "Discuss one advantage of incorporating a wood-burning stove in a modern living room.", marks: 12, openList: true, group: {"claimMax":2,"perOption":6,"options":["A centre piece for a group to gather around and socialise","Provides warmth to the family in the main room of the dwelling","Environmentally friendly if using timber for fuel","Reduces the use oil and gas to heat the area"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2022 Ordinary Level — © State Examinations Commission.",
    id: "cons-2022-ol-q1-a", topicId: "cons-3-4", conceptId: "vertical-section-wall-lintel-and-doorframe",
    section: "B", questionRef: "2022 OL Q1(a)",
    questionText: "To a scale of 1:5, draw a vertical section through the external wall, concrete lintels, doorframe and door. On your drawing show the typical construction details from 400 mm below to a level 400 mm above the concrete lintels. Include four typical dimensions.",
    tariffModel: {"kind":"bestNofParts","notation":"7 x 5","answer":7,"ofParts":12,"perPart":5}, totalMarks: 35,
    rows: [
    { id: "cons-2022-ol-q1-a-r1", kind: "anyN", verbatim: "Specification – typical detail", marks: 35, contextNote: "Specification – typical detail", openList: true, group: {"claimMax":7,"perOption":5,"options":["19 mm external render","Concrete block outer leaf 100 mm","Full fill insulated cavity 200 mm","Concrete block inner leaf 100 mm","15 mm internal plaster","Concrete lintels","Wall tie","Stepped DPC","Airtight tape","Cavity closer","Thermally broken doorframe 150 mm × 80 mm","Insulated external door 90 mm N.B. Any alternative detailing which complies with current Building Regulations is acceptable"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2022 Ordinary Level — © State Examinations Commission.",
    id: "cons-2022-ol-q3-b", topicId: "cons-5-6", conceptId: "pipework-for-flushing-with-rainwater",
    section: "B", questionRef: "2022 OL Q3(b)",
    questionText: "The stored rainwater is used for flushing toilets. On the sketch, show the pipework necessary to take rainwater from the underground tank to the storage tank in the attic. Show the pipework necessary to connect the toilet cistern to the storage tank in the attic. Include all necessary pumps and valves.",
    tariffModel: {"kind":"bestNofParts","notation":"6 x 4","answer":6,"ofParts":9,"perPart":4}, totalMarks: 24,
    rows: [
    { id: "cons-2022-ol-q3-b-r1", kind: "anyN", verbatim: "Typical details", marks: 24, contextNote: "Typical details", openList: true, group: {"claimMax":6,"perOption":4,"options":["Submersible pump in water storage tank","12 mm pipe from storage tank to filter","In line filter","230 litre attic storage tank","Overflow pipe","Ball valve","12 mm feed to toilet cistern","Toilet","All necessary valves"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2022 Ordinary Level — © State Examinations Commission.",
    id: "cons-2022-ol-q3-c", topicId: "cons-5-4", conceptId: "advantages-of-reusing-rainwater",
    section: "B", questionRef: "2022 OL Q3(c)",
    questionText: "Discuss one advantage of reusing rainwater in a dwelling house.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 6","answer":2,"ofParts":3,"perPart":6}, totalMarks: 12,
    rows: [
    { id: "cons-2022-ol-q3-c-r1", kind: "anyN", verbatim: "Discuss one advantage of reusing rainwater in a dwelling house.", marks: 12, openList: true, group: {"claimMax":2,"perOption":6,"options":["Sustainable living","Reduces flooding around property","Reduce the cost of water treatment due to reduced usage"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2022 Ordinary Level — © State Examinations Commission.",
    id: "cons-2022-ol-q5-a", topicId: "cons-4-4", conceptId: "vertical-section-bottom-three-steps",
    section: "B", questionRef: "2022 OL Q5(a)",
    questionText: "To a scale of 1:5, draw a vertical section through the centre of the bottom three steps of the stairs. Show the string, treads and risers. Include three typical dimensions on your drawing.",
    tariffModel: {"kind":"bestNofParts","notation":"7 x 5","answer":7,"ofParts":9,"perPart":5}, totalMarks: 35,
    rows: [
    { id: "cons-2022-ol-q5-a-r1", kind: "anyN", verbatim: "Specification – typical detail", marks: 35, contextNote: "Specification – typical detail", openList: true, group: {"claimMax":7,"perOption":5,"options":["String 250 mm × 50 mm","Tread 250 mm × 25 mm","Riser 170 mm x 20 mm","Joint between tread and riser","Nosing 16 mm minimum","Vertical wedge","Horizontal wedge","Glue blocks 60 mm × 60 mm","Pitch line (max 42⁰)"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2022 Ordinary Level — © State Examinations Commission.",
    id: "cons-2022-ol-q6-c", topicId: "cons-9-4", conceptId: "safety-precautions-with-power-tools",
    section: "B", questionRef: "2022 OL Q6(c)",
    questionText: "Using notes and a freehand sketch, describe one safety precaution that will reduce the risk to the public while the footpath is being replaced.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 13","answer":2,"ofParts":4,"perPart":13}, totalMarks: 26,
    rows: [
    { id: "cons-2022-ol-q6-c-r1", kind: "anyN", verbatim: "Using notes and a freehand sketch, describe one safety precaution that will reduce the risk to the public while the foot", marks: 26, openList: true, group: {"claimMax":2,"perOption":13,"options":["Erect signage to direct the public away from the work zone","Ensure guard rails and exclusion zone notices are in place to limit the proximity of the public to the work area","Ensure building material is stored at a safe distance from the open public zones","Enclose work area with dust shelter to prevent dust particles being blown into the open public zones"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2023 Ordinary Level — © State Examinations Commission.",
    id: "cons-2023-ol-q1-b", topicId: "cons-3-3", conceptId: "connecting-the-inner-and-outer-leaves",
    section: "B", questionRef: "2023 OL Q1(b)",
    questionText: "On your drawing, show the typical design detailing to connect the inner and outer leaves of the external wall.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 3","answer":2,"ofParts":13,"perPart":3}, totalMarks: 6,
    rows: [
    { id: "cons-2023-ol-q1-b-r1", kind: "anyN", verbatim: "Specification – typical detail", marks: 6, contextNote: "Specification – typical detail", openList: true, group: {"claimMax":2,"perOption":3,"options":["19 mm external render","Concrete block outer leaf 100 mm","Full fill insulated cavity 200 mm","Wall tie","Concrete block inner leaf 100 mm","15 mm internal plaster","Airtight tape","Joist hanger","225 × 50 mm Joist","Plasterboard ceiling","20 mm plywood decking","T & G hardwood flooring","Skirting board N.B. Any alternative detailing which complies with current Building Regulations is acceptable"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2023 Ordinary Level — © State Examinations Commission.",
    id: "cons-2023-ol-q2-c", topicId: "cons-6-3", conceptId: "other-energy-upgrades-for-an-old-house",
    section: "B", questionRef: "2023 OL Q2(c)",
    questionText: "On a separate sketch show, using notes and freehand sketches, one other possible energy upgrade the homeowner could carry out to their house.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 14","answer":2,"ofParts":5,"perPart":14}, totalMarks: 28,
    rows: [
    { id: "cons-2023-ol-q2-c-r1", kind: "anyN", verbatim: "On a separate sketch show, using notes and freehand sketches, one other possible energy upgrade the homeowner could carr", marks: 28, openList: true, group: {"claimMax":2,"perOption":14,"options":["Increase insulation at roof level","Install solar panels to supplement electricity from the grid","Replace the heating system to a more energy efficient method","Replace open fireplace with a wood burning stove","Upgrade to high performance windows Any alternative detailing which complies with current Building Regulations is acceptable"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2023 Ordinary Level — © State Examinations Commission.",
    id: "cons-2023-ol-q3-a", topicId: "cons-5-2", conceptId: "pipework-for-a-solar-installation",
    section: "B", questionRef: "2023 OL Q3(a)",
    questionText: "Draw a large freehand sketch of the given house. On your sketch, show the pipework necessary to connect the solar collector to the hot water cylinder and supply hot water to a shower.",
    tariffModel: {"kind":"bestNofParts","notation":"8 x 5","answer":8,"ofParts":12,"perPart":5}, totalMarks: 40,
    rows: [
    { id: "cons-2023-ol-q3-a-r1", kind: "anyN", verbatim: "Typical details", marks: 40, contextNote: "Typical details", openList: true, group: {"claimMax":8,"perOption":5,"options":["Solar collector","Ø22 mm cold feed to collector","Ø22 mm hot return to cylinder","250 l cylinder","Circulation pump","24 l solar expansion vessel","Storage tank","Ø22 mm cold feed to cylinder","Ø28 mm expansion pipe","Ø22 mm hot water to shower","Shower unit","Stop valves and drain valve"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2024 Ordinary Level — © State Examinations Commission.",
    id: "cons-2024-ol-q3-a", topicId: "cons-5-2", conceptId: "hot-and-cold-water-pipework",
    section: "B", questionRef: "2024 OL Q3(a)",
    questionText: "Using a single-line labelled sketch, show the pipework required to provide hot and cold water to a mixer-shower and wash basin, and to provide cold water to a toilet cistern.",
    tariffModel: {"kind":"bestNofParts","notation":"8 x 5","answer":8,"ofParts":12,"perPart":5}, totalMarks: 40,
    rows: [
    { id: "cons-2024-ol-q3-a-r1", kind: "anyN", verbatim: "Typical details", marks: 40, contextNote: "Typical details", openList: true, group: {"claimMax":8,"perOption":5,"options":["15 mm rising main","Insulated storage tank","250 l cylinder","Ø22 mm cold feed to cylinder","Ø28 mm expansion pipe","Toilet cistern","Ø15 mm cold feed to toilet cistern","Wash basin","Ø15 mm hot and cold feed to wash basin","Mixer-shower","Ø15 mm hot and cold feed to mixer shower","Valves"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2024 Ordinary Level — © State Examinations Commission.",
    id: "cons-2024-ol-q5-a", topicId: "cons-3-6", conceptId: "vertical-section-external-wall-and-window",
    section: "B", questionRef: "2024 OL Q5(a)",
    stem: "The scheme groups its answer under: Specification – typical detail; 100 mm; 200 mm; 100 mm",
    questionText: "To a scale of 1:5, draw a vertical section through the external wall and the bottom of the window. Show the typical construction details from a level 400 mm below, to a level 300 mm above, the concrete window cill.",
    tariffModel: {"kind":"bestNofParts","notation":"8 x 5","answer":8,"ofParts":14,"perPart":5}, totalMarks: 40,
    rows: [
    { id: "cons-2024-ol-q5-a-r1", kind: "anyN", verbatim: "To a scale of 1:5, draw a vertical section through the external wall and the bottom of the window. Show the typical cons", marks: 40, openList: true, group: {"claimMax":8,"perOption":5,"options":["19 mm external render","Concrete block outer leaf","Full fill insulated cavity","Wall tie","Concrete block inner leaf","15 mm internal plaster","Cavity closer","DPC","Precast concrete cill","Throating / drip","Window board","Airtightness tape","Window frame 120 mm x 80 mm","Triple glazing Note: Any alternative detailing which complies with current Building Regulations is acceptable"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2025 Ordinary Level — © State Examinations Commission.",
    id: "cons-2025-ol-q1-b", topicId: "cons-3-4", conceptId: "preventing-rainwater-at-the-window-head",
    section: "B", questionRef: "2025 OL Q1(b)",
    questionText: "On your drawing, show the typical design detailing that prevents the penetration of rainwater at the window head.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 4","answer":2,"ofParts":12,"perPart":4}, totalMarks: 8,
    rows: [
    { id: "cons-2025-ol-q1-b-r1", kind: "anyN", verbatim: "Specification – typical detail", marks: 8, contextNote: "Specification – typical detail", openList: true, group: {"claimMax":2,"perOption":4,"options":["19 mm external render","Cavity closer","Concrete block outer leaf 100 mm","100 mm × 75 mm concrete lintel","Full fill insulated cavity 200 mm","Stepped DPC","Wall tie","Thermally broken window frame","Concrete block inner leaf 100 mm","Triple glazing","15 mm internal plaster","Airtightness tape N.B. Any alternative detailing which complies with current Building Regulations is acceptable"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2025 Ordinary Level — © State Examinations Commission.",
    id: "cons-2025-ol-q3-b", topicId: "cons-5-3", conceptId: "advantages-of-a-zoned-heating-system",
    section: "B", questionRef: "2025 OL Q3(b)",
    questionText: "Discuss one advantage of installing a zoned heating system so the radiators and hot water can be heated separately.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 5","answer":2,"ofParts":6,"perPart":5}, totalMarks: 10,
    rows: [
    { id: "cons-2025-ol-q3-b-r1", kind: "anyN", verbatim: "Discuss one advantage of installing a zoned heating system so the radiators and hot water can be heated separately.", marks: 10, openList: true, group: {"claimMax":2,"perOption":5,"options":["It is more energy efficient to only heat the zone you need","Reduced cost to homeowner","Avoids unnecessary energy use","More user control over your heating system","Only heating the water may lead to less wear and tear on the heating system","A zoned heating system is a more modern system which may increase the value of the home"]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC029GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Construction Studies 2025 Ordinary Level — © State Examinations Commission.",
    id: "cons-2025-ol-q5-a", topicId: "cons-4-4", conceptId: "vertical-section-top-three-steps",
    section: "B", questionRef: "2025 OL Q5(a)",
    questionText: "To a scale of 1:5, draw a vertical section through the centre of the top three steps of the stairs and the landing. Show the steps, trimmer joist, and a portion of the landing. Show 600 mm length of the landing.",
    tariffModel: {"kind":"bestNofParts","notation":"7 x 5","answer":7,"ofParts":11,"perPart":5}, totalMarks: 35,
    rows: [
    { id: "cons-2025-ol-q5-a-r1", kind: "anyN", verbatim: "Specification – typical detail", marks: 35, contextNote: "Specification – typical detail", openList: true, group: {"claimMax":7,"perOption":5,"options":["String 250 mm x 50 mm","Tread 250 mm x 25 mm","Riser 170 mm x 20 mm","Joint between tread and riser","Nosing – 16 mm minimum","Vertical & horizontal wedge","Glue blocks 60 x 60 mm","Pitch line/ nosing line (max 42⁰)","Trimmer joist 225 mm x 75 mm","First floor joist 225 mm x 50 mm","Tongue & groove floor Note: Any alternative detailing which complies with current Building Regulations is acceptable"]} },
    ],
  } as SecCard,
];
