/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Topic-tag pipeline, final step — regenerate the committed aggregate data file
 * from every per-subject wave file.
 *
 * Source of truth: scripts/paper-trail/topic-tags/tags/<subject>.json — one
 * verified PaperTopicTags[] per subject (grouped by paper, each question tagged
 * with its curriculum subtopic id, adversarially verified). Add a subject by
 * dropping its wave file here and re-running this.
 *
 * Emits: data/paperTrail/topicTags.ts (PAPER_TOPIC_TAGS + TOPIC_LABELS). Labels
 * are pulled from curriculum.ts for only the subtopic ids actually used.
 *
 * Usage:  node scripts/paper-trail/topic-tags/build-tags.mjs
 */
import fs from 'fs';
import path from 'path';

const TAGS_DIR = 'scripts/paper-trail/topic-tags/tags';

// all subject wave files → one array
const papers = [];
for (const fn of fs.readdirSync(TAGS_DIR).filter(f => f.endsWith('.json')).sort()) {
  const arr = JSON.parse(fs.readFileSync(path.join(TAGS_DIR, fn), 'utf8'));
  papers.push(...arr);
}
papers.sort(
  (a, b) =>
    a.subjectId.localeCompare(b.subjectId) ||
    b.year - a.year ||
    a.level.localeCompare(b.level) ||
    a.paperKey.localeCompare(b.paperKey),
);

// used subtopic ids
const used = new Set();
let questionCount = 0;
for (const p of papers) for (const q of p.q) {
  used.add(q.primary);
  if (q.secondary) used.add(q.secondary);
  questionCount++;
}

// curriculum id -> name (all subjects)
const ct = fs.readFileSync('curriculum.ts', 'utf8');
const cs = ct.indexOf('CURRICULUM: CurriculumSubject[] =');
const ca = ct.indexOf('[', ct.indexOf('=', cs));
let cd = 0, ce = -1;
for (let i = ca; i < ct.length; i++) {
  if (ct[i] === '[') cd++;
  else if (ct[i] === ']') { cd--; if (!cd) { ce = i; break; } }
}
const CUR = JSON.parse(ct.slice(ca, ce + 1).replace(/,\s*([\]}])/g, '$1'));
const NAME = {};
for (const subj of CUR) for (const st of subj.strands) for (const sub of st.subtopics) NAME[sub.id] = sub.name;

const labels = {};
for (const id of [...used].sort()) labels[id] = NAME[id] || id;

const subjects = [...new Set(papers.map(p => p.subjectId))];
const out = `/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Paper Trail — committed per-question topic tags (Tier 2). GENERATED by
 * scripts/paper-trail/topic-tags/build-tags.mjs from the verified per-subject
 * wave files. DO NOT hand-edit — edit the wave file + regenerate.
 *
 * Coverage: ${subjects.join(', ')} — ${papers.length} papers, ${questionCount} questions.
 */

import { type PaperTopicTags } from '../../types/paperTrailTopics';

export const TOPIC_LABELS: Record<string, string> = ${JSON.stringify(labels, null, 2)};

export const PAPER_TOPIC_TAGS: PaperTopicTags[] = ${JSON.stringify(papers, null, 1)};
`;
fs.writeFileSync('data/paperTrail/topicTags.ts', out);
console.log(`wrote ${papers.length} papers, ${questionCount} questions, ${Object.keys(labels).length} topics (${subjects.join(', ')})`);
