/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/landing/hall-cover.mjs — do not edit by hand.
 *
 * What each hall paper's cover prints, lifted off the SEC PDF in the Paper
 * Trail corpus: the sitting line as printed, its length in minutes (end time
 * minus start time), the marks line as printed, and the paper's own
 * instructions — the cover's where it has them, otherwise the printed
 * "Instructions" / "Treoracha" block on the page given. Nothing here is typed.
 */

export interface HallCover {
  /** The StackPaper id in ../fx-c/papers.ts. */
  id: string;
  year: number;
  /** The SEC fileid the text was lifted from. */
  file: string;
  /** The day-and-time line as the cover prints it. */
  sitting: string;
  /** The sitting's length: end time minus start time, from that line. */
  minutes: number;
  /** The marks line as printed, where the cover prints one. */
  marks: string | null;
  /** The paper's printed instructions, one item per printed paragraph or bullet. */
  instructions: string[];
  /** The page the instructions were printed on: 1 is the cover. */
  instructionsPage: number;
}

export const HALL_COVERS: Record<string, HallCover> = {
  "physics": {
    id: "physics",
    year: 2023,
    file: "LC021ALP000EV.pdf",
    sitting: "WEDNESDAY, 21 JUNE – MORNING, 9:30 TO 12:30",
    minutes: 180,
    marks: null,
    instructions: [
      "Answer three questions from Section A and five questions from Section B.",
      "Relevant data are listed in the Formulae and Tables booklet, which is available from the Superintendent.",
    ],
    instructionsPage: 1,
  },
  "english": {
    id: "english",
    year: 2025,
    file: "LC002ALP100EV.pdf",
    sitting: "Wednesday, 4 June – Morning, 9.30 – 12.20",
    minutes: 170,
    marks: "Total Marks: 200",
    instructions: [
      "• This paper is divided into two sections, Section I COMPREHENDING and Section II COMPOSING.",
      "• The paper contains three texts on the general theme of PERSPECTIVES.",
      "• Candidates should familiarise themselves with each of the texts before beginning their answers.",
      "• Both sections of this paper (COMPREHENDING and COMPOSING) must be attempted.",
      "• Each section carries 100 marks.",
      "SECTION I – COMPREHENDING",
      "• Two Questions, A and B, follow each text.",
      "• Candidates must answer a Question A on one text and a Question B on a different text. Candidates must answer only one Question A and only one Question B.",
      "N.B. Candidates may NOT answer a Question A and a Question B on the same text.",
      "SECTION II – COMPOSING",
      "• Candidates must write on one of the compositions 1 – 7.",
    ],
    instructionsPage: 1,
  },
  "maths": {
    id: "maths",
    year: 2025,
    file: "LC003ALP100EV.pdf",
    sitting: "Friday 6 June Afternoon 2:00 - 4:30",
    minutes: 150,
    marks: "300 marks",
    instructions: [
      "There are two sections in this examination paper.",
      "Section A Concepts and Skills 150 marks 6 questions",
      "Section B Contexts and Applications 150 marks 4 questions",
      "Answer questions as follows:",
      "• any five questions from Section A – Concepts and Skills",
      "• any three questions from Section B – Contexts and Applications.",
      "Write your Examination Number in the box on the front cover.",
      "Write your answers in blue or black pen. You may use pencil in graphs and diagrams only.",
      "This examination booklet will be scanned and your work will be presented to an examiner on screen. Anything that you write outside of the answer areas may not be seen by the examiner.",
      "Write all answers into this booklet. There is space for extra work at the back of the booklet.",
      "If you need to use it, label any extra work clearly with the question number and part.",
      "The superintendent will give you a copy of the Formulae and Tables booklet. You must return it at the end of the examination. You are not allowed to bring your own copy into the examination.",
      "In general, diagrams are not to scale.",
      "You will lose marks if your solutions do not include relevant supporting work.",
      "You may lose marks if the appropriate units of measurement are not included, where relevant.",
      "You may lose marks if your answers are not given in simplest form, where relevant.",
    ],
    instructionsPage: 3,
  },
  "construction-studies": {
    id: "construction-studies",
    year: 2023,
    file: "LC029ALP000EV.pdf",
    sitting: "Friday, 16 June Afternoon, 2:00 - 5:00",
    minutes: 180,
    marks: "(300 marks)",
    instructions: [
      "(a) Answer any five questions.",
      "(b) All questions carry equal marks.",
      "(c) Answers must be written in ink.",
      "(d) Drawings and sketches are to be made in pencil.",
      "(e) Write the number of the question distinctly before each answer.",
      "(f) Neat freehand sketches to illustrate written descriptions should be made.",
      "(g) The name, sizes, dimensions and other necessary particulars of each material indicated must be noted on the drawings.",
    ],
    instructionsPage: 1,
  },
  "irish": {
    id: "irish",
    year: 2022,
    file: "LC001GLP000IV.pdf",
    sitting: "Dé Luain 13 Meitheamh Tráthnóna 2:00 – 3:50",
    minutes: 110,
    marks: "160 marc",
    instructions: [
      "Scríobh do Scrúduimhir agus Lá agus Mí do Bhreithe sna boscaí ar an gclúdach tosaigh.",
      "Scríobh do chuid freagraí ar gach cuid den scrúdú seo sna spásanna atá curtha ar fáil sa fhreagarleabhar seo.",
      "Scríobh do chuid freagraí le peann i ndúch gorm nó dubh. Ní ceadmhach peann luaidhe a úsáid.",
      "Déanfar an freagarleabhar seo a scanadh agus is ar scáileán a chuirfear do chuid oibre i láthair an scrúdaitheora. Mar sin is féidir nach bhfeicfidh an scrúdaitheoir aon rud a scríobhfaidh tú taobh amuigh de bhoscaí na bhfreagraí.",
      "Tá dhá chuid sa scrúdú seo.",
      "Cuid I An Chluastuiscint 60 marc",
      "Cuid II An Cheapadóireacht 100 marc",
    ],
    instructionsPage: 2,
  },
  "economics": {
    id: "economics",
    year: 2024,
    file: "LC034ALP000EV.pdf",
    sitting: "Friday 21 June Morning 9:30 - 12:00",
    minutes: 150,
    marks: "400 marks",
    instructions: [
      "There are two sections in this paper.",
      "This examination carries 400 marks in total.",
      "Section A: 100 marks",
      "Answer 8 out of 10 questions from this section.",
      "Questions 2, 3 and 4 contain an internal choice.",
      "Section B: 300 marks",
      "Answer 4 out of 6 questions.",
      "All questions in this section carry 75 marks",
      "Write your answers in blue or black pen.",
      "Write your answers in the spaces provided in this booklet. There is space for extra work at the end of the booklet. Label any such extra work clearly with the question number and part.",
      "This examination booklet will be scanned and your work will be presented to an examiner on screen. Anything that you write outside of the answer areas may not be seen by the examiner.",
      "The superintendent will give you a copy of the Formulae and Tables booklet, if required. You must return it at the end of the examination. You are not allowed to bring your own copy into the examination.",
      "Calculators may be used.",
    ],
    instructionsPage: 2,
  },
};
