/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/landing/tunnel-years.mjs — do not edit. One entry per
 * year directory in the Paper Trail corpus, with the PDFs it holds. The same
 * figures are recorded in public/assets/landing/tunnel/years.json.
 */

export interface TunnelYear { year: number; papers: number }
export const YEARS: readonly TunnelYear[] = [{"year":2010,"papers":248},{"year":2011,"papers":269},{"year":2012,"papers":268},{"year":2013,"papers":270},{"year":2014,"papers":267},{"year":2015,"papers":262},{"year":2016,"papers":259},{"year":2017,"papers":248},{"year":2018,"papers":267},{"year":2019,"papers":246},{"year":2020,"papers":150},{"year":2021,"papers":238},{"year":2022,"papers":319},{"year":2023,"papers":319},{"year":2024,"papers":313},{"year":2025,"papers":317},{"year":2026,"papers":313}];
export const TOTAL_PAPERS = 4573;
