import { AnimatePresence,motion,useReducedMotion } from 'framer-motion';
import { ArrowDown,ArrowRight,Check,RotateCcw } from 'lucide-react';
import React,{ useMemo,useState } from 'react';
import { useModuleDraft } from '../../hooks/useModuleDraft';
import { Button as KButton,Switch } from '../approved-ui-runtime';
import { YetSequence } from './YetDirections';
export const equationItems = [
 ['E','Expectancy','Your belief you can succeed. Low confidence = high procrastination.'],
 ['V','Value','How rewarding or meaningful the task feels.'],
 ['I','Impulsiveness','Your susceptibility to distractions.'],
 ['D','Delay','How far away the deadline is. A task that is boring, feels impossible, is easily interrupted, and has a distant deadline is a recipe for maximum procrastination.'],
];
const yetItems = [['1','Identify the Block',"Name the specific thing you’re struggling with right now."],['2','Add “Yet”','Turn your “I can’t” into “I can’t… yet.” One word changes the whole meaning.'],['3','Bridge to Action','Finish the sentence with “…so I will” and a specific, concrete next step.']];
function LeverSketch({letter}: {letter:string}) {
 return <svg className="bf-lever-sketch" viewBox="0 0 72 42" aria-hidden="true">
  {letter==='E'? [0,1,2,3].map(i=><rect key={i} x={6+i*16} y={32-i*8} width="9" height={8+i*8} rx="2" fill={i===3?'var(--module-orange)':'none'} stroke={i===3?'var(--module-orange)':'var(--module-ink)'}/>):letter==='V'?<><circle cx="36" cy="21" r="18" fill="none" stroke="var(--module-ink)"/><circle cx="36" cy="21" r="10" fill="none" stroke="var(--module-ink)"/><circle cx="36" cy="21" r="4" fill="var(--module-orange)"/></>:letter==='I'?<><path d="M4 21h64" stroke="var(--module-line)" strokeDasharray="3 4"/><circle cx="17" cy="21" r="10" fill="var(--module-orange)"/>{[38,58].map(x=><circle key={x} cx={x} cy="21" r="5" fill="var(--module-surface)" stroke="var(--module-ink)"/>)}</>:<><path d="M5 24h62M5 17v14M67 17v14" stroke="var(--module-ink)"/>{[20,36,52].map(x=><path key={x} d={`M${x} 21v6`} stroke="var(--module-line)"/>)}<circle cx="20" cy="24" r="5" fill="var(--module-orange)"/></>}
 </svg>;
}
export function InstructionList({kind='equation'}:{kind?:string}) {
 if(kind!=='equation')return <YetSequence items={yetItems}/>;
 return <ol className="bf-instructions bf-concept-cards">{equationItems.map(([n,title,desc])=><li key={n}><span className="bf-index">{n}</span><div className="bf-instruction-copy"><h4>{title}</h4><p>{desc}</p></div><LeverSketch letter={n}/></li>)}</ol>;
}
export function ExerciseHeading({eyebrow,title,children}:any){return <header className="bf-heading"><p className="bf-eyebrow">{eyebrow||'Try the idea'}</p><h3>{title}</h3><p>{children}</p></header>;}
export function BrandedEquation(){
 const [vars,setVars]=useState({E:50,V:50,I:50,D:50});
 const pct=Math.min(100,Math.round(((vars.E*vars.V)/(1+vars.I*vars.D/100))/((100*100)/(1+1*1/100))*100));
 const level=pct>=65?'High':pct>=35?'Medium':'Low';
 const issues=[];if(vars.E<=30)issues.push('you don’t believe you can succeed');if(vars.V<=30)issues.push('the task feels boring or meaningless');if(vars.I>=70)issues.push('you’re highly susceptible to distractions');if(vars.D>=70)issues.push('the deadline feels far away');
 const diagnosis=issues.length?`Your motivation is ${level.toLowerCase()} because ${issues.join(' and ')}.`:level==='High'?'All four levers are working in your favour. This is a task you’ll likely start without much resistance.':'No single factor is critical, but the overall balance could be stronger. Try boosting your belief or the task’s value.';
 return <section className="bf-exercise bf-equation"><ExerciseHeading title="The Procrastination Equation">Adjust the four levers to see what drives — or kills — your motivation.</ExerciseHeading><div className="bf-equation-result"><div className="bf-gauge"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43" fill="none" stroke="var(--module-line)" strokeWidth="5"/><motion.circle cx="50" cy="50" r="43" fill="none" stroke="var(--module-orange)" strokeWidth="5" strokeLinecap="round" animate={{strokeDasharray:`${pct*2.702} 270.2`}} transform="rotate(-90 50 50)"/></svg><strong>{pct}<small>%</small></strong></div><div><p className="bf-eyebrow">Motivation · {level}</p><p><strong>E and V</strong> boost motivation.<br/><strong>I and D</strong> drain it.</p></div></div><div className="bf-levers">{equationItems.map(([key,name])=><div className="bf-lever" key={key}><div className="bf-lever-top"><span className="bf-letter">{key}</span><output htmlFor={'lever-'+key}>{vars[key as keyof typeof vars]}<small>/100</small></output></div><label htmlFor={'lever-'+key}>{name}</label><p>{key==='E'?'Belief you can succeed':key==='V'?'How rewarding it feels':key==='I'?'Distraction susceptibility':'Distance to deadline'}</p><div className="bf-lever-meter" aria-hidden="true"><div className="bf-meter-track"><motion.div initial={false} animate={{height:`${vars[key as keyof typeof vars]}%`}} transition={{type:'spring',stiffness:210,damping:25}}/></div><span>{key==='E'||key==='V'?'↑':'↓'}</span></div><input id={'lever-'+key} type="range" min="1" max="100" value={vars[key as keyof typeof vars]} aria-valuenow={vars[key as keyof typeof vars]} onChange={e=>setVars(v=>({...v,[key]:Number(e.target.value)}))} aria-label={name} style={{'--range-fill':`${vars[key as keyof typeof vars]}%`} as React.CSSProperties}/><span className="bf-direction">{key==='E'||key==='V'?'↑ Increase':'↓ Decrease'}</span></div>)}</div><div className="bf-diagnosis" role="status"><span className="bf-eyebrow">Diagnosis</span><p>{diagnosis}</p></div></section>;
}
export function BrandedCircuitBreaker(){
 const [text,setText]=useState(''),lower=text.toLowerCase();
 const qualities=[{label:'Self-Forgiveness',words:['forgive','okay',"it's fine","it's ok","that's ok",'human','everyone','normal','mistake']},{label:'Forward Action',words:['i will','next time','tomorrow','going to','start','try','plan','can']},{label:'Self-Compassion',words:['kind','gentle','breathe','calm','deserve']}].map(q=>({...q,detected:q.words.some(w=>lower.includes(w))}));
 return <section className="bf-exercise" data-success={qualities.every(q=>q.detected)||undefined}><ExerciseHeading title="The Circuit Breaker">Rewrite this self-critical thought into something kinder and more action-focused.</ExerciseHeading><div className="bf-thought"><p className="bf-eyebrow">Self-critical thought</p><blockquote>I’m so useless, I wasted the whole day.</blockquote></div><div className="bf-connector"><ArrowDown size={18}/><span>Rewrite it</span></div><div className="bf-rewrite"><label className="bf-eyebrow" htmlFor="rewrite">Your rewrite</label><textarea id="rewrite" value={text} onChange={e=>setText(e.target.value)} placeholder="Rewrite this into something kinder and more action-focused…"/><p className="bf-eyebrow">Qualities detected in your rewrite</p><div className="bf-qualities" role="status">{qualities.map(q=><span key={q.label} className={q.detected?'detected':''}>{q.detected?<Check size={14}/>:<span className="bf-empty-check"/>}{q.label}</span>)}</div>{qualities.every(q=>q.detected)&&<p className="bf-complete" data-success="true"><Check size={16}/>You’ve broken the circuit. A kinder thought, and a next step.</p>}</div></section>;
}
const plans=[['I open Instagram during study time','I will close the app and do one practice question'],['I feel overwhelmed by a topic','I will break it into 3 smaller parts and tackle just the first one'],["I haven’t started by 4pm",'I will open my textbook to page 1 and read for 2 minutes'],['I finish a Pomodoro','I will stand up, stretch, and drink some water']];
export function BrandedAutopilot(){
 const [ifText,setIfText]=useModuleDraft('procrastination-protocol','if-text',''),[thenText,setThenText]=useModuleDraft('procrastination-protocol','then-text',''),[submitted,setSubmitted]=useState(false),[revision,setRevision]=useState(0);const reduced=useReducedMotion();
 const change=(setter:any,value:string)=>{setter(value);setSubmitted(false);};
 return <section className="bf-exercise" data-success={submitted?String(revision):undefined}><ExerciseHeading title="The “If-Then” Autopilot">Pre-load a decision to bypass willpower. Fill in both fields or pick a template below.</ExerciseHeading><div className="bf-templates">{plans.map(([trigger,action])=><KButton variant="outline" key={trigger} onClick={()=>{setIfText(trigger);setThenText(action);setSubmitted(false);}}>IF {trigger}</KButton>)}</div><div className="bf-plan-fields"><label>IF <span>(trigger)</span><input type="text" value={ifText} onChange={e=>change(setIfText,e.target.value)} placeholder="e.g. I open Instagram during study time"/></label><label>THEN <span>(action)</span><input type="text" value={thenText} onChange={e=>change(setThenText,e.target.value)} placeholder="e.g. I will close the app and do one practice question"/></label></div><KButton className="bf-primary" disabled={!ifText.trim()||!thenText.trim()} onClick={()=>{setSubmitted(true);setRevision(r=>r+1);}}>Lock In Plan<ArrowRight size={16}/></KButton><AnimatePresence>{submitted&&<motion.div key="saved-plan" className="bf-plan-output" role="status" data-success="true" initial={reduced?false:{height:0,opacity:0,y:12}} animate={{height:'auto',opacity:1,y:0}} exit={{opacity:0,height:0}} transition={{type:'spring',stiffness:230,damping:26}}><p className="bf-eyebrow"><motion.span key={revision} className="bf-lock-check" initial={reduced?false:{scale:.4,rotate:-25}} animate={{scale:1,rotate:0}} transition={{delay:.15,type:'spring',stiffness:280,damping:15}}><Check size={16}/></motion.span>Your autopilot plan</p><div className="bf-plan-sentence"><p><span>IF</span><span>{ifText}</span></p><p><span>THEN</span><span>{thenText}</span></p></div></motion.div>}</AnimatePresence></section>;
}
export function BrandedBridge({scenarios}:any){
 const [index,setIndex]=useState(0),[placed,setPlaced]=useState<string[]>([]),[feedback,setFeedback]=useState(''),[weak,setWeak]=useState('');const scenario=scenarios[index],reduced=useReducedMotion();
 const options=useMemo(()=>{const actions=[...scenario.strong,...scenario.weak];for(let i=actions.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[actions[i],actions[j]]=[actions[j],actions[i]];}return actions;},[index]);
 return <section className="bf-exercise" data-success={placed.length===3||undefined}><ExerciseHeading eyebrow="Growth mindset activity" title="Bridge Builder">Build a bridge from “Yet” to your goal by choosing specific, concrete actions.</ExerciseHeading><div className="bf-bridge-meta"><p className="bf-eyebrow">Bridge strength</p><output>{placed.length} / 3 planks</output></div><div className="bf-bridge-scene"><div className="bf-bridge-end bf-bridge-start"><span className="bf-eyebrow">Yet</span><p>{scenario.yet}</p></div><div className="bf-bridge-gap"><svg viewBox="0 0 240 120" preserveAspectRatio="none" aria-hidden="true"><path d="M0 48Q120 92 240 48M0 78Q120 115 240 78" fill="none" stroke="var(--module-line)" strokeWidth="1.5"/>{[26,74,120,166,214].map(x=><path key={x} d={`M${x} ${48+22*Math.sin(x/240*Math.PI)}v30`} stroke="var(--module-line)"/>)}</svg><div className="bf-bridge-deck">{[0,1,2].map(i=><motion.div key={i} className={`bf-plank ${i<placed.length?'placed':''}`} animate={i<placed.length?{y:0,rotate:0,opacity:1}:{y:0,rotate:0,opacity:.7}} initial={false} aria-label={`Plank ${i+1}${i<placed.length?': placed':': empty'}`}><AnimatePresence>{i<placed.length?<motion.span key="placed" initial={reduced?false:{y:-22,rotate:-8,scale:.75}} animate={{y:0,rotate:0,scale:1}} transition={{type:'spring',stiffness:210,damping:14}}>Plank {i+1}</motion.span>:<span>{i+1}</span>}</AnimatePresence></motion.div>)}</div></div><div className="bf-bridge-end bf-bridge-goal"><span className="bf-eyebrow">Goal</span><p>{scenario.goal}</p></div></div>{feedback&&<motion.p key={weak} className="bf-feedback" role="status" aria-invalid="true" animate={reduced?{}:{x:[0,-4,4,-3,0]}}>{feedback}</motion.p>}{placed.length===3?<motion.div className="bf-diagnosis" role="status" data-success="true" initial={{opacity:0}} animate={{opacity:1}}><p className="bf-eyebrow">Bridge complete</p><p>You turned “yet” into a concrete plan.</p></motion.div>:<><p className="bf-eyebrow">Choose an action to place on the bridge</p><div className="bf-bridge-options">{options.map(action=><KButton variant="push" key={action} disabled={placed.includes(action)} aria-invalid={weak===action&&feedback?true:undefined} aria-pressed={placed.includes(action)} onClick={()=>{if(scenario.strong.includes(action)){setPlaced(p=>[...p,action]);setFeedback('');}else{setWeak(action);setFeedback(['Too vague — what specifically will you do?',"That’s wishful thinking — name a concrete step.",'Not a strategy — try something measurable.'][scenario.weak.indexOf(action)]);}}}>{placed.includes(action)&&<Check size={16}/>}<span>{action}</span></KButton>)}</div></>}<KButton variant="ghost" className="bf-text-button" onClick={()=>{setIndex((index+1)%scenarios.length);setPlaced([]);setFeedback('');}}><RotateCcw size={14}/>Try another scenario</KButton></section>;
}
const myths=[['Hope is just wishful thinking.','FALSE. Hope is an active skill — it combines the drive to start (willpower) with a plan to get there (waypower).'],["You’re either born hopeful or you’re not.",'FALSE. Hope is something you can practise and get better at. Your brain physically rewires itself the more you use it.'],['Hope is the same as optimism.',"FALSE. Optimism says ‘things will work out.’ Hope says ‘I can MAKE things work out — and here’s my plan.’"]];
export function BrandedMythCard({front,back}:any){const[flipped,setFlipped]=useState(false),reduced=useReducedMotion();return <button className="bf-flip-card" aria-pressed={flipped} aria-label={front} data-sound={flipped?'close':'open'} onClick={()=>setFlipped(!flipped)}><motion.div className="bf-flip-inner" animate={{rotateY:flipped?180:0}} transition={{duration:reduced?0:.55,ease:[.16,1,.3,1]}}><div className="bf-flip-front" aria-hidden={flipped}><span className="bf-eyebrow">The myth</span><p>{front}</p><span className="bf-flip-hint">Tap to turn<RotateCcw size={13}/></span></div><div className="bf-flip-back" aria-hidden={!flipped}><span className="bf-eyebrow"><span className="bf-fact-mark"><Check size={14}/></span>The fact</span><p>{back.replace(/^FALSE\.\s*/,'')}</p><span className="bf-flip-hint">Turn back<RotateCcw size={13}/></span></div></motion.div></button>;}
export function BrandedHopeDiagnostic(){return <section className="bf-exercise"><ExerciseHeading title="Hope Circuit Diagnostic">Let’s bust some common myths about where hope comes from.</ExerciseHeading><div className="bf-flip-grid">{myths.map(([front,back])=><BrandedMythCard key={front} front={front} back={back}/>)}</div></section>;}
export function BrandedPracticeSorter(){const activities=[{name:'Highlighting notes',type:'naive'},{name:'Doing a past paper (timed)',type:'deep'},{name:'Watching a video',type:'naive'},{name:'Explaining a concept out loud',type:'deep'}];const[choices,setChoices]=useState<Record<string,string>>({});return <section className="bf-exercise"><ExerciseHeading title="Deep vs. Naive Practice">Which of these activities trigger myelin growth?</ExerciseHeading><div className="bf-practice-list">{activities.map(act=><div key={act.name}><span>{act.name}</span><div>{['naive','deep'].map(type=><KButton variant="push" key={type} className={choices[act.name]===type?(type===act.type?'is-correct':'is-incorrect'):''} aria-label={`${type==='deep'?'Deep':'Naive'} practice: ${act.name}`} aria-pressed={choices[act.name]===type} data-success={choices[act.name]===type&&type===act.type||undefined} aria-invalid={choices[act.name]===type&&type!==act.type||undefined} onClick={()=>setChoices(c=>({...c,[act.name]:type}))}>{type==='deep'?'Deep':'Naive'}{choices[act.name]===type&&(type===act.type?<Check size={14}/>:<span>×</span>)}</KButton>)}</div></div>)}</div></section>;}
export function BrandedThoughtReframer(){
 const[thought,setThought]=useState(''),[states,setStates]=useState([false,false,false]);const count=states.filter(Boolean).length;
 const items=[['Personal → Specific',"It’s about me","It’s about this situation"],['Pervasive → Limited','It affects everything',"It’s just this one area"],['Permanent → Temporary','It will always be this way',"It’s temporary"]];
 const reframe=count===0?thought:count===3?`My approach to “${thought.trim()}” isn’t working yet — but it’s one specific area I can improve with the right strategy.`:`“${thought.trim()}” — but ${[states[0]?"it’s about the situation, not me":'',states[1]?"it’s only this one area":'',states[2]?"it’s temporary":''].filter(Boolean).join(', and ')}.`;
 return <section className="bf-exercise"><ExerciseHeading title="Thought Reframer">Type a negative thought about school or study, then flip the 3 Ps to rewrite the script.</ExerciseHeading><label className="bf-eyebrow" htmlFor="reframe-thought">Your thought</label><input id="reframe-thought" className="bf-thought-input" value={thought} onChange={e=>setThought(e.target.value)} placeholder="e.g. I’m terrible at maths"/><p className="bf-reframe-note">This is about school and study. If something feels bigger than that, talk to someone you trust.</p><div className="bf-reframe-rows">{items.map(([title,left,right],i)=><div key={title}><div className="bf-reframe-row-heading"><span className="bf-index">{i+1}</span><h4>{title}</h4><span className="bf-reframe-state">{states[i]?'Reframed':'Original'}</span></div><div className="bf-reframe-switch"><span className={!states[i]?'current':''}>{left}</span><Switch checked={states[i]} onCheckedChange={(checked:boolean)=>setStates(v=>v.map((state,j)=>j===i?checked:state))} aria-label={`Reframe ${title}`}/><span className={states[i]?'current':''}>{right}</span></div></div>)}</div><div className="bf-resilience"><div><span className="bf-eyebrow">Resilience score</span><output>{Math.round(count/3*100)}%</output></div><div className="bf-resilience-track"><motion.div initial={false} animate={{width:`${count/3*100}%`}}/></div></div>{thought.trim()&&<motion.div className="bf-reframed-thought" role="status" key={count} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}><p className="bf-eyebrow">{count?'Your reframe':'Start with one switch'}</p><p>{reframe}</p></motion.div>}</section>;
}
