/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Paper Trail — shared types for the SEC past-papers library.
 *
 * The data itself lives in paperTrailData.ts (generated by
 * scripts/paper-trail/build-index.py from the harvested SEC archive manifest);
 * these types are the contract between the generator and the tool UI.
 */

export type PaperLevel = 'higher' | 'ordinary' | 'foundation' | 'common';
export type PaperLang = 'ev' | 'iv';
export type PaperCycle = 'lc' | 'jc' | 'lca';

/** One PDF in Firebase Storage: fileid (basename) + size in bytes. */
export interface PaperDoc {
  f: string;
  b: number;
}

/** One sittable paper within a subject-year-level-language slice. */
export interface PaperItem {
  /** Human label from the SEC archive, e.g. "Paper One / Higher Level (EV)". */
  label: string;
  doc: PaperDoc;
  /** The marking scheme covering this paper (SEC schemes usually cover the
   *  whole level-year in one document, so siblings may share one scheme). */
  scheme?: PaperDoc;
  /** Modified version for vision-impaired candidates. */
  modified?: boolean;
  /** Present (=1) when a verified per-question answer map (PaperAnswerMap) has
   *  shipped for this paper — the viewer shows the "Answers" toggle. Eager
   *  presence flag only; the map itself is a lazily-fetched Storage sidecar.
   *  Set by build-index.py ONLY for QA-passed grammar profiles. */
  answers?: 1;
}

/** One segment of a question's marking-scheme region: a scheme page (1-based,
 *  pdf.js getPage convention) and an optional clip rect as fractions [x0,y0,x1,y1]
 *  of that page. Absent rect (page-jump mode) means "just jump here". */
export interface PaperAnswerSeg {
  p: number;
  r?: [number, number, number, number];
}

/** One question's anchor: where it sits on the paper, and where its answer lives
 *  in the marking scheme. */
export interface PaperAnswerQuestion {
  /** Question number as printed, e.g. "1" (string: some subjects use "1a").
   *  Always a sequential integer for ordering + uniqueness; the human-facing
   *  label (when it differs, e.g. section-restarting language papers) is `label`. */
  n: string;
  /** Optional display label shown in the reveal header instead of "Question {n}",
   *  for papers whose questions restart per section (e.g. "Text II · Q1"). */
  label?: string;
  /** Optional physical sequence within the paper. `n` is a stable card identity,
   *  so a later repair that recovers previously-colliding section-restart
   *  questions must not renumber shipped cards. In that exceptional case this
   *  records the real print order while `n` remains stable. */
  printOrder?: number;
  /** Paper page the question header is on (1-based). */
  pP: number;
  /** Question's vertical band on that paper page, fractions [start, end]. */
  pY: [number, number];
  /** Optional audited paper crop for a frozen legacy card whose original
   *  anchor omits shared instructions or table headings. Like `schemeRegion`,
   *  this improves display without changing the shipped pP/pY identity. */
  paperRegion?: PaperAnswerSeg[];
  /** Marking-scheme region: ordered page crops (mode 'crop') or a single
   *  jump target (mode 'pagejump'). */
  region: PaperAnswerSeg[];
  /** Optional corrected display crop for a frozen legacy card. `region` is
   *  part of the shipped card identity and must remain byte-for-byte stable;
   *  this additive field lets a later audit remove collision spillover or
   *  point the UI at the card's actual answer without mutating that identity. */
  schemeRegion?: PaperAnswerSeg[];
  mode: 'crop' | 'pagejump';
  /** Confidence 0..1 (1 = clean crop; lower = degraded to page-jump). */
  conf: number;
  /** Optional explicit crop-END for the paper-side region (section-restart
   *  "island" papers): the page + vertical fraction where this question's crop
   *  must stop, INDEPENDENT of the next anchor. Set only when the next printed
   *  anchor is not the natural end — e.g. a reading section's last question,
   *  whose crop must end at the following passage/section rather than bleed
   *  into it. When absent, the region runs to the next anchor as before. */
  endP?: number;
  endY?: number;
}

/** Per-paper answer map — the lazily-fetched Storage sidecar. Coordinates ONLY:
 *  no answer text, no image bytes. Generated by scripts/paper-trail/anchor-map.py;
 *  the viewer renders crops of the real scheme PDF from these coordinates. */
export interface PaperAnswerMap {
  /** Schema version. */
  v: number;
  paperFileid: string;
  /** The marking-scheme PDF the regions index into. */
  schemeFileid: string;
  /** SEC component code of the paper (e.g. "100" = Paper 1). */
  component: string;
  /** The paper's scheme section, 1-based half-open [lo, hi). Every region page
   *  falls inside this band (the Paper 1 / Paper 2 shared-scheme guard). */
  band: [number, number];
  copyright: string;
  /** Hosted sidecars may carry paper anchors only. They deliberately make no
   *  marking-scheme claim, but can be merged additively with a verified answer
   *  map at runtime so long multi-page paper questions keep their full extent. */
  paperOnly?: 1;
  /** Audited per-map override for a booklet whose real printed questions span
   *  more than the conservative three-page default. Kept map-level so an
   *  unverified distant anchor cannot silently relax another paper. */
  maxCropPages?: number;
  q: PaperAnswerQuestion[];
}

export interface PaperEntry {
  year: number;
  level: PaperLevel;
  lang: PaperLang;
  papers: PaperItem[];
  /** Context worth a line in the UI, e.g. "November 2020 deferred sitting". */
  note?: string;
}

export interface PaperTrailSubject {
  id: string;
  name: string;
  cycle: PaperCycle;
  levels: PaperLevel[];
  /** Link to curriculum.ts subject id where one exists. */
  curriculumId?: string;
  /** Profile-picker names that refer to this subject ("Ag Science", "DCG"…). */
  aliases?: string[];
}

/** An explained hole — rendered honestly, never as a dead link. */
export interface PaperTrailGap {
  subjectId: string;
  year: number;
  reason: string;
}

/** A recently opened document, persisted per student.
 *  Identity is the composite `key` — SEC fileids are NOT unique across years
 *  (the same fileid recurs every year), so the bare fileid cannot be the key. */
export interface RecentPaper {
  /** `${subjectId}|${year}|${level}|${lang}|${doc fileid}` */
  key: string;
  subjectId: string;
  year: number;
  level: PaperLevel;
  lang: PaperLang;
  label: string;
  /** Which side was open last. */
  kind: 'paper' | 'scheme';
  /** Storage fileids for relaunch. */
  doc: PaperDoc;
  scheme?: PaperDoc;
  /** 1-based last page viewed, per side. */
  paperPage: number;
  schemePage: number;
  /** epoch ms */
  at: number;
}

export const recentKey = (
  subjectId: string,
  year: number,
  level: PaperLevel,
  lang: PaperLang,
  fileid: string,
) => `${subjectId}|${year}|${level}|${lang}|${fileid}`;

export interface PaperTrailState {
  recents: RecentPaper[];
  lastLevel?: PaperLevel;
  lastLang?: PaperLang;
}
