/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Paper Trail — shared types for the SEC past-papers library.
 *
 * The data itself lives in paperTrailData.ts (generated by
 * scripts/paper-trail/build-index.py from the harvested SEC archive manifest);
 * these types are the contract between the generator and the tool UI.
 */

export type PaperLevel = 'higher' | 'ordinary' | 'foundation' | 'common';
export type PaperLang = 'ev' | 'iv';
export type PaperCycle = 'lc' | 'jc' | 'lca';

/** One PDF in Firebase Storage: fileid (basename) + size in bytes. */
export interface PaperDoc {
  f: string;
  b: number;
}

/** One sittable paper within a subject-year-level-language slice. */
export interface PaperItem {
  /** Human label from the SEC archive, e.g. "Paper One / Higher Level (EV)". */
  label: string;
  doc: PaperDoc;
  /** The marking scheme covering this paper (SEC schemes usually cover the
   *  whole level-year in one document, so siblings may share one scheme). */
  scheme?: PaperDoc;
  /** Modified version for vision-impaired candidates. */
  modified?: boolean;
}

export interface PaperEntry {
  year: number;
  level: PaperLevel;
  lang: PaperLang;
  papers: PaperItem[];
  /** Context worth a line in the UI, e.g. "November 2020 deferred sitting". */
  note?: string;
}

export interface PaperTrailSubject {
  id: string;
  name: string;
  cycle: PaperCycle;
  levels: PaperLevel[];
  /** Link to curriculum.ts subject id where one exists. */
  curriculumId?: string;
  /** Profile-picker names that refer to this subject ("Ag Science", "DCG"…). */
  aliases?: string[];
}

/** An explained hole — rendered honestly, never as a dead link. */
export interface PaperTrailGap {
  subjectId: string;
  year: number;
  reason: string;
}

/** A recently opened document, persisted per student.
 *  Identity is the composite `key` — SEC fileids are NOT unique across years
 *  (the same fileid recurs every year), so the bare fileid cannot be the key. */
export interface RecentPaper {
  /** `${subjectId}|${year}|${level}|${lang}|${doc fileid}` */
  key: string;
  subjectId: string;
  year: number;
  level: PaperLevel;
  lang: PaperLang;
  label: string;
  /** Which side was open last. */
  kind: 'paper' | 'scheme';
  /** Storage fileids for relaunch. */
  doc: PaperDoc;
  scheme?: PaperDoc;
  /** 1-based last page viewed, per side. */
  paperPage: number;
  schemePage: number;
  /** epoch ms */
  at: number;
}

export const recentKey = (
  subjectId: string,
  year: number,
  level: PaperLevel,
  lang: PaperLang,
  fileid: string,
) => `${subjectId}|${year}|${level}|${lang}|${fileid}`;

export interface PaperTrailState {
  recents: RecentPaper[];
  lastLevel?: PaperLevel;
  lastLang?: PaperLang;
}
