/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Mathematics cards, Higher Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/maths/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the strands of the Mathematics syllabus examined from 2015.
 * Higher and Ordinary sit two papers, and a citation names which.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "maths",
  specVersion: "lc-maths-2015",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q1-b", topicId: "maths-3-2", conceptId: "multiply-out-simplify-leaving-certificate-2025",
    section: "B", questionRef: "2025 HL Paper 1 Q1(b)",
    questionText: "Multiply out and simplify: (4x−10√x ) (2x+ 5√x−7 )",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 4, 6, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p1-q1-b-r1", kind: "anyN", verbatim: "Work of merit, for example some correct work in distributing the terms Correct answers without supporting work", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 4, two parts for 6, three parts for 10. Marked in order: Low Partial Credit; High Partial Credit.", openList: true, group: {"claimMax":2,"perOption":4,"options":["Work of merit, for example some correct work in distributing the terms Correct answers without supporting work","6 of the 9 terms in the last two lines correct (ignoring excess terms) 8y⁴ −78y² + 70y (Method 2)"],"perOptionSteps":[4,6]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q1-c", topicId: "maths-4-2", conceptId: "factor-12x-information-three-solutions-equation",
    section: "B", questionRef: "2025 HL Paper 1 Q1(c)",
    questionText: "(2x+ 3) is a factor of 4x³ −12x² −7x+ 30. Use this information to find the three solutions to the following equation in x: 4x³ −12x² −7x+ 30 = 0 x= _____________ , x= _____________ , and x= _____________",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 4, 6, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p1-q1-c-r1", kind: "anyN", verbatim: "Sets up long division / array/product", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 4, three parts for 6, four parts for 10. Marked in order: Step 1; Step 2; Step 3; Step 4; Step 5.", openList: true, group: {"claimMax":4,"perOption":2,"options":["Sets up long division / array/product","Finds first term in quotient (2x² or 10)","Finds 2x² −9x+ 10","Factorises 2x² −9x+ 10 / fully","Finds 3 values of x"],"perOptionSteps":[2,2,2,4]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q2-a", topicId: "maths-2-3", conceptId: "function-defined-sin",
    section: "B", questionRef: "2025 HL Paper 1 Q2(a)",
    questionText: "A function is defined for x∈ℝ by: f(x) = 6 + x2 + sin 4x",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 3, 5)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 5,
    rows: [
    { id: "maths-2025-hl-p1-q2-a-r1", kind: "anyN", verbatim: "Finds slope of tangent when x= 0", marks: 5, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 3, three parts for 5. Marked in order: Step 1; Step 2; Step 3; Step 4.", openList: true, group: {"claimMax":3,"perOption":2,"options":["Finds slope of tangent when x= 0","Finds y-value when x= 0","Substitutes into equation of line","Solution in required form"],"perOptionSteps":[2,1,2]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q4-a", topicId: "maths-5-2", conceptId: "function-defined-expression-you-not-need",
    section: "B", questionRef: "2025 HL Paper 1 Q4(a)",
    questionText: "The function f(x) is defined for x∈ℝ by: f(x) = (3x⁵ −4)²⁸ Find an expression for f′(x). You do not need to simplify your answer. (b) The function g(x) is defined for x∈ℝ, x≠3∙5, by: g(x) = 3 2x−7 By finding g′(x), show that this function has no local maximum or minimum points",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 3, 4, 5)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 5,
    rows: [
    { id: "maths-2025-hl-p1-q4-a-r1", kind: "anyN", verbatim: "Indicates multiplication of top", marks: 5, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 3, three parts for 4, four parts for 5. Marked in order: Step 1; Step 2; Step 3; Step 4; Step 1; Step 2; Step 3; Step 4; Step 1; Step 2; Step 3; Step 4.", openList: true, group: {"claimMax":4,"perOption":2,"options":["Indicates multiplication of top","Expands top line","Expands bottom line","Writes in the form a+ b","2 + 3i= 4a+ 4b−5a−5bi²","Sets Re = Re and Im = Im","Solves for 1 variable (a or b)","Solves for 2nd variable","Writes 2 + 3i in polar form","Writes 4 −5i in polar form","Evaluates","Writes in the form a+ b"],"perOptionSteps":[2,1,1,1]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q4-b", topicId: "maths-5-2", conceptId: "function-defined-finding-function-has-local",
    section: "B", questionRef: "2025 HL Paper 1 Q4(b)",
    questionText: "The function g(x) is defined for x∈ℝ, x≠3∙5, by: g(x) = 3 2x−7 By finding g′(x), show that this function has no local maximum or minimum points",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 4, 6, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p1-q4-b-r1", kind: "anyN", verbatim: "1 root evaluated using De Moivre’s", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 4, two parts for 6, three parts for 10. Marked in order: Step 3; Step 4.", openList: true, group: {"claimMax":2,"perOption":4,"options":["1 root evaluated using De Moivre’s","2nd root found"],"perOptionSteps":[4,6]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q5-a", topicId: "maths-3-1", conceptId: "function-defined-20x-write-form-constants",
    section: "B", questionRef: "2025 HL Paper 1 Q5(a)",
    questionText: "The function g(x) is defined for x∈ℝ by: g(x) = 5x² + 20x−12 Write g(x) in the following form, where a, h, k∈ℤ are constants: g(x) = a(x+ h)² + k (b) p is a positive constant",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 4, 6, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p1-q5-a-r1", kind: "anyN", verbatim: "Work of merit, for example, factors out 5 from two terms, or squares out (x+ h)² Some correct differentiation Finds a", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 4, three parts for 6, four parts for 10. Marked in order: Low Partial Credit; Mid Partial Credit; High Partial Credit.", openList: true, group: {"claimMax":3,"perOption":2,"options":["Work of merit, for example, factors out 5 from two terms, or squares out (x+ h)² Some correct differentiation Finds a","Find h or k Finds the turning point","Finds or identifies any two of a, h or k Finds the turning point and identifies a"],"perOptionSteps":[2,2,6]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q5-b", topicId: "maths-3-2", conceptId: "positive-constant-laws-logs-write-expression",
    section: "B", questionRef: "2025 HL Paper 1 Q5(b)",
    questionText: "p is a positive constant. Use the laws of logs to write the expression: ln[ (e³ p)⁵ ] in the form c+ dln p, where c, d∈ℤ are constants",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 4, 6, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p1-q5-b-r1", kind: "anyN", verbatim: "Deals with power of 5", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 4, two parts for 6, three parts for 10. Marked in order: Step 1; Step 2; Step 3; Step 1; Step 2; Step 3; Step 1; Step 2; Step 3; Step 1; Step 2; Step 3.", openList: true, group: {"claimMax":3,"perOption":4,"options":["Deals with power of 5","Splits up e³p","Finishes","Splits up e¹⁵p⁵","Deals with powers","Finishes","States x= 0","Finds y when x= 0","Substitutes (0, −7) into the curve","Writes y in terms of x","Substitutes the expression for y into","Substitutes x= 0"],"perOptionSteps":[4,2,4]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q6-a", topicId: "maths-4-1", conceptId: "write-down-descending-powers-first-terms",
    section: "B", questionRef: "2025 HL Paper 1 Q6(a)",
    questionText: "Write down, in descending powers of p, the first 3 terms in the binomial expansion of: (2p+ 3)⁷ Give each term in its simplest form. For example, the first term should be of the form a p⁷ , where a is a constant",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 4, 6, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p1-q6-a-r1", kind: "anyN", verbatim: "Work of merit, for example, one binomial coefficient correct, or writes (2p)⁷, Writes (2p+ 3)(2p+ 3) or similar", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 4, three parts for 6, four parts for 10. Marked in order: Low Partial Credit; Mid Partial Credit; High Partial Credit.", openList: true, group: {"claimMax":3,"perOption":2,"options":["Work of merit, for example, one binomial coefficient correct, or writes (2p)⁷, Writes (2p+ 3)(2p+ 3) or similar","1 of the first three relevant terms found correctly Part of 2 relevant terms correct (binomial coefficient, (2p)^k, or 3^k)","(2p+ 3)⁷ expanded correctly but relevant three terms not identified First 3 terms in ascending powers of p simplified 1 error, otherwise correct (note that the error could be, for example, consistent mishandling of (2p), or powers adding to the wrong number in each term)"],"perOptionSteps":[2,2,6]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p1-q10-iii", topicId: "maths-4-3", conceptId: "iii-integration-24t-average-speed-dani",
    section: "B", questionRef: "2025 HL Paper 1 Q10(iii)",
    questionText: "(iii) Use integration, and v(t) = −t² + 24t−48∙4, to find the average speed of Dani’s car for 4 < t≤8",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 3, 5)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 5,
    rows: [
    { id: "maths-2025-hl-p1-q10-iii-r1", kind: "anyN", verbatim: "Splits in 3 fractions / divides top", marks: 5, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 3, three parts for 5. Marked in order: Step 1; Step 2; Step 3.", openList: true, group: {"claimMax":3,"perOption":2,"options":["Splits in 3 fractions / divides top","Simplifies (before taking limits)","Takes limits"],"perOptionSteps":[2,1,2]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p2-q1-b", topicId: "maths-2-2", conceptId: "line-has-equation",
    section: "B", questionRef: "2025 HL Paper 2 Q1(b)",
    questionText: "The line l has equation y= − 1 3 x+ 11",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 3, 5, 7, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p2-q1-b-r1", kind: "anyN", verbatim: "Finds ml", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 3, two parts for 5, three parts for 7, four parts for 10. Marked in order: Step 1; Step 2; Step 3; Step 1; Step 2; Step 3; Step 1; Step 2.", openList: true, group: {"claimMax":4,"perOption":3,"options":["Finds ml","Finds mh","Subs in formula","Finds ml","Finds mh","Finds 161 ∙56 …⁰ and 21 ∙8 …⁰","Finds ml","Finds mh"],"perOptionSteps":[3,2,2,3]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p2-q1-c", topicId: "maths-3-1", conceptId: "line-cuts-axis-point-axis",
    section: "B", questionRef: "2025 HL Paper 2 Q1(c)",
    questionText: "A line cuts the x-axis at the point A(a, 0) and the y-axis at B(0, b), where a, b ∈ℤ",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 4, 7, 10, 15)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 15,
    rows: [
    { id: "maths-2025-hl-p2-q1-c-r1", kind: "anyN", verbatim: "Finds area for one set of a and b (not  a", marks: 15, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 4, two parts for 7, three parts for 10, four parts for 15. Marked in order: Step 1; Step 2; Step 3; Step 4; Step 1; Step 2; Step 3; Step 4.", openList: true, group: {"claimMax":4,"perOption":4,"options":["Finds area for one set of a and b (not  a","Finds area for a correct set of values of","Finds one equation","Finds second equation","1 equation in a and b","Second equation in a and b","Finds a or b","Finds equations of 2 lines"],"perOptionSteps":[4,3,3,5]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p2-q2-b", topicId: "maths-3-1", conceptId: "circle-has-equation-constant-28x-46y",
    section: "B", questionRef: "2025 HL Paper 2 Q2(b)",
    questionText: "The circle t has the following equation, where k∈ℝ is a constant: x² + y² + 28x−46y+ k= 0 The horizontal line y= k is a tangent to the circle t. Find the two possible values of k",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 4, 7, 10, 15)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 15,
    rows: [
    { id: "maths-2025-hl-p2-q2-b-r1", kind: "anyN", verbatim: "Finds in terms of k, point of tangency", marks: 15, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 4, two parts for 7, three parts for 10, four parts for 15. Marked in order: Step 1; Step 2; Step 3; Step 1; Step 2; Step 3; Step 1; Step 2; Step 3.", openList: true, group: {"claimMax":4,"perOption":4,"options":["Finds in terms of k, point of tangency","Equation in k ( in solution)","Quadratic equation in the form","Finds centre and radius","Equation in k ( in solution)","Quadratic equation in form","Finds centre and radius","23 + √725 −k or 23 −√725 −k","Quadratic equation in form"],"perOptionSteps":[4,3,3,5]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p2-q4-c", topicId: "maths-3-1", conceptId: "frequency-table-shows-ages-people-another",
    section: "B", questionRef: "2025 HL Paper 2 Q4(c)",
    questionText: "The frequency table below shows the ages of the people in another class, where k∈ℕ",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 3, 5, 7, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p2-q4-c-r1", kind: "anyN", verbatim: "Finds mid-interval values", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 3, two parts for 5, three parts for 7, four parts for 10. Marked in order: Step 1; Step 2; Step 3; Step 4.", openList: true, group: {"claimMax":4,"perOption":3,"options":["Finds mid-interval values","Finds a correct expression in k for","Writes an equation in k","Solves for k"],"perOptionSteps":[3,2,2,3]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p2-q6-a", topicId: "maths-2-3", conceptId: "all-six-solutions-equation-360-720",
    section: "B", questionRef: "2025 HL Paper 2 Q6(a)",
    questionText: "Find all six solutions to the following equation in A, where −360° ≤A≤720°: sin A= 1 2",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 3, 4, 5)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 5,
    rows: [
    { id: "maths-2025-hl-p2-q6-a-r1", kind: "anyN", verbatim: "Finds reference angle", marks: 5, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 3, three parts for 4, four parts for 5. Marked in order: Step 1; Step 2; Step 3; Step 4.", openList: true, group: {"claimMax":4,"perOption":2,"options":["Finds reference angle","Finds 2nd angle in first revolution","Finds values < 0°","Finds values > 360°"],"perOptionSteps":[2,1,1,1]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p2-q6-c", topicId: "maths-2-3", conceptId: "triangle",
    section: "B", questionRef: "2025 HL Paper 2 Q6(c)",
    questionText: "In the triangle A, |A| = 2, |B| = 3, and |A| = 4",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 3, 5, 7, 10)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "maths-2025-hl-p2-q6-c-r1", kind: "anyN", verbatim: "Fills in cosine rule", marks: 10, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 3, two parts for 5, three parts for 7, four parts for 10. Marked in order: Step 1; Step 2; Step 3.", openList: true, group: {"claimMax":3,"perOption":3,"options":["Fills in cosine rule","Finds c∠C","Finds t∠C"],"perOptionSteps":[3,2,5]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "higher",
    paperFileid: null,
    schemeCitation: "Marking points quoted from the SEC marking scheme, Mathematics 2025 Higher Level — © State Examinations Commission.",
    id: "maths-2025-hl-p2-q10-b", topicId: "maths-1-6", conceptId: "using-values-table-construct-confidence-interval",
    section: "B", questionRef: "2025 HL Paper 2 Q10(b)",
    questionText: "Using values from the table, construct a 95% confidence interval for the population mean score of country X. Give each value correct to 1 decimal place",
    tariffModel: {"kind":"fixed","notation":"Scale (0, 2, 3, 4, 5)","answer":null,"ofParts":null,"perPart":null}, totalMarks: 5,
    rows: [
    { id: "maths-2025-hl-p2-q10-b-r1", kind: "anyN", verbatim: "Finds 1∙96 ×", marks: 5, contextNote: "The scheme marks this on a sliding scale: nothing for 0, one part for 2, two parts for 3, three parts for 4, four parts for 5. Marked in order: Step 2; Step 4.", openList: true, group: {"claimMax":2,"perOption":2,"options":["Finds 1∙96 ×","Finds C.I."],"perOptionSteps":[2,3]} },
    ],
  } as SecCard,
];
