/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export interface CAOCourse {
  code: string;
  title: string;
  institution: string;
  level: 5 | 6 | 7 | 8;
  typicalPoints: number;
  duration: number;
  interestTags: string[];
  workStyleTags: string[];
  careerPaths: string[];
  subjectBonus: string[];
  region: string;
  description: string;
  employability: 1 | 2 | 3 | 4 | 5;
  salaryBand: 'low' | 'mid' | 'high';
  pathwayType?: 'cao' | 'plc' | 'apprenticeship';
}

// ─── Taxonomies ─────────────────────────────────────────────────────────────

export const INTEREST_TAGS = [
  'technology', 'science', 'healthcare', 'business', 'finance',
  'engineering', 'arts', 'media', 'education', 'law',
  'environment', 'sport', 'psychology', 'social-care', 'languages',
  'design', 'agriculture', 'music', 'politics', 'food',
] as const;

export const WORK_STYLE_TAGS = [
  'hands-on', 'analytical', 'creative', 'people-focused',
  'research-driven', 'structured', 'flexible', 'team-based',
  'independent', 'leadership',
] as const;

export const REGIONS: Record<string, string> = {
  dublin: 'Dublin',
  cork: 'Cork',
  galway: 'Galway',
  limerick: 'Limerick',
  midlands: 'Midlands',
  southeast: 'South East',
  northwest: 'North West',
  southwest: 'South West',
};

export const INSTITUTIONS: Record<string, string> = {
  UCD: 'University College Dublin',
  TCD: 'Trinity College Dublin',
  UCC: 'University College Cork',
  UL: 'University of Limerick',
  'U of Galway': 'University of Galway',
  DCU: 'Dublin City University',
  MU: 'Maynooth University',
  RCSI: 'RCSI University of Medicine',
  'TU Dublin': 'Technological University Dublin',
  TUS: 'Technological University of the Shannon',
  ATU: 'Atlantic Technological University',
  SETU: 'South East Technological University',
  MTU: 'Munster Technological University',
  PLC: 'Post Leaving Certificate',
  SOLAS: 'SOLAS Apprenticeship',
  ETB: 'Education & Training Board',
};

// ─── Course Database — 2025 CAO Round 1 Points ─────────────────────────────

export const CAO_COURSES: CAOCourse[] = [
  // ── UCD ─────────────────────────────────────────────────────────────────
  {
    code: 'DN201', title: 'Computer Science', institution: 'UCD', level: 8, typicalPoints: 542,
    duration: 4, interestTags: ['technology', 'science'], workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Engineer', 'Data Scientist', 'AI Researcher'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'dublin', description: 'Study algorithms, AI, software engineering and data science at Ireland\'s largest CS school.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DN150', title: 'Engineering', institution: 'UCD', level: 8, typicalPoints: 578,
    duration: 4, interestTags: ['engineering', 'technology', 'science'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Civil Engineer', 'Mechanical Engineer', 'Biomedical Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths', 'DCG', 'Construction Studies'],
    region: 'dublin', description: 'Common entry to all engineering disciplines with specialisation from second year.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DN230', title: 'Actuarial & Financial Studies', institution: 'UCD', level: 8, typicalPoints: 613,
    duration: 4, interestTags: ['finance', 'business', 'science'], workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Actuary', 'Risk Analyst', 'Financial Modeller'],
    subjectBonus: ['Mathematics', 'Economics', 'Accounting', 'Business'],
    region: 'dublin', description: 'One of Europe\'s top actuarial programmes with industry exam exemptions built in.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DN200', title: 'Science', institution: 'UCD', level: 8, typicalPoints: 544,
    duration: 4, interestTags: ['science', 'environment', 'healthcare'],
    workStyleTags: ['research-driven', 'analytical', 'independent'],
    careerPaths: ['Research Scientist', 'Lab Manager', 'Environmental Consultant'],
    subjectBonus: ['Mathematics', 'Biology', 'Chemistry', 'Physics'],
    region: 'dublin', description: 'Choose from 20+ science subjects including physics, chemistry, biology, maths and computer science.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'DN100', title: 'Architecture', institution: 'UCD', level: 8, typicalPoints: 556,
    duration: 5, interestTags: ['design', 'arts', 'engineering'],
    workStyleTags: ['creative', 'hands-on', 'team-based'],
    careerPaths: ['Architect', 'Urban Planner', 'Interior Designer'],
    subjectBonus: ['Art', 'Mathematics', 'DCG', 'Construction Studies', 'Physics'],
    region: 'dublin', description: 'A five-year programme leading to professional accreditation as an architect.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'DN520', title: 'BA Joint Honours', institution: 'UCD', level: 8, typicalPoints: 420,
    duration: 3, interestTags: ['arts', 'languages', 'politics', 'psychology'],
    workStyleTags: ['creative', 'independent', 'research-driven'],
    careerPaths: ['Journalist', 'Policy Analyst', 'Teacher'],
    subjectBonus: ['English', 'History', 'Irish', 'French', 'German', 'Spanish'],
    region: 'dublin', description: 'Choose from 30+ subjects across humanities, social sciences and languages in one of Ireland\'s most flexible arts degrees.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'DN700', title: 'Social Sciences', institution: 'UCD', level: 8, typicalPoints: 491,
    duration: 3, interestTags: ['psychology', 'social-care', 'politics'],
    workStyleTags: ['people-focused', 'research-driven', 'analytical'],
    careerPaths: ['Social Worker', 'Psychologist', 'Policy Researcher'],
    subjectBonus: ['English', 'Mathematics', 'History', 'Geography'],
    region: 'dublin', description: 'Study sociology, politics, economics and social policy with pathways to social work and public policy.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'DN450', title: 'General Nursing', institution: 'UCD', level: 8, typicalPoints: 444,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured', 'team-based'],
    careerPaths: ['Registered Nurse', 'Clinical Nurse Specialist', 'Nurse Manager'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics', 'Mathematics'],
    region: 'dublin', description: 'Train as a general nurse with extensive clinical placements in major Dublin hospitals.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'DN300', title: 'Veterinary Medicine', institution: 'UCD', level: 8, typicalPoints: 590,
    duration: 5, interestTags: ['science', 'agriculture', 'healthcare'],
    workStyleTags: ['hands-on', 'research-driven', 'people-focused'],
    careerPaths: ['Veterinarian', 'Animal Researcher', 'Agricultural Consultant'],
    subjectBonus: ['Biology', 'Chemistry', 'Ag Science', 'Mathematics', 'Physics'],
    region: 'dublin', description: 'Ireland\'s only veterinary degree — covering companion animal, equine, farm and wildlife medicine.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DN250', title: 'Agricultural Science', institution: 'UCD', level: 8, typicalPoints: 432,
    duration: 4, interestTags: ['agriculture', 'environment', 'science'],
    workStyleTags: ['hands-on', 'research-driven', 'flexible'],
    careerPaths: ['Agricultural Advisor', 'Food Scientist', 'Farm Manager'],
    subjectBonus: ['Ag Science', 'Biology', 'Chemistry', 'Geography'],
    region: 'dublin', description: 'Study crop science, animal science, soil science and agri-business with industry placements.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'DN650', title: 'Commerce', institution: 'UCD', level: 8, typicalPoints: 555,
    duration: 3, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Accountant', 'Marketing Manager', 'Business Analyst'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'dublin', description: 'Ireland\'s leading business degree with streams in accounting, finance, management and marketing.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'DN610', title: 'Business & Law', institution: 'UCD', level: 8, typicalPoints: 566,
    duration: 5, interestTags: ['business', 'law'], workStyleTags: ['analytical', 'people-focused', 'structured'],
    careerPaths: ['Corporate Lawyer', 'Business Consultant', 'Investment Banker'],
    subjectBonus: ['English', 'Mathematics', 'Business', 'Economics', 'Accounting'],
    region: 'dublin', description: 'A dual-degree programme combining Commerce and Law for careers at the intersection of business and legal practice.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DN600', title: 'Law', institution: 'UCD', level: 8, typicalPoints: 567,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Barrister', 'Solicitor', 'Legal Advisor'],
    subjectBonus: ['English', 'History', 'Politics & Society', 'Economics'],
    region: 'dublin', description: 'Study law at UCD with mooting, clinical legal education and international exchange options.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'DN420', title: 'Physiotherapy', institution: 'UCD', level: 8, typicalPoints: 579,
    duration: 4, interestTags: ['healthcare', 'sport', 'science'],
    workStyleTags: ['hands-on', 'people-focused', 'analytical'],
    careerPaths: ['Physiotherapist', 'Sports Physio', 'Rehabilitation Specialist'],
    subjectBonus: ['Biology', 'Physics', 'Mathematics', 'Chemistry'],
    region: 'dublin', description: 'Train as a physiotherapist with clinical placements across hospitals and sports settings.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DN720', title: 'Psychology', institution: 'UCD', level: 8, typicalPoints: 545,
    duration: 3, interestTags: ['psychology', 'science'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Clinical Psychologist', 'Researcher', 'HR Specialist'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'dublin', description: 'An accredited psychology degree with a strong research and clinical focus.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'DN670', title: 'Economics & Finance', institution: 'UCD', level: 8, typicalPoints: 625,
    duration: 3, interestTags: ['finance', 'business'],
    workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Economist', 'Financial Analyst', 'Investment Banker'],
    subjectBonus: ['Mathematics', 'Economics', 'Accounting'],
    region: 'dublin', description: 'A highly competitive programme combining economics and finance with strong career prospects.',
    employability: 5, salaryBand: 'high',
  },

  // ── TCD ─────────────────────────────────────────────────────────────────
  {
    code: 'TR033', title: 'Computer Science', institution: 'TCD', level: 8, typicalPoints: 543,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Developer', 'Systems Architect', 'Machine Learning Engineer'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics', 'Applied Maths'],
    region: 'dublin', description: 'Study computer science at Ireland\'s top-ranked university with strong industry links.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'TR004', title: 'Law', institution: 'TCD', level: 8, typicalPoints: 578,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Barrister', 'Solicitor', 'Legal Advisor'],
    subjectBonus: ['English', 'History', 'Politics & Society', 'Economics'],
    region: 'dublin', description: 'Study law at Trinity with moot court experience and pathways to the Bar or solicitor qualification.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'TR032', title: 'Engineering', institution: 'TCD', level: 8, typicalPoints: 577,
    duration: 5, interestTags: ['engineering', 'technology', 'science'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Structural Engineer', 'Electronic Engineer', 'Biomedical Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths', 'Chemistry'],
    region: 'dublin', description: 'Common entry to civil, mechanical, electronic and biomedical engineering at Trinity.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'TR081', title: 'Business, Economics & Social Studies', institution: 'TCD', level: 8, typicalPoints: 566,
    duration: 4, interestTags: ['business', 'finance', 'politics'],
    workStyleTags: ['analytical', 'leadership', 'team-based'],
    careerPaths: ['Management Consultant', 'Economist', 'Financial Analyst'],
    subjectBonus: ['Mathematics', 'Business', 'Economics', 'Accounting'],
    region: 'dublin', description: 'Trinity\'s BESS programme — study business, economics, political science and sociology.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'TR060', title: 'Biological & Biomedical Sciences', institution: 'TCD', level: 8, typicalPoints: 554,
    duration: 4, interestTags: ['science', 'healthcare'],
    workStyleTags: ['research-driven', 'analytical', 'independent'],
    careerPaths: ['Research Scientist', 'Pharmaceutical Scientist', 'Biotech Researcher'],
    subjectBonus: ['Mathematics', 'Biology', 'Chemistry', 'Physics'],
    region: 'dublin', description: 'Study science at Trinity with world-class labs and research opportunities.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'TR003', title: 'History', institution: 'TCD', level: 8, typicalPoints: 526,
    duration: 4, interestTags: ['arts', 'politics'],
    workStyleTags: ['research-driven', 'independent', 'analytical'],
    careerPaths: ['Historian', 'Museum Curator', 'Heritage Officer'],
    subjectBonus: ['History', 'English', 'Politics & Society', 'Geography'],
    region: 'dublin', description: 'Study ancient, medieval and modern history in the heart of Dublin\'s historic campus.',
    employability: 2, salaryBand: 'mid',
  },
  {
    code: 'TR052', title: 'Dental Science', institution: 'TCD', level: 8, typicalPoints: 625,
    duration: 5, interestTags: ['healthcare', 'science'],
    workStyleTags: ['hands-on', 'people-focused', 'structured'],
    careerPaths: ['Dentist', 'Oral Surgeon', 'Dental Researcher'],
    subjectBonus: ['Biology', 'Chemistry', 'Physics', 'Mathematics'],
    region: 'dublin', description: 'Ireland\'s leading dental school — clinical experience from second year at Dublin Dental University Hospital.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'TR006', title: 'Psychology', institution: 'TCD', level: 8, typicalPoints: 578,
    duration: 4, interestTags: ['psychology', 'science', 'social-care'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Clinical Psychologist', 'Researcher', 'HR Specialist'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'dublin', description: 'An accredited psychology degree with a strong research and clinical focus.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'TR031', title: 'Mathematics', institution: 'TCD', level: 8, typicalPoints: 598,
    duration: 4, interestTags: ['science', 'finance', 'technology'],
    workStyleTags: ['analytical', 'independent', 'research-driven'],
    careerPaths: ['Actuary', 'Data Scientist', 'Quantitative Analyst'],
    subjectBonus: ['Mathematics', 'Applied Maths', 'Physics'],
    region: 'dublin', description: 'Study pure and applied mathematics at Trinity with pathways to finance, tech and research.',
    employability: 5, salaryBand: 'high',
  },

  // ── UCC ─────────────────────────────────────────────────────────────────
  {
    code: 'CK401', title: 'Computer Science', institution: 'UCC', level: 8, typicalPoints: 456,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Engineer', 'Cybersecurity Analyst', 'Data Engineer'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'cork', description: 'Study computing in one of Ireland\'s leading tech hubs with industry work placement.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'CK600', title: 'Engineering', institution: 'UCC', level: 8, typicalPoints: 543,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Process Engineer', 'Electrical Engineer', 'Civil Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths', 'Chemistry'],
    region: 'cork', description: 'Common-entry engineering with specialisations in civil, electrical, energy and process engineering.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'CK101', title: 'Arts', institution: 'UCC', level: 8, typicalPoints: 300,
    duration: 3, interestTags: ['arts', 'languages', 'psychology'],
    workStyleTags: ['creative', 'independent', 'research-driven'],
    careerPaths: ['Writer', 'Teacher', 'Communications Officer'],
    subjectBonus: ['English', 'Irish', 'History', 'French', 'German', 'Spanish'],
    region: 'cork', description: 'A flexible arts degree with 30+ subject combinations including languages, history, philosophy and music.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'CK201', title: 'Commerce', institution: 'UCC', level: 8, typicalPoints: 511,
    duration: 3, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Accountant', 'Business Manager', 'HR Manager'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'cork', description: 'Study business in Cork with specialisms in accounting, finance, management, information systems and marketing.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'CK301', title: 'Law (Pathways)', institution: 'UCC', level: 8, typicalPoints: 532,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Solicitor', 'Barrister', 'Legal Executive'],
    subjectBonus: ['English', 'History', 'Politics & Society'],
    region: 'cork', description: 'Study law in Cork with moot courts and optional pathways to criminology and government.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'CK710', title: 'General Nursing', institution: 'UCC', level: 8, typicalPoints: 452,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Midwife', 'Clinical Nurse Manager'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'cork', description: 'Train as a nurse in Cork with clinical placements in CUH and regional hospitals.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'CK102', title: 'Social Science', institution: 'UCC', level: 8, typicalPoints: 400,
    duration: 3, interestTags: ['social-care', 'psychology', 'politics'],
    workStyleTags: ['people-focused', 'research-driven', 'analytical'],
    careerPaths: ['Social Worker', 'Community Development Worker', 'Policy Analyst'],
    subjectBonus: ['English', 'History', 'Geography', 'Mathematics'],
    region: 'cork', description: 'Study sociology, politics, economics and philosophy with pathways to social work and community development.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'CK120', title: 'Applied Psychology', institution: 'UCC', level: 8, typicalPoints: 536,
    duration: 4, interestTags: ['psychology', 'science'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Clinical Psychologist', 'Behavioural Therapist', 'Researcher'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'cork', description: 'An accredited applied psychology degree with strong research and clinical training.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'CK703', title: 'Pharmacy', institution: 'UCC', level: 8, typicalPoints: 602,
    duration: 5, interestTags: ['healthcare', 'science'],
    workStyleTags: ['analytical', 'people-focused', 'structured'],
    careerPaths: ['Pharmacist', 'Pharmaceutical Scientist', 'Regulatory Affairs'],
    subjectBonus: ['Chemistry', 'Biology', 'Mathematics', 'Physics'],
    region: 'cork', description: 'Train as a pharmacist with lab work, clinical placements and drug development modules.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'CK702', title: 'Dentistry', institution: 'UCC', level: 8, typicalPoints: 613,
    duration: 5, interestTags: ['healthcare', 'science'],
    workStyleTags: ['hands-on', 'people-focused', 'structured'],
    careerPaths: ['Dentist', 'Oral Surgeon', 'Orthodontist'],
    subjectBonus: ['Biology', 'Chemistry', 'Physics', 'Mathematics'],
    region: 'cork', description: 'Study dentistry in Cork with clinical experience from early in the programme.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'CK412', title: 'Agricultural Science', institution: 'UCC', level: 8, typicalPoints: 484,
    duration: 4, interestTags: ['agriculture', 'environment', 'science'],
    workStyleTags: ['hands-on', 'research-driven', 'flexible'],
    careerPaths: ['Agricultural Advisor', 'Food Scientist', 'Agri-Business Manager'],
    subjectBonus: ['Ag Science', 'Biology', 'Chemistry', 'Geography'],
    region: 'cork', description: 'Study agricultural science in Cork with industry placements and research projects.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'CK204', title: 'Finance', institution: 'UCC', level: 8, typicalPoints: 578,
    duration: 3, interestTags: ['finance', 'business'],
    workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Financial Analyst', 'Investment Banker', 'Risk Manager'],
    subjectBonus: ['Mathematics', 'Accounting', 'Economics', 'Business'],
    region: 'cork', description: 'A specialised finance degree with strong quantitative skills and industry connections.',
    employability: 5, salaryBand: 'high',
  },

  // ── University of Galway ───────────────────────────────────────────────
  {
    code: 'GY301', title: 'Science', institution: 'U of Galway', level: 8, typicalPoints: 440,
    duration: 4, interestTags: ['science', 'environment'],
    workStyleTags: ['research-driven', 'analytical', 'independent'],
    careerPaths: ['Marine Biologist', 'Environmental Scientist', 'Lab Researcher'],
    subjectBonus: ['Mathematics', 'Biology', 'Chemistry', 'Physics'],
    region: 'galway', description: 'Study science in Galway with unique options in marine science, environmental science and bioinformatics.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'GY350', title: 'Computer Science & IT', institution: 'U of Galway', level: 8, typicalPoints: 440,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Developer', 'IT Consultant', 'Data Analyst'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'galway', description: 'Study computing in one of Ireland\'s fastest-growing tech regions.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'GY101', title: 'Arts', institution: 'U of Galway', level: 8, typicalPoints: 350,
    duration: 3, interestTags: ['arts', 'languages', 'politics'],
    workStyleTags: ['creative', 'independent', 'research-driven'],
    careerPaths: ['Journalist', 'Teacher', 'Civil Servant'],
    subjectBonus: ['English', 'Irish', 'History', 'French', 'German'],
    region: 'galway', description: 'A flexible arts degree with excellent Irish language studies and unique subjects like archaeology and classics.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'GY201', title: 'Commerce', institution: 'U of Galway', level: 8, typicalPoints: 454,
    duration: 3, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Accountant', 'Financial Advisor', 'Marketing Manager'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'galway', description: 'Study business in Galway with professional accounting exemptions and work placement.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'GY401', title: 'Engineering', institution: 'U of Galway', level: 8, typicalPoints: 542,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Biomedical Engineer', 'Mechanical Engineer', 'Energy Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths', 'Construction Studies'],
    region: 'galway', description: 'Common-entry engineering with streams in biomedical, civil, electronic, energy and mechanical.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'GY251', title: 'Law (BCL)', institution: 'U of Galway', level: 8, typicalPoints: 520,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Solicitor', 'Barrister', 'Human Rights Advocate'],
    subjectBonus: ['English', 'History', 'Politics & Society', 'Irish'],
    region: 'galway', description: 'Study law in Galway with a strong emphasis on human rights and public interest law.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'GY515', title: 'Nursing', institution: 'U of Galway', level: 8, typicalPoints: 441,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Public Health Nurse', 'Nurse Educator'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'galway', description: 'Train as a nurse with placements across Galway and the west of Ireland.',
    employability: 5, salaryBand: 'mid',
  },

  // ── UL ──────────────────────────────────────────────────────────────────
  {
    code: 'LM121', title: 'Computer Science', institution: 'UL', level: 8, typicalPoints: 382,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Engineer', 'Game Developer', 'IT Architect'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'limerick', description: 'Study CS at UL with an 8-month co-op work placement built into the degree.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'LM116', title: 'Engineering', institution: 'UL', level: 8, typicalPoints: 510,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Mechanical Engineer', 'Aeronautical Engineer', 'Manufacturing Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths', 'DCG'],
    region: 'limerick', description: 'Common-entry engineering with co-op placement and streams in mechanical, civil, electronic and more.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'LM002', title: 'Arts', institution: 'UL', level: 8, typicalPoints: 316,
    duration: 4, interestTags: ['arts', 'languages', 'media'],
    workStyleTags: ['creative', 'independent', 'flexible'],
    careerPaths: ['Journalist', 'PR Specialist', 'Teacher'],
    subjectBonus: ['English', 'Irish', 'History', 'French', 'German', 'Spanish'],
    region: 'limerick', description: 'A four-year arts degree with co-op placement and subjects like journalism, new media and sociology.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'LM050', title: 'Business Studies', institution: 'UL', level: 8, typicalPoints: 444,
    duration: 4, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Business Analyst', 'Finance Manager', 'Entrepreneur'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'limerick', description: 'A business degree with UL\'s signature 8-month co-op work placement.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'LM020', title: 'Law & Accounting', institution: 'UL', level: 8, typicalPoints: 444,
    duration: 4, interestTags: ['law', 'finance', 'business'],
    workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Corporate Lawyer', 'Tax Advisor', 'Compliance Officer'],
    subjectBonus: ['English', 'Accounting', 'Business', 'Mathematics'],
    region: 'limerick', description: 'Combine law and accounting with professional exam exemptions and co-op work placement.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'LM090', title: 'PE with Teacher Education', institution: 'UL', level: 8, typicalPoints: 531,
    duration: 4, interestTags: ['education', 'sport', 'science'],
    workStyleTags: ['people-focused', 'hands-on', 'leadership'],
    careerPaths: ['Secondary School Teacher', 'PE Teacher', 'Sports Coordinator'],
    subjectBonus: ['Mathematics', 'Biology', 'Physics'],
    region: 'limerick', description: 'A concurrent teacher education degree in physical education.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'LM150', title: 'Nursing (General)', institution: 'UL', level: 8, typicalPoints: 412,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Emergency Nurse', 'Nurse Manager'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'limerick', description: 'Train as a nurse with clinical placements in UHL and regional hospitals across the mid-west.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'LM058', title: 'Financial Mathematics', institution: 'UL', level: 8, typicalPoints: 457,
    duration: 4, interestTags: ['finance', 'science', 'technology'],
    workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Quantitative Analyst', 'Risk Manager', 'Data Scientist'],
    subjectBonus: ['Mathematics', 'Applied Maths', 'Economics', 'Physics'],
    region: 'limerick', description: 'Combine mathematics and finance with co-op work placement and strong industry links.',
    employability: 5, salaryBand: 'high',
  },

  // ── DCU ─────────────────────────────────────────────────────────────────
  {
    code: 'DC121', title: 'Computer Science', institution: 'DCU', level: 8, typicalPoints: 487,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'team-based'],
    careerPaths: ['Software Developer', 'Cloud Engineer', 'Data Scientist'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'dublin', description: 'Study computing at DCU with an emphasis on software engineering and a paid internship year.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DC200', title: 'Engineering (Common Entry)', institution: 'DCU', level: 8, typicalPoints: 543,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Biomedical Engineer', 'Mechanical Engineer', 'Robotics Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths', 'Engineering'],
    region: 'dublin', description: 'Common-entry engineering at DCU with streams in biomedical, electronic and mechanical.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DC002', title: 'Education (Primary Teaching)', institution: 'DCU', level: 8, typicalPoints: 485,
    duration: 4, interestTags: ['education', 'social-care'],
    workStyleTags: ['people-focused', 'creative', 'leadership'],
    careerPaths: ['Primary School Teacher', 'Learning Support Teacher', 'Education Researcher'],
    subjectBonus: ['Irish', 'English', 'Mathematics'],
    region: 'dublin', description: 'Train as a primary school teacher at DCU\'s Institute of Education with school placements each year.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'DC111', title: 'Business Studies', institution: 'DCU', level: 8, typicalPoints: 510,
    duration: 4, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Business Analyst', 'Marketing Manager', 'Entrepreneur'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'dublin', description: 'Study business at DCU with a paid internship year and strong links to Irish industry.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'DC132', title: 'Journalism', institution: 'DCU', level: 8, typicalPoints: 409,
    duration: 4, interestTags: ['media', 'arts', 'politics'],
    workStyleTags: ['creative', 'people-focused', 'flexible'],
    careerPaths: ['Journalist', 'Broadcaster', 'Digital Content Creator'],
    subjectBonus: ['English', 'History', 'Politics & Society'],
    region: 'dublin', description: 'Ireland\'s top journalism programme with a newsroom on campus and industry placements.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'DC131', title: 'Communication Studies', institution: 'DCU', level: 8, typicalPoints: 360,
    duration: 4, interestTags: ['media', 'arts'],
    workStyleTags: ['creative', 'people-focused', 'team-based'],
    careerPaths: ['PR Manager', 'Content Strategist', 'Social Media Manager'],
    subjectBonus: ['English', 'Business', 'Art'],
    region: 'dublin', description: 'Study media, communications and culture with practical digital skills and industry placement.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'DC208', title: 'Psychology', institution: 'DCU', level: 8, typicalPoints: 533,
    duration: 4, interestTags: ['psychology', 'science', 'social-care'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Psychologist', 'Counsellor', 'Behavioural Scientist'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'dublin', description: 'An accredited psychology degree with strong research methods training and work placement.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'DC215', title: 'General Nursing', institution: 'DCU', level: 8, typicalPoints: 424,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Children\'s Nurse', 'Nurse Educator'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'dublin', description: 'Train as a nurse at DCU with clinical placements across Dublin\'s major hospitals.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'DC232', title: 'Civil Law (BCL)', institution: 'DCU', level: 8, typicalPoints: 496,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Solicitor', 'Barrister', 'Legal Advisor'],
    subjectBonus: ['English', 'History', 'Politics & Society'],
    region: 'dublin', description: 'Study law at DCU with internship placement and practical legal skills.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'DC123', title: 'Data Science', institution: 'DCU', level: 8, typicalPoints: 500,
    duration: 4, interestTags: ['technology', 'science', 'finance'],
    workStyleTags: ['analytical', 'independent', 'research-driven'],
    careerPaths: ['Data Scientist', 'Machine Learning Engineer', 'Analytics Consultant'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'dublin', description: 'Study data science at DCU with a paid internship year and strong industry demand.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'DC202', title: 'Sport Science & Health', institution: 'DCU', level: 8, typicalPoints: 518,
    duration: 4, interestTags: ['sport', 'science', 'healthcare'],
    workStyleTags: ['hands-on', 'people-focused', 'research-driven'],
    careerPaths: ['Sports Scientist', 'Strength Coach', 'Performance Analyst'],
    subjectBonus: ['Biology', 'Physics', 'Mathematics', 'Chemistry'],
    region: 'dublin', description: 'Study the science of human performance at DCU\'s sports facilities.',
    employability: 3, salaryBand: 'mid',
  },

  // ── MU (Maynooth) ──────────────────────────────────────────────────────
  {
    code: 'MH601', title: 'Computer Science (through Arts)', institution: 'MU', level: 8, typicalPoints: 360,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Developer', 'Systems Analyst', 'DevOps Engineer'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'dublin', description: 'Study computer science at Maynooth with strong maths foundations and industry links.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'MH101', title: 'Arts', institution: 'MU', level: 8, typicalPoints: 300,
    duration: 3, interestTags: ['arts', 'languages', 'music', 'psychology'],
    workStyleTags: ['creative', 'independent', 'research-driven'],
    careerPaths: ['Teacher', 'Writer', 'Arts Administrator'],
    subjectBonus: ['English', 'Irish', 'History', 'French', 'Music'],
    region: 'dublin', description: 'Maynooth\'s flagship arts programme with unique options including music, medieval studies and anthropology.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'MH201', title: 'Science', institution: 'MU', level: 8, typicalPoints: 352,
    duration: 4, interestTags: ['science', 'environment'],
    workStyleTags: ['research-driven', 'analytical', 'independent'],
    careerPaths: ['Researcher', 'Science Teacher', 'Environmental Consultant'],
    subjectBonus: ['Mathematics', 'Biology', 'Chemistry', 'Physics'],
    region: 'dublin', description: 'Study science at Maynooth with options in biology, chemistry, physics, maths and psychology.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'MH304', title: 'Engineering', institution: 'MU', level: 8, typicalPoints: 364,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Electronic Engineer', 'Robotics Engineer', 'Systems Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths'],
    region: 'dublin', description: 'Study electronic and computer engineering at Maynooth with strong industry connections.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'MH501', title: 'Law (LLB)', institution: 'MU', level: 8, typicalPoints: 452,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Solicitor', 'Barrister', 'Policy Analyst'],
    subjectBonus: ['English', 'History', 'Politics & Society'],
    region: 'dublin', description: 'Study law at Maynooth with a focus on social justice and human rights.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'MH001', title: 'Education (Primary Teaching)', institution: 'MU', level: 8, typicalPoints: 506,
    duration: 4, interestTags: ['education', 'social-care'],
    workStyleTags: ['people-focused', 'creative', 'leadership'],
    careerPaths: ['Primary School Teacher', 'Special Education Teacher', 'Educational Psychologist'],
    subjectBonus: ['Irish', 'English', 'Mathematics'],
    region: 'dublin', description: 'Train as a primary school teacher at Ireland\'s largest teacher education programme.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'MH209', title: 'Psychology', institution: 'MU', level: 8, typicalPoints: 488,
    duration: 4, interestTags: ['psychology', 'science'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Psychologist', 'Researcher', 'Behavioural Therapist'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'dublin', description: 'An accredited psychology degree with a strong research focus and modern labs.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'MH107', title: 'Social Science', institution: 'MU', level: 8, typicalPoints: 348,
    duration: 3, interestTags: ['social-care', 'politics', 'psychology'],
    workStyleTags: ['people-focused', 'research-driven', 'analytical'],
    careerPaths: ['Social Worker', 'Policy Analyst', 'Community Worker'],
    subjectBonus: ['English', 'History', 'Geography', 'Mathematics'],
    region: 'dublin', description: 'Study social science at Maynooth with pathways to social work and public policy.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'MH401', title: 'Finance', institution: 'MU', level: 8, typicalPoints: 366,
    duration: 3, interestTags: ['finance', 'business'],
    workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Financial Analyst', 'Fund Manager', 'Risk Analyst'],
    subjectBonus: ['Mathematics', 'Accounting', 'Economics', 'Business'],
    region: 'dublin', description: 'Study finance at Maynooth with quantitative skills and industry connections.',
    employability: 4, salaryBand: 'high',
  },

  // ── RCSI ────────────────────────────────────────────────────────────────
  {
    code: 'RC005', title: 'Pharmacy', institution: 'RCSI', level: 8, typicalPoints: 589,
    duration: 5, interestTags: ['healthcare', 'science'],
    workStyleTags: ['analytical', 'people-focused', 'structured'],
    careerPaths: ['Pharmacist', 'Pharmaceutical Researcher', 'Clinical Pharmacist'],
    subjectBonus: ['Chemistry', 'Biology', 'Mathematics', 'Physics'],
    region: 'dublin', description: 'Train as a pharmacist at RCSI with integrated clinical placements and research opportunities.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'RC004', title: 'Physiotherapy', institution: 'RCSI', level: 8, typicalPoints: 566,
    duration: 4, interestTags: ['healthcare', 'sport', 'science'],
    workStyleTags: ['hands-on', 'people-focused', 'analytical'],
    careerPaths: ['Physiotherapist', 'Sports Rehabilitation', 'Musculoskeletal Specialist'],
    subjectBonus: ['Biology', 'Physics', 'Mathematics', 'Chemistry'],
    region: 'dublin', description: 'Train as a physiotherapist at RCSI with clinical placements in major Dublin hospitals.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'RC007', title: 'Dentistry', institution: 'RCSI', level: 8, typicalPoints: 613,
    duration: 5, interestTags: ['healthcare', 'science'],
    workStyleTags: ['hands-on', 'people-focused', 'structured'],
    careerPaths: ['Dentist', 'Oral Surgeon', 'Dental Researcher'],
    subjectBonus: ['Biology', 'Chemistry', 'Physics', 'Mathematics'],
    region: 'dublin', description: 'Study dentistry at RCSI with state-of-the-art simulation facilities.',
    employability: 5, salaryBand: 'high',
  },

  // ── TU Dublin ───────────────────────────────────────────────────────────
  {
    code: 'TU856', title: 'Computer Science', institution: 'TU Dublin', level: 8, typicalPoints: 443,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'team-based'],
    careerPaths: ['Full Stack Developer', 'Cloud Engineer', 'Tech Lead'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'dublin', description: 'Study computing at TU Dublin\'s Grangegorman campus with industry-focused projects and placement.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'TU805', title: 'Engineering (General Entry)', institution: 'TU Dublin', level: 8, typicalPoints: 490,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Mechanical Engineer', 'Production Engineer', 'Quality Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Engineering', 'DCG', 'Applied Maths'],
    region: 'dublin', description: 'Study engineering at Ireland\'s largest technological university.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'TU903', title: 'Business & Management', institution: 'TU Dublin', level: 8, typicalPoints: 455,
    duration: 4, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Business Manager', 'Marketing Executive', 'Entrepreneur'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'dublin', description: 'Study business at TU Dublin with practical projects and industry connections.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'TU918', title: 'Law (LL.B.)', institution: 'TU Dublin', level: 8, typicalPoints: 420,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Solicitor', 'Barrister', 'Legal Advisor'],
    subjectBonus: ['English', 'History', 'Politics & Society'],
    region: 'dublin', description: 'Study law at TU Dublin with practical legal clinics and industry connections.',
    employability: 4, salaryBand: 'high',
  },
  {
    code: 'TU854', title: 'Science (General Entry)', institution: 'TU Dublin', level: 8, typicalPoints: 445,
    duration: 4, interestTags: ['science', 'healthcare'],
    workStyleTags: ['research-driven', 'analytical', 'hands-on'],
    careerPaths: ['Pharmaceutical Scientist', 'Lab Analyst', 'Research Scientist'],
    subjectBonus: ['Mathematics', 'Biology', 'Chemistry', 'Physics'],
    region: 'dublin', description: 'Study science at TU Dublin with specialisation options and industry placement.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'TU850', title: 'Data Science & AI', institution: 'TU Dublin', level: 8, typicalPoints: 434,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'independent', 'research-driven'],
    careerPaths: ['Data Scientist', 'AI Engineer', 'Machine Learning Specialist'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'dublin', description: 'Study data science and artificial intelligence with strong industry demand.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'TU936', title: 'Sports Science & Health', institution: 'TU Dublin', level: 8, typicalPoints: 465,
    duration: 4, interestTags: ['sport', 'science', 'healthcare'],
    workStyleTags: ['hands-on', 'people-focused', 'research-driven'],
    careerPaths: ['Sports Scientist', 'Strength Coach', 'Performance Analyst'],
    subjectBonus: ['Biology', 'Physics', 'Mathematics'],
    region: 'dublin', description: 'Study sport science and health at TU Dublin with modern lab facilities.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'TU910', title: 'Accounting', institution: 'TU Dublin', level: 8, typicalPoints: 380,
    duration: 4, interestTags: ['finance', 'business'],
    workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Accountant', 'Auditor', 'Tax Consultant'],
    subjectBonus: ['Accounting', 'Mathematics', 'Business', 'Economics'],
    region: 'dublin', description: 'Study accounting at TU Dublin with professional exam exemptions.',
    employability: 4, salaryBand: 'mid',
  },

  // ── TUS (Technological University of the Shannon) ──────────────────────
  {
    code: 'US822', title: 'Software Design with AI', institution: 'TUS', level: 8, typicalPoints: 342,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Developer', 'AI Engineer', 'Data Analyst'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'midlands', description: 'Study software development with a focus on artificial intelligence at TUS.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'US840', title: 'Business', institution: 'TUS', level: 8, typicalPoints: 278,
    duration: 4, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Accountant', 'Business Manager', 'Financial Analyst'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'midlands', description: 'Study business in the midlands with strong industry links and professional accounting exemptions.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'US887', title: 'Civil Engineering', institution: 'TUS', level: 8, typicalPoints: 410,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Civil Engineer', 'Structural Engineer', 'Project Manager'],
    subjectBonus: ['Mathematics', 'Physics', 'Construction Studies', 'DCG'],
    region: 'midlands', description: 'Study civil engineering at TUS with hands-on labs and industry placement.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'US877', title: 'General Nursing', institution: 'TUS', level: 8, typicalPoints: 389,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Mental Health Nurse', 'Nurse Manager'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'midlands', description: 'Train as a nurse with TUS — smaller class sizes and excellent clinical placements.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'US920', title: 'Social Care Work', institution: 'TUS', level: 8, typicalPoints: 327,
    duration: 4, interestTags: ['social-care', 'psychology'],
    workStyleTags: ['people-focused', 'flexible', 'team-based'],
    careerPaths: ['Social Care Worker', 'Disability Support Worker', 'Youth Worker'],
    subjectBonus: ['English', 'Home Economics', 'Biology'],
    region: 'midlands', description: 'Study social care with professional placements in residential, community and disability settings.',
    employability: 4, salaryBand: 'low',
  },
  {
    code: 'US850', title: 'Law', institution: 'TUS', level: 8, typicalPoints: 327,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Solicitor', 'Legal Executive', 'Compliance Officer'],
    subjectBonus: ['English', 'History', 'Business'],
    region: 'midlands', description: 'Study law at TUS with practical legal skills and industry placements.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'US924', title: 'Applied Psychology', institution: 'TUS', level: 8, typicalPoints: 424,
    duration: 4, interestTags: ['psychology', 'science'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Psychologist', 'Counsellor', 'Researcher'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'midlands', description: 'Study applied psychology at TUS with research training and work placements.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'US860', title: 'Biotechnology with Biopharmaceutical Science', institution: 'TUS', level: 8, typicalPoints: 408,
    duration: 4, interestTags: ['science', 'healthcare'],
    workStyleTags: ['research-driven', 'analytical', 'structured'],
    careerPaths: ['Biotech Researcher', 'Pharmaceutical Scientist', 'Quality Control'],
    subjectBonus: ['Biology', 'Chemistry', 'Mathematics'],
    region: 'midlands', description: 'Study biotechnology with a focus on biopharmaceutical science and industry placement.',
    employability: 5, salaryBand: 'mid',
  },

  // ── ATU (Atlantic Technological University) ────────────────────────────
  {
    code: 'AU361', title: 'Computer Science', institution: 'ATU', level: 8, typicalPoints: 307,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Developer', 'Web Developer', 'IT Consultant'],
    subjectBonus: ['Mathematics', 'Computer Science'],
    region: 'galway', description: 'Study computing at ATU with industry-focused software projects.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'AU301', title: 'Business', institution: 'ATU', level: 8, typicalPoints: 287,
    duration: 4, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Business Manager', 'HR Officer', 'Marketing Executive'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting'],
    region: 'galway', description: 'Study business at ATU with industry placement and small class sizes.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'AU380', title: 'General Nursing', institution: 'ATU', level: 8, typicalPoints: 340,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Public Health Nurse', 'Nurse Educator'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'galway', description: 'Train as a nurse at ATU with excellent support and clinical placements.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'AU649', title: 'Engineering (Common Entry)', institution: 'ATU', level: 8, typicalPoints: 465,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Civil Engineer', 'Mechanical Engineer', 'Project Manager'],
    subjectBonus: ['Mathematics', 'Physics', 'Construction Studies', 'DCG'],
    region: 'northwest', description: 'Study engineering at ATU with a focus on renewable energy and modern technologies.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'AU310', title: 'LLB (Law)', institution: 'ATU', level: 8, typicalPoints: 326,
    duration: 4, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Solicitor', 'Legal Executive', 'Compliance Officer'],
    subjectBonus: ['English', 'History', 'Business'],
    region: 'galway', description: 'Study law at ATU with practical legal clinics and placements.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'AU662', title: 'Sport & Exercise Science', institution: 'ATU', level: 8, typicalPoints: 400,
    duration: 4, interestTags: ['sport', 'science'],
    workStyleTags: ['hands-on', 'people-focused', 'team-based'],
    careerPaths: ['Sports Scientist', 'Fitness Consultant', 'Performance Analyst'],
    subjectBonus: ['Biology', 'Mathematics', 'Physics'],
    region: 'northwest', description: 'Study sport and exercise science at ATU with practical coaching placements.',
    employability: 3, salaryBand: 'mid',
  },
  {
    code: 'AU696', title: 'Applied Social Care', institution: 'ATU', level: 8, typicalPoints: 310,
    duration: 4, interestTags: ['social-care', 'psychology'],
    workStyleTags: ['people-focused', 'flexible', 'team-based'],
    careerPaths: ['Social Care Worker', 'Youth Worker', 'Family Support Worker'],
    subjectBonus: ['English', 'Home Economics', 'History'],
    region: 'northwest', description: 'Study social care at ATU with community placements and pathways to social work.',
    employability: 3, salaryBand: 'low',
  },
  {
    code: 'AU374', title: 'Physiotherapy', institution: 'ATU', level: 8, typicalPoints: 531,
    duration: 4, interestTags: ['healthcare', 'sport', 'science'],
    workStyleTags: ['hands-on', 'people-focused', 'analytical'],
    careerPaths: ['Physiotherapist', 'Sports Physio', 'Rehabilitation Specialist'],
    subjectBonus: ['Biology', 'Physics', 'Mathematics', 'Chemistry'],
    region: 'galway', description: 'Train as a physiotherapist at ATU with clinical placements across the west.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'AU698', title: 'Psychology', institution: 'ATU', level: 8, typicalPoints: 352,
    duration: 4, interestTags: ['psychology', 'science'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Psychologist', 'Researcher', 'Counsellor'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'northwest', description: 'Study psychology at ATU with research methods training and practical placements.',
    employability: 3, salaryBand: 'mid',
  },

  // ── SETU (South East Technological University) ─────────────────────────
  {
    code: 'SE600', title: 'Computer Science', institution: 'SETU', level: 8, typicalPoints: 309,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Engineer', 'Cybersecurity Specialist', 'Cloud Developer'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'southeast', description: 'Study computing in Waterford\'s growing tech hub with industry work placement.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'SE400', title: 'Business', institution: 'SETU', level: 8, typicalPoints: 273,
    duration: 4, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Business Manager', 'Accountant', 'Financial Advisor'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'southeast', description: 'Study business in the south-east with work placement and professional exam exemptions.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'SE700', title: 'Engineering', institution: 'SETU', level: 8, typicalPoints: 307,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Civil Engineer', 'Manufacturing Engineer', 'Energy Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Construction Studies', 'Engineering'],
    region: 'southeast', description: 'Study engineering in the south-east with practical workshops and industry placement.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'SE500', title: 'Science', institution: 'SETU', level: 8, typicalPoints: 279,
    duration: 4, interestTags: ['science', 'healthcare'],
    workStyleTags: ['research-driven', 'analytical', 'hands-on'],
    careerPaths: ['Pharmaceutical Scientist', 'Lab Analyst', 'Quality Control'],
    subjectBonus: ['Mathematics', 'Biology', 'Chemistry', 'Physics'],
    region: 'southeast', description: 'Study science in Waterford with a focus on pharmaceutical and biomedical science.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'SE915', title: 'General Nursing', institution: 'SETU', level: 8, typicalPoints: 409,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Psychiatric Nurse', 'Nurse Manager'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'southeast', description: 'Train as a nurse in the south-east with clinical placements in UHW and regional hospitals.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'SE917', title: 'Applied Social Studies', institution: 'SETU', level: 8, typicalPoints: 280,
    duration: 4, interestTags: ['social-care', 'psychology'],
    workStyleTags: ['people-focused', 'flexible', 'team-based'],
    careerPaths: ['Social Care Worker', 'Youth Worker', 'Disability Support'],
    subjectBonus: ['English', 'Home Economics', 'Biology'],
    region: 'southeast', description: 'Study social care in Waterford with professional placements each year.',
    employability: 4, salaryBand: 'low',
  },
  {
    code: 'SE502', title: 'Agricultural Science', institution: 'SETU', level: 8, typicalPoints: 381,
    duration: 4, interestTags: ['agriculture', 'environment', 'science'],
    workStyleTags: ['hands-on', 'independent', 'flexible'],
    careerPaths: ['Farm Manager', 'Agricultural Advisor', 'Agri-Business Manager'],
    subjectBonus: ['Ag Science', 'Biology', 'Geography', 'Business'],
    region: 'southeast', description: 'Study agricultural science in the south-east with farm placements.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'SE205', title: 'Psychology', institution: 'SETU', level: 8, typicalPoints: 433,
    duration: 4, interestTags: ['psychology', 'science'],
    workStyleTags: ['research-driven', 'analytical', 'people-focused'],
    careerPaths: ['Psychologist', 'Counsellor', 'Researcher'],
    subjectBonus: ['Mathematics', 'Biology', 'English'],
    region: 'southeast', description: 'Study psychology at SETU with research training and professional placements.',
    employability: 3, salaryBand: 'mid',
  },

  // ── MTU (Munster Technological University) ─────────────────────────────
  {
    code: 'MT800', title: 'Software Development', institution: 'MTU', level: 8, typicalPoints: 442,
    duration: 4, interestTags: ['technology', 'science'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Software Developer', 'Data Engineer', 'Cybersecurity Analyst'],
    subjectBonus: ['Mathematics', 'Computer Science', 'Physics'],
    region: 'southwest', description: 'Study computing at MTU Cork with industry-focused projects and work placement.',
    employability: 5, salaryBand: 'high',
  },
  {
    code: 'MT830', title: 'Engineering (Common Entry)', institution: 'MTU', level: 8, typicalPoints: 487,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'team-based'],
    careerPaths: ['Mechanical Engineer', 'Biomedical Engineer', 'Electrical Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Engineering', 'DCG'],
    region: 'southwest', description: 'Study engineering at MTU with excellent lab facilities and close links to Cork\'s pharma sector.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'MT941', title: 'Business (Common Entry)', institution: 'MTU', level: 8, typicalPoints: 301,
    duration: 4, interestTags: ['business', 'finance'],
    workStyleTags: ['analytical', 'team-based', 'leadership'],
    careerPaths: ['Accountant', 'Business Analyst', 'Marketing Manager'],
    subjectBonus: ['Mathematics', 'Business', 'Accounting', 'Economics'],
    region: 'southwest', description: 'Study business at MTU Cork with professional accounting exemptions and work placement.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'MT926', title: 'General Nursing', institution: 'MTU', level: 8, typicalPoints: 380,
    duration: 4, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Registered Nurse', 'Community Nurse', 'Nurse Educator'],
    subjectBonus: ['Biology', 'Chemistry', 'Home Economics'],
    region: 'southwest', description: 'Train as a nurse in Cork with clinical placements in CUH and Kerry General Hospital.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'MT872', title: 'Pharmaceutical Science', institution: 'MTU', level: 8, typicalPoints: 309,
    duration: 4, interestTags: ['science', 'healthcare'],
    workStyleTags: ['research-driven', 'analytical', 'structured'],
    careerPaths: ['Pharmaceutical Scientist', 'Quality Assurance', 'Regulatory Affairs'],
    subjectBonus: ['Chemistry', 'Biology', 'Mathematics', 'Physics'],
    region: 'southwest', description: 'Study pharmaceutical science at MTU with direct links to Cork\'s biopharma industry.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'MT974', title: 'Social Care', institution: 'MTU', level: 8, typicalPoints: 308,
    duration: 4, interestTags: ['social-care', 'psychology'],
    workStyleTags: ['people-focused', 'flexible', 'team-based'],
    careerPaths: ['Social Care Worker', 'Youth Worker', 'Community Worker'],
    subjectBonus: ['English', 'Home Economics', 'Biology'],
    region: 'southwest', description: 'Study social care at MTU with professional placements in youth, disability and community settings.',
    employability: 4, salaryBand: 'low',
  },
  {
    code: 'MT871', title: 'Biomedical Science', institution: 'MTU', level: 8, typicalPoints: 555,
    duration: 4, interestTags: ['science', 'healthcare'],
    workStyleTags: ['research-driven', 'analytical', 'structured'],
    careerPaths: ['Biomedical Scientist', 'Lab Manager', 'Clinical Researcher'],
    subjectBonus: ['Biology', 'Chemistry', 'Mathematics', 'Physics'],
    region: 'southwest', description: 'Study biomedical science at MTU with clinical laboratory placements.',
    employability: 5, salaryBand: 'mid',
  },
  {
    code: 'MT877', title: 'Agricultural Science', institution: 'MTU', level: 8, typicalPoints: 331,
    duration: 4, interestTags: ['agriculture', 'environment', 'science'],
    workStyleTags: ['hands-on', 'research-driven', 'flexible'],
    careerPaths: ['Agricultural Advisor', 'Farm Manager', 'Agri-Business Manager'],
    subjectBonus: ['Ag Science', 'Biology', 'Chemistry', 'Geography'],
    region: 'southwest', description: 'Study agricultural science at MTU with farm placements across Munster.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'MT845', title: 'Electrical Engineering', institution: 'MTU', level: 8, typicalPoints: 380,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['analytical', 'hands-on', 'structured'],
    careerPaths: ['Electrical Engineer', 'Control Systems Engineer', 'Renewable Energy Engineer'],
    subjectBonus: ['Mathematics', 'Physics', 'Applied Maths', 'Engineering'],
    region: 'southwest', description: 'Study electrical engineering with a focus on energy systems and automation.',
    employability: 5, salaryBand: 'high',
  },

  // ── Level 6/7 Courses (broader access) ────────────────────────────────
  {
    code: 'US720', title: 'Business (Level 7)', institution: 'TUS', level: 7, typicalPoints: 171,
    duration: 3, interestTags: ['business'],
    workStyleTags: ['analytical', 'team-based'],
    careerPaths: ['Office Administrator', 'Sales Representative', 'Retail Manager'],
    subjectBonus: ['Business', 'Mathematics', 'English'],
    region: 'midlands', description: 'A three-year business degree with progression to Level 8.',
    employability: 3, salaryBand: 'low',
  },
  {
    code: 'US773', title: 'Engineering (Level 7)', institution: 'TUS', level: 7, typicalPoints: 223,
    duration: 3, interestTags: ['engineering', 'technology'],
    workStyleTags: ['hands-on', 'analytical'],
    careerPaths: ['Engineering Technician', 'Maintenance Technician', 'CAD Drafter'],
    subjectBonus: ['Mathematics', 'Physics', 'Engineering'],
    region: 'midlands', description: 'A three-year engineering degree with hands-on lab work and progression pathways.',
    employability: 4, salaryBand: 'low',
  },
  {
    code: 'AU200', title: 'Business (Level 7)', institution: 'ATU', level: 7, typicalPoints: 178,
    duration: 3, interestTags: ['business'],
    workStyleTags: ['analytical', 'team-based'],
    careerPaths: ['Office Manager', 'HR Assistant', 'Customer Service Manager'],
    subjectBonus: ['Business', 'Mathematics', 'English'],
    region: 'northwest', description: 'A three-year business degree with progression to Level 8 in the north-west.',
    employability: 3, salaryBand: 'low',
  },
  {
    code: 'SE609', title: 'Software Development (Level 7)', institution: 'SETU', level: 7, typicalPoints: 244,
    duration: 3, interestTags: ['technology'],
    workStyleTags: ['analytical', 'creative'],
    careerPaths: ['Junior Developer', 'IT Support Specialist', 'Web Developer'],
    subjectBonus: ['Mathematics', 'Computer Science'],
    region: 'southeast', description: 'A three-year software development degree with add-on year to reach Level 8.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'MT736', title: 'Mechanical Engineering (Level 7)', institution: 'MTU', level: 7, typicalPoints: 320,
    duration: 3, interestTags: ['engineering', 'technology'],
    workStyleTags: ['hands-on', 'analytical', 'team-based'],
    careerPaths: ['Engineering Technician', 'CAD Designer', 'Production Supervisor'],
    subjectBonus: ['Mathematics', 'Physics', 'Engineering'],
    region: 'southwest', description: 'A three-year engineering degree with pathways to add on a Level 8 year.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'AU190', title: 'Early Childhood Education (Level 7)', institution: 'ATU', level: 7, typicalPoints: 163,
    duration: 3, interestTags: ['education', 'social-care'],
    workStyleTags: ['people-focused', 'creative', 'flexible'],
    careerPaths: ['Early Years Educator', 'Creche Manager', 'SNA'],
    subjectBonus: ['English', 'Irish', 'Home Economics', 'Art'],
    region: 'galway', description: 'Train in early childhood care and education with professional placements in early years settings.',
    employability: 4, salaryBand: 'low',
  },
  {
    code: 'MT573', title: 'Social Care Work (Level 7)', institution: 'MTU', level: 7, typicalPoints: 290,
    duration: 3, interestTags: ['social-care', 'psychology'],
    workStyleTags: ['people-focused', 'flexible', 'team-based'],
    careerPaths: ['Social Care Worker', 'Family Support Worker', 'Disability Services'],
    subjectBonus: ['English', 'Home Economics', 'Biology'],
    region: 'southwest', description: 'Study social care at MTU with professional placements in community and residential settings.',
    employability: 4, salaryBand: 'low',
  },
  {
    code: 'US738', title: 'Veterinary Nursing (Level 7)', institution: 'TUS', level: 7, typicalPoints: 430,
    duration: 3, interestTags: ['agriculture', 'science', 'healthcare'],
    workStyleTags: ['hands-on', 'people-focused', 'structured'],
    careerPaths: ['Veterinary Nurse', 'Animal Welfare Officer', 'Pet Nutrition Advisor'],
    subjectBonus: ['Biology', 'Ag Science', 'Chemistry'],
    region: 'midlands', description: 'Train as a veterinary nurse with extensive placements in veterinary practices across Ireland.',
    employability: 4, salaryBand: 'low',
  },
  {
    code: 'MT541', title: 'Business (Level 7)', institution: 'MTU', level: 7, typicalPoints: 250,
    duration: 3, interestTags: ['business'],
    workStyleTags: ['analytical', 'team-based'],
    careerPaths: ['Business Administrator', 'Sales Manager', 'Office Manager'],
    subjectBonus: ['Business', 'Mathematics', 'English'],
    region: 'southwest', description: 'A three-year business degree at MTU with progression to Level 8.',
    employability: 3, salaryBand: 'low',
  },
  {
    code: 'SE508', title: 'Agriculture (Level 7)', institution: 'SETU', level: 7, typicalPoints: 315,
    duration: 3, interestTags: ['agriculture', 'environment', 'science'],
    workStyleTags: ['hands-on', 'independent', 'flexible'],
    careerPaths: ['Farm Manager', 'Agricultural Advisor', 'Agri-Business Manager'],
    subjectBonus: ['Ag Science', 'Biology', 'Geography', 'Business'],
    region: 'southeast', description: 'Study agriculture in the south-east with farm placements and agri-business modules.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'AU261', title: 'Computing (Level 7)', institution: 'ATU', level: 7, typicalPoints: 243,
    duration: 3, interestTags: ['technology'],
    workStyleTags: ['analytical', 'creative'],
    careerPaths: ['Junior Developer', 'IT Support', 'Web Developer'],
    subjectBonus: ['Mathematics', 'Computer Science'],
    region: 'galway', description: 'A three-year computing degree at ATU with add-on year to Level 8.',
    employability: 4, salaryBand: 'mid',
  },
  {
    code: 'MT703', title: 'Computing (Level 7)', institution: 'MTU', level: 7, typicalPoints: 250,
    duration: 3, interestTags: ['technology'],
    workStyleTags: ['analytical', 'creative'],
    careerPaths: ['Junior Developer', 'IT Support Specialist', 'Network Technician'],
    subjectBonus: ['Mathematics', 'Computer Science'],
    region: 'southwest', description: 'A three-year computing degree at MTU with progression to Level 8.',
    employability: 4, salaryBand: 'mid',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PLC COURSES (Level 5 — QQI)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    code: 'PLC-NUR', title: 'Pre-Nursing Studies', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'structured', 'hands-on'],
    careerPaths: ['Nurse (via degree progression)', 'Healthcare Assistant', 'Midwife (via progression)'],
    subjectBonus: ['Biology', 'Home Economics'],
    region: 'dublin', description: 'A one-year QQI Level 5 course providing a pathway to nursing degrees. Includes anatomy, care skills, and clinical placement.',
    employability: 4, salaryBand: 'mid', pathwayType: 'plc',
  },
  {
    code: 'PLC-BUS', title: 'Business Studies', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['business', 'finance'],
    workStyleTags: ['structured', 'analytical', 'leadership'],
    careerPaths: ['Office Administrator', 'Business Degree (via progression)', 'Accounts Clerk'],
    subjectBonus: ['Business', 'Accounting', 'Economics'],
    region: 'dublin', description: 'A one-year business course with QQI Level 5 certification. Covers bookkeeping, communications, marketing, and work experience.',
    employability: 3, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-ART', title: 'Art, Craft & Design', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['design', 'arts'],
    workStyleTags: ['creative', 'hands-on', 'independent'],
    careerPaths: ['Art College (via portfolio + QQI)', 'Graphic Designer', 'Craft Maker'],
    subjectBonus: ['Art', 'DCG'],
    region: 'dublin', description: 'A portfolio preparation and foundation course for students aiming to progress to art and design degrees. Includes drawing, painting, sculpture, and digital design.',
    employability: 3, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-IT', title: 'Computer Science & IT', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['technology'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['IT Support', 'Computing Degree (via progression)', 'Junior Developer'],
    subjectBonus: ['Computer Science', 'Mathematics'],
    region: 'cork', description: 'A one-year computing course covering programming basics, networking, databases, and web development. Strong progression to IT degrees.',
    employability: 4, salaryBand: 'mid', pathwayType: 'plc',
  },
  {
    code: 'PLC-MEDIA', title: 'Media & Film Production', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['media', 'arts', 'design'],
    workStyleTags: ['creative', 'flexible', 'hands-on'],
    careerPaths: ['Media Degree (via progression)', 'Video Editor', 'Content Creator'],
    subjectBonus: ['English', 'Art'],
    region: 'dublin', description: 'A one-year course in video production, journalism, digital media, and communications. Includes practical projects and industry placements.',
    employability: 3, salaryBand: 'mid', pathwayType: 'plc',
  },
  {
    code: 'PLC-SPORT', title: 'Sports Studies & Exercise Science', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['sport', 'healthcare'],
    workStyleTags: ['hands-on', 'people-focused', 'flexible'],
    careerPaths: ['Fitness Instructor', 'Sports Science Degree (via progression)', 'Coach'],
    subjectBonus: ['Biology', 'Physics'],
    region: 'limerick', description: 'A one-year course covering anatomy, exercise science, coaching, and nutrition. Pathway to sports science and physiotherapy degrees.',
    employability: 3, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-CHILD', title: 'Early Childhood Care & Education', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['education', 'social-care', 'psychology'],
    workStyleTags: ['people-focused', 'creative', 'structured'],
    careerPaths: ['Childcare Worker', 'Early Years Educator', 'Education Degree (via progression)'],
    subjectBonus: ['Home Economics', 'Biology'],
    region: 'galway', description: 'A one-year course preparing students for careers in childcare and early education. Includes child development, play-based learning, and supervised placement.',
    employability: 4, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-HEALTH', title: 'Healthcare Support', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['healthcare', 'social-care'],
    workStyleTags: ['people-focused', 'hands-on', 'structured'],
    careerPaths: ['Healthcare Assistant', 'Nursing Degree (via progression)', 'Home Care Worker'],
    subjectBonus: ['Biology', 'Home Economics'],
    region: 'cork', description: 'A one-year course providing skills for healthcare support roles. Covers patient care, infection control, and clinical practice.',
    employability: 5, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-LAW', title: 'Legal Studies', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['law', 'politics'],
    workStyleTags: ['analytical', 'structured', 'research-driven'],
    careerPaths: ['Law Degree (via progression)', 'Legal Secretary', 'Court Clerk'],
    subjectBonus: ['English', 'History'],
    region: 'dublin', description: 'A one-year introduction to Irish and EU law. Covers criminal law, contract law, constitutional law, and legal research skills.',
    employability: 3, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-PSYCH', title: 'Applied Psychology', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['psychology', 'social-care', 'healthcare'],
    workStyleTags: ['people-focused', 'research-driven', 'analytical'],
    careerPaths: ['Psychology Degree (via progression)', 'Youth Worker', 'Community Support Worker'],
    subjectBonus: ['Biology', 'English'],
    region: 'dublin', description: 'A one-year course introducing psychology concepts. Covers developmental, social, and abnormal psychology with research methods.',
    employability: 3, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-ANIMAL', title: 'Animal Care & Management', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['agriculture', 'science', 'environment'],
    workStyleTags: ['hands-on', 'flexible', 'independent'],
    careerPaths: ['Veterinary Nursing (via progression)', 'Animal Care Worker', 'Kennel Manager'],
    subjectBonus: ['Biology', 'Ag Science'],
    region: 'midlands', description: 'A one-year course covering animal husbandry, welfare, nutrition, and handling. Includes practical placement at veterinary clinics or farms.',
    employability: 3, salaryBand: 'low', pathwayType: 'plc',
  },
  {
    code: 'PLC-HOSP', title: 'Hospitality & Tourism', institution: 'PLC', level: 5, typicalPoints: 0,
    duration: 1, interestTags: ['food', 'business'],
    workStyleTags: ['people-focused', 'flexible', 'hands-on'],
    careerPaths: ['Hotel Receptionist', 'Restaurant Manager', 'Tourism Degree (via progression)'],
    subjectBonus: ['Home Economics', 'Business', 'French'],
    region: 'galway', description: 'A one-year course in hospitality operations, customer service, food safety, and tourism. Includes industry work experience.',
    employability: 4, salaryBand: 'low', pathwayType: 'plc',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // APPRENTICESHIPS (SOLAS / Generation Apprenticeship)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    code: 'APP-ELEC', title: 'Electrical Apprenticeship', institution: 'SOLAS', level: 6, typicalPoints: 0,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['hands-on', 'structured', 'analytical'],
    careerPaths: ['Electrician', 'Electrical Contractor', 'Maintenance Technician'],
    subjectBonus: ['Mathematics', 'Physics', 'Construction Studies'],
    region: 'dublin', description: 'A 4-year earn-while-you-learn apprenticeship combining on-the-job training with off-the-job phases at ETB training centres and institutes of technology.',
    employability: 5, salaryBand: 'mid', pathwayType: 'apprenticeship',
  },
  {
    code: 'APP-PLUMB', title: 'Plumbing Apprenticeship', institution: 'SOLAS', level: 6, typicalPoints: 0,
    duration: 4, interestTags: ['engineering'],
    workStyleTags: ['hands-on', 'structured', 'independent'],
    careerPaths: ['Plumber', 'Plumbing Contractor', 'Gas Installer'],
    subjectBonus: ['Mathematics', 'Construction Studies', 'Physics'],
    region: 'cork', description: 'A 4-year apprenticeship learning pipework, heating systems, and water services. Combines paid employment with training centre phases.',
    employability: 5, salaryBand: 'mid', pathwayType: 'apprenticeship',
  },
  {
    code: 'APP-CARP', title: 'Carpentry & Joinery Apprenticeship', institution: 'SOLAS', level: 6, typicalPoints: 0,
    duration: 4, interestTags: ['engineering', 'design'],
    workStyleTags: ['hands-on', 'creative', 'independent'],
    careerPaths: ['Carpenter', 'Furniture Maker', 'Site Foreman'],
    subjectBonus: ['Construction Studies', 'DCG', 'Mathematics'],
    region: 'limerick', description: 'A 4-year apprenticeship in construction carpentry and joinery. Learn on active building sites while attending off-the-job training phases.',
    employability: 5, salaryBand: 'mid', pathwayType: 'apprenticeship',
  },
  {
    code: 'APP-MOTOR', title: 'Motor Mechanic Apprenticeship', institution: 'SOLAS', level: 6, typicalPoints: 0,
    duration: 4, interestTags: ['engineering', 'technology'],
    workStyleTags: ['hands-on', 'analytical', 'structured'],
    careerPaths: ['Motor Mechanic', 'Workshop Manager', 'Vehicle Inspector'],
    subjectBonus: ['Physics', 'Mathematics', 'Engineering'],
    region: 'dublin', description: 'A 4-year apprenticeship covering engine systems, diagnostics, and vehicle repair. Earn while you learn with a registered employer.',
    employability: 5, salaryBand: 'mid', pathwayType: 'apprenticeship',
  },
  {
    code: 'APP-SWDEV', title: 'Software Developer Apprenticeship', institution: 'SOLAS', level: 6, typicalPoints: 0,
    duration: 2, interestTags: ['technology'],
    workStyleTags: ['analytical', 'creative', 'independent'],
    careerPaths: ['Junior Software Developer', 'Full-Stack Developer', 'DevOps Engineer'],
    subjectBonus: ['Computer Science', 'Mathematics'],
    region: 'dublin', description: 'A 2-year Generation Apprenticeship combining paid employment at a tech company with off-the-job learning. Covers programming, databases, and software engineering.',
    employability: 5, salaryBand: 'high', pathwayType: 'apprenticeship',
  },
  {
    code: 'APP-ACCT', title: 'Accounting Technician Apprenticeship', institution: 'SOLAS', level: 6, typicalPoints: 0,
    duration: 2, interestTags: ['finance', 'business'],
    workStyleTags: ['analytical', 'structured', 'independent'],
    careerPaths: ['Accounting Technician', 'Bookkeeper', 'Payroll Administrator'],
    subjectBonus: ['Accounting', 'Mathematics', 'Business'],
    region: 'dublin', description: 'A 2-year apprenticeship working in an accounting practice while studying for ATI qualifications. Earn a salary from day one.',
    employability: 5, salaryBand: 'mid', pathwayType: 'apprenticeship',
  },
  {
    code: 'APP-CHEF', title: 'Commis Chef Apprenticeship', institution: 'SOLAS', level: 6, typicalPoints: 0,
    duration: 2, interestTags: ['food'],
    workStyleTags: ['hands-on', 'creative', 'flexible'],
    careerPaths: ['Chef', 'Head Chef', 'Restaurant Owner'],
    subjectBonus: ['Home Economics'],
    region: 'galway', description: 'A 2-year apprenticeship training in professional kitchens. Learn food preparation, menu planning, and kitchen management while earning a wage.',
    employability: 4, salaryBand: 'mid', pathwayType: 'apprenticeship',
  },
  {
    code: 'APP-INSUR', title: 'Insurance Practice Apprenticeship', institution: 'SOLAS', level: 8, typicalPoints: 0,
    duration: 3, interestTags: ['finance', 'business'],
    workStyleTags: ['analytical', 'structured', 'people-focused'],
    careerPaths: ['Insurance Underwriter', 'Claims Manager', 'Risk Analyst'],
    subjectBonus: ['Business', 'Mathematics', 'Economics'],
    region: 'dublin', description: 'A 3-year earn-and-learn degree apprenticeship in insurance. Work at an insurance company while studying for a Level 8 degree.',
    employability: 5, salaryBand: 'high', pathwayType: 'apprenticeship',
  },
];

// ─── Lookup Helpers ─────────────────────────────────────────────────────────

export function getCourseByCode(code: string): CAOCourse | undefined {
  return CAO_COURSES.find(c => c.code === code);
}

export function hydrateCourses(codes: string[]): CAOCourse[] {
  return codes
    .map(code => getCourseByCode(code))
    .filter((c): c is CAOCourse => c !== undefined);
}

// ─── Course Page URLs ──────────────────────────────────────────────────────

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

export function getCoursePageUrl(course: CAOCourse): string {
  const code = course.code.toLowerCase();
  const slug = slugify(course.title);
  const institution = INSTITUTIONS[course.institution] || course.institution;

  switch (course.institution) {
    // CAO code in URL — verified working
    case 'UCC': return `https://www.ucc.ie/en/${code}/`;
    case 'MTU': return `https://www.mtu.ie/courses/${code}/`;
    case 'TUS': return `https://tus.ie/courses/${code}/`;

    // Title slug in URL — verified working
    case 'TCD': return `https://www.tcd.ie/courses/undergraduate/courses/${slug}/`;
    case 'UL': return `https://www.ul.ie/courses/${slug}`;
    case 'RCSI': return `https://www.rcsi.com/dublin/undergraduate/${slug}`;

    // Title slug + CAO code in URL — verified working
    case 'TU Dublin': return `https://www.tudublin.ie/study/undergraduate/courses/${slug}-${code}/`;

    // PLC / Apprenticeship portals
    case 'PLC': return `https://www.qualifax.ie/`;
    case 'SOLAS': return `https://www.apprenticeship.ie/`;
    case 'ETB': return `https://www.etbi.ie/`;

    // All others: DuckDuckGo auto-redirect to first result
    default:
      return `https://duckduckgo.com/?q=${encodeURIComponent(`\\ ${course.code} ${course.title} ${institution} undergraduate`)}`;
  }
}
