/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Future Finder — RIASEC + work-values coding for the CAO courses.
 *
 * Generated 2026-06-03 by MULTI-RATER coding: 3 independent rater agents coded
 * each course's Holland RIASEC code + top work-values from the field / O*NET
 * destination-occupation codes, reconciled by position-weighted consensus
 * (1st letter weight 3, 2nd 2, 3rd 1, summed across raters; top non-zero letters
 * = riasecCode; the 6 summed weights = riasecProfile, used for Pearson matching).
 *
 * Inter-rater agreement: lead-letter all-3 agree 142 (95%); >=2 agree
 * 149 (100%); exact 3-letter 87 (58%); mean pairwise Iachan
 * congruence 0.973/1.0. The 149-course OUTCOME SET is
 * unchanged — this is metadata keyed by course code. A human guidance-counsellor
 * ratification pass is the recommended final 10% (see redesign plan).
 */
import { type CourseRiasec } from './futureFinderRiasec';

export const COURSE_RIASEC: Record<string, CourseRiasec> = {
  "DN201": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["achievement","independence","working-conditions"] },
  "DN150": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","recognition"] },
  "DN230": { riasecCode: "CIE", riasecProfile: {"R":0,"I":6,"A":0,"S":0,"E":3,"C":9}, workValues: ["achievement","recognition","working-conditions"] },
  "DN200": { riasecCode: "IRA", riasecProfile: {"R":6,"I":9,"A":2,"S":0,"E":0,"C":1}, workValues: ["achievement","independence","working-conditions"] },
  "DN100": { riasecCode: "AIR", riasecProfile: {"R":3,"I":6,"A":9,"S":0,"E":0,"C":0}, workValues: ["achievement","independence","recognition"] },
  "DN520": { riasecCode: "AIS", riasecProfile: {"R":0,"I":4,"A":9,"S":4,"E":1,"C":0}, workValues: ["independence","achievement","relationships"] },
  "DN700": { riasecCode: "SIE", riasecProfile: {"R":0,"I":6,"A":1,"S":9,"E":2,"C":0}, workValues: ["relationships","achievement","independence"] },
  "DN450": { riasecCode: "SIR", riasecProfile: {"R":3,"I":6,"A":0,"S":9,"E":0,"C":0}, workValues: ["relationships","support","working-conditions"] },
  "DN300": { riasecCode: "IRS", riasecProfile: {"R":6,"I":9,"A":0,"S":3,"E":0,"C":0}, workValues: ["achievement","recognition","independence"] },
  "DN250": { riasecCode: "RIE", riasecProfile: {"R":8,"I":7,"A":0,"S":0,"E":3,"C":0}, workValues: ["achievement","independence","working-conditions"] },
  "DN650": { riasecCode: "ECI", riasecProfile: {"R":0,"I":3,"A":0,"S":0,"E":9,"C":6}, workValues: ["achievement","recognition","relationships"] },
  "DN610": { riasecCode: "EIC", riasecProfile: {"R":0,"I":6,"A":0,"S":0,"E":9,"C":3}, workValues: ["achievement","recognition","independence"] },
  "DN600": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":3,"E":9,"C":0}, workValues: ["achievement","recognition","independence"] },
  "DN420": { riasecCode: "SIR", riasecProfile: {"R":3,"I":6,"A":0,"S":9,"E":0,"C":0}, workValues: ["relationships","achievement","independence"] },
  "DN720": { riasecCode: "ISA", riasecProfile: {"R":0,"I":9,"A":3,"S":6,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "DN670": { riasecCode: "ICE", riasecProfile: {"R":0,"I":9,"A":0,"S":0,"E":3,"C":6}, workValues: ["achievement","recognition","independence"] },
  "TR033": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["achievement","independence","working-conditions"] },
  "TR004": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":3,"E":9,"C":0}, workValues: ["achievement","recognition","independence"] },
  "TR032": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","recognition"] },
  "TR081": { riasecCode: "EIC", riasecProfile: {"R":0,"I":6,"A":0,"S":0,"E":9,"C":3}, workValues: ["achievement","recognition","independence"] },
  "TR060": { riasecCode: "IRA", riasecProfile: {"R":6,"I":9,"A":2,"S":0,"E":0,"C":1}, workValues: ["achievement","independence","working-conditions"] },
  "TR003": { riasecCode: "IAE", riasecProfile: {"R":0,"I":9,"A":6,"S":0,"E":3,"C":0}, workValues: ["independence","achievement","recognition"] },
  "TR052": { riasecCode: "ISR", riasecProfile: {"R":3,"I":9,"A":0,"S":6,"E":0,"C":0}, workValues: ["achievement","recognition","independence"] },
  "TR006": { riasecCode: "ISA", riasecProfile: {"R":0,"I":9,"A":3,"S":6,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "TR031": { riasecCode: "ICR", riasecProfile: {"R":3,"I":9,"A":0,"S":0,"E":0,"C":6}, workValues: ["achievement","independence","recognition"] },
  "CK401": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["achievement","independence","working-conditions"] },
  "CK600": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","recognition"] },
  "CK101": { riasecCode: "AIS", riasecProfile: {"R":0,"I":4,"A":9,"S":4,"E":1,"C":0}, workValues: ["independence","achievement","relationships"] },
  "CK201": { riasecCode: "ECI", riasecProfile: {"R":0,"I":3,"A":0,"S":0,"E":9,"C":6}, workValues: ["achievement","recognition","relationships"] },
  "CK301": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":3,"E":9,"C":0}, workValues: ["achievement","recognition","independence"] },
  "CK710": { riasecCode: "SIR", riasecProfile: {"R":3,"I":4,"A":0,"S":9,"E":0,"C":2}, workValues: ["relationships","achievement","support"] },
  "CK102": { riasecCode: "SIE", riasecProfile: {"R":0,"I":6,"A":0,"S":9,"E":3,"C":0}, workValues: ["relationships","achievement","independence"] },
  "CK120": { riasecCode: "ISA", riasecProfile: {"R":0,"I":9,"A":3,"S":6,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "CK703": { riasecCode: "ICS", riasecProfile: {"R":0,"I":9,"A":0,"S":3,"E":0,"C":6}, workValues: ["achievement","recognition","relationships"] },
  "CK702": { riasecCode: "ISR", riasecProfile: {"R":4,"I":9,"A":0,"S":5,"E":0,"C":0}, workValues: ["achievement","recognition","independence"] },
  "CK412": { riasecCode: "RIE", riasecProfile: {"R":8,"I":7,"A":0,"S":0,"E":3,"C":0}, workValues: ["independence","achievement","working-conditions"] },
  "CK204": { riasecCode: "CIE", riasecProfile: {"R":0,"I":5,"A":0,"S":0,"E":4,"C":9}, workValues: ["achievement","recognition","working-conditions"] },
  "GY301": { riasecCode: "IRA", riasecProfile: {"R":6,"I":9,"A":3,"S":0,"E":0,"C":0}, workValues: ["achievement","independence","working-conditions"] },
  "GY350": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","independence","working-conditions"] },
  "GY101": { riasecCode: "AIS", riasecProfile: {"R":0,"I":6,"A":9,"S":3,"E":0,"C":0}, workValues: ["independence","achievement","recognition"] },
  "GY201": { riasecCode: "CEI", riasecProfile: {"R":0,"I":3,"A":0,"S":0,"E":6,"C":9}, workValues: ["achievement","recognition","working-conditions"] },
  "GY401": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","independence"] },
  "GY251": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":3,"E":9,"C":0}, workValues: ["achievement","recognition","independence"] },
  "GY515": { riasecCode: "SIR", riasecProfile: {"R":3,"I":4,"A":0,"S":9,"E":0,"C":2}, workValues: ["relationships","achievement","support"] },
  "LM121": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","independence","working-conditions"] },
  "LM116": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","independence"] },
  "LM002": { riasecCode: "AIS", riasecProfile: {"R":0,"I":6,"A":9,"S":2,"E":1,"C":0}, workValues: ["independence","achievement","recognition"] },
  "LM050": { riasecCode: "ECI", riasecProfile: {"R":0,"I":3,"A":0,"S":0,"E":9,"C":6}, workValues: ["achievement","recognition","independence"] },
  "LM020": { riasecCode: "ECI", riasecProfile: {"R":0,"I":3,"A":0,"S":0,"E":8,"C":7}, workValues: ["achievement","recognition","working-conditions"] },
  "LM090": { riasecCode: "SRE", riasecProfile: {"R":6,"I":0,"A":0,"S":9,"E":3,"C":0}, workValues: ["relationships","achievement","support"] },
  "LM150": { riasecCode: "SIR", riasecProfile: {"R":3,"I":4,"A":0,"S":9,"E":0,"C":2}, workValues: ["relationships","achievement","support"] },
  "LM058": { riasecCode: "ICR", riasecProfile: {"R":2,"I":9,"A":0,"S":0,"E":1,"C":6}, workValues: ["achievement","recognition","independence"] },
  "DC121": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","independence","working-conditions"] },
  "DC200": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","independence"] },
  "DC002": { riasecCode: "SAE", riasecProfile: {"R":0,"I":0,"A":6,"S":9,"E":3,"C":0}, workValues: ["relationships","achievement","support"] },
  "DC111": { riasecCode: "ECI", riasecProfile: {"R":0,"I":3,"A":0,"S":0,"E":9,"C":6}, workValues: ["achievement","recognition","independence"] },
  "DC132": { riasecCode: "AES", riasecProfile: {"R":0,"I":0,"A":9,"S":3,"E":6,"C":0}, workValues: ["independence","recognition","achievement"] },
  "DC131": { riasecCode: "AES", riasecProfile: {"R":0,"I":0,"A":9,"S":3,"E":6,"C":0}, workValues: ["relationships","recognition","independence"] },
  "DC208": { riasecCode: "ISA", riasecProfile: {"R":0,"I":9,"A":3,"S":6,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "DC215": { riasecCode: "SIR", riasecProfile: {"R":3,"I":4,"A":0,"S":9,"E":0,"C":2}, workValues: ["relationships","achievement","support"] },
  "DC232": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":3,"E":9,"C":0}, workValues: ["achievement","recognition","independence"] },
  "DC123": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["achievement","independence","working-conditions"] },
  "DC202": { riasecCode: "IRS", riasecProfile: {"R":6,"I":9,"A":0,"S":3,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "MH601": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","independence","working-conditions"] },
  "MH101": { riasecCode: "ASE", riasecProfile: {"R":0,"I":0,"A":9,"S":6,"E":3,"C":0}, workValues: ["independence","achievement","recognition"] },
  "MH201": { riasecCode: "IRS", riasecProfile: {"R":6,"I":9,"A":0,"S":3,"E":0,"C":0}, workValues: ["achievement","independence","relationships"] },
  "MH304": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","independence"] },
  "MH501": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":3,"E":9,"C":0}, workValues: ["achievement","recognition","independence"] },
  "MH001": { riasecCode: "SAE", riasecProfile: {"R":0,"I":0,"A":6,"S":9,"E":3,"C":0}, workValues: ["relationships","achievement","support"] },
  "MH209": { riasecCode: "ISA", riasecProfile: {"R":0,"I":9,"A":3,"S":6,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "MH107": { riasecCode: "SIE", riasecProfile: {"R":0,"I":6,"A":0,"S":9,"E":3,"C":0}, workValues: ["relationships","achievement","support"] },
  "MH401": { riasecCode: "CIE", riasecProfile: {"R":0,"I":6,"A":0,"S":0,"E":3,"C":9}, workValues: ["achievement","recognition","working-conditions"] },
  "RC005": { riasecCode: "ICS", riasecProfile: {"R":0,"I":9,"A":0,"S":3,"E":0,"C":6}, workValues: ["achievement","working-conditions","recognition"] },
  "RC004": { riasecCode: "SIR", riasecProfile: {"R":3,"I":6,"A":0,"S":9,"E":0,"C":0}, workValues: ["relationships","achievement","independence"] },
  "RC007": { riasecCode: "IRS", riasecProfile: {"R":5,"I":9,"A":0,"S":4,"E":0,"C":0}, workValues: ["achievement","recognition","independence"] },
  "TU856": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","independence","working-conditions"] },
  "TU805": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","independence"] },
  "TU903": { riasecCode: "ECS", riasecProfile: {"R":0,"I":0,"A":0,"S":3,"E":9,"C":6}, workValues: ["achievement","recognition","relationships"] },
  "TU918": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":3,"E":9,"C":0}, workValues: ["achievement","recognition","independence"] },
  "TU854": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","independence","working-conditions"] },
  "TU850": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["achievement","independence","working-conditions"] },
  "TU936": { riasecCode: "IRS", riasecProfile: {"R":6,"I":9,"A":0,"S":3,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "TU910": { riasecCode: "CEI", riasecProfile: {"R":0,"I":3,"A":0,"S":0,"E":6,"C":9}, workValues: ["achievement","working-conditions","recognition"] },
  "US822": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","independence","working-conditions"] },
  "US840": { riasecCode: "ECS", riasecProfile: {"R":0,"I":1,"A":0,"S":2,"E":9,"C":6}, workValues: ["achievement","recognition","working-conditions"] },
  "US887": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":1,"C":2}, workValues: ["achievement","working-conditions","independence"] },
  "US877": { riasecCode: "SIR", riasecProfile: {"R":3,"I":6,"A":0,"S":9,"E":0,"C":0}, workValues: ["relationships","support","achievement"] },
  "US920": { riasecCode: "SEC", riasecProfile: {"R":0,"I":0,"A":0,"S":9,"E":6,"C":3}, workValues: ["relationships","support","achievement"] },
  "US850": { riasecCode: "EIC", riasecProfile: {"R":0,"I":6,"A":0,"S":0,"E":9,"C":3}, workValues: ["achievement","recognition","working-conditions"] },
  "US924": { riasecCode: "ISA", riasecProfile: {"R":0,"I":8,"A":3,"S":7,"E":0,"C":0}, workValues: ["relationships","achievement","independence"] },
  "US860": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","support","working-conditions"] },
  "AU361": { riasecCode: "ICR", riasecProfile: {"R":4,"I":9,"A":0,"S":0,"E":0,"C":5}, workValues: ["achievement","independence","working-conditions"] },
  "AU301": { riasecCode: "EC", riasecProfile: {"R":0,"I":0,"A":0,"S":0,"E":9,"C":6}, workValues: ["achievement","recognition","relationships"] },
  "AU380": { riasecCode: "SIR", riasecProfile: {"R":3,"I":6,"A":0,"S":9,"E":0,"C":0}, workValues: ["relationships","support","achievement"] },
  "AU649": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":1,"C":2}, workValues: ["achievement","working-conditions","independence"] },
  "AU310": { riasecCode: "EIS", riasecProfile: {"R":0,"I":6,"A":0,"S":2,"E":9,"C":1}, workValues: ["achievement","recognition","independence"] },
  "AU662": { riasecCode: "RIS", riasecProfile: {"R":7,"I":7,"A":0,"S":4,"E":0,"C":0}, workValues: ["achievement","relationships","working-conditions"] },
  "AU696": { riasecCode: "SEC", riasecProfile: {"R":0,"I":0,"A":0,"S":9,"E":6,"C":3}, workValues: ["relationships","support","achievement"] },
  "AU374": { riasecCode: "SIR", riasecProfile: {"R":4,"I":5,"A":0,"S":9,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "AU698": { riasecCode: "ISA", riasecProfile: {"R":0,"I":9,"A":3,"S":6,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "SE600": { riasecCode: "ICR", riasecProfile: {"R":4,"I":9,"A":0,"S":0,"E":0,"C":5}, workValues: ["achievement","independence","working-conditions"] },
  "SE400": { riasecCode: "EC", riasecProfile: {"R":0,"I":0,"A":0,"S":0,"E":9,"C":6}, workValues: ["achievement","recognition","relationships"] },
  "SE700": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":1,"C":2}, workValues: ["achievement","working-conditions","independence"] },
  "SE500": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","support","working-conditions"] },
  "SE915": { riasecCode: "SIR", riasecProfile: {"R":3,"I":6,"A":0,"S":9,"E":0,"C":0}, workValues: ["relationships","support","achievement"] },
  "SE917": { riasecCode: "SEC", riasecProfile: {"R":0,"I":0,"A":0,"S":9,"E":6,"C":3}, workValues: ["relationships","support","achievement"] },
  "SE502": { riasecCode: "RIE", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":3,"C":0}, workValues: ["independence","working-conditions","achievement"] },
  "SE205": { riasecCode: "ISA", riasecProfile: {"R":0,"I":9,"A":3,"S":6,"E":0,"C":0}, workValues: ["achievement","relationships","independence"] },
  "MT800": { riasecCode: "ICR", riasecProfile: {"R":4,"I":9,"A":0,"S":0,"E":0,"C":5}, workValues: ["achievement","independence","working-conditions"] },
  "MT830": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":1,"C":2}, workValues: ["achievement","working-conditions","independence"] },
  "MT941": { riasecCode: "ECI", riasecProfile: {"R":0,"I":2,"A":0,"S":0,"E":9,"C":6}, workValues: ["achievement","recognition","working-conditions"] },
  "MT926": { riasecCode: "SIR", riasecProfile: {"R":3,"I":6,"A":0,"S":9,"E":0,"C":0}, workValues: ["relationships","support","achievement"] },
  "MT872": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["achievement","support","working-conditions"] },
  "MT974": { riasecCode: "SEC", riasecProfile: {"R":0,"I":0,"A":0,"S":9,"E":6,"C":3}, workValues: ["relationships","support","achievement"] },
  "MT871": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["achievement","working-conditions","support"] },
  "MT877": { riasecCode: "RIE", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":3,"C":0}, workValues: ["independence","working-conditions","achievement"] },
  "MT845": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":1,"C":2}, workValues: ["achievement","working-conditions","independence"] },
  "US720": { riasecCode: "ECS", riasecProfile: {"R":0,"I":0,"A":0,"S":1,"E":8,"C":7}, workValues: ["working-conditions","relationships","support"] },
  "US773": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["working-conditions","achievement","support"] },
  "AU200": { riasecCode: "ECS", riasecProfile: {"R":0,"I":0,"A":0,"S":1,"E":8,"C":7}, workValues: ["working-conditions","relationships","support"] },
  "SE609": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["independence","achievement","working-conditions"] },
  "MT736": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["working-conditions","achievement","independence"] },
  "AU190": { riasecCode: "SAE", riasecProfile: {"R":0,"I":0,"A":6,"S":9,"E":1,"C":1}, workValues: ["relationships","support","working-conditions"] },
  "MT573": { riasecCode: "SEC", riasecProfile: {"R":0,"I":0,"A":0,"S":9,"E":4,"C":2}, workValues: ["relationships","achievement","support"] },
  "US738": { riasecCode: "RSI", riasecProfile: {"R":9,"I":3,"A":0,"S":6,"E":0,"C":0}, workValues: ["relationships","working-conditions","support"] },
  "MT541": { riasecCode: "ECS", riasecProfile: {"R":0,"I":0,"A":0,"S":1,"E":9,"C":6}, workValues: ["relationships","achievement","working-conditions"] },
  "SE508": { riasecCode: "REI", riasecProfile: {"R":9,"I":3,"A":0,"S":0,"E":5,"C":1}, workValues: ["independence","working-conditions","achievement"] },
  "AU261": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["independence","achievement","working-conditions"] },
  "MT703": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["independence","achievement","working-conditions"] },
  "PLC-NUR": { riasecCode: "SRI", riasecProfile: {"R":5,"I":2,"A":0,"S":9,"E":0,"C":2}, workValues: ["relationships","support","working-conditions"] },
  "PLC-BUS": { riasecCode: "CES", riasecProfile: {"R":0,"I":0,"A":0,"S":1,"E":6,"C":9}, workValues: ["working-conditions","support","achievement"] },
  "PLC-ART": { riasecCode: "ARE", riasecProfile: {"R":6,"I":0,"A":9,"S":0,"E":1,"C":1}, workValues: ["independence","achievement","recognition"] },
  "PLC-IT": { riasecCode: "IRC", riasecProfile: {"R":5,"I":9,"A":0,"S":0,"E":0,"C":4}, workValues: ["independence","achievement","working-conditions"] },
  "PLC-MEDIA": { riasecCode: "AER", riasecProfile: {"R":2,"I":0,"A":9,"S":0,"E":6,"C":0}, workValues: ["independence","achievement","recognition"] },
  "PLC-SPORT": { riasecCode: "SRE", riasecProfile: {"R":6,"I":0,"A":0,"S":9,"E":2,"C":0}, workValues: ["relationships","achievement","working-conditions"] },
  "PLC-CHILD": { riasecCode: "SAE", riasecProfile: {"R":0,"I":0,"A":6,"S":9,"E":1,"C":1}, workValues: ["relationships","support","working-conditions"] },
  "PLC-HEALTH": { riasecCode: "SRC", riasecProfile: {"R":6,"I":0,"A":0,"S":9,"E":0,"C":2}, workValues: ["relationships","support","working-conditions"] },
  "PLC-LAW": { riasecCode: "CEI", riasecProfile: {"R":0,"I":1,"A":0,"S":1,"E":6,"C":9}, workValues: ["working-conditions","achievement","support"] },
  "PLC-PSYCH": { riasecCode: "SIA", riasecProfile: {"R":0,"I":6,"A":2,"S":9,"E":0,"C":0}, workValues: ["relationships","achievement","support"] },
  "PLC-ANIMAL": { riasecCode: "RSI", riasecProfile: {"R":9,"I":3,"A":0,"S":5,"E":0,"C":0}, workValues: ["independence","working-conditions","relationships"] },
  "PLC-HOSP": { riasecCode: "ESC", riasecProfile: {"R":0,"I":0,"A":0,"S":6,"E":9,"C":3}, workValues: ["relationships","working-conditions","recognition"] },
  "APP-ELEC": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":3}, workValues: ["working-conditions","independence","achievement"] },
  "APP-PLUMB": { riasecCode: "RIC", riasecProfile: {"R":9,"I":5,"A":0,"S":0,"E":0,"C":4}, workValues: ["independence","working-conditions","achievement"] },
  "APP-CARP": { riasecCode: "RAC", riasecProfile: {"R":9,"I":0,"A":6,"S":0,"E":0,"C":2}, workValues: ["independence","achievement","working-conditions"] },
  "APP-MOTOR": { riasecCode: "RIC", riasecProfile: {"R":9,"I":6,"A":0,"S":0,"E":0,"C":2}, workValues: ["working-conditions","independence","achievement"] },
  "APP-SWDEV": { riasecCode: "IRC", riasecProfile: {"R":6,"I":9,"A":0,"S":0,"E":0,"C":3}, workValues: ["independence","achievement","working-conditions"] },
  "APP-ACCT": { riasecCode: "CEI", riasecProfile: {"R":0,"I":2,"A":0,"S":0,"E":6,"C":9}, workValues: ["working-conditions","achievement","support"] },
  "APP-CHEF": { riasecCode: "RAE", riasecProfile: {"R":9,"I":0,"A":5,"S":0,"E":4,"C":0}, workValues: ["working-conditions","achievement","relationships"] },
  "APP-INSUR": { riasecCode: "CEI", riasecProfile: {"R":0,"I":2,"A":0,"S":1,"E":6,"C":9}, workValues: ["working-conditions","achievement","recognition"] },
};
