/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * A hand-lettered note in the character's own line that writes itself:
 * 'you are here' beside the rail, 'join with your school's code' beside the
 * sign-up link, 'the end' on the footer line. The lettering is a single
 * stroke path generated by scripts/landing/lettering.mjs; this component
 * decides how it is written:
 *   scroll   — CSS view() timeline (falls back to `timed` where unsupported)
 *   timed    — once, when it scrolls into view (for notes inside sticky boxes,
 *              where a view timeline would never move)
 *   progress — driven by a MotionValue 0…1 (the footer's reveal)
 * Under reduced motion or ?static=1 the note is simply printed. The words
 * come from copy.ts as an aria-label; the SVG itself is hidden from AT.
 */

import React, { useEffect, useMemo, useRef } from 'react';
import { useInView, type MotionValue } from 'framer-motion';
import { useReducedMotion } from '../../Motion';
import { COPY } from '../copy';
import { isStatic, supportsScrollTimeline } from './env';
import here from './notes/here.svg?raw';
import join from './notes/join.svg?raw';
import end from './notes/end.svg?raw';

export type NoteId = 'here' | 'join' | 'end';
const SVG: Record<NoteId, string> = { here, join, end };

export const Note: React.FC<{
  id: NoteId;
  mode?: 'scroll' | 'timed' | 'progress';
  progress?: MotionValue<number>;
  /** Progress at which the last stroke lands (progress mode). */
  from?: number;
  to?: number;
  className?: string;
  style?: React.CSSProperties;
}> = ({ id, mode = 'scroll', progress, from = 0, to = 1, className = '', style }) => {
  const ref = useRef<HTMLSpanElement>(null);
  const reduce = useReducedMotion();
  const seen = useInView(ref, { once: true, margin: '-12% 0px' as never });
  const still = reduce || isStatic();
  // One object for the life of the note: a fresh { __html } each render makes React re-set innerHTML,
  // which would throw away the dash offset written below and replay a timed stroke.
  const html = useMemo(() => ({ __html: SVG[id] }), [id]);
  const resolved = mode === 'scroll' && !supportsScrollTimeline() ? 'timed' : mode;

  // Progress mode: write the dash offset straight from the MotionValue, no React state.
  useEffect(() => {
    if (still || resolved !== 'progress' || !progress) return;
    const el = ref.current;
    if (!el) return;
    const ink = el.querySelector<SVGPathElement>('.fx-note-ink');
    const star = el.querySelector<SVGPathElement>('.fx-note-star');
    const apply = (v: number) => {
      const t = Math.min(1, Math.max(0, (v - from) / (to - from)));
      if (ink) ink.style.strokeDashoffset = String(1 - t);
      if (star) star.style.opacity = t > 0.97 ? '1' : '0';
    };
    apply(progress.get());
    return progress.on('change', apply);
  }, [still, resolved, progress, from, to]);

  const cls = ['fx-note', className];
  if (!still) {
    cls.push('fx-note--armed');
    if (resolved === 'scroll') cls.push('fx-note--scroll');
    if (resolved === 'timed') { cls.push('fx-note--timed'); if (seen) cls.push('fx-note--go'); }
  }
  return (
    <span
      ref={ref}
      role="img"
      aria-label={COPY.fx.notes[id]}
      className={cls.join(' ')}
      style={style}
      dangerouslySetInnerHTML={html}
    />
  );
};

export default Note;
