const original=new URLSearchParams(location.search).get('style')||'window';let style=original,frame=0,playing=false;const portal=document.querySelector('.portal'),inner=document.querySelector('.portal-inner'),edge=document.querySelector('.edge'),outline=document.querySelector('.draw-frame'),rect=outline.querySelector('rect'),range=document.getElementById('progress'),percent=document.getElementById('percent'),reduce=document.getElementById('reduce'),current=document.getElementById('current');const names={lift:'The paper lift',window:'The rising window',spread:'The opening spread',draw:'The drawn frame',blot:'Current ink blot'};const duration=style==='draw'?1050:800;document.getElementById('motion-name').textContent=names[style];document.getElementById('duration').textContent=(duration/1000)+' seconds';reduce.checked=matchMedia('(prefers-reduced-motion: reduce)').matches;
function render(value){const p=reduce.checked?1:Math.min(1,Math.max(0,value));range.value=Math.round(p*100);percent.textContent=Math.round(p*100)+'%';portal.style.transform='none';portal.style.opacity='1';portal.style.clipPath='none';portal.style.maskImage='none';inner.style.transform='none';outline.style.opacity='0';edge.style.opacity='0';if(style==='lift'){portal.style.opacity=Math.min(1,p*1.6);portal.style.transform=`translateY(${(1-p)*(innerWidth<480?12:24)}px)`}if(style==='window'){portal.style.clipPath=`inset(${(1-p)*100}% 0 0 0 round 13px)`;inner.style.transform=`translateY(${(1-p)*100}%)`}if(style==='spread'){portal.style.clipPath=`inset(0 ${(1-p)*50}% 0 ${(1-p)*50}% round 13px)`;edge.style.opacity=String(Math.max(0,1-p*2))}if(style==='draw'){outline.style.opacity=String(p<.78?1:Math.max(0,(1-p)/.22));rect.style.strokeDashoffset=String(100-Math.min(100,p/.65*100));const f=Math.max(0,(p-.45)/.55);portal.style.opacity=String(f);portal.style.transform=`translateY(${(1-f)*8}px)`}if(style==='blot'){portal.style.maskImage="url('assets/blot.png')";portal.style.maskRepeat='no-repeat';portal.style.maskPosition='center';portal.style.maskSize=`${p*280}% ${p*280}%`}}
function stop(){cancelAnimationFrame(frame);playing=false}function play(){stop();if(reduce.checked){render(1);document.getElementById('status').textContent='Reduced motion: the complete portal appears immediately.';return}playing=true;let start;function tick(now){if(!start)start=now;let p=Math.min(1,(now-start)/(style==='draw'?1050:800));render(1-Math.pow(1-p,3));if(p<1)frame=requestAnimationFrame(tick);else{playing=false;document.getElementById('status').textContent='Finished. Replay, or drag to inspect any moment.'}}document.getElementById('status').textContent='Playing '+names[style].toLowerCase()+'.';frame=requestAnimationFrame(tick)}range.oninput=()=>{stop();if(reduce.checked){reduce.checked=false}render(Number(range.value)/100);document.getElementById('status').textContent='Paused at '+range.value+'% of the reveal.'};document.getElementById('replay').onclick=play;reduce.onchange=()=>{stop();render(1);document.getElementById('status').textContent=reduce.checked?'Reduced motion: the complete portal appears immediately.':'Motion enabled. Press replay.'};current.onclick=()=>{style=style==='blot'?original:'blot';current.textContent=style==='blot'?'Back to '+names[original]:'Compare current blot';current.setAttribute('aria-pressed',style==='blot');document.getElementById('motion-name').textContent=names[style];play()};render(1);

const scrollTrial=document.getElementById('scroll-trial');scrollTrial.href='motion.html?style='+original+'&scroll=1';
if(new URLSearchParams(location.search).get('scroll')==='1'){
 document.body.classList.add('scroll-study');
 document.querySelector('main').insertAdjacentHTML('beforebegin',`<nav class="scroll-nav"><a href="index.html#reveals">← Back to the board</a><label>Reveal <select id="scroll-style">${Object.entries(names).map(([id,label])=>`<option value="${id}" ${id===style?'selected':''}>${id==='blot'?'Current':({lift:'R01',window:'R02',spread:'R03',draw:'R04'})[id]} · ${label}</option>`).join('')}</select></label><span>Review only</span></nav><section class="scroll-intro"><p class="eyebrow">Nextstepuni · motion study</p><h2>Scroll to open<br>the chapter.</h2><p>Let the frame arrive as you move down the page.<br>Use the menu above to compare a different reveal.</p><div class="scroll-cue">SCROLL TO TRY IT <span>↓</span></div></section>`);
 document.querySelector('main').insertAdjacentHTML('afterend','<section class="scroll-outro"><p class="eyebrow">The reveal is complete</p><h2>Now let the content<br>do the talking.</h2><p>Scroll back up to see the transition in reverse.</p><a href="index.html#reveals">Back to all four directions ↗</a></section>');
 document.getElementById('scroll-style').onchange=e=>{style=e.target.value;document.getElementById('motion-name').textContent=names[style];paintScroll()};
 document.querySelector('.scene-head').insertAdjacentHTML('afterend','<div class="scroll-context"><p class="eyebrow">I · Mark Bank</p><h2>Answer the real question.<br>See where the marks come from.</h2><p>A page from the app, opening with the scroll.</p></div>');
 const paintScroll=()=>{const top=document.querySelector('.stage').getBoundingClientRect().top;const p=(innerHeight*.88-top)/(innerHeight*.67);render(Math.max(0,Math.min(1,p)))};
 addEventListener('scroll',paintScroll,{passive:true});addEventListener('resize',paintScroll);requestAnimationFrame(paintScroll);
}
