/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Engineering cards, Ordinary Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/engineering/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the headings of the Engineering syllabus, section 2 Materials and Technology.
 * The written paper sets nine questions of 50 marks at Higher and seven at Ordinary; candidates answer six and four.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "engineering",
  specVersion: "lc-engineering-materials-and-technology",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q3-c", topicId: "eng-2-6", conceptId: "safety-precautions-be-observed-during-heat",
    section: "A", questionRef: "2021 OL Q3(c)",
    stem: "point cutting edge",
    questionText: "State two safety precautions to be observed during the heat treatment of metals.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "Wear heat resistant gloves when preforming heat treatment of metals.", marks: 8, accepts: ["Do not leave hot metals lying around in case people accidently pick up the piece."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q3-d", topicId: "eng-3-8", conceptId: "malleability-or-advantages-robotics-manufacturing",
    section: "A", questionRef: "2021 OL Q3(d)",
    stem: "Engineering ‐ Ordinary level 4",
    questionText: "Explain any two of the following terms: (i) Malleability, OR State two advantages of robotics in manufacturing. (ii) Compressive strength, OR State two ways in which the use of robotic technology can improve the safety of a work environment. (iii) Ductility, (iv) Tensile strength.",
    tariffModel: {"kind":"fixed"}, totalMarks: 12,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "The ability of a material to be hammered and/or formed without breaking.", marks: 12, accepts: ["Robotic technology can reduce the number of injuries associated with lifting heavy objects. Robotics can also be used to reduce the need for workers to lift or carry heavy objects.","A material is said to be ductile when it can be permanently stretched, without fracture. It must be plastic enough to allow deformation and strong enough not to fracture. A metal must be ductile to enable it to be stretched / drawn into wire.","The ability of a material to withstand being pulled apart or stretched.","Robotics offer precision placement of components in manufacturing.","Robotics offer precision when performing manufacturing processes such as welding & paint spraying."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q4-a-ii", topicId: "eng-2-10", conceptId: "steps-necessary-ensure-successful-soft-soldered",
    section: "A", questionRef: "2021 OL Q4(a)(ii)",
    stem: ". (50 marks)",
    questionText: "Describe two steps necessary to ensure a successful soft soldered joint.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "The surfaces to be joined must be perfectly clean and coated with flux.", marks: 6, accepts: ["A good flow of heat to the joint is essential. Before applying the solder, the joint must be brought to the temperature at which the solder melts."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q4-d", topicId: "eng-2-10", conceptId: "safety-precautions-be-observed-when-using",
    section: "A", questionRef: "2021 OL Q4(d)",
    stem: "Engineering ‐ Ordinary level 5",
    questionText: "State two safety precautions to be observed when using an electrical soldering iron.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Avoid leaving a hot soldering iron on a desk after use.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q5-a-ii", topicId: "eng-2-13", conceptId: "aid-diagram-any-manufacturing-processes-named",
    section: "A", questionRef: "2021 OL Q5(a)(ii)",
    stem: ". (50 marks)",
    questionText: "Describe, with the aid of a diagram, any one of the manufacturing processes named by you at Q5(a)(i) above.",
    tariffModel: {"kind":"fixed"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "A thermoplastic sheet is clamped in a frame and heat is applied until the sheet begins to sag. At this stage, the mould is lifted up into the plastic sheet and vacuum pressure is applied. This causes the plastic sheet to pull against the mold and form the final shape. After cooling, the mould is lowered and the plastic part is removed from the frame. Excess material is trimmed away.", marks: 10, accepts: ["Heater Plunger Mould Molten plastic Injection nozzle Thermoplastic is softened by heating it inside an injection nozzle. The softened plastic is forced by a plunger into a cold mould where it hardens rapidly and is then ejected. Injection molding is used for the rapid molding of components.","Air Parison Split mould Plastic bottle Used to produce articles from a heated thermoplastic tube called a parison.","The mould closes around the extruded parison and air is blow inside forcing the parison out against the wall of the mould. The article is moulded by the internal shape of a split mould. The component is allowed to cool before being removed from the opened mould."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q5-d", topicId: "eng-2-10", conceptId: "safety-precautions-be-observed-when-using",
    section: "A", questionRef: "2021 OL Q5(d)",
    stem: "Engineering ‐ Ordinary level 6",
    questionText: "State two safety precautions to be observed when using an adhesive to bond acrylic.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Always work in a well-ventilated area.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q2-d-i", topicId: "eng-2-15", conceptId: "advantage-using-belt-pulley-mechanism-drive",
    section: "A", questionRef: "2022 OL Q2(d)(i)",
    stem: "roll cage seat wheel rim belt and pulley mechanism Engineering - Ordinary level 3",
    questionText: "State one advantage of using a belt and pulley mechanism in a drive system.",
    tariffModel: {"kind":"fixed"}, totalMarks: 4,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "lubrication. Easier to assemble compared to gear drive systems.", marks: 4 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q4-d", topicId: "eng-2-10", conceptId: "safety-precautions-be-observed-when-gas",
    section: "A", questionRef: "2022 OL Q4(d)",
    stem: "Engineering - Ordinary level 5",
    questionText: "State two safety precautions to be observed when gas welding.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Check the hoses for any damage before you start welding.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q5-d", topicId: "eng-1-9", conceptId: "safety-precautions-be-observed-when-working",
    section: "A", questionRef: "2022 OL Q5(d)",
    stem: "seat belts dashboard number plate door handles headlights Engineering - Ordinary level 6",
    questionText: "List two safety precautions to be observed when working with hot plastics.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Do not leave pieces of hot plastic unattended on the bench / work area.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2023 Ordinary Level — © State Examinations Commission.",
    id: "eng-2023-ol-q3-b-i", topicId: "eng-2-6", conceptId: "effect-does-hardening-have-steel",
    section: "A", questionRef: "2023 OL Q3(b)(i)",
    stem: ". (50 marks)",
    questionText: "What effect does hardening have on steel?",
    tariffModel: {"kind":"fixed"}, totalMarks: 7,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Hardening increases the hardness of steel resulting in the steel retaining its cutting edge.", marks: 7 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2023 Ordinary Level — © State Examinations Commission.",
    id: "eng-2023-ol-q3-b-ii", topicId: "eng-2-6", conceptId: "tempering-process",
    section: "A", questionRef: "2023 OL Q3(b)(ii)",
    stem: ". (50 marks)",
    questionText: "Describe the tempering process.",
    tariffModel: {"kind":"fixed"}, totalMarks: 7,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Tempering removes some of the hardness while increasing the toughness of a metal. It is achieved by heating the metal to a specific temperature which is determined by the colour of the metal. On heating, colours appear and when the correct colour is achieved i.e., light straw appears at approx. 250° - 350°, it is quenched in cold water.", marks: 7 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2023 Ordinary Level — © State Examinations Commission.",
    id: "eng-2023-ol-q3-d-i", topicId: "eng-3-8", conceptId: "toughness-areas-where-robotic-technology-used",
    section: "A", questionRef: "2023 OL Q3(d)(i)",
    stem: "exoskeleton suit",
    questionText: "Toughness, Describe two areas where robotic technology is used in health care.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Roving robots in emergency rooms can support the evaluation of patients by connecting with a remote specialist who can converse with them, review their records and examine patients with special cameras.", marks: 6 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2023 Ordinary Level — © State Examinations Commission.",
    id: "eng-2023-ol-q3-d-ii", topicId: "eng-3-8", conceptId: "ductility-ways-exoskeleton-suits-can-help",
    section: "A", questionRef: "2023 OL Q3(d)(ii)",
    stem: "exoskeleton suit",
    questionText: "Ductility, State two ways in which exoskeleton suits can help the recovery process.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Exoskeleton suits can help people with spinal cord injuries gain some mobility, helping to improve cardiovascular health, slow the loss of fat tissue, build lean muscle mass, improve bowel function, and aid in pain management", marks: 6 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2023 Ordinary Level — © State Examinations Commission.",
    id: "eng-2023-ol-q4-d", topicId: "eng-2-10", conceptId: "safety-precautions-be-observed-when-working",
    section: "A", questionRef: "2023 OL Q4(d)",
    stem: ". (50 marks)",
    questionText: "State two safety precautions to be observed when working with adhesives.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Wear suitable gloves to avoid the adhesives coming in contact with your skin.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2023 Ordinary Level — © State Examinations Commission.",
    id: "eng-2023-ol-q7-c-i", topicId: "eng-2-16", conceptId: "use-solenoid",
    section: "A", questionRef: "2023 OL Q7(c)(i)",
    stem: "short leg long leg colour bands Leaving Certificate 2023 Engineering – Ordinary level 8",
    questionText: "State one use of a solenoid.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "diameter of round bars or the internal diameter of holes. The measurement can be read directly from a digital display.", marks: 6, accepts: ["to convert electrical energy into mechanical work. It can be used to open and close pneumatic valves / turn on or off an electrical switch / operate as a locking mechanism….","Plunger moves in and out."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2024 Ordinary Level — © State Examinations Commission.",
    id: "eng-2024-ol-q2-d-i", topicId: "eng-2-10", conceptId: "advantage-using-temporary-joining-process",
    section: "A", questionRef: "2024 OL Q2(d)(i)",
    stem: "weight plates seat frame leg press weight machine coupling",
    questionText: "State one advantage of using a temporary joining process.",
    tariffModel: {"kind":"fixed"}, totalMarks: 4,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Component parts can be easily dismantled if there is repair work required or new parts to be replaced.", marks: 4 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q6-c-ii", topicId: "eng-2-13", conceptId: "any-processes-named-you-q6-c",
    section: "A", questionRef: "2025 OL Q6(c)(ii)",
    stem: "stunt bike pegs",
    questionText: "Describe any one of the processes named by you, at Q6(c)(i) above. OR Name one CNC machine commonly used in the engineering workshop.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "used in the engineering workshop.", marks: 6 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q6-c-iii", topicId: "eng-2-11", conceptId: "specify-any-items-personal-protective-equipment",
    section: "A", questionRef: "2025 OL Q6(c)(iii)",
    stem: "stunt bike pegs",
    questionText: "Specify any two items of personal protective equipment (PPE) that should be worn when operating a centre lathe. OR Give two advantages of using CNC machines.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Wear goggles.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q7-c-i", topicId: "eng-2-16", conceptId: "advantage-using-printed-circuit-board-pcb",
    section: "A", questionRef: "2025 OL Q7(c)(i)",
    stem: "microchip",
    questionText: "State one advantage of using a Printed Circuit Board (PCB) for the assembly of circuits.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "Used for accurately measuring the diameter of round bars or internal diameters of holes.", marks: 6, accepts: ["Quicker to assemble and ensures better circuit operation when • complete."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q7-c-ii", topicId: "eng-2-16", conceptId: "examples-where-printed-circuit-board-pcb",
    section: "A", questionRef: "2025 OL Q7(c)(ii)",
    stem: "microchip",
    questionText: "Give two examples where a Printed Circuit Board (PCB) may be used.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Used to check the diameter of twist drills.", marks: 6 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q7-c-iii", topicId: "eng-2-16", conceptId: "term-microchip",
    section: "A", questionRef: "2025 OL Q7(c)(iii)",
    stem: "microchip",
    questionText: "Explain the term microchip.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "Micrometers are specially designed for the measurement of very small objects. They allow for the highly precise measurement of any item that fits between the anvil and spindle.", marks: 6, accepts: ["A microchip is an integrated circuit (IC) containing a set of micro‐ electronic circuits made up of transistors, resistors and capacitors and their interconnectors etched onto small pieces of semiconductor material."] },
    ],
  } as SecCard,
];
