/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Engineering cards, Ordinary Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/engineering/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the headings of the Engineering syllabus, section 2 Materials and Technology.
 * The written paper sets nine questions of 50 marks at Higher and seven at Ordinary; candidates answer six and four.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "engineering",
  specVersion: "lc-engineering-materials-and-technology",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q4-d", topicId: "eng-2-10", conceptId: "safety-precautions-be-observed-when-gas",
    section: "A", questionRef: "2022 OL Q4(d)",
    stem: "Engineering - Ordinary level 5",
    questionText: "State two safety precautions to be observed when gas welding.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Check the hoses for any damage before you start welding.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q6-c", topicId: "eng-2-11", conceptId: "any-other-processes-can-be-carried",
    section: "A", questionRef: "2022 OL Q6(c)",
    stem: "Engineering - Ordinary level 7",
    questionText: "A lathe process is shown opposite. Laser cutting is an important CNC (Computer Numerical Controlled) manufacturing process. List any three advantages of using a laser cutter to cut out the shapes shown.",
    tariffModel: {"kind":"fixed"}, totalMarks: 15,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "The laser cutter can cut with high precision. Total (15) Marks", marks: 15, accepts: ["Can process components that would be considered very complicated.","Check that the tool tip is in line with the centre of the workpiece.","Align the tool tip outside of the line where you require to cut.","Select a suitable cutting speed and direction and turn on the lathe.","Engage the tool tip into the turning workpiece and cut in a continuous motion.","Facing off / parallel turning / taper during / knurling / drilling. OR"] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q6-c-ii", topicId: "eng-2-13", conceptId: "any-processes-named-you-q6-c",
    section: "A", questionRef: "2025 OL Q6(c)(ii)",
    stem: "stunt bike pegs",
    questionText: "Describe any one of the processes named by you, at Q6(c)(i) above. Name one CNC machine commonly used in the engineering workshop.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "used in the engineering workshop.", marks: 6 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q6-c-iii", topicId: "eng-2-11", conceptId: "specify-any-items-personal-protective-equipment",
    section: "A", questionRef: "2025 OL Q6(c)(iii)",
    stem: "stunt bike pegs",
    questionText: "Specify any two items of personal protective equipment (PPE) that should be worn when operating a centre lathe. Give two advantages of using CNC machines.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Wear goggles.", marks: 8 },
    ],
  } as SecCard,
];
