/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Engineering cards, Ordinary Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/engineering/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the headings of the Engineering syllabus, section 2 Materials and Technology.
 * The written paper sets nine questions of 50 marks at Higher and seven at Ordinary; candidates answer six and four.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "engineering",
  specVersion: "lc-engineering-materials-and-technology",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q5-a-ii", topicId: "eng-1-9", conceptId: "aid-diagram-any-manufacturing-processes-named",
    section: "A", questionRef: "2021 OL Q5(a)(ii)",
    stem: ". (50 marks)",
    questionText: "Describe, with the aid of a diagram, any one of the manufacturing processes named by you at Q5(a)(i) above.",
    tariffModel: {"kind":"fixed"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "A - Vacuum forming:", marks: 10, accepts: ["A thermoplastic sheet is clamped in a frame and heat is applied until the sheet begins to sag. At this stage, the mould is lifted up into the plastic sheet and vacuum pressure is applied. This causes the plastic sheet to pull against the mold and form the final shape. After cooling, the mould is lowered and the plastic part is removed from the frame. Excess material is trimmed away.","Heater Plunger Mould Molten plastic Injection nozzle Thermoplastic is softened by heating it inside an injection nozzle. The softened plastic is forced by a plunger into a cold mould where it hardens rapidly and is then ejected. Injection molding is used for the rapid molding of components.","Air Parison Split mould Plastic bottle Used to produce articles from a heated thermoplastic tube called a parison.","The mould closes around the extruded parison and air is blow inside forcing the parison out against the wall of the mould. The article is moulded by the internal shape of a split mould. The component is allowed to cool before being removed from the opened mould."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2021 Ordinary Level — © State Examinations Commission.",
    id: "eng-2021-ol-q7-c-ii", topicId: "eng-3-12", conceptId: "draw-electronic-symbol-each-electronic-component",
    section: "A", questionRef: "2021 OL Q7(c)(ii)",
    stem: "Hole: Ø30 ± 0.06 mm Shaft: Ø30 ± 0.08 mm Engineering ‐ Ordinary level 8 Engineering ‐ Ordinary level 8",
    questionText: "Draw the electronic symbol for each electronic component named.",
    tariffModel: {"kind":"fixed"}, totalMarks: 5,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "of round bars or internal diameters of holes.", marks: 5, accepts: ["Measurement can be read directly from a digital display.","Motor:","Switch:"] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q2-d-i", topicId: "eng-2-15", conceptId: "advantage-using-belt-pulley-mechanism-drive",
    section: "A", questionRef: "2022 OL Q2(d)(i)",
    stem: "roll cage seat wheel rim belt and pulley mechanism Engineering - Ordinary level 3",
    questionText: "State one advantage of using a belt and pulley mechanism in a drive system.",
    tariffModel: {"kind":"fixed"}, totalMarks: 4,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "lubrication. Easier to assemble compared to gear drive systems.", marks: 4 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q4-d", topicId: "eng-2-10", conceptId: "safety-precautions-be-observed-when-gas",
    section: "A", questionRef: "2022 OL Q4(d)",
    stem: "Engineering - Ordinary level 5",
    questionText: "State two safety precautions to be observed when gas welding.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Check the hoses for any damage before you start welding.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2022 Ordinary Level — © State Examinations Commission.",
    id: "eng-2022-ol-q5-d", topicId: "eng-1-9", conceptId: "safety-precautions-be-observed-when-working",
    section: "A", questionRef: "2022 OL Q5(d)",
    stem: "seat belts dashboard number plate door handles headlights Engineering - Ordinary level 6",
    questionText: "List two safety precautions to be observed when working with hot plastics.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Do not leave pieces of hot plastic unattended on the bench / work area.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2023 Ordinary Level — © State Examinations Commission.",
    id: "eng-2023-ol-q3-b-i", topicId: "eng-2-6", conceptId: "effect-does-hardening-have-steel",
    section: "A", questionRef: "2023 OL Q3(b)(i)",
    stem: ". (50 marks)",
    questionText: "What effect does hardening have on steel?",
    tariffModel: {"kind":"fixed"}, totalMarks: 7,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Hardening increases the hardness of steel resulting in the steel retaining its cutting edge.", marks: 7 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q6-c-ii", topicId: "eng-2-13", conceptId: "any-processes-named-you-q6-c",
    section: "A", questionRef: "2025 OL Q6(c)(ii)",
    stem: "stunt bike pegs",
    questionText: "Describe any one of the processes named by you, at Q6(c)(i) above. Name one CNC machine commonly used in the engineering workshop.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "used in the engineering workshop.", marks: 6 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q6-c-iii", topicId: "eng-2-11", conceptId: "specify-any-items-personal-protective-equipment",
    section: "A", questionRef: "2025 OL Q6(c)(iii)",
    stem: "stunt bike pegs",
    questionText: "Specify any two items of personal protective equipment (PPE) that should be worn when operating a centre lathe. Give two advantages of using CNC machines.",
    tariffModel: {"kind":"fixed"}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Wear goggles.", marks: 8 },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q7-c-i", topicId: "eng-3-12", conceptId: "advantage-using-printed-circuit-board-pcb",
    section: "A", questionRef: "2025 OL Q7(c)(i)",
    stem: "microchip",
    questionText: "State one advantage of using a Printed Circuit Board (PCB) for the assembly of circuits.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "alt", verbatim: "Used for accurately measuring the diameter of round bars or internal diameters of holes.", marks: 6, accepts: ["Quicker to assemble and ensures better circuit operation when • complete."] },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC027GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Engineering 2025 Ordinary Level — © State Examinations Commission.",
    id: "eng-2025-ol-q7-c-ii", topicId: "eng-2-11", conceptId: "examples-where-printed-circuit-board-pcb",
    section: "A", questionRef: "2025 OL Q7(c)(ii)",
    stem: "microchip",
    questionText: "Give two examples where a Printed Circuit Board (PCB) may be used.",
    tariffModel: {"kind":"fixed"}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "Used to check the diameter of twist drills.", marks: 6 },
    ],
  } as SecCard,
];
