/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Economics cards, Higher Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/economics/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the strands of the specification the papers were actually sat
 * under. Economics was first examined on it in 2021, so the whole 2021-2025
 * corpus sits on one syllabus with nothing to straddle.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "economics",
  specVersion: "lc-economics-2019",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2024, level: "higher",
    paperFileid: "LC034ALP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2024 Higher Level — © State Examinations Commission.",
    id: "econ-2024-hl-q11-a-iii", topicId: "economics-4-1", conceptId: "disadvantages-of-tourism",
    section: "B", questionRef: "2024 HL Q11(a)(iii)",
    questionText: "Outline one possible disadvantage of increasing tourism numbers in the Irish economy.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 6","answer":1,"ofParts":5,"perPart":6}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A disadvantage of rising tourism numbers — any one", marks: 6, contextNote: "One disadvantage, 6 marks. The scheme wants the point AND the explanation of it — naming the disadvantage without saying why is not what the marks are for.", openList: true, group: {"claimMax":1,"perOption":6,"options":["Increased pressure on infrastructure/services – increased tourism means that services that are already under pressure in Ireland come under more strain. This can upset local populations who also use these services and can cause unrest.","Increased prices – tourist hotspots are often associated with inflated prices. An example of this can be clearly seen in Temple Bar in Dublin where in response to tourism many businesses have increased prices and as a result locals have faced higher prices for goods/services.","Increased pressure to secure workers – with rising tourism numbers the hospitality sector is under pressure to attract workers and this may also lead to an wage rates increases.","Possible damage to the environment – with increasing numbers damage may be caused to heritage sites and/or the local environment.","Increased littering/pollution – tourist hotspots are often the most littered. An example of this can be clearly seen in beach areas during the summer or areas associated with nightlife."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "higher",
    paperFileid: "LC034ALP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2024 Higher Level — © State Examinations Commission.",
    id: "econ-2024-hl-q11-b-iii", topicId: "economics-3-0", conceptId: "uses-of-national-income-statistics",
    section: "B", questionRef: "2024 HL Q11(b)(iii)",
    questionText: "Outline two uses of the information provided by national income statistics.",
    tariffModel: {"kind":"bestNofParts","notation":"2 @ 4","answer":2,"ofParts":6,"perPart":4}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A use of national income statistics — any two", marks: 8, contextNote: "Two uses, 4 marks each. Each is the use and what it is used FOR; the scheme pairs them.", openList: true, group: {"claimMax":2,"perOption":4,"options":["Indication of alterations to our standard of living - Any change in national income figures will indicate the level of economic growth, or otherwise, within the country from one year to the next, and give a general indication of changes to the standard of living - Used by trade unions to justify wage demands.","A way of comparing the standard of living in different countries - We can use the national income statistics to compare the standard of living in our country with that of other countries.","Help determine EU budget contributions - The national income statistics will determine the contribution, if any, which Ireland must make to the EU budget. The figure will also be used within the EU to determine those countries which require financial aid from the EU and the amount of that aid.","Formulating economic policy / helps government in economic decision making - Governments have a greater influence on the development and growth of the economy. To effectively plan for this governments need information about the economy such as that provided by the National Income statistics.","Evaluating economic policy - Evaluate economic policy to assess changes to the economy and economic changes in the various sectors, and to provide a benchmark against which progress can be monitored, it is useful to have national statistics.","Effective research - They show the distribution of income throughout the country."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "higher",
    paperFileid: "LC034ALP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2024 Higher Level — © State Examinations Commission.",
    id: "econ-2024-hl-q14-a-i", topicId: "economics-2-0", conceptId: "monopolistic-competition-characteristics",
    section: "B", questionRef: "2024 HL Q14(a)(i)",
    questionText: "Outline three characteristics (other than many sellers) of a firm operating in monopolistic competition.",
    tariffModel: {"kind":"bestNofParts","notation":"3 @ 5","answer":3,"ofParts":5,"perPart":5}, totalMarks: 15,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A characteristic of monopolistic competition — any three", marks: 15, contextNote: "Three characteristics, 5 marks each. \"Many sellers\" is excluded by the question — the scheme lists five others, all set in the restaurant market the question describes.", openList: true, group: {"claimMax":3,"perOption":5,"options":["There are many buyers - an individual customer, by their own actions, cannot influence the market price of the food on offer at the restaurant.","Each firm seeks to maximise profits - the aim of each company is to maximise profits, to do this they produce the quantity where MC = MR","Freedom of entry and exit - no barriers to entry exist in the restaurant industry. It is possible for outlets to enter and exit the industry as they wish.","Reasonable knowledge regarding profits - everyone is assumed to have reasonable knowledge as to the profits made by other firms, consumers have reasonable knowledge of the prices being charged.","Product differentiation exists - the foods/ meals on offer from the many restaurants are not identical but may be close substitutes. Firms may use advertising and special offers to attract consumers i.e. Early Bird Special."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "higher",
    paperFileid: "LC034ALP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2024 Higher Level — © State Examinations Commission.",
    id: "econ-2024-hl-q14-b-ii", topicId: "economics-2-0", conceptId: "monopolistic-competition-consumer-advantage",
    section: "B", questionRef: "2024 HL Q14(b)(ii)",
    questionText: "Outline one possible economic advantage to consumers of monopolistic competitive markets.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 5","answer":1,"ofParts":4,"perPart":5}, totalMarks: 5,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An advantage to consumers — any one", marks: 5, contextNote: "One advantage, 5 marks.", openList: true, group: {"claimMax":1,"perOption":5,"options":["Consumers benefit from increased choice - differentiation creates diversity of goods for consumers and they benefit from having more choice / potentially lower prices.","Access to information - as the firms in this industry engage in competitive advertising, it could be argued that consumers have the benefit of access to more information / consumers may have access to brand loyalty bonuses.","Normal profit - as firms earn normal profit in the long run, consumers are less likely to be exploited by higher prices.","Increased quality of services - due to competition, there may be more innovation / competition within the industry. Consumers may as a result benefit from a better quality of service / product."]} },
    ],
  } as SecCard,
];
