/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Economics cards, Ordinary Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/economics/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the strands of the specification the papers were actually sat
 * under. Economics was first examined on it in 2021, so the whole 2021-2025
 * corpus sits on one syllabus with nothing to straddle.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "economics",
  specVersion: "lc-economics-2019",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2021 Ordinary Level — © State Examinations Commission.",
    id: "econ-2021-ol-q11-b-i-neg", topicId: "economics-4-1", conceptId: "disadvantages-of-globalisation",
    section: "B", questionRef: "2021 OL Q11(b)(i) — disadvantages",
    questionText: "Outline two possible disadvantages of globalisation.",
    tariffModel: {"kind":"bestNofParts","notation":"2 @ 3","answer":2,"ofParts":4,"perPart":3}, totalMarks: 6,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A disadvantage of globalisation — any two", marks: 6, contextNote: "Two disadvantages, 3 marks each.", openList: true, group: {"claimMax":2,"perOption":3,"options":["Widens the gap between rich and poor - The biggest drawback is that it is widening the gap between rich and poor - empowers those with specialist skills to charge higher prices","Environmental impact - The connection between economic and environmental problems can be clearly seen in the widespread social and economic impacts on deforestation and air pollution.","Outsourcing - Due to outsourcing, globalisation may deprive an entire country of his jobs and resources","Lower cost countries - Global companies hold a lot of negotiating power over governments and can be highly persuasive in getting them to adjust their policies on wages and taxes."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2021, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2021 Ordinary Level — © State Examinations Commission.",
    id: "econ-2021-ol-q11-b-iii", topicId: "economics-4-1", conceptId: "why-mncs-locate-in-ireland",
    section: "B", questionRef: "2021 OL Q11(b)(iii)",
    questionText: "Outline two reasons why multinational companies choose to locate in Ireland.",
    tariffModel: {"kind":"bestNofParts","notation":"2 @ 7","answer":2,"ofParts":6,"perPart":7}, totalMarks: 14,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A reason MNCs locate in Ireland — any two", marks: 14, contextNote: "Two reasons, 7 marks each, split 3 for the reason and 4 for developing it.", openList: true, group: {"claimMax":2,"perOption":7,"options":["Low rates of taxation: the rate of corporation profits tax in Ireland is one of the lowest within the EU.","Access to EU market / Member of the euro currency: firms which locate in Ireland have access to free movement of their goods within the EU. Ireland is a member of the euro and this makes payment for international transactions within the eurozone much easier and hence more attractive.","Availability of state incentives: firms can avail of attractive grants and other incentives provided by the state e.g. grants towards research and development etc.","Good industrial relations: social partnerships have resulted in relative industrial peace offering firms uninterrupted production.","Stable rate of economic growth: the rate of economic growth in Ireland was one of the more attractive within the EU and this has led to confidence amongst investors, who see Ireland as an attractive market for their goods.","Stable economic climate: by international standards Ireland’s economy is performing exceptionally well. This has increased business confidence which encourages firms to locate here."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2022 Ordinary Level — © State Examinations Commission.",
    id: "econ-2022-ol-q11-a-ii", topicId: "economics-2-0", conceptId: "advantages-of-many-firms-for-consumers",
    section: "B", questionRef: "2022 OL Q11(a)(ii)",
    stem: "Set on a chart of US streaming services by number of users — YouTube highest, Vimeo lowest.",
    questionText: "Outline two advantages for consumers of many firms providing streaming services in this market.",
    tariffModel: {"kind":"fixed","notation":"1 x 8 + 1 x 4","answer":null,"ofParts":null,"perPart":null}, totalMarks: 12,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An advantage to consumers — any two", marks: null, contextNote: "Two advantages, the first paid 8 and the second 4.", openList: true, group: {"claimMax":2,"perOption":8,"options":["Gives the consumer more choice – firms may introduce more choice of content in order to attact consumers.","More competitive prices – firms may reduce their prices to attract new consumers.","Improved quality / range of programming – firms providing the service might provide better service / a wider range of services due to the competition.","Increased innovation – firms may be more innovative in programming / content and consumers will benefit from this."],"perOptionSteps":[8,4]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2022 Ordinary Level — © State Examinations Commission.",
    id: "econ-2022-ol-q11-c-ii", topicId: "economics-2-0", conceptId: "barriers-to-entry",
    section: "B", questionRef: "2022 OL Q11(c)(ii)",
    questionText: "Firms who may wish to enter a monopoly industry face barriers to entry. Outline two possible barriers to entry.",
    tariffModel: {"kind":"bestNofParts","notation":"2 x 4","answer":2,"ofParts":7,"perPart":4}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A barrier to entry — any two", marks: 8, contextNote: "Two barriers, 4 marks each.", openList: true, group: {"claimMax":2,"perOption":4,"options":["The Government may grant a company the sole right to produce a good or supply a service","A patent / copyright will confer the sole right on a business to a particular manufacturing process for a particular commodity.","Firms may enter trade agreements with other suppliers i.e. collude with them so that no other firm can supply the product or service in the market.","A company may acquire the sole right to the available raw materials thereby becoming a monopoly in that particular industry e.g. oil exploration company.","For some industries the capital required to get established in that industry is so large that only the company which can raise the necessary capital can operate in the market.","By merging with a competitor or buying out the competitor a firm may become a monopoly supplier in that industry.","An individual or group of individuals may, by fear, force or threats, stop other individuals competing with the supplier e.g. the supply of illegal drugs."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2022, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2022 Ordinary Level — © State Examinations Commission.",
    id: "econ-2022-ol-q11-c-iii", topicId: "economics-1-3", conceptId: "government-intervention-dominant-firm",
    section: "B", questionRef: "2022 OL Q11(c)(iii)",
    questionText: "Suggest one way governments can intervene in the market if one firm becomes too dominant.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 4","answer":1,"ofParts":2,"perPart":4}, totalMarks: 4,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A way government can intervene — any one", marks: 4, contextNote: "One way, 4 marks.", openList: true, group: {"claimMax":1,"perOption":4,"options":["Regulation: regulators can ensure that dominant firms do not abuse their dominant position by investigating behaviour which may be deemed against the consumer’s interests. Decide the prices which they can charge such as electricity.","Legislation: the government / EU can use laws which make it illegal to engage in anti- competitive or abusive behaviour by companies holding a dominant position. Where a dominant firm is found to be engaged in behaviour against the consumer’s interests they can be fined."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2023 Ordinary Level — © State Examinations Commission.",
    id: "econ-2023-ol-q11-a-i", topicId: "economics-2-0", conceptId: "monopolistic-competition-identified",
    section: "B", questionRef: "2023 OL Q11(a)(i)",
    questionText: "Outline two reasons why, in your opinion, the hair and beauty industries are an example of monopolistic competition.",
    tariffModel: {"kind":"fixed","notation":"1st @ 6 + 2nd @ 4","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A reason it is monopolistic competition — any two", marks: null, contextNote: "Two reasons, the first paid 6 and the second 4.", openList: true, group: {"claimMax":2,"perOption":6,"options":["There are many firms in the industry: each seller can influence their sales.","There are many buyers in the industry: no buyer can influence market price.","The products and services are close substitutes for each other: this allows for extensive advertising.","Firms wish to maximise profits where MC=MR."],"perOptionSteps":[6,4]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2023 Ordinary Level — © State Examinations Commission.",
    id: "econ-2023-ol-q11-a-ii", topicId: "economics-2-0", conceptId: "monopolistic-competition-consumer-advantages",
    section: "B", questionRef: "2023 OL Q11(a)(ii)",
    questionText: "Outline two advantages for consumers of monopolistic competition.",
    tariffModel: {"kind":"fixed","notation":"1st @ 6 + 2nd @ 4","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An advantage to consumers — any two", marks: null, contextNote: "Two advantages, the first paid 6 and the second 4.", openList: true, group: {"claimMax":2,"perOption":6,"options":["Consumers benefit from increased choice.","Due to competition the consumer may benefit from more competitive pricing.","They may also benefit from better quality of service.","As firms earn normal profit in the long run, consumers are less likely to be exploited by higher prices.","Due to competition, there may be more innovation in the industry.","As the firms in this industry engage in competitive advertising, it could be argued that consumers have the benefit of access to more information / consumers may have access to brand loyalty bonuses."],"perOptionSteps":[6,4]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2023 Ordinary Level — © State Examinations Commission.",
    id: "econ-2023-ol-q12-b-ii", topicId: "economics-3-1", conceptId: "principles-of-a-good-tax-system",
    section: "B", questionRef: "2023 OL Q12(b)(ii)",
    questionText: "Explain two other principles of a good tax system that you would consider important in the current economic climate.",
    tariffModel: {"kind":"fixed","notation":"1st @ 8 + 2nd @ 4","answer":null,"ofParts":null,"perPart":null}, totalMarks: 12,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A principle of a good tax system — any two", marks: null, contextNote: "Two principles, the first paid 8 and the second 4. Equity — ability to pay — is excluded by the question.", openList: true, group: {"claimMax":2,"perOption":8,"options":["A good tax system should not be a disincentive to work.","Convenient: It should be easy and convenient to collect the tax.","It should discourage tax evasion.","Certainty: the amount of tax to be paid should be clear or certain.","Economic: The revenue collected should exceed the cost of collection."],"perOptionSteps":[8,4]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2023 Ordinary Level — © State Examinations Commission.",
    id: "econ-2023-ol-q12-c-i", topicId: "economics-1-3", conceptId: "benefit-of-the-electricity-credit",
    section: "B", questionRef: "2023 OL Q12(c)(i)",
    questionText: "Outline one benefit of the €600 electricity credit to the Irish household.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 8","answer":1,"ofParts":5,"perPart":8}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A benefit to the household — any one", marks: 8, contextNote: "One benefit, 8 marks.", openList: true, group: {"claimMax":1,"perOption":8,"options":["It helps Irish households to maintain their standard of living during cost of living crisis.","It reduces the costs of electricity for households in a time of high energy inflation.","It reduces the risk of energy poverty for fixed/low income families.","It may help reduce stress / anxiety for households facing increasing bills.","Helps low income families by providing them with more disposable income."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2023 Ordinary Level — © State Examinations Commission.",
    id: "econ-2023-ol-q12-c-ii", topicId: "economics-0-2", conceptId: "household-actions-to-cut-electricity-use",
    section: "B", questionRef: "2023 OL Q12(c)(ii)",
    questionText: "Describe two actions an Irish household could take to reduce their electricity bills and make them more sustainable.",
    tariffModel: {"kind":"fixed","notation":"1st @ 10 + 2nd @ 4","answer":null,"ofParts":null,"perPart":null}, totalMarks: 14,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An action the household could take — any two", marks: null, contextNote: "Two actions, the first paid 10 and the second 4.", openList: true, group: {"claimMax":2,"perOption":10,"options":["The Irish household could reduce their consumption of electricity: switch off unused appliances.","The Irish household could look at alternative ways of accessing energy e.g. install solar panels.","They could ensure their electrical appliances are more energy efficient: switch to improved energy rating appliances.","They could be more mindful of usage e.g. standby, boiling a full kettle for one cup of tea. Use dishwashers/ washing machines with full loads."],"perOptionSteps":[10,4]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2023, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2023 Ordinary Level — © State Examinations Commission.",
    id: "econ-2023-ol-q13-a-ii", topicId: "economics-4-2", conceptId: "advantages-of-exports",
    section: "B", questionRef: "2023 OL Q13(a)(ii)",
    questionText: "Describe two advantages of exports for the Irish economy.",
    tariffModel: {"kind":"fixed","notation":"1st @ 8 + 2nd @ 2","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An advantage of exports — any two", marks: null, contextNote: "Two advantages, the first paid 8 and the second 2.", openList: true, group: {"claimMax":2,"perOption":8,"options":["Increased national income: exporting goods and services generates money for the Irish economy and leads to an increase in economic growth.","Employment: the demand for Irish goods and services abroad leads to an increase in jobs in the Irish economy.","Government revenue will increase in terms of increase in corporation tax collected and PAYE and VAT collected.","Benefit of economies of scale for the Irish firms exporting abroad. These are the cost savings that will come with increased production to meet the demand for Irish goods and services abroad."],"perOptionSteps":[8,2]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2024 Ordinary Level — © State Examinations Commission.",
    id: "econ-2024-ol-q11-a-ii", topicId: "economics-1-2", conceptId: "effect-of-energy-costs-on-business",
    section: "B", questionRef: "2024 OL Q11(a)(ii)",
    stem: "Set on a chart of Irish electricity price increases from 2020 to 2022.",
    questionText: "Outline one possible economic effect of these price increases on businesses in Ireland.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 8","answer":1,"ofParts":6,"perPart":8}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An economic effect on business — any one", marks: 8, contextNote: "One effect, 8 marks.", openList: true, group: {"claimMax":1,"perOption":8,"options":["Increased costs for business due to higher prices: The higher expenditure on electricity will increase the costs of running a business.","Increased prices for consumers: If the business passes the increased costs on to the consumer this means higher prices for consumers which could lead to a fall in demand for goods and services.","Fall in profits: If consumers face higher prices and demand less of the good or service this would lead to a fall in profit for the business. If the business decides to absorb the increased costs themselves this will lead to a fall in their profit.","Electricity conservation: Higher electricity prices may encourage some businesses to be more conscious of their energy usage and invest in energy-saving appliances or practices to reduce their electricity consumption.","Switching to alternative sources of energy or switching provider: Some businesses might switch to alternative sources of energy, such as natural gas, oil, or renewable energy sources, to mitigate the impact of higher electricity prices.","Reduced competitiveness: Higher electricity prices can make businesses less competitive, as they face higher operating costs. This may lead to reduced production, job losses, or business closures."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2024 Ordinary Level — © State Examinations Commission.",
    id: "econ-2024-ol-q11-a-iii", topicId: "economics-1-3", conceptId: "electricity-credit-rationale",
    section: "B", questionRef: "2024 OL Q11(a)(iii)",
    questionText: "During winter 2023 – 2024, the Irish government granted all households a credit of €450 towards their electricity bills. Why, in your opinion, did the government do this?",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 8","answer":1,"ofParts":6,"perPart":8}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A reason the government granted the credit — any one", marks: 8, contextNote: "One reason, 8 marks. The question asks for an opinion, and the scheme answers it with six the examiner will accept — it is not open-ended.", openList: true, group: {"claimMax":1,"perOption":8,"options":["To alleviate the financial burden/economic welfare of Irish households Higher electricity bills have put a significant financial strain on households. By providing the €450 credit, the government aimed to alleviate some of this burden and help households manage their expenses.","To support low-income families: Higher electricity bills disproportionately affected low-income families, leading to energy poverty. The credit helped ensure these households could maintain basic energy services, such as heating and lighting.","To stimulate the economy: By reducing the financial burden of higher electricity bills, households may have had more disposable income to spend on other goods and services, potentially maintaining Ireland’s economic growth.","To increase consumer confidence: The €450 government credit helped improve consumer confidence, as it showed the government's commitment to addressing higher electricity prices and supporting households.","To maintain social stability: Ever increasing electricity prices could have led to public dissatisfaction and unrest. By providing the credit, the government was able to demonstrate its responsiveness to the public's concerns and maintain social stability.","Buy time for policy adjustments: The government is working on long-term solutions to address higher electricity prices, for example the 2023 Climate Action Plan commits that up to 80% of Ireland’s electricity will be sourced from renewables by 2030. The €450 credit provided short-term relief to households while such longer-term solutions are implemented."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2024, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2024 Ordinary Level — © State Examinations Commission.",
    id: "econ-2024-ol-q11-b-iii", topicId: "economics-2-0", conceptId: "oligopoly-in-ireland",
    section: "B", questionRef: "2024 OL Q11(b)(iii)",
    questionText: "The electricity market is an example of an oligopoly market in Ireland. Give one example of an oligopoly market in Ireland and explain a reason for your choice.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 8","answer":1,"ofParts":4,"perPart":8}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A reason a market is an oligopoly — any one", marks: 8, contextNote: "One reason, 8 marks. The scheme accepts mobile phones, broadband, insurance, banking, TV services or supermarkets as the example; the marks are for the reason.", openList: true, group: {"claimMax":1,"perOption":8,"options":["Only a few providers dominate the market: The market is becoming increasingly concentrated, with the largest providers dominating, e.g. the three largest companies control over 80% of the market.","Barriers to entry exist in the market: The barriers enable such firms to maintain their share of the market, e.g. high start-up costs associated with establishing and maintaining plants /relevant infrastructure / meeting regulatory requirements.","Non-price competition exists in the market: Oligopolistic firms often engage in non-price competition, such as marketing, customer service, and product differentiation. In these markets, firms may compete on factors like green energy offerings, smart metering technology etc.","Interdependence exists between firms: The actions of one firm in these markets can significantly impact the other providers, as there are so few major players. This interdependence can lead to strategic decision-making and potential collusion among the firms, e.g. whenever one provider announced a price increase recently it tended to be followed swiftly by similar increases from competing firms."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2025 Ordinary Level — © State Examinations Commission.",
    id: "econ-2025-ol-q11-b-iii", topicId: "economics-2-0", conceptId: "perfect-competition-consumer-advantage",
    section: "B", questionRef: "2025 OL Q11(b)(iii)",
    questionText: "As a consumer what, in your opinion, is the main advantage of a perfectly competitive market? Explain your answer.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 8","answer":1,"ofParts":3,"perPart":8}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An advantage to the consumer — any one", marks: 8, contextNote: "One advantage, 8 marks. The question asks for an opinion and the scheme answers it with the three the examiner accepts.", openList: true, group: {"claimMax":1,"perOption":8,"options":["Low prices - firms are competitive so must operate at lowest point of AC meaning lowest possible prices for consumers. Consumers are not exploited as they have perfect information.","No Advertising – consumers are not taken advantage of with persuasive advertising.","Efficient use of scarce resources – as each firm produces at the lowest point of average cost."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2025 Ordinary Level — © State Examinations Commission.",
    id: "econ-2025-ol-q11-c-i", topicId: "economics-2-2", conceptId: "dublin-airport-passenger-cap",
    section: "B", questionRef: "2025 OL Q11(c)(i)",
    stem: "Dublin Airport has a cap of 32 million passengers a year, which was exceeded in 2024.",
    questionText: "Outline one reason why, in your opinion, a limit has been placed on the number of passengers who can pass through Dublin Airport.",
    tariffModel: {"kind":"bestNofParts","notation":"1 @ 8","answer":1,"ofParts":3,"perPart":8}, totalMarks: 8,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "A reason for the passenger cap — any one", marks: 8, contextNote: "One reason, 8 marks.", openList: true, group: {"claimMax":1,"perOption":8,"options":["Reduce emissions – flying creates a lot of emissions and greenhouse gases which will have a negative impact on the environment. A limit may help reduce emissions.","Reduce traffic around Dublin airport – this will reduce traffic congestion for residents.","Reduce noise pollution – for local residents as less planes will fly reducing the negative impact on residents. Reduce overcrowding – Dublin airport is already stretched and at capacity during busy periods. Facilities may need to be improved before more passengers can be facilitated. (ii) If this passenger cap remains unchanged outline the possible economic effect this may 1stx 7 have on each of the following: 2ndx 3 • Tourism into Ireland 3rd x 3 • Other airports in Ireland i.e. Cork, Shannon and Ireland West Airport • Economic growth in Ireland. Tourism into Ireland This could lead to a reduction in the number of tourists that will visit Ireland, through Dublin airport. This could reduce the money coming into the country. It may also make it more expensive for tourists to visit Ireland, through some other route, and that could impact businesses in Ireland dependent on tourism negatively. Other airports in Ireland i.e. Cork, Shannon and Ireland West Airport Airlines might incentivise travel to other airports in Ireland. These airports may be cheaper to fly in to now which could lead to more traffic into these airports. Economic growth in Ireland This could impact Ireland’s economic growth negatively. If less people visit Ireland as it is now more expensive to do so – economic growth will fall as there will be a reduction in injections into the circular flow as tourists are spending less money in the country. It could also lead to unemployment which will have knock on effects for economic growth."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2025 Ordinary Level — © State Examinations Commission.",
    id: "econ-2025-ol-q13-c", topicId: "economics-3-1", conceptId: "uses-of-the-apple-tax-money",
    section: "B", questionRef: "2025 OL Q13(c)",
    questionText: "Outline two areas of infrastructure the Irish government could spend the €14 billion Apple tax money on (other than a new city and reunification of Ireland). Justify your choice in each case.",
    tariffModel: {"kind":"bestNofParts","notation":"2 @ 7","answer":2,"ofParts":6,"perPart":7}, totalMarks: 14,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An area of infrastructure — any two", marks: 14, contextNote: "Two areas, 7 marks each. The scheme opens with \"Accept relevant infrastructure spending\", so this list is what it names rather than all it allows.", openList: true, group: {"claimMax":2,"perOption":7,"options":["Social Housing – build more social and affordable housing which would help with homelessness and with the generation which currently feels locked out of housing market.","Public transport – increase bus and rail services in rural areas / extend DART; LUAS; metro systems allowing for increased use of public transport.","School building – Improve facilities in schools, allowing for better learning environment for more students and teachers.","Water infrastructure – upgrade Ireland’s ageing water infrastructure meaning less boiled water notices and safe drinking water for more people.","Invest in Ireland’s electricity provision – demand for electricity is increasing and provision must be made its sustainability into the future.","Build / expand hospitals health centres – so that the health sector can provide the services which are needed."]} },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2025, level: "ordinary",
    paperFileid: "LC034GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Economics 2025 Ordinary Level — © State Examinations Commission.",
    id: "econ-2025-ol-q14-c", topicId: "economics-4-0", conceptId: "ldc-actions-to-improve-welfare",
    section: "B", questionRef: "2025 OL Q14(b)",
    questionText: "Suggest two actions the governments of LDCs receiving aid can take to improve their citizens’ welfare.",
    tariffModel: {"kind":"fixed","notation":"1st @ 6 + 2nd @ 4","answer":null,"ofParts":null,"perPart":null}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "anyN", verbatim: "An action to improve citizens’ welfare — any two", marks: null, contextNote: "Two actions. The paper pays the first 6 and the second 4 — the scheme writes the split out in words rather than in the marks column.", openList: true, group: {"claimMax":2,"perOption":6,"options":["Infrastructure Development - investing in essential infrastructure such as clean water systems, sanitation facilities, and roads can significantly improve public health and access to markets. This would enhance the quality of life for citizens, promote economic growth, and facilitate access to education and healthcare services.","Education and skills training - allocating funds towards education, including primary and vocational training, can empower citizens with essential skills. This can lead to improved employment opportunities, higher income levels, and greater overall economic development, helping to break the cycle of poverty.","Healthcare - expand access to hospitals, clinics, and medical supplies to reduce disease and improve life expectancy. Investing in clean water and sanitation can also prevent the spread of illnesses.","Job Creation - support local businesses, invest in agriculture, and encourage industries that create employment, reducing dependency on aid and fostering long- term development."],"perOptionSteps":[6,4]} },
    ],
  } as SecCard,
];
