/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Economics cards, Ordinary Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/economics/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the strands of the specification the papers were actually sat
 * under. Economics was first examined on it in 2021, so the whole 2021-2025
 * corpus sits on one syllabus with nothing to straddle.
 */

import type { SecCard } from '../../../../types/markBank';

export const CARDS: SecCard[] = [

];
