/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * The tunnel of years. Between the chapters and the examiner, the reader
 * scrolls INTO the seventeen years the Paper Trail holds: one viewport-sized
 * numeral per year, set in Source Serif 4 at the display weight, laid out in
 * depth along z on a sticky stage with CSS perspective. The scroll position
 * through the section is the only clock — each year comes toward the reader,
 * passes, and the next is already there. The nearest year is crisp; deeper
 * ones are lighter by opacity steps (never blurred). Every year stands on one
 * hairline horizon with its paper count as a small mono label beside it. The
 * counts are the PDFs per year in the corpus (fx-i/years.ts, generated by
 * scripts/landing/tunnel-years.mjs).
 *
 * Reduced motion, ?static=1: a flat ruled row of the years with their counts.
 * Phones: a shorter tunnel, the same idea.
 */

import React, { useEffect, useRef, useState } from 'react';
import { useMotionValueEvent, useScroll } from 'framer-motion';
import { useReducedMotion } from '../../Motion';
import { isStatic } from '../fx/env';
import { YEARS } from '../fx-i/years';
import { Container, Eyebrow } from '../primitives';
import { FONT, L } from '../theme';
import '../fx-i/fx-i.css';

const TEXT = {
  eyebrow: 'Paper Trail · 2010 to 2026',
  caption: `${YEARS.length === 17 ? 'Seventeen' : String(YEARS.length)} years of papers, one numeral each. Scroll through them.`,
  captionFlat: `${YEARS.length === 17 ? 'Seventeen' : String(YEARS.length)} years of papers in the Paper Trail, 2010 to 2026.`,
} as const;

/** Scroll room per year, in viewport heights. Phones get a shorter tunnel. */
const STEP_VH = { desktop: 34, phone: 24 } as const;
/** Depth between consecutive years, as a fraction of the stage's perspective distance (fx-i.css: 900px, 640px on phones). */
const DEPTH = 0.9;
/** The year that has just passed fades out over this much of one step in front of the eye. */
const PASS = 0.55;
/** Opacity by depth in whole steps behind the nearest year: crisp, then lighter, then gone. */
const LEVELS = [1, 0.5, 0.28, 0.15, 0.07, 0];
/** Where the tunnel starts: the first year is this far away at the top of the section. */
const LEAD = 0.75;

const fmt = new Intl.NumberFormat('en-IE');

/** The flat variant: a ruled row of the years and their counts. */
const FlatYears: React.FC = () => (
  <section id="tunnel" aria-labelledby="tunnel-title" className="py-[72px] md:py-[128px]" style={{ scrollMarginTop: 70 }}>
    <Container>
      <Eyebrow>{TEXT.eyebrow}</Eyebrow>
      <h2 id="tunnel-title" className="mt-3 mb-8" style={{ fontFamily: FONT.serif, fontWeight: 600, fontSize: 20, lineHeight: 1.3, letterSpacing: '-0.01em', color: L.ink, margin: 0, maxWidth: '40ch' }}>{TEXT.captionFlat}</h2>
      <ol className="fxi-flat mt-8">
        {YEARS.map(y => (
          <li key={y.year}>
            <span className="fxi-num">{y.year}</span>
            <span className="fxi-count">{fmt.format(y.papers)} papers</span>
          </li>
        ))}
      </ol>
    </Container>
  </section>
);

const TunnelOfYears: React.FC = () => {
  const reduce = useReducedMotion();
  const [flat, setFlat] = useState<boolean | null>(null);
  const [phone, setPhone] = useState(false);
  useEffect(() => {
    setFlat(isStatic());
    const mq = window.matchMedia('(max-width: 767px)');
    const sync = () => setPhone(mq.matches);
    sync();
    mq.addEventListener('change', sync);
    return () => mq.removeEventListener('change', sync);
  }, []);

  const sectionRef = useRef<HTMLElement>(null);
  const listRef = useRef<HTMLOListElement>(null);
  const { scrollYProgress } = useScroll({ target: sectionRef, offset: ['start start', 'end end'] });

  const place = (progress: number) => {
    const list = listRef.current;
    if (!list) return;
    const n = YEARS.length;
    // p is the reader's position in years: year i is at the eye when p === i.
    const p = -LEAD + progress * (n - 1 + LEAD);
    const P = phone ? 640 : 900;
    const items = list.children;
    for (let i = 0; i < items.length; i++) {
      const el = items[i] as HTMLElement;
      const dz = i - p; // steps ahead of the eye (negative once passed)
      let opacity: number;
      if (dz < 0) opacity = Math.max(0, 1 + dz / PASS);
      else {
        const k = Math.min(Math.floor(dz), LEVELS.length - 1);
        const f = Math.min(1, dz - k);
        opacity = LEVELS[k] + (LEVELS[Math.min(k + 1, LEVELS.length - 1)] - LEVELS[k]) * f;
      }
      const z = -dz * DEPTH * P;
      const on = opacity > 0.004 && z < P * 0.95;
      el.style.visibility = on ? 'visible' : 'hidden';
      el.style.opacity = on ? opacity.toFixed(3) : '0';
      el.style.transform = on ? `translate(-50%, -100%) translateZ(${z.toFixed(1)}px)` : '';
      el.style.zIndex = String(i);
    }
  };
  useMotionValueEvent(scrollYProgress, 'change', place);
  useEffect(() => { if (flat === false) place(scrollYProgress.get()); });

  if (reduce || flat !== false) return <FlatYears />;

  const step = phone ? STEP_VH.phone : STEP_VH.desktop;
  return (
    <section
      ref={sectionRef}
      id="tunnel"
      aria-labelledby="tunnel-title"
      className="fxi-tunnel"
      style={{ height: `calc(100vh + ${YEARS.length * step}vh)`, scrollMarginTop: 0 }}
    >
      <div className="fxi-stage">
        <div className="fxi-head">
          <Container>
            <Eyebrow>{TEXT.eyebrow}</Eyebrow>
            <h2 id="tunnel-title" className="mt-3" style={{ fontFamily: FONT.serif, fontWeight: 600, fontSize: 20, lineHeight: 1.3, letterSpacing: '-0.01em', color: L.ink, margin: 0, maxWidth: '30ch' }}>{TEXT.caption}</h2>
          </Container>
        </div>
        <div className="fxi-horizon" aria-hidden="true" />
        <ol ref={listRef} className="fxi-years">
          {YEARS.map(y => (
            <li key={y.year} className="fxi-year">
              <span className="fxi-num">{y.year}</span>
              <span className="fxi-count">{fmt.format(y.papers)} papers</span>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
};

export default TunnelOfYears;
