/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark Bank — authored Ancient Greek cards, Ordinary Level.
 *
 * GENERATED by scripts/markbank/build-deck.mjs. Do not edit by hand.
 *
 * Every question, marking point and mark value is transcribed from the marking
 * scheme for that card's own year and level in examiner-reports/ancient-greek/schemes/,
 * and the build drops any card whose content cannot be found there. Figure paths,
 * hashes and SEC paper file ids are resolved from data on disk by the build
 * script — never typed — because both historical figure corruptions in this repo
 * entered through a hand-transcribed path.
 *
 * Cards are tagged to the task types of the legacy Leaving Certificate Ancient
 * Greek written paper, which is the paper every sitting in the bank was sat on.
 * Ancient Greek is examined in ONE booklet with no listening test. Its questions
 * print a CHOICE of routes a candidate answers one of — "Answer Section A or
 * Section B" — so a card names the route it was set under, and Question 3's two
 * routes are the syllabus's two prescribed courses, A World of Heroes and The
 * Intellectual Revolution. Every unseen comprehension card carries the Greek
 * passage, the English summary and the vocabulary the SEC glossed it with, bound
 * to the page of the question paper they were printed on; a card whose ask names
 * a photograph opens the plate page at the back of the same booklet. Translation
 * asks are NOT carded: the scheme prices them by segment, and the segments are
 * the source text — Greek for the unseen passages, English for the composition —
 * and never a model answer.
 */

import type { SecCard } from '../../../../types/markBank';

const base = {
  source: 'sec' as const,
  subjectId: "ancient-greek",
  specVersion: "lc-ancient-greek-syllabus",
  qa: { gates: ['verbatim', 'tariff', 'figure'], humanReviewedBy: 'agent-verified', humanReviewedAt: '2026-07-31' },
};

export const CARDS: SecCard[] = [
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-q2-ii-a", topicId: "ancient-greek-4-3", conceptId: "agr-situation-start",
    section: "Q2", questionRef: "2015 OL Q2(ii)(a)",
    stem: "Answer any four of the following questions. (Each question carries ten marks):-",
    questionText: "Explain the situation at the start of the passage above.",
    tariffModel: {"kind":"questionTotal"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Athene appears in a dream to persuade Nausikaa to go to the beach and find shipwrecked Odysseus.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-q2-ii-b", topicId: "ancient-greek-4-3", conceptId: "agr-between-gives-help-him",
    section: "Q2", questionRef: "2015 OL Q2(ii)(b)",
    stem: "Answer any four of the following questions. (Each question carries ten marks):-",
    questionText: "Outline briefly the meeting between Nausikaa and Odysseus and the help that she gives to him.",
    tariffModel: {"kind":"questionTotal"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Odysseus woken by ball-playing girls.", marks: null },
    { id: "r-2", kind: "point", verbatim: "His appearance frightens all but Nausikaa.", marks: null },
    { id: "r-3", kind: "point", verbatim: "She offers him clothing and an introduction to her father.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-q2-ii-c", topicId: "ancient-greek-4-3", conceptId: "agr-character-depict-homer-justify",
    section: "Q2", questionRef: "2015 OL Q2(ii)(c)",
    stem: "Answer any four of the following questions. (Each question carries ten marks):-",
    questionText: "In your opinion, how skilfully does Homer depict the character of Nausikaa? Justify your answer.",
    tariffModel: {"kind":"questionTotal"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Presents her as a young girl, of marriageable age, fun loving on the beach, conscious of her position in the eyes of her people.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-q2-ii-d", topicId: "ancient-greek-4-3", conceptId: "agr-first-number-person-present",
    section: "Q2", questionRef: "2015 OL Q2(ii)(d)",
    stem: "Answer any four of the following questions. (Each question carries ten marks):-",
    questionText: "Give the First Person, Singular Number, Present Tense of any two of these verbs underlined above: ἔειπεν, ἄγωνται, ἀναβαίνει, χαίρουσιν.",
    tariffModel: {"kind":"orderedSplit","notation":"5 + 5"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Λέγω ; ἂγω / ἄγομαι ; ἀναβαίνω ; χαίρω .", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-q2-ii-e", topicId: "ancient-greek-4-3", conceptId: "agr-aristarkhos-arose-between-dispute",
    section: "Q2", questionRef: "2015 OL Q2(ii)(e)",
    stem: "Answer any four of the following questions. (Each question carries ten marks):-",
    questionText: "Give a summary of the dispute that arose between Aristarkhos and Theophemos.",
    tariffModel: {"kind":"questionTotal"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Aristarkhos gets into a fight with Theophemos over possession of ship.s gear.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Theophemos bribes jurors to win assault case.", marks: null },
    { id: "r-3", kind: "point", verbatim: "He raids Aristarkhos’ farm before appewal can be heard.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-q2-ii-f", topicId: "ancient-greek-4-3", conceptId: "agr-creation-epimetheus-played-prometheus",
    section: "Q2", questionRef: "2015 OL Q2(ii)(f)",
    stem: "Answer any four of the following questions. (Each question carries ten marks):-",
    questionText: "Outline the roles played by Epimetheus and Prometheus in the Creation story.",
    tariffModel: {"kind":"questionTotal"}, totalMarks: 10,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Prometheus and Epimetheus are instructed by Zeus to assist in the Creation story.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Epimetheus gives characteristics to animals, Prometheus steals fire and wisdom for men.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-a-q3-i", topicId: "ancient-greek-4-5", conceptId: "agr-cause-chief-events-led",
    section: "Q3", questionRef: "2015 OL Section A Q3(i)",
    questionText: "Summarise the chief events that led up to the start of the Peloponnesian War in 431 BC. What was its main cause, in your opinion?",
    tariffModel: {"kind":"orderedSplit","notation":"8 + 8 + 7 + 7"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Rivalry at Persian Wars; Growth of Athenian Empire; Pericles’ policies; Corcyra; Potidaea ; Plataea.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Give main cause of War.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-a-q3-ii", topicId: "ancient-greek-4-5", conceptId: "agr-athens-brasidas-epaminondas-nicias",
    section: "Q3", questionRef: "2015 OL Section A Q3(ii)",
    questionText: "Write short notes on any two of the following:- the plague at Athens; the Peace of Nicias; Brasidas; Epaminondas.",
    tariffModel: {"kind":"orderedSplit","notation":"(8 + 7) + (8 + 7)"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Plague at Athens: Citizens confined; many deaths including Pericles; Thucydides’ account.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Peace of Nicias: End of 1st phase of War; Cleon & Brasidas dead; Both sides needed break Brasidas: Successful Spartan general; Campaigned in Cherosoese; died at battle of Amphipolis.", marks: null },
    { id: "r-3", kind: "point", verbatim: "Epaminondas: Leader of Theban hegemony; Developed phalanx; died at battle of Mantinea.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-a-q3-iii", topicId: "ancient-greek-4-5", conceptId: "agr-advance-alexander-assess-battle",
    section: "Q3", questionRef: "2015 OL Section A Q3(iii)",
    questionText: "Pick any one of the battles fought by Alexander the Great. Explain briefly the situation in advance of the battle, outline its course, and assess its importance in the career of Alexander.",
    tariffModel: {"kind":"orderedSplit","notation":"8 + 8 + 7 + 7"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Choose battle; Explain background; Outline its course; Assess its importance.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-a-q3-iv", topicId: "ancient-greek-4-5", conceptId: "agr-archons-draco-ecclesia-peisistratus",
    section: "Q3", questionRef: "2015 OL Section A Q3(iv)",
    questionText: "Write short notes on any two of the following:- Draco; Peisistratus; ecclesia; archons.",
    tariffModel: {"kind":"orderedSplit","notation":"(8 + 7) + (8 + 7)"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Draco: 7th Century BC Athenian legislator; Codified laws; Noted for severity of punishments", marks: null },
    { id: "r-2", kind: "point", verbatim: "Peisistratus: 3 times sole ruler at Athens; City prospered; Rule passed on to son", marks: null },
    { id: "r-3", kind: "point", verbatim: "Ecclesia: Assembly of full Athenian citizens; Elected magistrates, Decided on war; Met at Pnyx; Legislated on proposals from Boule; Prytanneis managed it", marks: null },
    { id: "r-4", kind: "point", verbatim: "Archons: 9 important annual magistrates in Athens; Military commander; Name to year", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-b-q3-i", topicId: "ancient-greek-4-5", conceptId: "agr-importance-life-philosopher-plato",
    section: "Q3", questionRef: "2015 OL Section B Q3(i)",
    questionText: "Give an account of the life and work of Plato. Discuss briefly his importance as a philosopher.",
    tariffModel: {"kind":"orderedSplit","notation":"8 + 8 + 7 + 7"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Plato (427 – 348 BC): Noble Athenian; associate of Socrates; visited Syracuse 3 times; founded Academy.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Name two works.", marks: null },
    { id: "r-3", kind: "point", verbatim: "Continued the Socratic tradition through his Academy.", marks: null },
    { id: "r-4", kind: "point", verbatim: "Theory of Forms.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-b-q3-ii", topicId: "ancient-greek-4-5", conceptId: "agr-attributed-epics-homer-homeric",
    section: "Q3", questionRef: "2015 OL Section B Q3(ii)",
    questionText: "Name the two epics attributed to Homer. Outline briefly what each of them is about, and mention some of the features of the style of Homeric poetry.",
    tariffModel: {"kind":"orderedSplit","notation":"10 + 10 + 10"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Iliad and Odyssey.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Brief account of each.", marks: null },
    { id: "r-3", kind: "point", verbatim: "Oral composition; Gods; Heroes; Vivid stories; Stock epithets; Epic similes.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-b-q3-iii", topicId: "ancient-greek-4-5", conceptId: "agr-black-differences-figure-geometric",
    section: "Q3", questionRef: "2015 OL Section B Q3(iii)",
    questionText: "Describe briefly the differences which would help you recognise whether an ancient Greek vase-painting was Geometric, Black Figure, or Red Figure.",
    tariffModel: {"kind":"orderedSplit","notation":"10 + 10 + 10"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Geometric vase: Geometric patterns; All-over painting; Funeral scenes.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Black Figure vase: Background left natural colour of clay; Figures painted black.", marks: null },
    { id: "r-3", kind: "point", verbatim: "Red Figure vases: Background painted black; Figures in reddish colour of clay.", marks: null },
    ],
  } as SecCard,
  {
    ...base, kind: "question",
    year: 2015, level: "ordinary",
    paperFileid: "LC007GLP000EV",
    schemeCitation: "Marking points quoted from the SEC marking scheme, Ancient Greek 2015 Ordinary Level — © State Examinations Commission.",
    id: "agr-2015-ol-b-q3-iv", topicId: "ancient-greek-4-5", conceptId: "agr-aphrodite-column-doric-figures",
    section: "Q3", questionRef: "2015 OL Section B Q3(iv)",
    questionText: "Write short notes on any two of the following:- Kouros figures; the Doric column; Pheidias; Aphrodite of Melos (Venus de Milo).",
    tariffModel: {"kind":"orderedSplit","notation":"(8 + 7) + (8 + 7)"}, totalMarks: 30,
    rows: [
    { id: "r-1", kind: "point", verbatim: "Kouros figures: Static pose; Facing front; Stylised hair; Archaic smile; weak musculature.", marks: null },
    { id: "r-2", kind: "point", verbatim: "Doric column: Stout columns; Capital plain; Triglyphs and Metopes.", marks: null },
    { id: "r-3", kind: "point", verbatim: "Pheidias: Athenian sculptor; master cfaftsman of Parthenon frieze; chryselephantine statues of Athene at Athens, and of Zeus at Olympia.", marks: null },
    { id: "r-4", kind: "point", verbatim: "Aphrodite of Melos: Hellenistic period; Roman copy; Nudity not in Classical female statues; Movement in body; Anatomy realistic.", marks: null },
    ],
  } as SecCard,
];
