/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/landing/examiner-cards.mjs — do not edit by hand.
 *
 * Every question is verbatim from the SEC paper and every point, mark and
 * line of a possible response verbatim from the SEC marking scheme, read from
 * the gated Mark Bank card files. Accept alternatives are the scheme's own or
 * the same thing written differently, and are listed with their reasons in
 * the script. Attribute as printed on each item.
 */

import type { MarkPoint } from '../marking/marker';

export interface ExamFigure { src: string; alt: string; width: number; height: number }

export interface MarkQuestion {
  id: string;
  subject: string;
  ref: string;
  year: number;
  level: 'Higher' | 'Ordinary';
  stem?: string;
  question: string;
  figure?: ExamFigure;
  points: MarkPoint[];
  total: number;
  attribution: string;
}

export interface MarkSubject { id: string; label: string; questions: MarkQuestion[] }

/** A scheme point named in a possible response, with the tariff the scheme prints beside it. */
export interface ResponsePoint { id: string; label: string; marks: number; tariff: string }
/** One line of the scheme's possible response and the point it earns. */
export interface ResponseLine { id: string; text: string; pointId: string }

export interface ResponseQuestion {
  id: string;
  subject: string;
  ref: string;
  year: number;
  level: 'Higher' | 'Ordinary';
  stem?: string;
  question: string;
  /** The tariff notation as the scheme prints it, e.g. "4 x 5m (2+3)". */
  notation: string;
  points: ResponsePoint[];
  lines: ResponseLine[];
  total: number;
  attribution: string;
}

/** "Mark my answer": five subjects, four questions each. */
export const MARK_SUBJECTS: MarkSubject[] = [
  {
    "id": "biology",
    "label": "Biology",
    "questions": [
      {
        "id": "bio-2025-hl-q1-a",
        "subject": "Biology",
        "ref": "2025 HL Q1(a)",
        "year": 2025,
        "level": "Higher",
        "stem": "Section A — Question 1. Best five answers from (a) – (f).",
        "question": "Write the general formula for carbohydrates.",
        "points": [
          {
            "id": "r-formula",
            "verbatim": "Cx(H2O)y",
            "marks": 4,
            "accept": [
              [
                "Cx(H2O)y"
              ],
              [
                "Cn(H2O)n"
              ]
            ]
          }
        ],
        "total": 4,
        "attribution": "SEC Leaving Certificate Biology 2025 Higher Level — © State Examinations Commission"
      },
      {
        "id": "bio-2025-hl-q3-a",
        "subject": "Biology",
        "ref": "2025 HL Q3(a)",
        "year": 2025,
        "level": "Higher",
        "question": "Name the cell organelle shown.",
        "figure": {
          "src": "/exam-figures/biology/biology-2025-hl-mitochondrion.png",
          "alt": "Cross-section of a mitochondrion: a smooth outer membrane and an inner membrane folded into long finger-like cristae, with small dots scattered through the interior.",
          "width": 541,
          "height": 281
        },
        "points": [
          {
            "id": "r-a",
            "verbatim": "Mitochondrion",
            "marks": 2
          }
        ],
        "total": 2,
        "attribution": "SEC Leaving Certificate Biology 2025 Higher Level — © State Examinations Commission"
      },
      {
        "id": "bio-2025-hl-q4-c",
        "subject": "Biology",
        "ref": "2025 HL Q4(c)",
        "year": 2025,
        "level": "Higher",
        "question": "(i) What term describes cells without membrane-bound organelles? (ii) What term describes cells with membrane-bound organelles?",
        "points": [
          {
            "id": "r-ci",
            "verbatim": "(i) — Prokaryotic",
            "marks": 3
          },
          {
            "id": "r-cii",
            "verbatim": "(ii) — Eukaryotic",
            "marks": 3
          }
        ],
        "total": 6,
        "attribution": "SEC Leaving Certificate Biology 2025 Higher Level — © State Examinations Commission"
      },
      {
        "id": "bio-2024-hl-q14-c-ii",
        "subject": "Biology",
        "ref": "2024 HL Q14(c)(ii)",
        "year": 2024,
        "level": "Higher",
        "question": "Name the two biochemical components that make up all viruses.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "Protein",
            "marks": 3
          },
          {
            "id": "r-2",
            "verbatim": "Nucleic acid (or DNA or RNA)",
            "marks": 3,
            "accept": [
              [
                "nucleic acid"
              ],
              [
                "DNA"
              ],
              [
                "RNA"
              ]
            ]
          }
        ],
        "total": 6,
        "attribution": "SEC Leaving Certificate Biology 2024 Higher Level — © State Examinations Commission"
      }
    ]
  },
  {
    "id": "chemistry",
    "label": "Chemistry",
    "questions": [
      {
        "id": "chem-2021-hl-q11-c-iii",
        "subject": "Chemistry",
        "ref": "2021 HL Q11(c)(iii)",
        "year": 2021,
        "level": "Higher",
        "question": "What happens in a radioactive nucleus during beta decay?",
        "points": [
          {
            "id": "r-1",
            "verbatim": "neutron changes into a proton",
            "marks": 3
          },
          {
            "id": "r-2",
            "verbatim": "and an electron which is emitted",
            "marks": 3
          }
        ],
        "total": 6,
        "attribution": "SEC Leaving Certificate Chemistry 2021 Higher Level — © State Examinations Commission"
      },
      {
        "id": "chem-2021-hl-q4-a",
        "subject": "Chemistry",
        "ref": "2021 HL Q4(a)",
        "year": 2021,
        "level": "Higher",
        "stem": "Q4 requires eight items to be answered; each item is worth six marks.",
        "question": "How many (i) electrons, (ii) neutrons, does a 32/16 S2– ion have?",
        "points": [
          {
            "id": "r-1",
            "verbatim": "18 electrons",
            "marks": 3
          },
          {
            "id": "r-2",
            "verbatim": "16 neutrons",
            "marks": 3
          }
        ],
        "total": 6,
        "attribution": "SEC Leaving Certificate Chemistry 2021 Higher Level — © State Examinations Commission"
      },
      {
        "id": "chem-2021-hl-q11-c-ii",
        "subject": "Chemistry",
        "ref": "2021 HL Q11(c)(ii)",
        "year": 2021,
        "level": "Higher",
        "question": "Name the scientist whose work on cathode rays led him to identify the electron as a subatomic particle.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "J.J. Thomson",
            "marks": 3
          }
        ],
        "total": 3,
        "attribution": "SEC Leaving Certificate Chemistry 2021 Higher Level — © State Examinations Commission"
      },
      {
        "id": "chem-2021-hl-q11-d-b-ii",
        "subject": "Chemistry",
        "ref": "2021 HL Q11(d)B(ii)",
        "year": 2021,
        "level": "Higher",
        "stem": "Aluminium is extracted from molten aluminium oxide by electrolysis.",
        "question": "Why must the aluminium oxide be molten?",
        "points": [
          {
            "id": "r-1",
            "verbatim": "ions are free to move",
            "marks": 3
          }
        ],
        "total": 3,
        "attribution": "SEC Leaving Certificate Chemistry 2021 Higher Level — © State Examinations Commission"
      }
    ]
  },
  {
    "id": "physics",
    "label": "Physics",
    "questions": [
      {
        "id": "phys-2022-hl-q7-i",
        "subject": "Physics",
        "ref": "2022 HL Q7(i)",
        "year": 2022,
        "level": "Higher",
        "stem": "A spring of natural length 150 mm obeys Hooke’s law.",
        "question": "State Hooke’s law.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "extension",
            "marks": 2
          },
          {
            "id": "r-2",
            "verbatim": "proportional to force",
            "marks": 2
          }
        ],
        "total": 4,
        "attribution": "SEC Leaving Certificate Physics 2022 Higher Level — © State Examinations Commission"
      },
      {
        "id": "phys-2021-hl-q7-i",
        "subject": "Physics",
        "ref": "2021 HL Q7(i)",
        "year": 2021,
        "level": "Higher",
        "question": "State Newton's second law of motion.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "force is proportional to",
            "marks": 3
          },
          {
            "id": "r-2",
            "verbatim": "rate of change of momentum",
            "marks": 3
          }
        ],
        "total": 6,
        "attribution": "SEC Leaving Certificate Physics 2021 Higher Level — © State Examinations Commission"
      },
      {
        "id": "phys-2022-hl-q6-k",
        "subject": "Physics",
        "ref": "2022 HL Q6(k)",
        "year": 2022,
        "level": "Higher",
        "question": "What is thermionic emission? Where does it occur in an X-ray tube?",
        "points": [
          {
            "id": "r-1",
            "verbatim": "emission of electrons",
            "marks": 2
          },
          {
            "id": "r-2",
            "verbatim": "from a hot surface",
            "marks": 2
          },
          {
            "id": "r-3",
            "verbatim": "cathode",
            "marks": 3
          }
        ],
        "total": 7,
        "attribution": "SEC Leaving Certificate Physics 2022 Higher Level — © State Examinations Commission"
      },
      {
        "id": "phys-2022-hl-q7-v",
        "subject": "Physics",
        "ref": "2022 HL Q7(v)",
        "year": 2022,
        "level": "Higher",
        "stem": "An object on a spring is pulled down and released, and moves with simple harmonic motion.",
        "question": "What is the speed of the body when it has maximum acceleration?",
        "points": [
          {
            "id": "r-1",
            "verbatim": "zero",
            "marks": 3,
            "accept": [
              [
                "zero"
              ],
              [
                "0"
              ]
            ]
          }
        ],
        "total": 3,
        "attribution": "SEC Leaving Certificate Physics 2022 Higher Level — © State Examinations Commission"
      }
    ]
  },
  {
    "id": "agricultural-science",
    "label": "Agricultural Science",
    "questions": [
      {
        "id": "agsci-2021-hl-q7a",
        "subject": "Agricultural Science",
        "ref": "2021 HL Q7(a)",
        "year": 2021,
        "level": "Higher",
        "question": "All agriculture depends on biodiversity. Explain biodiversity.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "Variety of plant and animal life in a habitat (ecosystem).",
            "marks": 2
          }
        ],
        "total": 2,
        "attribution": "SEC Leaving Certificate Agricultural Science 2021 Higher Level — © State Examinations Commission"
      },
      {
        "id": "agsci-2021-hl-q8a",
        "subject": "Agricultural Science",
        "ref": "2021 HL Q8(a)",
        "year": 2021,
        "level": "Higher",
        "stem": "The following is a kill out sheet (lairage docket) for 2 Aberdeen Angus (AA) heifers and 2 Limousine (LM) heifers from John's farm. Analyse the sheet and answer the questions which follow.",
        "question": "Briefly explain the term conformation.",
        "figure": {
          "src": "/exam-figures/agricultural-science/markbank/agricultural-science-2021-HL-paper-p13-i0.png",
          "alt": "A table from the exam paper. Columns: Tag number, Breed, Sex, Age (months), Conformation, Fat, Carcase Weight (kg). Rows: 217981261073, 235207471646, 215038714153, 214346622696. 5 rows by 7 columns, as printed in the paper.",
          "width": 994,
          "height": 219
        },
        "points": [
          {
            "id": "r-1",
            "verbatim": "Shape and muscle distribution of the animal",
            "marks": 2
          }
        ],
        "total": 2,
        "attribution": "SEC Leaving Certificate Agricultural Science 2021 Higher Level — © State Examinations Commission"
      },
      {
        "id": "agsci-2021-hl-q9a",
        "subject": "Agricultural Science",
        "ref": "2021 HL Q9(a)",
        "year": 2021,
        "level": "Higher",
        "question": "Explain genomic selection.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "Animals or plants selected based on their DNA (or genetic material)",
            "marks": 2
          }
        ],
        "total": 2,
        "attribution": "SEC Leaving Certificate Agricultural Science 2021 Higher Level — © State Examinations Commission"
      },
      {
        "id": "agsci-2021-hl-q10a",
        "subject": "Agricultural Science",
        "ref": "2021 HL Q10(a)",
        "year": 2021,
        "level": "Higher",
        "stem": "The Murphy family operate one of Ireland's sheep dairy farms in Co. Galway. They produce artisan products for a niche market. Their produce is available in approximately 50 shops and in some of Ireland's top restaurants.",
        "question": "Distinguish between artisan produce and a niche market.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "AP ‐ food produced in microenterprise with unique characteristics",
            "marks": 2
          },
          {
            "id": "r-2",
            "verbatim": "NM ‐ small specialised market for a particular product or service",
            "marks": 2
          }
        ],
        "total": 4,
        "attribution": "SEC Leaving Certificate Agricultural Science 2021 Higher Level — © State Examinations Commission"
      }
    ]
  },
  {
    "id": "business",
    "label": "Business",
    "questions": [
      {
        "id": "bus-2025-ol-s1-q1",
        "subject": "Business",
        "ref": "2025 OL Section 1 Q1",
        "year": 2025,
        "level": "Ordinary",
        "question": "What do the following letters stand for? Write each answer in the space provided: EGM, LEO, GDP.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "EGM — Extraordinary General Meeting",
            "marks": 4
          },
          {
            "id": "r-2",
            "verbatim": "LEO — Local Enterprise Offices",
            "marks": 3
          },
          {
            "id": "r-3",
            "verbatim": "GDP — Gross Domestic Product",
            "marks": 3
          }
        ],
        "total": 10,
        "attribution": "SEC Leaving Certificate Business 2025 Ordinary Level — © State Examinations Commission"
      },
      {
        "id": "bus-2021-ol-s2-q5di",
        "subject": "Business",
        "ref": "2021 OL Section 2 Q5(D)(i)",
        "year": 2021,
        "level": "Ordinary",
        "question": "In Maslow’s Hierarchy of Needs pyramid, list the missing levels 2, 4 and 5.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "2: Safety/Security",
            "marks": 5,
            "accept": [
              [
                "safety"
              ],
              [
                "security"
              ]
            ]
          },
          {
            "id": "r-2",
            "verbatim": "4: Esteem",
            "marks": 5
          },
          {
            "id": "r-3",
            "verbatim": "5: Self Actualisation",
            "marks": 5,
            "accept": [
              [
                "self actualisation"
              ],
              [
                "self-actualisation"
              ],
              [
                "self actualization"
              ],
              [
                "self-actualization"
              ]
            ]
          }
        ],
        "total": 15,
        "attribution": "SEC Leaving Certificate Business 2021 Ordinary Level — © State Examinations Commission"
      },
      {
        "id": "bus-2024-ol-s2-q2aii",
        "subject": "Business",
        "ref": "2024 OL Section 2 Q2(A)(ii)",
        "year": 2024,
        "level": "Ordinary",
        "stem": "Domestic Environment.",
        "question": "Ór-Real Irish Butter operates in the secondary sector of the Irish economy. Name the two other sectors of the economy.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "Primary Sector",
            "marks": 5,
            "accept": [
              [
                "primary"
              ]
            ]
          },
          {
            "id": "r-2",
            "verbatim": "Tertiary Sector",
            "marks": 5,
            "accept": [
              [
                "tertiary"
              ]
            ]
          }
        ],
        "total": 10,
        "attribution": "SEC Leaving Certificate Business 2024 Ordinary Level — © State Examinations Commission"
      },
      {
        "id": "bus-2024-ol-s2-q4d",
        "subject": "Business",
        "ref": "2024 OL Section 2 Q4(D)",
        "year": 2024,
        "level": "Ordinary",
        "stem": "The Consumer Protection Act 2007 protects consumers from unfair commercial practices.",
        "question": "Name the organisation responsible for enforcing the Consumer Protection Act 2007.",
        "points": [
          {
            "id": "r-1",
            "verbatim": "Competition and Consumer Protection Commission (CCPC).",
            "marks": 10,
            "accept": [
              [
                "competition",
                "consumer",
                "protection",
                "commission"
              ],
              [
                "CCPC"
              ]
            ]
          }
        ],
        "total": 10,
        "attribution": "SEC Leaving Certificate Business 2024 Ordinary Level — © State Examinations Commission"
      }
    ]
  }
];

/** "What the examiner wants": full-marks answers, line by line, each line mapped to its point. */
export const WANTS: ResponseQuestion[] = [
  {
    "id": "bus-2021-hl-s3-q8b",
    "subject": "Business",
    "ref": "2021 HL Section 3 Q8(B)",
    "year": 2021,
    "level": "Higher",
    "stem": "Aimee Connolly started working behind a makeup counter when she was a transition year student. While studying at university, Aimee decided to create her own makeup business and produce makeup products. ‘Sculpted by Aimee’ is now a very popular makeup brand. The products are sold nationally and internationally.",
    "question": "Describe the first four stages involved in the development process of a new product.",
    "notation": "4 x 5m (2+3)",
    "points": [
      {
        "id": "p1",
        "label": "Idea Generation",
        "marks": 5,
        "tariff": "5 (2 + 3)"
      },
      {
        "id": "p2",
        "label": "Product Screening",
        "marks": 5,
        "tariff": "5 (2 + 3)"
      },
      {
        "id": "p3",
        "label": "Concept Development",
        "marks": 5,
        "tariff": "5 (2 + 3)"
      },
      {
        "id": "p4",
        "label": "Feasibility Study",
        "marks": 5,
        "tariff": "5 (2 + 3)"
      }
    ],
    "lines": [
      {
        "id": "p1-l1",
        "text": "Initial ideas for the new product are thought up systematically.",
        "pointId": "p1"
      },
      {
        "id": "p1-l2",
        "text": "They can be internal or external.",
        "pointId": "p1"
      },
      {
        "id": "p1-l3",
        "text": "Ideas may be generated by brain-storming sessions, market research, staff suggestions, customer suggestions/feedback on existing products or services, competitors, R&D etc.",
        "pointId": "p1"
      },
      {
        "id": "p2-l1",
        "text": "All ideas are vetted and the impractical and unworkable ideas are dropped, leaving the most viable ones for further examination and development.",
        "pointId": "p2"
      },
      {
        "id": "p2-l2",
        "text": "Careful screening helps businesses avoid huge expenses in developing ideas that are subsequently not marketable and ensures that good opportunities are not lost.",
        "pointId": "p2"
      },
      {
        "id": "p3-l1",
        "text": "This involves turning the idea into an actual product or service that will appeal to/meet the needs of customers.",
        "pointId": "p3"
      },
      {
        "id": "p3-l2",
        "text": "A unique selling point (USP) is identified which will differentiate it from other products on the market.",
        "pointId": "p3"
      },
      {
        "id": "p4-l1",
        "text": "This is carried out to assess if a product has potential.",
        "pointId": "p4"
      },
      {
        "id": "p4-l2",
        "text": "It looks at whether it can be produced technically (production feasibility) and if it will be profitable (financial feasibility).",
        "pointId": "p4"
      },
      {
        "id": "p4-l3",
        "text": "Will it meet government regulation regarding safety standards, and will it be marketable etc.?",
        "pointId": "p4"
      },
      {
        "id": "p4-l4",
        "text": "It seeks answers to questions such as, what demand will there be for the product; what will it cost to produce and can the business afford it?",
        "pointId": "p4"
      }
    ],
    "total": 20,
    "attribution": "SEC Leaving Certificate Business 2021 Higher Level — © State Examinations Commission"
  },
  {
    "id": "bus-2024-hl-s1-q6",
    "subject": "Business",
    "ref": "2024 HL Section 1 Q6",
    "year": 2024,
    "level": "Higher",
    "question": "Distinguish between an Embargo and a Quota.",
    "notation": "2@5m(3+2)",
    "points": [
      {
        "id": "p1",
        "label": "Embargo",
        "marks": 5,
        "tariff": "5 (3 + 2)"
      },
      {
        "id": "p2",
        "label": "Quota",
        "marks": 5,
        "tariff": "5 (3 + 2)"
      }
    ],
    "lines": [
      {
        "id": "p1-l1",
        "text": "This is a total ban on the import of goods from one particular country.",
        "pointId": "p1"
      },
      {
        "id": "p1-l2",
        "text": "It is often done for political reasons.",
        "pointId": "p1"
      },
      {
        "id": "p2-l1",
        "text": "Quotas are limits imposed on the import of goods and services.",
        "pointId": "p2"
      },
      {
        "id": "p2-l2",
        "text": "Quotas are used as a trade barrier to limit the amount of a certain type of product and or the amount of goods from a certain country that can be imported.",
        "pointId": "p2"
      }
    ],
    "total": 10,
    "attribution": "SEC Leaving Certificate Business 2024 Higher Level — © State Examinations Commission"
  },
  {
    "id": "econ-2022-hl-q13-a-ii",
    "subject": "Economics",
    "ref": "2022 HL Q13(a)(ii)",
    "year": 2022,
    "level": "Higher",
    "question": "The Irish government uses both direct and indirect tax to raise government revenue. Distinguish between these two types of taxes. Use examples of each to support your answer.",
    "notation": "(6 + 2) + (6 + 2)",
    "points": [
      {
        "id": "p1",
        "label": "Direct taxes",
        "marks": 8,
        "tariff": "8 (6 + 2)"
      },
      {
        "id": "p2",
        "label": "Indirect taxes",
        "marks": 8,
        "tariff": "8 (6 + 2)"
      }
    ],
    "lines": [
      {
        "id": "p1-l1",
        "text": "Direct taxes are taxes placed upon income and wealth.",
        "pointId": "p1"
      },
      {
        "id": "p1-l2",
        "text": "e.g., P.A.Y.E. and capital gains tax.",
        "pointId": "p1"
      },
      {
        "id": "p2-l1",
        "text": "Indirect taxes are taxes placed on spending on goods and services.",
        "pointId": "p2"
      },
      {
        "id": "p2-l2",
        "text": "e.g., V.A.T. and excise duties.",
        "pointId": "p2"
      }
    ],
    "total": 16,
    "attribution": "SEC Leaving Certificate Economics 2022 Higher Level — © State Examinations Commission"
  }
];

/** "Mark one yourself": a different question, its points to be placed on its own response lines. */
export const PLACE: ResponseQuestion = {
  "id": "bus-2025-hl-s3-q5b",
  "subject": "Business",
  "ref": "2025 HL Section 3 Q5(B)",
  "year": 2025,
  "level": "Higher",
  "question": "Conduct a SWOT analysis for a business of your choice.",
  "notation": "4 @ 5m (2+3)",
  "points": [
    {
      "id": "p1",
      "label": "Strengths",
      "marks": 5,
      "tariff": "5 (2 + 3)"
    },
    {
      "id": "p2",
      "label": "Weaknesses",
      "marks": 5,
      "tariff": "5 (2 + 3)"
    },
    {
      "id": "p3",
      "label": "Opportunities",
      "marks": 5,
      "tariff": "5 (2 + 3)"
    },
    {
      "id": "p4",
      "label": "Threats",
      "marks": 5,
      "tariff": "5 (2 + 3)"
    }
  ],
  "lines": [
    {
      "id": "p1-l1",
      "text": "These refer to positive internal factors",
      "pointId": "p1"
    },
    {
      "id": "p2-l1",
      "text": "Is an internal aspect of the business that could be improved. Areas of the business that could be bettered.",
      "pointId": "p2"
    },
    {
      "id": "p3-l1",
      "text": "External factors the business could take advantage of. Things that could help the business grow and increase sales.",
      "pointId": "p3"
    },
    {
      "id": "p4-l1",
      "text": "External factors - that could have a negative effect on the business. External factors that the business has no control over and that could lead to a decrease in sales.",
      "pointId": "p4"
    }
  ],
  "total": 20,
  "attribution": "SEC Leaving Certificate Business 2025 Higher Level — © State Examinations Commission"
};
