/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Mark my answer. Twenty real questions across five subjects, four per
 * subject, from the Mark Bank card files (fx-d/examinerData.ts, generated by
 * scripts/landing/examiner-cards.mjs). Pick a subject on the app's own pill
 * bar, pick a question, write, press Mark it. The deterministic marker
 * (marking/marker.ts) earns a point when the answer says what the scheme's
 * line says; the scheme column, blank until then, prints the points verbatim
 * with the earned ones ticked in orange and the missed ones labelled as what
 * the examiner wanted.
 *
 * Starguy watches the textarea while it has focus, nods once per earned
 * point, tilts when nothing earned and hops at full marks — the one place on
 * the page allowed to make him react to typing.
 */

import React, { useEffect, useId, useRef, useState } from 'react';
import HorizontalTabs from '../../ui/HorizontalTabs';
import { useReducedMotion } from '../../Motion';
import { Button, Frame, TextTabs } from '../primitives';
import { L } from '../theme';
import { isStatic } from '../fx/env';
import { markAnswer, type MarkResult } from '../marking/marker';
import { MARK_SUBJECTS } from './examinerData';
import { reactToMarks, starguy } from './starguy';

const TEXT = {
  frame: 'Mark Bank',
  subject: 'Subject',
  question: 'Question',
  yours: 'Your answer',
  placeholder: 'Write it as you would in the exam…',
  mark: 'Mark it',
  again: 'Try again',
  scheme: 'The marking scheme',
  point: 'point',
  points: 'points',
  hidden: 'hidden until marked',
  wanted: 'What the examiner wanted',
  full: 'Full marks',
  none: 'Nothing earned yet',
  some: 'Earned',
  marks: 'marks',
} as const;

const STAGGER = 320;

const MarkMyAnswer: React.FC = () => {
  const [subjectId, setSubjectId] = useState(MARK_SUBJECTS[0].id);
  const [picked, setPicked] = useState<Record<string, string>>({});
  const subject = MARK_SUBJECTS.find(s => s.id === subjectId) ?? MARK_SUBJECTS[0];
  const q = subject.questions.find(x => x.id === picked[subject.id]) ?? subject.questions[0];

  const [answer, setAnswer] = useState('');
  const [result, setResult] = useState<MarkResult | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const cancelRef = useRef<() => void>(() => undefined);
  const reduce = useReducedMotion();
  const instant = reduce || isStatic();
  const uid = useId();

  // A new question starts clean, and any reaction still queued is dropped.
  useEffect(() => { setAnswer(''); setResult(null); cancelRef.current(); }, [q.id]);
  useEffect(() => () => { cancelRef.current(); starguy({ kind: 'unwatch' }); }, []);

  const mark = () => {
    // Sentence-final punctuation is not part of a word: "cathode." must meet "cathode" and "0." must meet "0".
    // (The shared tokeniser keeps a full stop that ends the answer or follows a digit; decimals such as 3.5 are left alone.)
    const r = markAnswer(answer.replace(/[.!?,;:](?=\s|$)/g, ' '), q.points);
    setResult(r);
    cancelRef.current();
    cancelRef.current = reactToMarks(r.hits.filter(h => h.matched).length, r.hits.length, instant ? 0 : STAGGER);
  };
  const reset = () => { setAnswer(''); setResult(null); cancelRef.current(); textareaRef.current?.focus(); };

  const earned = result?.earned ?? 0;
  const word = !result ? '' : earned === result.total ? TEXT.full : earned === 0 ? TEXT.none : TEXT.some;

  return (
    <Frame title={`${TEXT.frame} · ${subject.label}`} meta={`${q.year} · ${q.level} Level`}>
      {/* The subject switch: the app's own pill bar, its pill gliding between subjects */}
      <div className="fxc-bar" style={{ padding: '10px 14px', borderBottom: `1px solid ${L.hairline}` }}>
        <HorizontalTabs
          variant="pill"
          size="sm"
          label={TEXT.subject}
          options={MARK_SUBJECTS.map(s => ({ value: s.id, label: s.label }))}
          value={subjectId}
          onChange={setSubjectId}
          className="w-fit max-w-full"
        />
      </div>
      {/* The question picker: the paper's own numbering */}
      <div style={{ padding: '0 14px', borderBottom: `1px solid ${L.hairline}` }}>
        <TextTabs
          size="sm"
          ariaLabel={TEXT.question}
          items={subject.questions.map(x => ({ id: x.id, label: x.ref }))}
          active={q.id}
          onChange={id => setPicked(p => ({ ...p, [subject.id]: id }))}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2">
        {/* The question and the answer */}
        <div className="fxd-answer" style={{ padding: 20 }}>
          {q.stem && <p className="fxd-stem">{q.stem}</p>}
          <p className="fxd-q">{q.question}</p>
          {q.figure && (
            <img className="fxd-fig" src={q.figure.src} alt={q.figure.alt} width={q.figure.width} height={q.figure.height} loading="lazy" decoding="async" style={{ maxHeight: 220, width: 'auto' }} />
          )}
          <label className="fxd-mono" htmlFor={`${uid}-a`} style={{ display: 'block', marginTop: 20, marginBottom: 8 }}>{TEXT.yours}</label>
          <textarea
            id={`${uid}-a`}
            ref={textareaRef}
            className="fxd-textarea"
            rows={4}
            value={answer}
            placeholder={TEXT.placeholder}
            spellCheck={false}
            onChange={e => { setAnswer(e.target.value); if (result) { setResult(null); cancelRef.current(); } }}
            onFocus={e => starguy({ kind: 'watch', el: e.currentTarget })}
            onBlur={() => starguy({ kind: 'unwatch' })}
            onKeyDown={e => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) { e.preventDefault(); mark(); } }}
          />
          <div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-3">
            <Button variant="ink" onClick={mark}>{TEXT.mark}</Button>
            {result && <Button variant="ghost" onClick={reset}>{TEXT.again}</Button>}
            <span className="fxd-mono" style={{ marginLeft: 'auto' }}>{q.total} {TEXT.marks}</span>
          </div>
        </div>

        {/* The scheme column: blank rows with their marks until the answer is marked */}
        <div className="fxd-scheme-col" aria-live="polite">
          <div className="fxd-mono" style={{ marginBottom: 6 }}>
            {TEXT.scheme} · {q.points.length} {q.points.length === 1 ? TEXT.point : TEXT.points}
          </div>
          <ol className="fxd-points">
            {q.points.map((p, i) => {
              const hit = result?.hits[i];
              const on = !!hit?.matched;
              const miss = !!result && !on;
              return (
                <li key={p.id} className="fxd-point">
                  <span
                    className={`fxd-sq fxd-point__sq ${on ? 'fxd-sq--on fxd-sq--pop' : ''} ${miss ? 'fxd-sq--miss' : ''}`}
                    style={on && !instant ? { animationDelay: `${result!.hits.slice(0, i).filter(h => h.matched).length * STAGGER}ms` } : undefined}
                    aria-hidden="true"
                  />
                  <div className={`fxd-point__text ${miss ? 'fxd-point__text--miss' : ''}`}>
                    {result ? (
                      <>
                        {p.verbatim}
                        {miss && <span className="fxd-point__tag">{TEXT.wanted}</span>}
                      </>
                    ) : (
                      <>
                        <span className="fxd-point__hidden" style={{ width: `${Math.min(100, 28 + p.verbatim.length * 2.4)}%` }} aria-hidden="true" />
                        <span className="sr-only">{TEXT.point} {i + 1}, {TEXT.hidden}</span>
                      </>
                    )}
                  </div>
                  <span className={`fxd-point__marks ${on ? 'fxd-point__marks--on' : ''}`}>{p.marks}</span>
                </li>
              );
            })}
          </ol>
          {result && (
            <div className="fxd-total" role="status">
              <span className="fxd-total__n">{result.earned}</span>
              <span className="fxd-total__of">/ {result.total}</span>
              <span className="fxd-total__word">{word}</span>
            </div>
          )}
        </div>
      </div>
      <div className="fxd-attrib">{q.attribution}</div>
    </Frame>
  );
};

export default MarkMyAnswer;
