/**
 * The tunnel of years: one numeral per year the Paper Trail holds, each with
 * its paper count. Counts the PDFs per year directory in the local SEC corpus
 * (gitignored; the same PDFs the app serves) and writes them to
 * public/assets/landing/tunnel/years.json (the record) and to
 * components/landing/fx-i/years.ts (the typed copy TunnelOfYears.tsx imports —
 * the page's tsconfig has no resolveJsonModule).
 *
 *   node scripts/landing/tunnel-years.mjs [corpus-root]
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = process.argv[2] ?? '/Users/alexlinehan/Documents/Nextstepuni-Launch-/paper-trail-corpus/exampapers';
const out = path.resolve(here, '../../public/assets/landing/tunnel/years.json');
const outTs = path.resolve(here, '../../components/landing/fx-i/years.ts');

const countPdfs = (dir) => {
  let n = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) n += countPdfs(path.join(dir, entry.name));
    else if (entry.isFile() && /\.pdf$/i.test(entry.name)) n += 1;
  }
  return n;
};

const years = fs.readdirSync(root, { withFileTypes: true })
  .filter(e => e.isDirectory() && /^\d{4}$/.test(e.name))
  .map(e => ({ year: Number(e.name), papers: countPdfs(path.join(root, e.name)) }))
  .sort((a, b) => a.year - b.year);

const total = years.reduce((s, y) => s + y.papers, 0);
fs.writeFileSync(out, JSON.stringify({ source: 'paper-trail-corpus/exampapers, PDFs per year directory', generated: new Date().toISOString().slice(0, 10), total, years }, null, 2) + '\n');
fs.writeFileSync(outTs, `/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/landing/tunnel-years.mjs — do not edit. One entry per
 * year directory in the Paper Trail corpus, with the PDFs it holds. The same
 * figures are recorded in public/assets/landing/tunnel/years.json.
 */

export interface TunnelYear { year: number; papers: number }
export const YEARS: readonly TunnelYear[] = ${JSON.stringify(years)};
export const TOTAL_PAPERS = ${total};
`);
console.log(`${years.length} years, ${total} papers → ${path.relative(process.cwd(), out)}`);
for (const y of years) console.log(`  ${y.year}  ${y.papers}`);
